Repository CitizenLabDotCo/citizenlab, pull requests merged in 2022-05, with the labels that each got.

#1876 Cl 477/stuck in sign up form final 2
  CHANGELOG.md
  front/app/components/SignUpIn/SignUp/index.tsx
  front/app/components/SignUpIn/SignUpInModal.tsx
  front/app/components/SignUpIn/events.ts
  front/app/components/SignUpIn/tracks.ts
  front/app/components/UI/Modal/index.tsx
  front/app/components/UserDeletedModalContent/index.tsx
  front/app/containers/App/index.tsx
  front/app/containers/App/openSignUpInModalIfNecessary.ts
  front/app/containers/ProjectsShowPage/shared/header/ProjectSharingModal.tsx
  front/app/containers/SignUpInPage/index.tsx
  front/app/containers/UsersEditPage/DeletionDialog.tsx
  front/app/modules/commercial/project_folders/citizen/components/ProjectFolderSharingModal/index.tsx
  front/app/modules/free/user_confirmation/citizen/components/ConfirmationSignupStep.tsx
  front/app/services/auth.ts
  front/app/utils/analytics.ts
Labels: structure

#1975 CL-717 Fix ordering and grouping of past and not-past events
  CHANGELOG.md
  back/app/finders/events_finder.rb
  back/lib/finder/sortable.rb
  back/spec/finders/events_finder_spec.rb
  front/app/containers/EventsPage/CurrentAndUpcomingEvents.tsx
  front/app/containers/EventsPage/EventsViewer/index.tsx
  front/app/containers/EventsPage/index.tsx
  front/app/containers/EventsPage/messages.ts
  front/app/containers/LandingPage/messages.ts
  front/app/hooks/useEvents.ts
  front/app/modules/commercial/events_widget/citizen/TopBar.tsx
  front/app/modules/commercial/events_widget/citizen/index.tsx
  front/app/services/events.ts
  front/app/translations/ar-MA.json
  front/app/translations/ar-SA.json
  front/app/translations/da-DK.json
  front/app/translations/de-DE.json
  front/app/translations/en-CA.json
  front/app/translations/en-GB.json
  front/app/translations/en.json
  front/app/translations/es-CL.json
  front/app/translations/es-ES.json
  front/app/translations/fr-BE.json
  front/app/translations/fr-FR.json
  front/app/translations/hr-HR.json
  front/app/translations/hu-HU.json
  front/app/translations/it-IT.json
  front/app/translations/kl-GL.json
  front/app/translations/lb-LU.json
  front/app/translations/mi.json
  front/app/translations/nb-NO.json
  front/app/translations/nl-BE.json
  front/app/translations/nl-NL.json
  front/app/translations/pl-PL.json
  front/app/translations/pt-BR.json
  front/app/translations/ro-RO.json
  front/app/translations/sr-Latn.json
  front/app/translations/sr-SP.json
Labels: structure

#1973 React router 3 admin
  front/.vscode/settings.json
  front/app/containers/Admin/dashboard/index.tsx
  front/app/containers/Admin/dashboard/routes.ts
  front/app/containers/Admin/dashboard/routes.tsx
  front/app/containers/Admin/index.tsx
  front/app/containers/Admin/initiatives/index.tsx
  front/app/containers/Admin/initiatives/routes.ts
  front/app/containers/Admin/initiatives/routes.tsx
  front/app/containers/Admin/messaging/AutomatedEmails/index.tsx
  front/app/containers/Admin/messaging/CustomEmails/All/index.tsx
  front/app/containers/Admin/messaging/CustomEmails/Edit/index.tsx
  front/app/containers/Admin/messaging/index.tsx
  front/app/containers/Admin/messaging/routes.ts
  front/app/containers/Admin/messaging/routes.tsx
  front/app/containers/Admin/routes.ts
  front/app/containers/Admin/routes.tsx
  front/app/containers/Admin/users/UsersGroup.tsx
  front/app/containers/Admin/users/index.tsx
  front/app/containers/Admin/users/routes.ts
  front/app/containers/Admin/users/routes.tsx
  front/app/routes.tsx
  front/package-lock.json
Labels: structure, react-router

#2016 CL-815 Fix admin auth and redirect
  front/app/containers/Admin/routes.tsx
  front/app/routes.tsx
Labels: react-router

#2002 [CL-806] [react-router] Dynamic module conversion
  front/app/containers/Admin/dashboard/routes.tsx
  front/app/containers/Admin/initiatives/routes.tsx
  front/app/containers/Admin/projects/project/general/index.tsx
  front/app/containers/Admin/projects/routes.tsx
  front/app/containers/Admin/routes.tsx
  front/app/containers/Admin/settings/areas/routes.ts
  front/app/containers/Admin/settings/routes.tsx
  front/app/modules/commercial/admin_project_templates/index.tsx
  front/app/modules/commercial/content_builder/index.tsx
  front/app/modules/commercial/custom_idea_statuses/index.tsx
  front/app/modules/commercial/custom_maps/index.tsx
  front/app/modules/commercial/custom_topics/index.tsx
  front/app/modules/commercial/customizable_navbar/admin/containers/NavigationSettings/index.tsx
  front/app/modules/commercial/customizable_navbar/admin/containers/index.tsx
  front/app/modules/commercial/customizable_navbar/index.tsx
  front/app/modules/commercial/geographic_dashboard/index.tsx
  front/app/modules/commercial/granular_permissions/index.tsx
  front/app/modules/commercial/idea_custom_fields/index.tsx
  front/app/modules/commercial/insights/admin/containers/index.tsx
  front/app/modules/commercial/insights/index.tsx
  front/app/modules/commercial/moderation/index.tsx
  front/app/modules/commercial/project_folders/admin/containers/index.tsx
  front/app/modules/commercial/project_folders/admin/containers/permissions/index.tsx
  front/app/modules/commercial/project_folders/admin/containers/settings/index.tsx
  front/app/modules/commercial/project_folders/index.tsx
  front/app/modules/commercial/user_custom_fields/admin/containers/CustomFields/RegistrationCustomFieldEdit/RegistrationCustomFieldOptions.tsx
  front/app/modules/commercial/user_custom_fields/admin/containers/CustomFields/RegistrationCustomFieldEdit/RegistrationCustomFieldSettings.tsx
  front/app/modules/commercial/user_custom_fields/admin/containers/CustomFields/RegistrationCustomFieldEdit/index.tsx
  front/app/modules/commercial/user_custom_fields/admin/containers/CustomFields/index.tsx
  front/app/modules/commercial/user_custom_fields/index.tsx
  front/app/modules/commercial/widgets/index.tsx
  front/app/root.tsx
  front/app/routes.tsx
  front/app/utils/moduleUtils.tsx
Labels: react-router

#1964 [CL-729] Do not show navbar item if corresponding feature is disabled
  CHANGELOG.md
  back/app/controllers/web_api/v1/nav_bar_items_controller.rb
  back/app/policies/nav_bar_item_policy.rb
  back/spec/acceptance/nav_bar_items_spec.rb
  front/app/modules/commercial/customizable_navbar/admin/containers/NavigationSettings/HiddenNavbarItemList/index.tsx
Labels: structure

#2052 [react-router] Fix FE tests
  front/app/components/EventCard/EventInformation/EventInformation.test.tsx
  front/app/components/admin/TabbedResource/TabbedResource.test.tsx
  front/app/containers/Admin/projects/project/index.test.tsx
  front/app/containers/MainHeader/DesktopNavbar/DesktopNavbar.test.tsx
  front/app/containers/MobileNavbar/MobileNavbar.test.tsx
  front/app/modules/commercial/content_builder/admin/components/ContentBuilderLayout/ContentBuilderLayout.test.tsx
  front/app/modules/commercial/content_builder/admin/components/ContentBuilderPreview/ContentBuilderPreview.test.tsx
  front/app/modules/commercial/content_builder/admin/components/ContentBuilderToggle/ContentBuilderToggle.test.tsx
  front/app/modules/commercial/content_builder/admin/components/ContentBuilderTopBar/ContentBuilderTopBar.test.tsx
  front/app/modules/commercial/customizable_navbar/admin/components/NavbarItemRow/NavbarItemRow.test.tsx
  front/app/modules/commercial/insights/admin/components/Category/Category.test.tsx
  front/app/modules/commercial/insights/admin/components/Idea/Idea.test.tsx
  front/app/modules/commercial/insights/admin/components/TopBar/RenameInsightsView.test.tsx
  front/app/modules/commercial/insights/admin/components/TopBar/TopBar.test.tsx
  front/app/modules/commercial/insights/admin/containers/Insights/Details/Categories/Categories.test.tsx
  front/app/modules/commercial/insights/admin/containers/Insights/Details/Details.test.tsx
  front/app/modules/commercial/insights/admin/containers/Insights/Details/Inputs/CreateCategory.test.tsx
  front/app/modules/commercial/insights/admin/containers/Insights/Details/Inputs/Export.test.tsx
  front/app/modules/commercial/insights/admin/containers/Insights/Details/Inputs/Inputs.test.tsx
  front/app/modules/commercial/insights/admin/containers/Insights/Details/Preview/Preview.test.tsx
  front/app/modules/commercial/insights/admin/containers/Insights/Detect/Detect.test.tsx
  front/app/modules/commercial/insights/admin/containers/Insights/Edit/Categories/Categories.test.tsx
  front/app/modules/commercial/insights/admin/containers/Insights/Edit/InputDetails/InputDetails.test.tsx
  front/app/modules/commercial/insights/admin/containers/Insights/Edit/InputsTable/Export.test.tsx
  front/app/modules/commercial/insights/admin/containers/Insights/Edit/InputsTable/InputsTable.test.tsx
  front/app/modules/commercial/insights/admin/containers/Insights/Edit/InputsTable/TableTitle.test.tsx
  front/app/modules/commercial/insights/admin/containers/Insights/Edit/RenameCategory.test.tsx
  front/app/modules/commercial/project_folders/admin/containers/permissions/index.tsx
  front/app/modules/commercial/user_custom_fields/admin/containers/CustomFields/RegistrationCustomFieldEdit/RegistrationCustomFieldOptions.tsx
  front/app/modules/commercial/user_custom_fields/admin/containers/CustomFields/RegistrationCustomFieldEdit/RegistrationCustomFieldSettings.tsx
  front/app/utils/__mocks__/withRouter.tsx
  front/app/utils/cl-router/__mocks__/Link.tsx
  front/app/utils/cl-router/__mocks__/withRouter.ts
  front/app/utils/moduleUtils.tsx
  front/app/utils/testUtils/rtl.tsx
  front/internals/jest/setup.js
Labels: react-router
