Repository CitizenLabDotCo/citizenlab, pull requests merged in 2022-10, with the labels that each got.

#2853 [CL-1762] Bugfix: Use Swedish content for default static_pages when creating tenant with Swedish locale
  CHANGELOG.md
  back/config/initializers/1_locales.rb
  front/app/containers/App/constants.ts
Labels: structure, 10%-project

#2900 [CL-1793] Flexible pages e2e tests
  front/app/containers/Admin/pagesAndMenu/components/SectionToggle/AdminEditButton.tsx
  front/app/containers/Admin/pagesAndMenu/components/SectionToggle/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/Attachments/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/CustomPageSettingsForm/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/HeaderImageDropzone.test.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/HeaderImageDropzone.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericTopInfoSection/index.tsx
  front/app/containers/CustomPageShow/CustomPageHeader/FullWidthBannerLayout.tsx
  front/app/icon.png
  front/cypress/e2e/admin/pages_and_menu/create_update_and_view_custom_page.cy.ts
  front/cypress/e2e/admin/pages_and_menu/update_hero_banner_content.cy.ts
  front/cypress/e2e/admin/pages_and_menu/update_homepage_content.cy.ts
  front/cypress/e2e/profile_edition.cy.ts
  front/cypress/fixtures/example.pdf
Labels: structure, Flexible Pages

#2915 [CL-1779] Flexible Pages R2 design review fixes
  front/app/components/admin/PageWrapper/index.tsx
  front/app/containers/Admin/pagesAndMenu/components/SectionFormWrapper.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/CustomPageSettingsForm/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/Edit/Content/BottomInfoSection/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/Edit/Content/TopInfoSection/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/Edit/Content/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/Edit/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/New/NewCustomPage.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/New/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/NavigationSettings/VisibleNavbarItemList/index.tsx
  front/app/containers/Admin/pagesAndMenu/routes.tsx
  front/app/modules/commercial/customizable_navbar/admin/containers/NavigationSettings/HiddenNavbarItemList/Header.tsx
  front/app/modules/commercial/customizable_navbar/admin/containers/NavigationSettings/HiddenNavbarItemList/index.tsx
  front/app/modules/commercial/customizable_navbar/admin/containers/NavigationSettings/VisibleNavbarItemList/index.tsx
  front/app/modules/commercial/customizable_navbar/admin/containers/index.tsx
Labels: structure, Flexible Pages

#2949 [no ticket] Fix TabbedResource header
  front/app/components/admin/TabbedResource/index.tsx
Labels: structure

#2968 Cl 1859 add edit page button for admins on custom page citizen
  front/app/containers/Admin/pagesAndMenu/containers/Attachments/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/Edit/HeroBanner/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/NavigationSettings/VisibleNavbarItemList/index.tsx
  front/app/containers/Admin/pagesAndMenu/routes.tsx
  front/app/containers/CustomPageShow/CustomPageHeader/AdminCustomPageEditButton.tsx
  front/app/containers/CustomPageShow/CustomPageHeader/FullWidthBannerLayout.tsx
  front/app/containers/CustomPageShow/CustomPageHeader/TwoColumnLayout.tsx
  front/app/containers/CustomPageShow/CustomPageHeader/TwoRowLayout.tsx
  front/app/containers/CustomPageShow/CustomPageHeader/index.tsx
  front/app/containers/CustomPageShow/index.tsx
  front/app/containers/CustomPageShow/messages.ts
  front/app/containers/LandingPage/SignedOutHeader/FullWidthBannerLayout.tsx
  front/app/modules/commercial/customizable_homepage_banner/citizen/TwoColumnLayout.tsx
  front/app/modules/commercial/customizable_homepage_banner/citizen/TwoRowLayout.tsx
  front/app/modules/commercial/customizable_navbar/admin/components/PoliciesSubtitle.tsx
  front/app/modules/commercial/customizable_navbar/admin/containers/NavigationSettings/HiddenNavbarItemList/HiddenNavbarItemList.test.tsx
  front/app/modules/commercial/customizable_navbar/admin/containers/NavigationSettings/HiddenNavbarItemList/index.tsx
  front/app/modules/commercial/customizable_navbar/admin/containers/NavigationSettings/VisibleNavbarItemList/VisibleNavbarItemList.test.tsx
  front/app/modules/commercial/customizable_navbar/admin/containers/NavigationSettings/VisibleNavbarItemList/index.tsx
  front/app/modules/commercial/customizable_navbar/admin/containers/NewPageForm/index.tsx
  front/app/translations/en.json
Labels: structure, Flexible Pages

#2981 Cl 1865 add view custom page button to each section s form
  front/app/containers/Admin/pagesAndMenu/components/SectionFormWrapper.tsx
  front/app/containers/Admin/pagesAndMenu/containers/Attachments/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/Edit/Content/BottomInfoSection/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/Edit/Content/TopInfoSection/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/Edit/HeroBanner/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/Edit/ViewCustomPageButton.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/Edit/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericBottomInfoSection/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericTopInfoSection/index.tsx
Labels: structure, Flexible Pages

#2990 Prevent toggle flashing on change
  front/app/containers/Admin/pagesAndMenu/components/SectionToggle/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/Edit/Content/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/EditHomepage/index.tsx
Labels: structure, Flexible Pages

#2911 CL-1814 Fix reference to location.query
  CHANGELOG.md
  front/app/containers/App/index.tsx
  front/app/containers/App/openVerificationModalIfSuccessOrError.ts
  front/app/modules/commercial/verification/citizen/components/VerificationError.tsx
  front/app/modules/commercial/verification/citizen/components/VerificationModal.tsx
Labels: structure

#2991 Cl 1867 use reusable components for layouts home/custom page
  front/app/components/LandingPages/admin/CTARadioButtons.tsx
  front/app/components/LandingPages/admin/messages.ts
  front/app/components/LandingPages/citizen/BannerButton.tsx
  front/app/components/LandingPages/citizen/FullWidthBannerLayout.ts
  front/app/components/LandingPages/citizen/HeaderContent.ts
  front/app/components/LandingPages/citizen/InfoSection.ts
  front/app/components/LandingPages/citizen/TwoColumnLayout.ts
  front/app/components/LandingPages/citizen/TwoRowLayout.ts
  front/app/components/LandingPages/citizen/index.ts
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/Edit/HeroBanner/CTAButtonFields.tsx
  front/app/containers/CustomPageShow/CustomPageHeader/FullWidthBannerLayout.tsx
  front/app/containers/CustomPageShow/CustomPageHeader/HeaderContent.tsx
  front/app/containers/CustomPageShow/CustomPageHeader/TwoColumnLayout.tsx
  front/app/containers/CustomPageShow/CustomPageHeader/TwoRowLayout.tsx
  front/app/containers/CustomPageShow/TopInfoSection.tsx
  front/app/containers/CustomPageShow/index.tsx
  front/app/containers/HomePage/Footer.tsx
  front/app/containers/HomePage/HomepageInfoSection.tsx
  front/app/containers/HomePage/InitiativesCTABox.tsx
  front/app/containers/HomePage/MainContent.tsx
  front/app/containers/HomePage/SignUpButton.tsx
  front/app/containers/HomePage/SignedInHeader.tsx
  front/app/containers/HomePage/SignedOutHeader/FullWidthBannerLayout.tsx
  front/app/containers/HomePage/SignedOutHeader/HeaderContent.tsx
  front/app/containers/HomePage/SignedOutHeader/index.tsx
  front/app/containers/HomePage/index.test.tsx
  front/app/containers/HomePage/index.tsx
  front/app/containers/HomePage/messages.ts
  front/app/containers/HomePage/tracks.ts
  front/app/modules/commercial/customizable_homepage_banner/admin/CTASettings.tsx
  front/app/modules/commercial/customizable_homepage_banner/citizen/CTA.tsx
  front/app/modules/commercial/customizable_homepage_banner/citizen/TwoColumnLayout.tsx
  front/app/modules/commercial/customizable_homepage_banner/citizen/TwoRowLayout.tsx
  front/app/modules/commercial/customizable_homepage_banner/index.tsx
  front/app/modules/commercial/events_widget/citizen/TopBar.tsx
  front/app/modules/commercial/events_widget/index.tsx
  front/app/modules/commercial/verification/citizen/components/VerificationOnboardingStep.tsx
  front/app/modules/commercial/verification/index.tsx
  front/app/routes.tsx
  front/app/utils/moduleUtils.tsx
Labels: structure, Flexible Pages

#2941 CL-1811 Set up oostende rrn verification
  CHANGELOG.md
  back/Gemfile.lock
  back/config/schemas/settings.schema.json.erb
  back/engines/commercial/id_oostende_rrn/app/lib/id_oostende_rrn/oostende_rrn_verification.rb
  back/engines/commercial/id_oostende_rrn/id_oostende_rrn.gemspec
  back/engines/commercial/id_oostende_rrn/lib/id_oostende_rrn.rb
  back/engines/commercial/id_oostende_rrn/lib/id_oostende_rrn/engine.rb
  back/engines/commercial/id_oostende_rrn/lib/id_oostende_rrn/version.rb
  back/engines/commercial/id_oostende_rrn/lib/id_oostende_rrn/wijk_budget_api.rb
  back/engines/commercial/id_oostende_rrn/spec/acceptance/oostende_rrn_verification_spec.rb
  front/app/modules/commercial/id_oostende_rrn/components/OostendeRrnButton.tsx
  front/app/modules/commercial/id_oostende_rrn/components/VerificationFormOostendeRrn.tsx
  front/app/modules/commercial/id_oostende_rrn/index.tsx
  front/app/modules/commercial/id_oostende_rrn/messages.ts
  front/app/modules/commercial/id_oostende_rrn/services/verificationMethods.ts
  front/app/modules/commercial/id_oostende_rrn/services/verify.ts
  front/app/modules/index.ts
  front/app/translations/en.json
Labels: structure

#3046 [Flexible pages r2] Assorted styling and layout fixes
  front/app/containers/Admin/pagesAndMenu/containers/NavigationSettings/NavbarItemRow/index.tsx
  front/app/containers/CustomPageShow/CustomPageHeader/TwoColumnLayout.tsx
  front/app/containers/CustomPageShow/index.tsx
Labels: structure, Flexible Pages

#3027 [CL-1793] Flexible pages r2 e2e test fixes
  front/app/containers/CustomPageShow/index.tsx
  front/cypress.config.ts
  front/cypress/e2e/admin/pages_and_menu/create_update_and_view_custom_page.cy.ts
  front/cypress/e2e/admin/pages_and_menu/update_homepage_hero_banner_content.cy.ts
  front/cypress/e2e/admin/pages_and_menu/update_homepage_text_content_and_sections.cy.ts
  front/cypress/e2e/profile_edition.cy.ts
  front/cypress/support/commands.ts
Labels: structure, Flexible Pages

#3059 CL-1878 Log project status transitions as Activities
  back/app/services/side_fx_project_service.rb
  back/spec/acceptance/projects_spec.rb
Labels: insights

#3010 [CL-1611] Improve project phase emails
  CHANGELOG.md
  back/app/models/notifications/project_phase_upcoming.rb
  back/app/views/projects/_about_project.mjml
  back/engines/free/email_campaigns/app/models/email_campaigns/campaigns/project_phase_started.rb
  back/engines/free/email_campaigns/app/models/email_campaigns/campaigns/project_phase_upcoming.rb
  back/engines/free/email_campaigns/app/views/email_campaigns/project_phase_started_mailer/campaign_mail.mjml
  back/engines/free/email_campaigns/app/views/email_campaigns/project_phase_upcoming_mailer/campaign_mail.mjml
  back/engines/free/email_campaigns/config/locales/en.yml
  back/engines/free/email_campaigns/spec/fixtures/locales/mailers.en.yml
  back/engines/free/email_campaigns/spec/mailers/previews/email_campaigns/project_phase_started_mailer_preview.rb
  back/engines/free/email_campaigns/spec/mailers/previews/email_campaigns/project_phase_upcoming_mailer_preview.rb
  back/engines/free/email_campaigns/spec/mailers/project_phase_started_mailer_spec.rb
  back/engines/free/email_campaigns/spec/mailers/project_phase_upcoming_mailer_spec.rb
Labels: structure

#3061 [CL-1786] Add Latvian
  CHANGELOG.md
  back/config/blocked_words/lv.txt
  back/config/initializers/1_locales.rb
  front/app/containers/App/constants.js
  front/app/containers/App/constants.ts
  front/app/i18n/lv-LV.ts
Labels: structure

#3063 [CL-1786] Add Catalan
  CHANGELOG.md
  back/config/blocked_words/ca.txt
  back/config/initializers/1_locales.rb
  front/app/containers/App/constants.js
  front/app/containers/App/constants.ts
  front/app/i18n/ca-ES.ts
Labels: structure

#3065 [CL-1786] Add Greek
  CHANGELOG.md
  back/config/blocked_words/el.txt
  back/config/initializers/1_locales.rb
  front/app/containers/App/constants.js
  front/app/containers/App/constants.ts
  front/app/i18n/el-GR.ts
Labels: structure

#3090 [No Ticket] Update changelog
  CHANGELOG.md
Labels: structure

#3066 [CL-1800] Toggle password login and signup individually
  CHANGELOG.md
  back/app/policies/user_policy.rb
  back/config/schemas/settings.schema.json.erb
  back/db/seeds/citizenlab.rb
  back/engines/commercial/project_folders/spec/policies/user_policy_spec.rb
  back/engines/commercial/project_management/spec/policies/user_policy_spec.rb
  back/spec/acceptance/users_spec.rb
  back/spec/models/user_spec.rb
  back/spec/policies/user_policy_spec.rb
  back/spec/requests/rack_attack_spec.rb
  back/spec/support/app_configuration_helper.rb
  front/app/components/SignUpIn/AuthProviders.tsx
  front/app/services/appConfiguration.ts
Labels: structure

#3021 [CL-1765] Update image URLs to new s3 values
  CHANGELOG.md
  README.md
  back/app/services/anonymize_user_service.rb
  back/app/views/application/_footer.mjml
  back/config/anonymize_users/avatars.csv
  back/config/initializers/carrierwave.rb
  back/config/tenant_templates/base.yml
  back/config/tenant_templates/e2etests_template.yml
  back/db/seeds/citizenlab.rb
  back/engines/commercial/bulk_import_ideas/app/services/bulk_import_ideas/import_ideas_service.rb
  back/engines/commercial/bulk_import_ideas/lib/tasks/bulk_import_ideas_tasks.rake
  back/engines/free/email_campaigns/app/views/email_campaigns/admin_digest_mailer/_statistics.mjml
  back/engines/free/email_campaigns/app/views/email_campaigns/application/_footer.mjml
  back/engines/free/email_campaigns/app/views/email_campaigns/assignee_digest_mailer/campaign_mail.mjml
  back/engines/free/email_campaigns/app/views/email_campaigns/first_idea_published_mailer/campaign_mail.mjml
  back/engines/free/email_campaigns/app/views/email_campaigns/idea_published_mailer/campaign_mail.mjml
  back/engines/free/email_campaigns/app/views/email_campaigns/ideas/_idea-minimal-with-increments.mjml
  back/engines/free/email_campaigns/app/views/email_campaigns/ideas/_idea-minimal.mjml
  back/engines/free/email_campaigns/app/views/email_campaigns/initiative_published_mailer/campaign_mail.mjml
  back/engines/free/email_campaigns/app/views/email_campaigns/initiatives/_initiative.mjml
  back/engines/free/email_campaigns/app/views/email_campaigns/moderator_digest_mailer/campaign_mail.mjml
  back/engines/free/email_campaigns/app/views/email_campaigns/user_digest_mailer/campaign_mail.mjml
  back/engines/free/email_campaigns/spec/mailers/previews/email_campaigns/user_digest_mailer_preview.rb
  back/spec/fixtures/template_without_images.yml
  back/spec/services/text_image_service_spec.rb
Labels: structure
