Repository CitizenLabDotCo/citizenlab, pull requests merged in 2022-11, with the labels that each got.

#3091 CL-1742 Refactor posts dimensions
  back/db/migrate/20221027170719_update_fact_posts_view.analytics.rb
  back/db/schema.rb
  back/db/views/analytics_fact_posts_v02.sql
  back/engines/commercial/analytics/app/models/analytics/fact_post.rb
  back/engines/commercial/analytics/db/migrate/20221027180337_update_fact_posts_view.rb
  back/engines/commercial/analytics/db/views/analytics_fact_posts_v02.sql
  back/engines/commercial/analytics/spec/services/analytics/query_runner_service_spec.rb
  back/engines/commercial/analytics/spec/services/analytics/query_validator_service_spec.rb
  front/app/modules/commercial/analytics/admin/hooks/usePostsFeedback/index.ts
Labels: insights

#3072 Cl 1890 Modules lazy imports
  front/app/components/Outlet/index.tsx
  front/app/modules/commercial/admin_project_templates/index.tsx
  front/app/modules/commercial/analytics/index.tsx
  front/app/modules/commercial/bulk_idea_import/index.tsx
  front/app/modules/commercial/custom_idea_statuses/index.tsx
  front/app/modules/commercial/custom_maps/index.tsx
  front/app/modules/commercial/custom_topics/index.tsx
  front/app/modules/commercial/customizable_homepage_banner/index.tsx
  front/app/modules/commercial/events_widget/index.tsx
  front/app/modules/commercial/flag_inappropriate_content/index.tsx
  front/app/modules/commercial/geographic_dashboard/index.tsx
  front/app/modules/commercial/granular_permissions/index.tsx
  front/app/modules/commercial/id_bogus/index.tsx
  front/app/modules/commercial/id_bosa_fas/index.tsx
  front/app/modules/commercial/id_clave_unica/index.tsx
  front/app/modules/commercial/id_cow/index.tsx
  front/app/modules/commercial/id_franceconnect/index.tsx
  front/app/modules/commercial/id_gent_rrn/index.tsx
  front/app/modules/commercial/id_id_card_lookup/index.tsx
  front/app/modules/commercial/id_oostende_rrn/index.tsx
  front/app/modules/commercial/idea_assignment/index.tsx
  front/app/modules/commercial/idea_custom_fields/index.tsx
  front/app/modules/commercial/insights/index.tsx
  front/app/modules/commercial/machine_translations/index.tsx
  front/app/modules/commercial/moderation/index.tsx
  front/app/modules/commercial/project_folders/index.tsx
  front/app/modules/commercial/project_management/index.tsx
  front/app/modules/commercial/representativeness/index.tsx
  front/app/modules/commercial/similar_ideas/index.tsx
  front/app/modules/commercial/smart_groups/index.tsx
  front/app/modules/commercial/user_custom_fields/index.tsx
  front/app/modules/commercial/verification/index.tsx
  front/app/modules/commercial/widgets/index.tsx
  front/app/modules/free/customizable_navbar/index.tsx
  front/app/modules/free/project_visibility/index.tsx
  front/app/modules/free/user_confirmation/index.tsx
  front/internals/scripts/converts-module-imports.js
Labels: platform

#3126 [CL-1611] Move about_project partial to conventional location
  back/engines/free/email_campaigns/app/views/email_campaigns/project_phase_started_mailer/campaign_mail.mjml
  back/engines/free/email_campaigns/app/views/email_campaigns/project_phase_upcoming_mailer/campaign_mail.mjml
  back/engines/free/email_campaigns/app/views/email_campaigns/projects/_about_project.mjml
Labels: structure

#3102 [CL-1914] Update Analytics API
  back/engines/commercial/analytics/app/controllers/analytics/web_api/v1/analytics_controller.rb
  back/engines/commercial/analytics/app/policies/analytics/analytics_policy.rb
  back/engines/commercial/analytics/app/services/analytics/query_runner_service.rb
  back/engines/commercial/analytics/app/services/analytics/query_schema.json
  back/engines/commercial/analytics/app/services/analytics/query_validator_service.rb
  back/engines/commercial/analytics/config/routes.rb
  back/engines/commercial/analytics/lib/query.rb
  back/engines/commercial/analytics/spec/acceptance/analytics_api_spec.rb
  back/engines/commercial/analytics/spec/acceptance/analytics_fact_schema_spec.rb
  back/engines/commercial/analytics/spec/acceptance/analytics_participations_spec.rb
  back/engines/commercial/analytics/spec/acceptance/analytics_registrations_spec.rb
  back/engines/commercial/analytics/spec/acceptance/analytics_visits_spec.rb
  back/engines/commercial/analytics/spec/services/analytics/query_runner_service_spec.rb
  back/engines/commercial/analytics/spec/services/analytics/query_validator_service_spec.rb
  front/app/modules/commercial/analytics/admin/components/VisitorsTrafficSourcesCard/getXlsxData.ts
  front/app/modules/commercial/analytics/admin/hooks/usePostsFeedback/index.ts
  front/app/modules/commercial/analytics/admin/hooks/useRegistrations/query.ts
  front/app/modules/commercial/analytics/admin/hooks/useVisitorLanguages/index.ts
  front/app/modules/commercial/analytics/admin/hooks/useVisitorReferrerTypes/index.ts
  front/app/modules/commercial/analytics/admin/hooks/useVisitorReferrers/query.ts
  front/app/modules/commercial/analytics/admin/hooks/useVisitorTypes/index.ts
  front/app/modules/commercial/analytics/admin/hooks/useVisitors/index.ts
  front/app/modules/commercial/analytics/admin/services/analyticsFacts.ts
  front/app/modules/commercial/analytics/admin/utils/query.ts
Labels: insights

#3124 [CL-1929] update gender pie chart styles
  CHANGELOG.md
  front/app/components/admin/Graphs/PieChart/index.tsx
  front/app/components/admin/Graphs/PieChart/utils.ts
  front/app/containers/Admin/dashboard/users/charts/PieChartByCategory.tsx
  front/app/containers/Admin/dashboard/users/charts/renderPieChartByCategoryTooltip.tsx
  front/app/modules/commercial/analytics/admin/components/VisitorsLanguageCard/index.tsx
  front/app/modules/commercial/analytics/admin/components/VisitorsTypeCard/index.tsx
  front/app/modules/commercial/user_custom_fields/admin/components/GenderChart.tsx
  front/app/modules/commercial/user_custom_fields/admin/components/renderGenderTooltip.tsx
Labels: insights

#3139 [CL-1745] Add email deliveries data model
  back/db/migrate/20221107124858_create_fact_email_deliveries_view.analytics.rb
  back/db/schema.rb
  back/db/views/analytics_fact_email_deliveries_v01.sql
  back/db/views/analytics_fact_participations_v02.sql
  back/engines/commercial/analytics/app/models/analytics/fact_email_delivery.rb
  back/engines/commercial/analytics/app/services/analytics/query_schema.json
  back/engines/commercial/analytics/db/migrate/20221102183715_create_fact_email_deliveries_view.rb
  back/engines/commercial/analytics/db/views/analytics_fact_email_deliveries_v01.sql
  back/engines/commercial/analytics/lib/query.rb
  back/engines/commercial/analytics/spec/acceptance/analytics_email_deliveries_spec.rb
  back/engines/commercial/analytics/spec/models/analytics/fact_email_delivery_spec.rb
Labels: insights

#3154 CL-1984 Improve type safety analytics
  front/app/modules/commercial/analytics/admin/hooks/useActiveUsers/parse.ts
  front/app/modules/commercial/analytics/admin/hooks/useActiveUsers/typings.ts
  front/app/modules/commercial/analytics/admin/hooks/useActiveUsers/utils.ts
  front/app/modules/commercial/analytics/admin/hooks/usePostsFeedback/parse.ts
  front/app/modules/commercial/analytics/admin/hooks/useRegistrations/parse.ts
  front/app/modules/commercial/analytics/admin/hooks/useRegistrations/typings.ts
  front/app/modules/commercial/analytics/admin/hooks/useRegistrations/utils.ts
  front/app/modules/commercial/analytics/admin/hooks/useVisitorReferrers/parse.ts
  front/app/modules/commercial/analytics/admin/hooks/useVisitors/parse.ts
  front/app/modules/commercial/analytics/admin/hooks/useVisitors/typings.ts
  front/app/modules/commercial/analytics/admin/hooks/useVisitors/utils.ts
  front/app/modules/commercial/analytics/admin/typings.ts
  front/app/modules/commercial/analytics/admin/utils/resolution.ts
  front/app/modules/commercial/analytics/admin/utils/timeSeries.ts
  front/app/utils/helperUtils.ts
Labels: insights

#3088 CL-1911 - Analytics invitations data model
  back/db/migrate/20221025131832_update_fact_registrations_view.analytics.rb
  back/db/migrate/20221027125738_update_dimension_users_view.analytics.rb
  back/db/schema.rb
  back/db/views/analytics_dimension_users_v02.sql
  back/db/views/analytics_fact_registrations_v02.sql
  back/engines/commercial/analytics/app/models/analytics/dimension_user.rb
  back/engines/commercial/analytics/app/models/analytics/fact_registration.rb
  back/engines/commercial/analytics/db/migrate/20221025141434_update_fact_registrations_view.rb
  back/engines/commercial/analytics/db/migrate/20221027135433_update_dimension_users_view.rb
  back/engines/commercial/analytics/db/views/analytics_dimension_users_v02.sql
  back/engines/commercial/analytics/db/views/analytics_fact_registrations_v02.sql
  back/engines/commercial/analytics/spec/acceptance/analytics_registrations_spec.rb
  back/engines/commercial/analytics/spec/models/analytics/fact_registration_spec.rb
Labels: insights

#3135 [CL-1923] Disable switching from existing participation method to native survey
  CHANGELOG.md
  front/app/containers/Admin/projects/project/messages.ts
  front/app/containers/Admin/projects/project/participationContext/components/ParticipationMethodPicker.tsx
  front/app/containers/Admin/projects/project/participationContext/components/labels.tsx
  front/app/containers/Admin/projects/project/timeline/index.tsx
  front/app/translations/admin/en.json
  front/cypress/e2e/admin/projects/edit_project_timeline.cy.ts
  front/cypress/e2e/admin/projects/project_settings.cy.ts
Labels: waiting for translations

#3044 CL-1910 Analytics events data model
  back/db/migrate/20221025100507_create_fact_events_view.analytics.rb
  back/db/schema.rb
  back/db/views/analytics_fact_events_v01.sql
  back/engines/commercial/analytics/app/models/analytics/fact_event.rb
  back/engines/commercial/analytics/app/services/analytics/query_schema.json
  back/engines/commercial/analytics/db/migrate/20221025105931_create_fact_events_view.rb
  back/engines/commercial/analytics/db/views/analytics_fact_events_v01.sql
  back/engines/commercial/analytics/db/views/analytics_fact_participations_v02.sql
  back/engines/commercial/analytics/lib/query.rb
  back/engines/commercial/analytics/spec/acceptance/analytics_events_spec.rb
  back/engines/commercial/analytics/spec/models/analytics/fact_event_spec.rb
Labels: insights

#3098 CL-1881 Model project status with a fact table
  back/Gemfile.lock
  back/db/migrate/20221103153024_create_fact_project_statuses_view.analytics.rb
  back/db/schema.rb
  back/db/views/analytics_fact_project_statuses_v01.sql
  back/engines/commercial/analytics/app/models/analytics/fact_project_status.rb
  back/engines/commercial/analytics/app/services/analytics/query_schema.json.erb
  back/engines/commercial/analytics/app/services/analytics/query_validator_service.rb
  back/engines/commercial/analytics/db/migrate/20221102152509_create_fact_project_statuses_view.rb
  back/engines/commercial/analytics/db/views/analytics_fact_project_statuses_v01.sql
  back/engines/commercial/analytics/lib/query.rb
  back/engines/commercial/analytics/spec/acceptance/analytics_project_statuses_spec.rb
  back/engines/commercial/analytics/spec/models/analytics/fact_project_status_spec.rb
  front/app/translations/admin/de-DE.json
  front/app/translations/admin/en-CA.json
  front/app/translations/admin/en-GB.json
  front/app/translations/admin/kl-GL.json
  front/app/translations/admin/lv-LV.json
  front/app/translations/admin/pt-BR.json
  front/app/translations/admin/tr-TR.json
Labels: insights

#2887 [CL-1151][CL-1986] Drop unused pages body_multiloc column
  back/app/models/static_page.rb
  back/db/migrate/20221006071220_remove_body_multiloc_from_static_pages.rb
  back/db/schema.rb
Labels: structure, Flexible Pages

#3171 CL-2008 Empty state of input status card
  front/app/containers/Admin/dashboard/overview/index.tsx
  front/app/modules/commercial/analytics/admin/components/InputStatusCard/DonutChart/CenterLabel.tsx
  front/app/modules/commercial/analytics/admin/components/InputStatusCard/DonutChart/index.tsx
  front/app/modules/commercial/analytics/admin/components/InputStatusCard/ProgressBars/generateEmptyData.ts
  front/app/modules/commercial/analytics/admin/components/InputStatusCard/ProgressBars/index.tsx
  front/app/modules/commercial/analytics/admin/components/InputStatusCard/StackedBars/index.tsx
  front/app/modules/commercial/analytics/admin/components/InputStatusCard/StackedBars/stackLabels.tsx
  front/app/modules/commercial/analytics/admin/components/InputStatusCard/StackedBars/stackedBarTooltip.tsx
  front/app/modules/commercial/analytics/admin/components/InputStatusCard/StackedBars/utils.ts
  front/app/modules/commercial/analytics/admin/components/InputStatusCard/index.tsx
  front/app/modules/commercial/analytics/admin/components/InputStatusCard/messages.ts
  front/app/modules/commercial/analytics/admin/components/PostFeedbackCard/index.tsx
  front/app/modules/commercial/analytics/admin/containers/InputStatus.tsx
  front/app/modules/commercial/analytics/admin/hooks/usePostsFeedback/index.ts
  front/app/modules/commercial/analytics/admin/hooks/usePostsFeedback/typings.ts
  front/app/modules/commercial/analytics/index.tsx
  front/app/utils/moduleUtils.tsx
Labels: insights

#3172 [CL-2007] Remove feature flag input status card, and delete old ideas chart
  front/app/containers/Admin/dashboard/overview/charts/IdeasByStatusChart.tsx
  front/app/containers/Admin/dashboard/overview/index.tsx
  front/app/modules/commercial/analytics/admin/containers/InputStatus.tsx
  front/app/modules/commercial/analytics/admin/containers/Visitors/index.tsx
  front/app/modules/commercial/analytics/index.tsx
  front/app/utils/moduleUtils.tsx
Labels: insights

#3152 Restrict direct imports from `@testing-library/react`
  front/.eslintrc.js
  front/app/components/admin/SlugInput/SlugInput.test.tsx
  front/app/utils/testUtils/rtl.tsx
Labels: platform

#3203 [CL-1811] Update changelog
  CHANGELOG.md
Labels: structure

#3158 [CL-1344] Improve type casting instance in form builder
  front/app/containers/Admin/formBuilder/containers/projects/forms/edit/index.tsx
  front/app/services/formCustomFields.ts
Labels: methods

#3204 [CL-1818] Add linked projects associations
  back/app/controllers/web_api/v1/areas_controller.rb
  back/app/models/area.rb
  back/app/models/static_page.rb
  back/app/models/topic.rb
  back/app/policies/static_page_policy.rb
  back/app/serializers/web_api/v1/area_serializer.rb
  back/app/serializers/web_api/v1/static_page_serializer.rb
  back/app/serializers/web_api/v1/topic_serializer.rb
  back/db/migrate/20221111132019_create_page_projects_filter_join_tables.rb
  back/db/migrate/20221114094435_add_default_value_to_project_filter_type_on_static_pages.rb
  back/db/schema.rb
  back/engines/commercial/custom_topics/app/controllers/custom_topics/web_api/v1/topics_controller.rb
  back/spec/models/static_page_spec.rb
Labels: structure

#3212 [CL-2036] Fix to detect both 'returning' and 'returningCustomer' in Matomo API output
  back/engines/commercial/analytics/app/services/analytics/matomo_data_importer.rb
  back/engines/commercial/analytics/spec/services/analytics/matomo_data_importer_spec.rb
Labels: insights

#3209 CL-2025 bottom info section for custom page
  front/app/components/LandingPages/citizen/InfoSection.ts
  front/app/components/LandingPages/citizen/InfoSection.tsx
  front/app/containers/CustomPageShow/TopInfoSection.tsx
  front/app/containers/CustomPageShow/index.tsx
  front/app/containers/HomePage/HomepageInfoSection.tsx
  front/app/containers/HomePage/index.tsx
Labels: structure

#3193 [CL-2020] Custom page create/edit linked projects selector
  back/app/policies/static_page_policy.rb
  back/app/serializers/web_api/v1/static_page_serializer.rb
  back/db/schema.rb
  front/app/components/HookForm/SlugInput/index.tsx
  front/app/components/HookForm/Tabs/Tabs.test.tsx
  front/app/components/HookForm/Tabs/index.tsx
  front/app/components/UI/Tabs/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/CustomPageSettingsForm/index.test.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/CustomPageSettingsForm/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/Edit/Settings/index.test.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/Edit/Settings/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/New/NewCustomPage.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/messages.ts
  front/app/hooks/fixtures/customPages.ts
  front/app/services/customPages.ts
  front/app/translations/admin/en.json
Labels: structure

#3195 [CL-1990] Add Page element to form builder back office
  front/app/components/HookForm/QuillMultilocWithLocaleSwitcher/index.tsx
  front/app/components/admin/ResourceList/SortableRow.tsx
  front/app/containers/Admin/formBuilder/components/FormBuilderSettings/PageSettings/index.tsx
  front/app/containers/Admin/formBuilder/components/FormBuilderSettings/PageSettings/messages.ts
  front/app/containers/Admin/formBuilder/components/FormBuilderSettings/index.tsx
  front/app/containers/Admin/formBuilder/components/FormBuilderSettings/utils.tsx
  front/app/containers/Admin/formBuilder/components/FormBuilderToolbox/index.tsx
  front/app/containers/Admin/formBuilder/components/FormFields/index.tsx
  front/app/containers/Admin/formBuilder/components/FormFields/utils.ts
  front/app/containers/Admin/formBuilder/components/messages.ts
  front/app/containers/Admin/formBuilder/containers/projects/forms/edit/index.tsx
  front/app/services/formCustomFields.ts
  front/app/translations/admin/en.json
  front/app/utils/yup/validateElementTitle.test.ts
  front/app/utils/yup/validateElementTitle.ts
  front/cypress/e2e/form_builder/elements/linear_scale_field.cy.ts
  front/cypress/e2e/form_builder/elements/multiple_choice_field.cy.ts
  front/cypress/e2e/form_builder/elements/number_field.cy.ts
  front/cypress/e2e/form_builder/elements/page_element.cy.ts
  front/package-lock.json
  front/package.json
Labels: waiting for translations, methods

#3206 CL-1312 Project status card
  front/app/components/admin/GraphCard/index.tsx
  front/app/containers/Admin/dashboard/overview/index.tsx
  front/app/modules/commercial/analytics/admin/components/ProjectStatusCard/config.test.ts
  front/app/modules/commercial/analytics/admin/components/ProjectStatusCard/config.ts
  front/app/modules/commercial/analytics/admin/components/ProjectStatusCard/index.tsx
  front/app/modules/commercial/analytics/admin/components/ProjectStatusCard/messages.ts
  front/app/modules/commercial/analytics/admin/components/StatCard/index.tsx
  front/app/modules/commercial/analytics/admin/containers/ProjectStatus.tsx
  front/app/modules/commercial/analytics/admin/hooks/useStatCard/typings.ts
  front/app/modules/commercial/analytics/admin/services/analyticsFacts.ts
  front/app/modules/commercial/analytics/index.tsx
  front/app/translations/admin/en.json
  front/app/utils/moduleUtils.tsx
Labels: insights

#3219 [CL-2051] Acceptance tests of projects list for static pages
  back/spec/acceptance/static_pages_spec.rb
Labels: structure

#3216 CL-2048 add projects only filter
  back/app/services/admin_publications_filtering_service.rb
  back/spec/acceptance/admin_publications_spec.rb
Labels: structure

#3221 [CL-1763] Fix Norwegian
  back/config/locales/nb-NO.yml
Labels: structure

#3187 CL-1998: Display questions per page
  front/app/components/Form/Components/Controls/index.tsx
  front/app/components/Form/Components/Layouts/CLPageLayout.tsx
  front/app/components/Form/Components/Layouts/utils.ts
  front/app/components/Form/contexts.ts
  front/app/components/Form/formConfig.tsx
  front/app/components/Form/index.tsx
  front/app/components/Form/messages.ts
  front/app/containers/IdeasEditPage/WithJSONForm/index.tsx
  front/app/containers/IdeasNewPage/WithJSONForm/Heading.tsx
  front/app/containers/IdeasNewPage/WithJSONForm/index.tsx
  front/app/containers/IdeasNewPage/index.tsx
  front/app/containers/IdeasNewPage/messages.ts
  front/app/translations/en.json
Labels: methods

#3233 [CL-2052] Handle nil omniauth.params
  CHANGELOG.md
  back/app/controllers/omniauth_callback_controller.rb
  back/spec/acceptance/omniauth_callback_spec.rb
Labels: structure

#3232 [CL-1818] Replace habtm with has_many
  back/app/models/area.rb
  back/app/models/areas_static_page.rb
  back/app/models/static_page.rb
  back/app/models/static_pages_topic.rb
  back/app/models/topic.rb
  back/db/migrate/20221111132019_create_page_projects_filter_join_tables.rb
  back/db/schema.rb
  back/spec/acceptance/admin_publications_spec.rb
  back/spec/models/static_page_spec.rb
Labels: structure

#3237 [CL-1318] Add email analytics card
  front/app/modules/commercial/analytics/admin/components/EmailDeliveriesCard/Chart/generateEmptyData.ts
  front/app/modules/commercial/analytics/admin/components/EmailDeliveriesCard/Chart/index.tsx
  front/app/modules/commercial/analytics/admin/components/EmailDeliveriesCard/Chart/renderTooltip.tsx
  front/app/modules/commercial/analytics/admin/components/EmailDeliveriesCard/EmailDeliveriesStats.tsx
  front/app/modules/commercial/analytics/admin/components/EmailDeliveriesCard/index.tsx
  front/app/modules/commercial/analytics/admin/components/EmailDeliveriesCard/messages.ts
  front/app/modules/commercial/analytics/admin/hooks/useEmailDeliveries/index.ts
  front/app/modules/commercial/analytics/admin/hooks/useEmailDeliveries/messages.ts
  front/app/modules/commercial/analytics/admin/hooks/useEmailDeliveries/parse.test.ts
  front/app/modules/commercial/analytics/admin/hooks/useEmailDeliveries/parse.ts
  front/app/modules/commercial/analytics/admin/hooks/useEmailDeliveries/translations.ts
  front/app/modules/commercial/analytics/admin/hooks/useEmailDeliveries/typings.ts
  front/app/modules/commercial/analytics/admin/hooks/useEmailDeliveries/utils.ts
  front/app/modules/commercial/analytics/admin/services/analyticsFacts.ts
  front/app/modules/commercial/analytics/index.tsx
  front/app/translations/admin/en.json
  front/app/utils/moduleUtils.tsx
Labels: insights

#3235 [CL-1823] Add advanced custom pages feature flag
  back/config/schemas/settings.schema.json.erb
  front/app/services/__mocks__/appConfiguration.ts
  front/app/services/appConfiguration.ts
Labels: structure

#3257 [CL-1959] BulkDeleteUsersJob - Batch not found user emails into one Sentry error
  back/engines/commercial/admin_api/app/jobs/admin_api/bulk_delete_users_job.rb
  back/engines/commercial/admin_api/spec/acceptance/users_spec.rb
Labels: structure

#3252 Cl 2076 fe skip this step is shown when skipping is not possible verification
  CHANGELOG.md
  front/app/components/AssignBudgetControl/index.tsx
  front/app/containers/ProjectsShowPage/shared/pb/PBExpenses.tsx
  front/app/modules/commercial/verification/citizen/components/VerificationMethods.tsx
  front/app/modules/commercial/verification/citizen/components/VerificationStatus.tsx
  front/app/utils/helperUtils.ts
Labels: structure

#3253 Cl 573/proposals feature toggle
  CHANGELOG.md
  front/app/components/InitiativeCards/ProposalsList.tsx
  front/app/containers/Admin/initiatives/index.tsx
  front/app/containers/Admin/initiatives/messages.ts
  front/app/containers/Admin/initiatives/settings/ProposalsFeatureToggle.tsx
  front/app/containers/Admin/initiatives/settings/VotingLimit.tsx
  front/app/containers/Admin/initiatives/settings/VotingThreshold.tsx
  front/app/containers/Admin/initiatives/settings/index.tsx
  front/app/containers/Admin/sideBar/index.tsx
  front/app/services/appConfiguration.ts
  front/app/translations/admin/ar-MA.json
  front/app/translations/admin/ar-SA.json
  front/app/translations/admin/ca-ES.json
  front/app/translations/admin/da-DK.json
  front/app/translations/admin/de-DE.json
  front/app/translations/admin/el-GR.json
  front/app/translations/admin/en-CA.json
  front/app/translations/admin/en-GB.json
  front/app/translations/admin/en.json
  front/app/translations/admin/es-CL.json
  front/app/translations/admin/es-ES.json
  front/app/translations/admin/fr-BE.json
  front/app/translations/admin/fr-FR.json
  front/app/translations/admin/hr-HR.json
  front/app/translations/admin/hu-HU.json
  front/app/translations/admin/it-IT.json
  front/app/translations/admin/kl-GL.json
  front/app/translations/admin/lb-LU.json
  front/app/translations/admin/lv-LV.json
  front/app/translations/admin/mi.json
  front/app/translations/admin/nb-NO.json
  front/app/translations/admin/nl-BE.json
  front/app/translations/admin/nl-NL.json
  front/app/translations/admin/pl-PL.json
  front/app/translations/admin/pt-BR.json
  front/app/translations/admin/ro-RO.json
  front/app/translations/admin/sr-Latn.json
  front/app/translations/admin/sv-SE.json
  front/app/translations/admin/tr-TR.json
Labels: structure

#3251 [CL-1960] Fix Sentry Error NoMethodError MachineTranslations
  back/engines/commercial/machine_translations/app/controllers/machine_translations/web_api/v1/machine_translations_controller.rb
  back/engines/commercial/machine_translations/app/services/machine_translations/machine_translation_service.rb
  back/engines/commercial/machine_translations/spec/acceptance/machine_translations_spec.rb
Labels: structure

#3278 [CL-2114] Use medium resource_class for back-lint CI
  .circleci/config.yml
Labels: structure

#3279 CL-2086 Remove user_custom_fields feature flag
  back/engines/commercial/user_custom_fields/lib/user_custom_fields/engine.rb
  back/engines/commercial/user_custom_fields/lib/user_custom_fields/feature_specifications/representativeness.rb
  back/engines/commercial/user_custom_fields/lib/user_custom_fields/feature_specifications/user_custom_fields.rb
  back/engines/commercial/user_custom_fields/spec/lib/app_configuration/settings_spec.rb
  front/app/containers/Admin/settings/registration/CustomFieldSettings/index.tsx
  front/app/services/appConfiguration.ts
Labels: insights

#3293 CL-2102 Move Customizable Navbar into core
  back/Gemfile.lock
  back/app/controllers/web_api/v1/nav_bar_items_controller.rb
  back/app/controllers/web_api/v1/static_pages_controller.rb
  back/app/policies/nav_bar_item_policy.rb
  back/app/policies/static_page_policy.rb
  back/app/serializers/web_api/v1/static_page_serializer.rb
  back/config/routes.rb
  back/doc/dependency_decisions.yml
  back/engines/free/customizable_navbar/README.md
  back/engines/free/customizable_navbar/app/controllers/customizable_navbar/web_api/v1/nav_bar_items_controller.rb
  back/engines/free/customizable_navbar/app/controllers/customizable_navbar/web_api/v1/patches/static_pages_controller.rb
  back/engines/free/customizable_navbar/app/policies/customizable_navbar/extensions/nav_bar_item_policy.rb
  back/engines/free/customizable_navbar/app/policies/customizable_navbar/patches/static_page_policy.rb
  back/engines/free/customizable_navbar/config/routes.rb
  back/engines/free/customizable_navbar/customizable_navbar.gemspec
  back/engines/free/customizable_navbar/lib/customizable_navbar.rb
  back/engines/free/customizable_navbar/lib/customizable_navbar/engine.rb
  back/engines/free/customizable_navbar/lib/customizable_navbar/version.rb
  back/engines/free/customizable_navbar/spec/acceptance/nav_bar_items_spec.rb
  back/engines/free/customizable_navbar/spec/acceptance/static_pages_spec.rb
  back/spec/acceptance/nav_bar_items_spec.rb
  back/spec/acceptance/static_pages_spec.rb
Labels: structure

#3249 [CL-1823] Hide advanced custom page configuration behinde feature flag
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/CustomPageSettingsForm/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/Edit/Content/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/EditHomepage/index.tsx
Labels: structure

#3318 [CL-1962] Sentry - ActiveJob::DeserializationError LogActivityJob
  back/app/services/side_fx_vote_service.rb
  back/spec/services/side_fx_vote_spec.rb
Labels: structure

#3328 Cl 1845 signed in banner responsiveness
  CHANGELOG.md
  front/app/containers/App/index.tsx
  front/app/containers/HomePage/SignedInHeader.tsx
  front/app/containers/HomePage/SignedInHeader/AcceptButton.tsx
  front/app/containers/HomePage/SignedInHeader/CompleteProfileStep.tsx
  front/app/containers/HomePage/SignedInHeader/CustomCTAStep.tsx
  front/app/containers/HomePage/SignedInHeader/FallbackStep.tsx
  front/app/containers/HomePage/SignedInHeader/HeaderImage.tsx
  front/app/containers/HomePage/SignedInHeader/OnboardingStep.tsx
  front/app/containers/HomePage/SignedInHeader/SkipButton.tsx
  front/app/containers/HomePage/SignedInHeader/VerificationOnboardingStep.tsx
  front/app/containers/HomePage/SignedInHeader/index.tsx
  front/app/containers/HomePage/VerificationOnboardingStep.tsx
  front/app/containers/HomePage/index.tsx
  front/app/hooks/useCurrentOnboardingCampaign.ts
  front/app/resources/GetOnboardingCampaigns.tsx
  front/app/services/onboardingCampaigns.ts
Labels: structure

#3228 [CL-1155] Fe show notice in back office when tags/areas can't be deleted
  back/app/controllers/web_api/v1/areas_controller.rb
  back/app/controllers/web_api/v1/topics_controller.rb
  back/app/serializers/web_api/v1/area_serializer.rb
  back/app/serializers/web_api/v1/topic_serializer.rb
  front/app/containers/Admin/settings/areas/all/index.tsx
  front/app/containers/Admin/settings/areas/messages.ts
  front/app/hooks/useAreas.ts
  front/app/hooks/useTopics.ts
  front/app/modules/commercial/custom_topics/admin/components/CustomTopicRow.tsx
  front/app/modules/commercial/custom_topics/admin/components/messages.ts
  front/app/modules/commercial/custom_topics/admin/containers/TopicsSettings/all/index.tsx
  front/app/services/areas.ts
  front/app/services/topics.ts
  front/app/translations/admin/en.json
Labels: structure

#3351 [CL-2061] Disable projects/events sections when project filter is none
  front/app/containers/Admin/pagesAndMenu/components/SectionToggle/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/Edit/Content/index.tsx
Labels: structure

#3350 [SLS-110] Add rake task to create API client
  back/engines/commercial/public_api/lib/tasks/public_api_tasks.rake
Labels: structure

#3156 Restrict passing empty folder to only admins
  front/app/modules/commercial/admin_project_templates/admin/components/UseTemplateModal.tsx
  front/app/modules/commercial/admin_project_templates/admin/components/messages.ts
  front/app/translations/admin/en.json
Labels: waiting for translations, methods

#3355 [CL-2061] Hide projects/events sections when project filter is none
  front/app/containers/Admin/pagesAndMenu/components/SectionToggle/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/Edit/Content/index.tsx
Labels: structure

#3336 [CL-2041] Add flexible row for form builder fields
  front/app/containers/Admin/formBuilder/components/FormFields/index.tsx
  front/app/containers/Admin/formBuilder/components/SortableRow/FlexibleRow/index.tsx
  front/app/containers/Admin/formBuilder/components/SortableRow/SortableRow.test.tsx
  front/app/containers/Admin/formBuilder/components/SortableRow/index.tsx
  front/package-lock.json
  front/package.json
Labels: methods

#3362 Cl 2057 changes brent
  front/app/components/HookForm/SlugInput/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/CustomPageSettingsForm/index.tsx
Labels: structure

#3208 Cl 2026 fe citizen facing show linked projects list
  front/app/components/ProjectAndFolderCards/ProjectAndFolderCardsInner.tsx
  front/app/components/ProjectAndFolderCards/components/ProjectsTabPanel.tsx
  front/app/components/ProjectAndFolderCards/components/PublicationStatusTabs.tsx
  front/app/components/ProjectAndFolderCards/components/getCardSizes.ts
Labels: structure

#3353 [CL-2057] Release 3: Various small UI changes
  front/app/components/HookForm/SlugInput/index.tsx
  front/app/components/UI/Tabs/index.tsx
  front/app/containers/Admin/pagesAndMenu/components/StickyContainer.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/CustomPageSettingsForm/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/Edit/ViewCustomPageButton.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/messages.ts
  front/app/translations/admin/en.json
Labels: structure

#3210 CL-2024 fe citizen facing show events
  front/app/components/LandingPages/citizen/EventsWidget.tsx
  front/app/components/LandingPages/citizen/messages.ts
  front/app/containers/CustomPageShow/CustomPageEvents.tsx
  front/app/containers/CustomPageShow/index.tsx
  front/app/containers/EventsPage/index.tsx
  front/app/containers/HomePage/index.tsx
  front/app/containers/HomePage/messages.ts
  front/app/hooks/useAdminPublications.ts
  front/app/hooks/useAdminPublicationsStatusCounts.ts
  front/app/hooks/useEvents.ts
  front/app/hooks/useIdeaMarkers.ts
  front/app/modules/commercial/events_widget/citizen/TopBar.tsx
  front/app/modules/commercial/events_widget/index.tsx
  front/cypress/e2e/admin/pages_and_menu/update_homepage_text_content_and_sections.cy.ts
  front/package-lock.json
  package-lock.json
Labels: structure
