Repository CitizenLabDotCo/citizenlab, pull requests merged in 2022-04, with the labels that each got.

#1748 [CL-547] Copy and UI changes per design review
  front/app/containers/Admin/messaging/texting/CampaignList/TextCampaignListRow.tsx
  front/app/containers/Admin/messaging/texting/ExistingSMSCampaign/index.tsx
  front/app/containers/Admin/messaging/texting/NewSMSCampaign/index.tsx
  front/app/containers/Admin/messaging/texting/SMSCampaignPreview/index.tsx
  front/app/containers/Admin/messaging/texting/components/SMSCampaignForm.tsx
Labels: structure, Texting MVP

#1730 Phone number validation New/EditSMSCampaign
  front/app/containers/Admin/messaging/routes.ts
  front/app/containers/Admin/messaging/texting/CampaignList/TextCampaignListRow.tsx
  front/app/containers/Admin/messaging/texting/CreatedSMSCampaignForm/index.tsx
  front/app/containers/Admin/messaging/texting/ExistingSMSCampaign/index.tsx
  front/app/containers/Admin/messaging/texting/NewSMSCampaign/index.tsx
  front/app/containers/Admin/messaging/texting/SMSCampaignPreview/index.tsx
  front/app/containers/Admin/messaging/texting/components/FormattedStatusLabel.tsx
  front/app/containers/Admin/messaging/texting/components/RemainingCharacters.tsx
  front/app/containers/Admin/messaging/texting/components/SMSCampaignForm.tsx
  front/app/hooks/useTextingCampaign.ts
  front/app/services/textingCampaigns.ts
Labels: structure, Texting MVP

#1786 [CL-529] Do not check GA in consent because it was disabled
  front/cypress/integration/cookie_consent.ts
Labels: structure

#1784 [CL-487] a11y audit 2.4.7: Focus Outline
  CHANGELOG.md
  front/app/components/ConsentManager/Banner.tsx
Labels: structure

#1785 [CL-571] Add support for Croatian language
  CHANGELOG.md
  back/config/blocked_words/hr.txt
  back/config/initializers/1_locales.rb
  front/app/containers/App/constants.js
  front/app/containers/App/constants.ts
  front/app/i18n/hr-HR.ts
  front/app/translations/admin/hr-HR.json
  front/app/translations/hr-HR.json
Labels: structure

#1778 [CL-482] a11y functionality events
  CHANGELOG.md
  front/app/components/PostShowComponents/Comments/CommentBody.tsx
  front/app/containers/ProjectsShowPage/shared/events/index.tsx
  front/app/containers/ProjectsShowPage/shared/header/ProjectActionButtons.tsx
  front/app/containers/ProjectsShowPage/shared/header/ProjectInfoSideBar.tsx
  front/app/utils/scroll.ts
Labels: structure

#1805 Remove Admin guide components
  front/app/containers/Admin/guide/AdminGuideArticle.tsx
  front/app/containers/Admin/guide/DecideSection.tsx
  front/app/containers/Admin/guide/EngageSection.tsx
  front/app/containers/Admin/guide/ManageSection.tsx
  front/app/containers/Admin/guide/SetupSection.tsx
  front/app/containers/Admin/guide/index.tsx
  front/app/containers/Admin/guide/messages.ts
  front/app/containers/Admin/guide/tracks.ts
  front/app/containers/Admin/routes.ts
  front/app/containers/Admin/sideBar/index.tsx
  front/app/modules/commercial/widgets/admin/components/GuideArticle.tsx
  front/app/modules/commercial/widgets/admin/messages.ts
  front/app/modules/commercial/widgets/index.tsx
  front/app/translations/admin/ar-SA.json
  front/app/translations/admin/da-DK.json
  front/app/translations/admin/de-DE.json
  front/app/translations/admin/en-CA.json
  front/app/translations/admin/en-GB.json
  front/app/translations/admin/en.json
  front/app/translations/admin/es-CL.json
  front/app/translations/admin/es-ES.json
  front/app/translations/admin/fr-BE.json
  front/app/translations/admin/fr-FR.json
  front/app/translations/admin/hu-HU.json
  front/app/translations/admin/it-IT.json
  front/app/translations/admin/kl-GL.json
  front/app/translations/admin/lb-LU.json
  front/app/translations/admin/mi.json
  front/app/translations/admin/nb-NO.json
  front/app/translations/admin/nl-BE.json
  front/app/translations/admin/nl-NL.json
  front/app/translations/admin/pl-PL.json
  front/app/translations/admin/pt-BR.json
  front/app/translations/admin/ro-RO.json
  front/app/translations/admin/sr-Latn.json
  front/app/utils/moduleUtils.ts
Labels: structure

#1821 [CL-482] Show more/less a11y fix
  CHANGELOG.md
  front/app/components/EventCard/EventInformation/index.tsx
  front/app/components/UI/QuillEditedContent/QuillEditedContent.test.tsx
  front/app/components/UI/QuillEditedContent/index.tsx
  front/app/containers/ProjectsShowPage/shared/header/ProjectInfo.tsx
  front/app/modules/commercial/project_folders/citizen/containers/ProjectFolderShowPage/ProjectFolderDescription.tsx
Labels: structure

#1775 CL-476 Accessibility: Correct HTML elements
  front/app/containers/EventsPage/index.tsx
  front/app/hooks/fixtures/pages.ts
Labels: structure

#1800 Remove modal no close prop
  front/app/components/SignUpIn/SignUpInModal.tsx
  front/app/components/UI/Modal/index.tsx
  front/app/containers/ProjectsShowPage/shared/header/ProjectSharingModal.tsx
  front/app/modules/commercial/project_folders/citizen/components/ProjectFolderSharingModal/index.tsx
Labels: structure

#1789 CL-527 SMS copy updates
  CHANGELOG.md
  front/app/containers/Admin/messaging/index.tsx
  front/app/containers/Admin/messaging/messages.ts
  front/app/translations/admin/ar-SA.json
  front/app/translations/admin/da-DK.json
  front/app/translations/admin/de-DE.json
  front/app/translations/admin/en-CA.json
  front/app/translations/admin/en-GB.json
  front/app/translations/admin/en.json
  front/app/translations/admin/es-CL.json
  front/app/translations/admin/es-ES.json
  front/app/translations/admin/fr-BE.json
  front/app/translations/admin/fr-FR.json
  front/app/translations/admin/hr-HR.json
  front/app/translations/admin/hu-HU.json
  front/app/translations/admin/it-IT.json
  front/app/translations/admin/kl-GL.json
  front/app/translations/admin/lb-LU.json
  front/app/translations/admin/mi.json
  front/app/translations/admin/nb-NO.json
  front/app/translations/admin/nl-BE.json
  front/app/translations/admin/nl-NL.json
  front/app/translations/admin/pl-PL.json
  front/app/translations/admin/pt-BR.json
  front/app/translations/admin/ro-RO.json
  front/app/translations/admin/sr-Latn.json
Labels: structure, Texting MVP

#1803 CL-494 Accessibility: Label email confirmation
  CHANGELOG.md
  front/app/modules/free/user_confirmation/citizen/components/ConfirmationSignupStep.tsx
  front/app/modules/free/user_confirmation/citizen/components/messages.ts
  front/app/translations/ar-SA.json
  front/app/translations/da-DK.json
  front/app/translations/de-DE.json
  front/app/translations/en-CA.json
  front/app/translations/en-GB.json
  front/app/translations/en.json
  front/app/translations/es-CL.json
  front/app/translations/es-ES.json
  front/app/translations/fr-BE.json
  front/app/translations/fr-FR.json
  front/app/translations/hr-HR.json
  front/app/translations/hu-HU.json
  front/app/translations/it-IT.json
  front/app/translations/kl-GL.json
  front/app/translations/lb-LU.json
  front/app/translations/mi.json
  front/app/translations/nb-NO.json
  front/app/translations/nl-BE.json
  front/app/translations/nl-NL.json
  front/app/translations/pl-PL.json
  front/app/translations/pt-BR.json
  front/app/translations/ro-RO.json
  front/app/translations/sr-Latn.json
  front/app/translations/sr-SP.json
  front/package-lock.json
Labels: structure

#1847 [CL-497] Add proper aria labels to nav components
  CHANGELOG.md
  front/app/containers/MainHeader/DesktopNavbar/index.tsx
  front/app/containers/MainHeader/messages.ts
  front/app/containers/PlatformFooter/index.tsx
  front/app/containers/PlatformFooter/messages.ts
  front/app/translations/en.json
Labels: waiting for translations, structure
