Repository CitizenLabDotCo/citizenlab, pull requests merged in 2022-06, with the labels that each got.

#2090 [react-router] [react-router] Fix react-router index routes
  front/app/containers/IdeasNewPage/index.tsx
  front/app/containers/IdeasShow/index.tsx
  front/app/containers/InitiativesShow/index.tsx
  front/app/services/locale.ts
Labels: structure, react-router

#1985 CL-810 Routing LoadingComponent v1
  front/app/components/UI/LoadableLoading/index.tsx
  front/app/components/UI/PageLoading/index.tsx
  front/app/components/UserDeletedModalContent/LoadableUserDeleted.tsx
  front/app/containers/Admin/dashboard/routes.tsx
  front/app/containers/Admin/ideas/routes.tsx
  front/app/containers/Admin/initiatives/routes.tsx
  front/app/containers/Admin/invitations/routes.tsx
  front/app/containers/Admin/messaging/routes.tsx
  front/app/containers/Admin/pages/routes.tsx
  front/app/containers/Admin/projects/routes.tsx
  front/app/containers/Admin/routes.tsx
  front/app/containers/Admin/settings/routes.tsx
  front/app/containers/Admin/users/routes.tsx
  front/app/containers/App/UserDeletedModal/illustration.png
  front/app/containers/App/UserDeletedModal/index.tsx
  front/app/containers/App/UserDeletedModal/messages.ts
  front/app/containers/App/index.tsx
  front/app/modules/commercial/project_folders/permissions/rules.ts
  front/app/routes.tsx
  front/app/services/permissions/rules/routePermissions.ts
  front/app/utils/moduleUtils.tsx
Labels: structure, react-router

#2101 Cl 904/folder routes
  front/app/containers/Admin/projects/routes.tsx
  front/app/modules/commercial/project_folders/admin/containers/index.tsx
  front/app/modules/commercial/project_folders/admin/containers/settings/ProjectFolderForm.tsx
  front/app/modules/commercial/project_folders/index.tsx
  front/app/utils/moduleUtils.tsx
Labels: structure, react-router

#2104 [react-router] [CL-867] Fix admins - projects - project tests
  front/app/components/admin/TabbedResource/index.tsx
  front/app/containers/Admin/projects/project/__snapshots__/index.test.tsx.snap
  front/app/containers/Admin/projects/project/index.test.tsx
  front/app/services/__mocks__/phases.ts
  front/app/services/participationContexts.ts
  front/app/services/phases.ts
Labels: structure, react-router

#2188 CL-896 Add test to seedfile spec
  back/spec/db/seedfile_spec.rb
Labels: structure, Flexible Pages

#2185 [CL-895] Add Pin model & join table for pinned admin publications
  back/app/models/admin_publication.rb
  back/app/models/home_page.rb
  back/app/models/pin.rb
  back/db/migrate/20220614135644_create_pages_and_pins.rb
  back/db/schema.rb
  back/spec/models/pin_spec.rb
Labels: Flexible Pages

#2202 [CL-895] Accept nested attributes for pins in HomePage
  back/app/models/home_page.rb
Labels: Flexible Pages

#2204 CL-1016 Rename two fields to original names
  back/app/models/home_page.rb
  back/db/migrate/20220620101315_rename_field_names_in_home_pages.rb
  back/db/schema.rb
Labels: structure, Flexible Pages

#2211 [CL-899] Add web endpoint to show/update home page
  back/app/controllers/web_api/v1/home_pages_controller.rb
  back/app/models/home_page.rb
  back/app/policies/home_page_policy.rb
  back/app/serializers/web_api/v1/home_page_serializer.rb
  back/config/routes.rb
  back/spec/acceptance/home_pages_spec.rb
Labels: Flexible Pages

#2201 CL-975 Make sharing options consistent
  CHANGELOG.md
  front/app/components/PostShowComponents/SharingModalContent/index.tsx
  front/app/components/PostShowComponents/SharingModalContent/messages.ts
  front/app/components/Sharing/SharingButtons/index.tsx
  front/app/components/Sharing/SharingDropdownButton/SharingDropdownContent.tsx
  front/app/components/Sharing/SharingDropdownButton/index.tsx
  front/app/components/Sharing/buttons/CopyLink.tsx
  front/app/components/Sharing/buttons/Email.tsx
  front/app/components/Sharing/buttons/Facebook.tsx
  front/app/components/Sharing/buttons/Messenger.tsx
  front/app/components/Sharing/buttons/Twitter.tsx
  front/app/components/Sharing/buttons/WhatsApp.tsx
  front/app/components/Sharing/messages.ts
  front/app/containers/IdeasShow/Buttons/IdeaSharingButton.test.tsx
  front/app/containers/IdeasShow/Buttons/IdeaSharingButton.tsx
  front/app/containers/IdeasShow/CTABox/Buttons/index.tsx
  front/app/containers/IdeasShow/RightColumnDesktop/index.tsx
  front/app/containers/IdeasShow/index.tsx
  front/app/containers/IdeasShow/messages.ts
  front/app/containers/InitiativesShow/index.tsx
  front/app/containers/InitiativesShow/messages.ts
  front/app/containers/ProjectsShowPage/messages.ts
  front/app/containers/ProjectsShowPage/shared/header/ProjectSharingModal.tsx
  front/app/modules/commercial/project_folders/citizen/components/ProjectFolderSharingModal/index.tsx
  front/app/modules/commercial/project_folders/citizen/components/ProjectFolderSharingModal/messages.ts
  front/app/translations/en.json
  front/app/utils/testUtils/rtl.tsx
  front/package-lock.json
  front/package.json
Labels: waiting for translations

#2249 [CL-898] Use AppHeaderBgUploader in HomePage model
  back/app/models/home_page.rb
Labels: structure, Flexible Pages

#2186 [CL-949] Add descriptive text to area display radio buttons
  CHANGELOG.md
  front/app/containers/Admin/projects/project/general/components/GeographicAreaInputs.tsx
  front/app/containers/Admin/projects/project/general/messages.ts
  front/app/containers/Admin/projects/project/participationContext/components/ParticipationMethodPicker.tsx
  front/app/containers/Admin/projects/project/participationContext/components/labels.tsx
  front/app/translations/admin/en.json
Labels: waiting for translations

#2267 CL-1066 Rename home page fields
  back/app/controllers/web_api/v1/home_pages_controller.rb
  back/app/models/home_page.rb
  back/app/serializers/web_api/v1/home_page_serializer.rb
  back/db/migrate/20220630084221_rename_fields_in_home_pages.rb
  back/db/schema.rb
  back/spec/acceptance/home_pages_spec.rb
  back/spec/models/home_page_spec.rb
Labels: structure, Flexible Pages
