Repository CitizenLabDotCo/citizenlab, pull requests merged in 2022-12, with the labels that each got.

#3365 Clean up of SectionToggleData
  front/app/containers/Admin/pagesAndMenu/components/SectionToggle/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/Edit/Content/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/EditHomepage/index.tsx
  front/app/modules/commercial/events_widget/admin/SectionToggle.tsx
Labels: structure

#3180 CL-1933 Reorganize overview dashboard
  front/app/components/admin/GraphWrappers/index.tsx
  front/app/containers/Admin/dashboard/components/filters/GroupFilter.tsx
  front/app/containers/Admin/dashboard/components/filters/ProjectFilter.tsx
  front/app/containers/Admin/dashboard/components/filters/TopicFilter.tsx
  front/app/containers/Admin/dashboard/components/filters/messages.ts
  front/app/containers/Admin/dashboard/messages.ts
  front/app/containers/Admin/dashboard/overview/ChartFilters.tsx
  front/app/containers/Admin/dashboard/overview/charts/SelectableResourceChart.tsx
  front/app/containers/Admin/dashboard/overview/index.tsx
  front/app/containers/Admin/dashboard/overview/messages.ts
  front/app/containers/Admin/dashboard/users/ChartFilters.tsx
  front/app/containers/Admin/dashboard/users/index.tsx
  front/app/modules/commercial/analytics/admin/containers/Events.tsx
  front/app/modules/commercial/analytics/admin/containers/Invitations.tsx
  front/app/modules/commercial/analytics/admin/containers/ProjectStatus.tsx
  front/app/modules/commercial/analytics/admin/containers/Proposals.tsx
  front/app/modules/commercial/analytics/admin/containers/Visitors/Charts.tsx
  front/app/translations/admin/ar-MA.json
  front/app/translations/admin/ar-SA.json
  front/app/translations/admin/ca-ES.json
  front/app/translations/admin/da-DK.json
  front/app/translations/admin/de-DE.json
  front/app/translations/admin/el-GR.json
  front/app/translations/admin/en-CA.json
  front/app/translations/admin/en-GB.json
  front/app/translations/admin/en.json
  front/app/translations/admin/es-CL.json
  front/app/translations/admin/es-ES.json
  front/app/translations/admin/fr-BE.json
  front/app/translations/admin/fr-FR.json
  front/app/translations/admin/hr-HR.json
  front/app/translations/admin/hu-HU.json
  front/app/translations/admin/it-IT.json
  front/app/translations/admin/kl-GL.json
  front/app/translations/admin/lb-LU.json
  front/app/translations/admin/lv-LV.json
  front/app/translations/admin/mi.json
  front/app/translations/admin/nb-NO.json
  front/app/translations/admin/nl-BE.json
  front/app/translations/admin/nl-NL.json
  front/app/translations/admin/pl-PL.json
  front/app/translations/admin/pt-BR.json
  front/app/translations/admin/ro-RO.json
  front/app/translations/admin/sr-Latn.json
  front/app/translations/admin/sv-SE.json
  front/app/translations/admin/tr-TR.json
Labels: insights

#3346 [CL-2109] Use event viewer in project page
  CHANGELOG.md
  front/app/components/EventCard/EventInformation/EventInformation.test.tsx
  front/app/components/EventCard/EventInformation/index.tsx
  front/app/containers/EventsPage/CurrentAndUpcomingEvents.tsx
  front/app/containers/EventsPage/EventsViewer/TopBar.tsx
  front/app/containers/EventsPage/EventsViewer/index.tsx
  front/app/containers/EventsPage/PastEvents.tsx
  front/app/containers/ProjectsShowPage/index.tsx
  front/app/containers/ProjectsShowPage/shared/events/index.tsx
  front/app/translations/en.json
  front/app/utils/messages.ts
Labels: methods

#3382 [CL-1933] fix show more
  CHANGELOG.md
  front/app/containers/Admin/dashboard/overview/charts/SelectableResourceChart.tsx
Labels: insights

#3379 CL-2172 Fix empty visitors response bug
  CHANGELOG.md
  front/app/components/admin/Graphs/_components/Container.tsx
  front/app/containers/Admin/dashboard/overview/index.tsx
  front/app/modules/commercial/analytics/admin/components/ActiveUsersCard/index.tsx
  front/app/modules/commercial/analytics/admin/components/EmailDeliveriesCard/index.tsx
  front/app/modules/commercial/analytics/admin/components/RegistrationsCard/index.tsx
  front/app/modules/commercial/analytics/admin/components/VisitorsCard/VisitorsCard.test.tsx
  front/app/modules/commercial/analytics/admin/components/VisitorsCard/index.tsx
  front/app/modules/commercial/analytics/admin/hooks/useActiveUsers/index.ts
  front/app/modules/commercial/analytics/admin/hooks/useActiveUsers/parse.test.ts
  front/app/modules/commercial/analytics/admin/hooks/useActiveUsers/parse.ts
  front/app/modules/commercial/analytics/admin/hooks/useActiveUsers/query.ts
  front/app/modules/commercial/analytics/admin/hooks/useActiveUsers/typings.ts
  front/app/modules/commercial/analytics/admin/hooks/useActiveUsers/utils.ts
  front/app/modules/commercial/analytics/admin/hooks/useEmailDeliveries/index.ts
  front/app/modules/commercial/analytics/admin/hooks/useEmailDeliveries/parse.test.ts
  front/app/modules/commercial/analytics/admin/hooks/useEmailDeliveries/parse.ts
  front/app/modules/commercial/analytics/admin/hooks/useEmailDeliveries/query.ts
  front/app/modules/commercial/analytics/admin/hooks/useEmailDeliveries/typings.ts
  front/app/modules/commercial/analytics/admin/hooks/useEmailDeliveries/utils.ts
  front/app/modules/commercial/analytics/admin/hooks/useRegistrations/index.ts
  front/app/modules/commercial/analytics/admin/hooks/useRegistrations/parse.test.ts
  front/app/modules/commercial/analytics/admin/hooks/useRegistrations/parse.ts
  front/app/modules/commercial/analytics/admin/hooks/useRegistrations/query.ts
  front/app/modules/commercial/analytics/admin/hooks/useRegistrations/typings.ts
  front/app/modules/commercial/analytics/admin/hooks/useRegistrations/utils.ts
  front/app/modules/commercial/analytics/admin/hooks/useVisitors/index.ts
  front/app/modules/commercial/analytics/admin/hooks/useVisitors/parse.ts
  front/app/modules/commercial/analytics/admin/hooks/useVisitors/query.ts
  front/app/modules/commercial/analytics/admin/hooks/useVisitors/typings.ts
  front/app/modules/commercial/analytics/admin/hooks/useVisitors/utils.ts
  front/app/modules/commercial/analytics/admin/typings.ts
  front/app/modules/commercial/analytics/admin/utils/resolution.ts
  front/app/modules/commercial/analytics/admin/utils/timeSeries.test.ts
  front/app/modules/commercial/analytics/admin/utils/timeSeries.ts
Labels: insights

#3364 CL-2171 Truncate excel sheet names to 31 chars
  CHANGELOG.md
  front/app/components/admin/Graphs/_components/Container.tsx
  front/app/components/admin/ReportExportMenu/index.tsx
  front/app/containers/Admin/dashboard/overview/index.tsx
  front/app/modules/commercial/analytics/admin/components/ActiveUsersCard/index.tsx
  front/app/modules/commercial/analytics/admin/components/EmailDeliveriesCard/index.tsx
  front/app/modules/commercial/analytics/admin/components/RegistrationsCard/index.tsx
  front/app/modules/commercial/analytics/admin/components/VisitorsCard/VisitorsCard.test.tsx
  front/app/modules/commercial/analytics/admin/components/VisitorsCard/index.tsx
  front/app/modules/commercial/analytics/admin/hooks/useActiveUsers/index.ts
  front/app/modules/commercial/analytics/admin/hooks/useActiveUsers/parse.test.ts
  front/app/modules/commercial/analytics/admin/hooks/useActiveUsers/parse.ts
  front/app/modules/commercial/analytics/admin/hooks/useActiveUsers/query.ts
  front/app/modules/commercial/analytics/admin/hooks/useActiveUsers/typings.ts
  front/app/modules/commercial/analytics/admin/hooks/useActiveUsers/utils.ts
  front/app/modules/commercial/analytics/admin/hooks/useEmailDeliveries/index.ts
  front/app/modules/commercial/analytics/admin/hooks/useEmailDeliveries/parse.test.ts
  front/app/modules/commercial/analytics/admin/hooks/useEmailDeliveries/parse.ts
  front/app/modules/commercial/analytics/admin/hooks/useEmailDeliveries/query.ts
  front/app/modules/commercial/analytics/admin/hooks/useEmailDeliveries/typings.ts
  front/app/modules/commercial/analytics/admin/hooks/useEmailDeliveries/utils.ts
  front/app/modules/commercial/analytics/admin/hooks/useRegistrations/index.ts
  front/app/modules/commercial/analytics/admin/hooks/useRegistrations/parse.test.ts
  front/app/modules/commercial/analytics/admin/hooks/useRegistrations/parse.ts
  front/app/modules/commercial/analytics/admin/hooks/useRegistrations/query.ts
  front/app/modules/commercial/analytics/admin/hooks/useRegistrations/typings.ts
  front/app/modules/commercial/analytics/admin/hooks/useRegistrations/utils.ts
  front/app/modules/commercial/analytics/admin/hooks/useVisitors/index.ts
  front/app/modules/commercial/analytics/admin/hooks/useVisitors/parse.ts
  front/app/modules/commercial/analytics/admin/hooks/useVisitors/query.ts
  front/app/modules/commercial/analytics/admin/hooks/useVisitors/typings.ts
  front/app/modules/commercial/analytics/admin/hooks/useVisitors/utils.ts
  front/app/modules/commercial/analytics/admin/typings.ts
  front/app/modules/commercial/analytics/admin/utils/resolution.ts
  front/app/modules/commercial/analytics/admin/utils/timeSeries.test.ts
  front/app/modules/commercial/analytics/admin/utils/timeSeries.ts
Labels: insights

#3349 CL-2161: user should not be able to move question above first page
  front/app/containers/Admin/formBuilder/components/FormBuilderSettings/index.tsx
  front/app/containers/Admin/formBuilder/components/FormFields/index.tsx
  front/app/containers/Admin/formBuilder/components/SortableRow/index.tsx
  front/app/containers/Admin/formBuilder/containers/projects/forms/edit/index.tsx
  front/cypress/e2e/form_builder/elements/page_element.cy.ts
Labels: methods

#3393 CL-2184 Fix project status stats card
  back/db/migrate/20221202110054_update_fact_project_statuses_view.analytics.rb
  back/db/schema.rb
  back/db/views/analytics_fact_project_statuses_v02.sql
  back/engines/commercial/analytics/app/models/analytics/fact_project_status.rb
  back/engines/commercial/analytics/db/migrate/20221202105918_update_fact_project_statuses_view.rb
  back/engines/commercial/analytics/db/views/analytics_fact_project_statuses_v02.sql
  back/engines/commercial/analytics/spec/acceptance/analytics_project_statuses_spec.rb
  front/app/modules/commercial/analytics/admin/components/ProjectStatusCard/config.test.ts
  front/app/modules/commercial/analytics/admin/components/ProjectStatusCard/config.ts
Labels: insights

#3394 CL-2183 - fix survey submit bar floating on mobile for surveys created before pages
  front/app/components/UI/PageContainer/index.tsx
  front/app/containers/IdeasNewPage/WithJSONForm/Heading.tsx
Labels: methods

#3366 [CL-2174] Add test of recipients for ProjectPhaseUpcoming Notifications
  back/spec/models/notification_spec.rb
  back/spec/models/notifications/project_phase_upcoming_spec.rb
Labels: structure

#3358 [CL-2156] Only send ProjectPhaseStared mail to Users who participated in Project
  CHANGELOG.md
  back/app/models/notifications/project_phase_started.rb
  back/spec/models/notification_spec.rb
  back/spec/models/notifications/project_phase_started_spec.rb
Labels: structure

#3250 CL-1941 Content builder separate instance: Root container
  front/app/components/admin/ContentBuilder/FullscreenContentBuilder/index.tsx
  front/app/modules/commercial/content_builder/admin/containers/index.tsx
Labels: insights

#3248 CL-1941 Content builder separate instance: Other parts
  front/.vscode/settings.json
  front/app/components/admin/ContentBuilder/EditModePreview/index.tsx
  front/app/components/admin/ContentBuilder/Editor/RenderNode/index.tsx
  front/app/components/admin/ContentBuilder/Editor/RenderNode/messages.ts
  front/app/components/admin/ContentBuilder/Editor/index.tsx
  front/app/components/admin/ContentBuilder/Frame/ContentBuilderFrame.test.tsx
  front/app/components/admin/ContentBuilder/Frame/index.tsx
  front/app/components/admin/ContentBuilder/FullscreenContentBuilder/index.tsx
  front/app/components/admin/ContentBuilder/FullscreenPreview/Wrapper.tsx
  front/app/components/admin/ContentBuilder/Settings/index.tsx
  front/app/components/admin/ContentBuilder/messages.ts
  front/app/modules/commercial/content_builder/admin/components/ContentBuilderEditModePreview/EditModePreview.tsx
  front/app/modules/commercial/content_builder/admin/components/ContentBuilderEditModePreview/index.tsx
  front/app/modules/commercial/content_builder/admin/components/ContentViewer/ContentViewer.test.tsx
  front/app/modules/commercial/content_builder/admin/components/ContentViewer/Viewer/Viewer.test.tsx
  front/app/modules/commercial/content_builder/admin/components/ContentViewer/Viewer/index.tsx
  front/app/modules/commercial/content_builder/admin/components/ContentViewer/index.tsx
  front/app/modules/commercial/content_builder/admin/components/Editor/index.tsx
  front/app/modules/commercial/content_builder/admin/containers/FullscreenPreview/FullscreenPreview.test.tsx
  front/app/modules/commercial/content_builder/admin/containers/FullscreenPreview/index.tsx
  front/app/modules/commercial/content_builder/admin/containers/index.tsx
  front/app/modules/commercial/content_builder/admin/messages.ts
  front/app/modules/commercial/content_builder/index.tsx
Labels: insights

#3214 [CL-2003] logic in the BE
  back/app/models/custom_field.rb
  back/app/serializers/web_api/v1/custom_field_serializer.rb
  back/app/services/form_logic_service.rb
  back/app/services/input_ui_schema_generator_service.rb
  back/config/locales/en.yml
  back/db/migrate/20221115113353_add_logic_to_custom_fields.rb
  back/db/schema.rb
  back/engines/commercial/idea_custom_fields/app/controllers/idea_custom_fields/web_api/v1/admin/idea_custom_fields_controller.rb
  back/engines/commercial/idea_custom_fields/spec/acceptance/idea_custom_fields_spec.rb
  back/engines/commercial/user_custom_fields/spec/acceptance/user_custom_fields_spec.rb
  back/spec/serializers/web_api/v1/custom_field_serializer_spec.rb
  back/spec/services/form_logic_service_spec.rb
  back/spec/services/input_ui_schema_generator_service_spec.rb
Labels: methods

#3186 CL-2012 Report builder: iteration 1 (back-end)
  back/Gemfile.lock
  back/app/controllers/application_controller.rb
  back/db/migrate/20221118094022_create_reports.report_builder.rb
  back/db/schema.rb
  back/engines/commercial/content_builder/spec/factories/layouts.rb
  back/engines/commercial/report_builder/app/controllers/report_builder/web_api/v1/reports_controller.rb
  back/engines/commercial/report_builder/app/models/report_builder/report.rb
  back/engines/commercial/report_builder/app/policies/report_builder/report_policy.rb
  back/engines/commercial/report_builder/app/serializers/report_builder/web_api/v1/report_serializer.rb
  back/engines/commercial/report_builder/app/services/report_builder/side_fx_report_service.rb
  back/engines/commercial/report_builder/config/routes.rb
  back/engines/commercial/report_builder/db/migrate/20221109151729_create_reports.rb
  back/engines/commercial/report_builder/lib/report_builder.rb
  back/engines/commercial/report_builder/lib/report_builder/engine.rb
  back/engines/commercial/report_builder/lib/report_builder/feature_specification.rb
  back/engines/commercial/report_builder/lib/report_builder/version.rb
  back/engines/commercial/report_builder/lib/tasks/report_builder_tasks.rake
  back/engines/commercial/report_builder/report_builder.gemspec
  back/engines/commercial/report_builder/spec/acceptance/reports_spec.rb
  back/engines/commercial/report_builder/spec/factories/reports.rb
  back/engines/commercial/report_builder/spec/models/report_builder/report_spec.rb
  back/engines/commercial/report_builder/spec/policies/report_builder/report_policy_spec.rb
  back/engines/commercial/report_builder/spec/services/report_builder/side_fx_report_service_spec.rb
Labels: insights

#3399 [CL-2184] fix project status properly
  back/db/migrate/20221205112729_refactor_fact_project_statuses_view.analytics.rb
  back/db/schema.rb
  back/db/views/analytics_fact_project_statuses_v03.sql
  back/engines/commercial/analytics/db/migrate/20221205110616_refactor_fact_project_statuses_view.rb
  back/engines/commercial/analytics/db/views/analytics_fact_project_statuses_v03.sql
  back/engines/commercial/analytics/spec/acceptance/analytics_project_statuses_spec.rb
  back/engines/commercial/analytics/spec/models/analytics/fact_project_status_spec.rb
  front/app/components/admin/Graphs/Statistic/index.tsx
  front/app/modules/commercial/analytics/admin/components/ProjectStatusCard/config.test.ts
  front/app/modules/commercial/analytics/admin/components/ProjectStatusCard/config.ts
  front/app/modules/commercial/analytics/admin/components/ProjectStatusCard/index.tsx
  front/app/modules/commercial/analytics/admin/components/StatCard/index.tsx
  front/app/modules/commercial/analytics/admin/hooks/useStatCard/typings.ts
  front/cypress/e2e/project_page_poll.cy.ts
Labels: insights

#3431 [CL-2237] Bump nokigiri
  back/Gemfile
  back/Gemfile.lock
Labels: structure

#3425 Cl 2088/move banner to core
  front/app/containers/Admin/pagesAndMenu/EditHomepage/HeroBanner/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/CTASettings.test.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/CTASettings.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/messages.ts
  front/app/containers/HomePage/SignedInHeader/CTA.tsx
  front/app/containers/HomePage/SignedInHeader/FallbackStep.tsx
  front/app/containers/HomePage/SignedOutHeader/CTA.tsx
  front/app/containers/HomePage/SignedOutHeader/HeaderContent.tsx
  front/app/containers/HomePage/SignedOutHeader/TwoColumnLayout.tsx
  front/app/containers/HomePage/SignedOutHeader/TwoRowLayout.tsx
  front/app/containers/HomePage/SignedOutHeader/index.tsx
  front/app/modules/commercial/customizable_homepage_banner/admin/messages.ts
  front/app/modules/commercial/customizable_homepage_banner/index.tsx
  front/app/modules/commercial/customizable_homepage_banner/services/appConfiguration.ts
  front/app/modules/commercial/customizable_homepage_banner/services/homepageSettings.ts
  front/app/modules/index.ts
  front/app/services/homepageSettings.ts
  front/app/utils/moduleUtils.tsx
Labels: structure, platform

#3427 Cl 2231 background color of custom page
  front/app/components/EventCard/EventInformation/index.tsx
  front/app/components/LandingPages/citizen/EventsWidget.tsx
  front/app/components/LandingPages/citizen/InfoSection.tsx
  front/app/components/LandingPages/citizen/index.ts
  front/app/components/ProjectAndFolderCards/ProjectAndFolderCardsInner.tsx
  front/app/components/ProjectAndFolderCards/components/Topbar/index.tsx
  front/app/components/ProjectAndFolderCards/utils.tsx
  front/app/components/UI/FileAttachments/index.tsx
  front/app/components/admin/PostManager/components/LazyPostPreview/Idea/IdeaContent.tsx
  front/app/components/admin/PostManager/components/LazyPostPreview/Idea/VotePreview.tsx
  front/app/components/admin/PostManager/components/LazyPostPreview/Initiative/InitiativeContent.tsx
  front/app/containers/Admin/index.tsx
  front/app/containers/CustomPageShow/CustomPageProjectsAndEvents.tsx
  front/app/containers/CustomPageShow/index.tsx
  front/app/containers/HomePage/MainContent.tsx
  front/app/containers/InitiativesShow/VoteControl/SharedStyles.tsx
  front/app/containers/InitiativesShow/index.tsx
  front/app/containers/PagesShowPage/index.tsx
  front/app/containers/ProjectFolderShowPage/ProjectFolderDescription.tsx
  front/app/containers/ProjectsShowPage/shared/header/ProjectInfo.tsx
  front/app/containers/ProjectsShowPage/timeline/PhaseDescription.tsx
  front/app/modules/commercial/content_builder/admin/components/ContentViewer/Viewer/index.tsx
  front/app/modules/commercial/events_widget/index.tsx
  front/app/modules/commercial/insights/admin/containers/Insights/Edit/Categories/index.tsx
  front/app/modules/commercial/insights/admin/containers/Reports/Charts/ParticipationPerTopic.tsx
Labels: structure

#3432 Bug/fix multiple rules bug
  front/app/components/Form/Components/Controls/visibilityUtils.test.ts
  front/app/components/Form/Components/Controls/visibilityUtils.ts
Labels: methods

#3442 [CL-2249] Improve localhost images & content
  back/spec/fixtures/image17.png
Labels: structure, 10%-project

#3419 [CL-2106] Add logic settings to form builder
  back/app/services/form_logic_service.rb
  back/engines/commercial/idea_custom_fields/app/controllers/idea_custom_fields/web_api/v1/admin/idea_custom_fields_controller.rb
  back/engines/commercial/idea_custom_fields/spec/acceptance/idea_custom_fields_spec.rb
  back/spec/lib/participation_method/native_survey_spec.rb
  back/spec/services/form_logic_service_spec.rb
  back/spec/services/input_ui_schema_generator_service_spec.rb
  front/app/containers/Admin/formBuilder/components/FormBuilderSettings/ConfigMultiselectWithLocaleSwitcher/index.tsx
  front/app/containers/Admin/formBuilder/components/FormBuilderSettings/ContentSettings/index.tsx
  front/app/containers/Admin/formBuilder/components/FormBuilderSettings/LogicSettings/RuleInput.tsx
  front/app/containers/Admin/formBuilder/components/FormBuilderSettings/LogicSettings/index.tsx
  front/app/containers/Admin/formBuilder/components/FormBuilderSettings/index.tsx
  front/app/containers/Admin/formBuilder/components/FormBuilderSettings/utils.tsx
  front/app/containers/Admin/formBuilder/components/FormBuilderToolbox/index.tsx
  front/app/containers/Admin/formBuilder/components/FormFields/utils.ts
  front/app/containers/Admin/formBuilder/components/messages.ts
  front/app/containers/Admin/formBuilder/containers/projects/forms/edit/index.tsx
  front/app/containers/Admin/formBuilder/containers/projects/forms/messages.ts
  front/app/hooks/useFormCustomFields.ts
  front/app/services/formCustomFields.ts
  front/app/translations/admin/en.json
Labels: methods

#3422 CL-2001: Allow dragging and dropping pages with questions
  front/app/containers/Admin/formBuilder/components/DragAndDrop/Drag.tsx
  front/app/containers/Admin/formBuilder/components/DragAndDrop/Drop.tsx
  front/app/containers/Admin/formBuilder/components/DragAndDrop/index.tsx
  front/app/containers/Admin/formBuilder/components/FlexibleRow/index.tsx
  front/app/containers/Admin/formBuilder/components/FormFields/FieldElement.tsx
  front/app/containers/Admin/formBuilder/components/FormFields/index.tsx
  front/app/containers/Admin/formBuilder/components/FormFields/utils.ts
  front/app/containers/Admin/formBuilder/components/SortableRow/SortableRow.test.tsx
  front/app/containers/Admin/formBuilder/components/SortableRow/index.tsx
  front/app/containers/Admin/formBuilder/containers/projects/forms/edit/index.tsx
  front/app/containers/Admin/formBuilder/containers/projects/forms/edit/utils.ts
  front/package-lock.json
  front/package.json
Labels: methods

#3446 CL-2253 Add copy
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/BannerImageFields.test.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/BannerImageFields.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/LayoutSettingField/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/messages.ts
  front/app/translations/admin/ar-MA.json
  front/app/translations/admin/ar-SA.json
  front/app/translations/admin/ca-ES.json
  front/app/translations/admin/da-DK.json
  front/app/translations/admin/de-DE.json
  front/app/translations/admin/el-GR.json
  front/app/translations/admin/en-CA.json
  front/app/translations/admin/en-GB.json
  front/app/translations/admin/en.json
  front/app/translations/admin/es-CL.json
  front/app/translations/admin/es-ES.json
  front/app/translations/admin/fr-BE.json
  front/app/translations/admin/fr-FR.json
  front/app/translations/admin/hr-HR.json
  front/app/translations/admin/hu-HU.json
  front/app/translations/admin/it-IT.json
  front/app/translations/admin/kl-GL.json
  front/app/translations/admin/lb-LU.json
  front/app/translations/admin/lv-LV.json
  front/app/translations/admin/mi.json
  front/app/translations/admin/nb-NO.json
  front/app/translations/admin/nl-BE.json
  front/app/translations/admin/nl-NL.json
  front/app/translations/admin/pl-PL.json
  front/app/translations/admin/pt-BR.json
  front/app/translations/admin/ro-RO.json
  front/app/translations/admin/sr-Latn.json
  front/app/translations/admin/sv-SE.json
  front/app/translations/admin/tr-TR.json
  front/package-lock.json
  front/package.json
Labels: structure

#3461 [CL-2199] Delete geographic dashboards
  front/app/components/admin/ServerError/index.tsx
  front/app/components/admin/ServerError/messages.ts
  front/app/modules/commercial/geographic_dashboard/admin/components/Tab.tsx
  front/app/modules/commercial/geographic_dashboard/admin/components/messages.ts
  front/app/modules/commercial/geographic_dashboard/admin/containers/dashboard/IdeaPane.tsx
  front/app/modules/commercial/geographic_dashboard/admin/containers/dashboard/index.tsx
  front/app/modules/commercial/geographic_dashboard/admin/containers/dashboard/messages.ts
  front/app/modules/commercial/geographic_dashboard/admin/containers/dashboard/tracks.ts
  front/app/modules/commercial/geographic_dashboard/index.tsx
  front/app/modules/index.ts
  front/app/resources/GetGeotaggedIdeas.tsx
  front/app/services/appConfiguration.ts
  front/app/services/ideas.ts
  front/app/translations/admin/ar-MA.json
  front/app/translations/admin/ar-SA.json
  front/app/translations/admin/ca-ES.json
  front/app/translations/admin/da-DK.json
  front/app/translations/admin/de-DE.json
  front/app/translations/admin/el-GR.json
  front/app/translations/admin/en-CA.json
  front/app/translations/admin/en-GB.json
  front/app/translations/admin/en.json
  front/app/translations/admin/es-CL.json
  front/app/translations/admin/es-ES.json
  front/app/translations/admin/fr-BE.json
  front/app/translations/admin/fr-FR.json
  front/app/translations/admin/hr-HR.json
  front/app/translations/admin/hu-HU.json
  front/app/translations/admin/it-IT.json
  front/app/translations/admin/kl-GL.json
  front/app/translations/admin/lb-LU.json
  front/app/translations/admin/lv-LV.json
  front/app/translations/admin/mi.json
  front/app/translations/admin/nb-NO.json
  front/app/translations/admin/nl-BE.json
  front/app/translations/admin/nl-NL.json
  front/app/translations/admin/pl-PL.json
  front/app/translations/admin/pt-BR.json
  front/app/translations/admin/ro-RO.json
  front/app/translations/admin/sr-Latn.json
  front/app/translations/admin/sv-SE.json
  front/app/translations/admin/tr-TR.json
Labels: platform

#3462 CL-2270 epic review fixes
  front/app/containers/CustomPageShow/index.tsx
Labels: structure

#3450 Upgrade cypress
  front/package-lock.json
  front/package.json
Labels: platform

#3473 CL-2220 Add widgets to toolbox
  front/app/components/admin/ContentBuilder/Toolbox/DraggableElement.tsx
  front/app/components/admin/Graphs/_components/Container.tsx
  front/app/containers/Admin/dashboard/users/Charts/AgeChart.tsx
  front/app/containers/Admin/dashboard/users/Charts/BarChartByCategory.tsx
  front/app/containers/Admin/dashboard/users/Charts/GenderChart.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Editor/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Toolbox/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/AnalyticsChartWidget/VisitorsReportCard.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/AnalyticsChartWidget/VisitorsTrafficSourcesReportCard.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/AnalyticsChartWidget/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/AnalyticsChartWidget/messages.ts
  front/app/containers/Admin/reporting/containers/ReportBuilder/index.tsx
  front/app/containers/Admin/reporting/messages.ts
  front/app/modules/commercial/analytics/admin/components/VisitorsTrafficSourcesCard/Chart.tsx
  front/app/modules/commercial/analytics/admin/typings.ts
  front/app/translations/admin/en.json
Labels: insights

#3460 Autofix import statements
  front/.eslintrc.js
  front/package-lock.json
  front/package.json
Labels: platform

#3466 CL-1968 Move project_visibility module to core
  front/app/containers/Admin/projects/project/index.tsx
  front/app/containers/Admin/projects/project/messages.ts
  front/app/containers/Admin/projects/project/permissions/components/Tab.tsx
  front/app/containers/Admin/projects/project/permissions/containers/ProjectManagement/index.tsx
  front/app/containers/Admin/projects/project/permissions/containers/ProjectManagement/messages.ts
  front/app/containers/Admin/projects/project/permissions/containers/ProjectVisibility/GroupAvatar.tsx
  front/app/containers/Admin/projects/project/permissions/containers/ProjectVisibility/ProjectGroupsList.tsx
  front/app/containers/Admin/projects/project/permissions/containers/ProjectVisibility/index.tsx
  front/app/containers/Admin/projects/project/permissions/containers/ProjectVisibility/messages.ts
  front/app/containers/Admin/projects/project/permissions/index.tsx
  front/app/modules/README.md
  front/app/modules/commercial/flag_inappropriate_content/index.tsx
  front/app/modules/commercial/matomo/matchPath.ts
  front/app/modules/free/project_visibility/admin/components/Tab.tsx
  front/app/modules/free/project_visibility/admin/containers/messages.ts
  front/app/modules/free/project_visibility/index.tsx
  front/app/modules/index.ts
  front/app/modules/utilComponents/RenderOnNotificationType.tsx
Labels: platform

#3453 CL-1982 Ignore EE branch for e2e test trigger
  dangerfile.ts
Labels: platform

#3472 CL-1944 About report widget
  front/app/components/admin/ContentBuilder/Widgets/NoWidgetSettings/index.tsx
  front/app/components/admin/ContentBuilder/Widgets/NoWidgetSettings/messages.ts
  front/app/containers/Admin/reporting/components/ReportBuilder/Editor/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Toolbox/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/AboutReportWidget/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/AboutReportWidget/messages.ts
  front/app/containers/Admin/reporting/containers/ReportBuilder/index.tsx
  front/app/translations/admin/en.json
Labels: insights

#3508 CL-2327 Remove customizable_homepage_banner from seeds
  back/engines/commercial/multi_tenancy/db/seeds/tenants.rb
  back/engines/commercial/multi_tenancy/lib/tasks/core/create_tenant.rake
Labels: structure

#3506 Cl 2318 header image phone mobile preview bug
  CHANGELOG.md
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/BannerImageFields.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/HeaderImageDropzone.tsx
Labels: structure

#3505 Cl 2319 wrong error message multiloc field when only 1 locale
  CHANGELOG.md
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/CustomPageSettingsForm/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/messages.ts
  front/app/translations/admin/en.json
Labels: structure

#3519 [CL-2282] Explain remove_not_allowed_parents filter with comments
  back/app/services/admin_publications_filtering_service.rb
  front/app/hooks/useAdminPublications.ts
Labels: structure

#3514 CL-2273 Add copy to AdminHQ description of signed in header overlay opacity
  .circleci/config.yml
  back/config/schemas/style.schema.json
  dangerfile.ts
Labels: structure

#3492 [CL-2255] Export registration_completed_at & invite_status to User xlsx
  CHANGELOG.md
  back/app/services/xlsx_service.rb
Labels: structure

#3471 CL-1947 Survey results widget
  front/.vscode/settings.json
  front/app/containers/Admin/formBuilder/components/FormResults/FormResultsQuestion.tsx
  front/app/containers/Admin/formBuilder/components/FormResults/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Editor/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Toolbox/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/AboutReportWidget/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/AnalyticsChartWidget/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/SurveyResultsWidget/Dot.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/SurveyResultsWidget/NoResults.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/SurveyResultsWidget/PhaseFilter.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/SurveyResultsWidget/ProjectFilter.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/SurveyResultsWidget/QuestionFilter.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/SurveyResultsWidget/SurveyResults.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/SurveyResultsWidget/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/SurveyResultsWidget/messages.ts
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/SurveyResultsWidget/utils.test.ts
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/SurveyResultsWidget/utils.ts
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/constants.ts
  front/app/modules/commercial/insights/index.tsx
  front/app/translations/admin/en.json
Labels: insights

#3520 [CL-2261] Rendering project name and period to about widget
  front/app/containers/Admin/reporting/components/ReportBuilder/Toolbox/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/AboutReportWidget/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/AboutReportWidget/messages.ts
  front/app/translations/admin/en.json
Labels: insights

#3522 CL-2334 Editor tests
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/SurveyResultsWidget/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilderPage/CreateReportModal.tsx
  front/app/containers/Admin/reporting/containers/ReportBuilder/ReportBuilder.test.tsx
  front/app/containers/Admin/reporting/containers/ReportBuilderPage/ReportBuilderPage.test.tsx
  front/app/containers/Admin/reporting/containers/ReportBuilderPage/index.tsx
Labels: insights

#3523 CL-2333 Report builder widget tests
  front/app/containers/Admin/reporting/components/ReportBuilder/Editor/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Toolbox/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/AnalyticsChartWidget/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/AnalyticsChartWidget/messages.ts
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/AgeWidget/AgeCard.test.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/AgeWidget/AgeCard.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/AgeWidget/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/ChartWidgetSettings.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/GenderWidget/GenderCard.test.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/GenderWidget/GenderCard.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/GenderWidget/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/NoChartData.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/VisitorsTrafficSourcesWidget/VisitorTrafficSourcesCard.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/VisitorsTrafficSourcesWidget/VisitorsTrafficSourcesCard.test.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/VisitorsTrafficSourcesWidget/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/VisitorsWidget/VisitorsCard.test.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/VisitorsWidget/VisitorsCard.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/VisitorsWidget/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/messages.ts
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/typings.ts
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/utils.test.ts
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/utils.ts
  front/app/translations/admin/en.json
Labels: insights

#3496 [CL-2291] Handle jumping to page in CLPageLayout
  back/.rubocop_todo.yml
  back/app/models/custom_field.rb
  back/app/serializers/web_api/v1/custom_field_serializer.rb
  back/app/services/form_logic_service.rb
  back/app/services/input_ui_schema_generator_service.rb
  back/engines/commercial/idea_custom_fields/spec/acceptance/idea_custom_fields_spec.rb
  back/spec/models/custom_field_spec.rb
  back/spec/serializers/web_api/v1/custom_field_serializer_spec.rb
  back/spec/services/form_logic_service_spec.rb
  back/spec/services/input_ui_schema_generator_service_spec.rb
  back/spec/services/json_forms_service_spec.rb
  front/app/components/Form/Components/Controls/visibilityUtils.ts
  front/app/components/Form/Components/Layouts/CLPageLayout.tsx
  front/app/components/Form/index.tsx
  front/app/components/Form/utils.ts
  front/app/containers/Admin/formBuilder/components/FormBuilderSettings/ContentSettings/index.tsx
  front/app/containers/Admin/formBuilder/components/FormBuilderSettings/LogicSettings/PageRuleInput.tsx
  front/app/containers/Admin/formBuilder/components/FormBuilderSettings/LogicSettings/QuestionRuleInput.tsx
  front/app/containers/Admin/formBuilder/components/FormBuilderSettings/LogicSettings/index.tsx
  front/app/containers/Admin/formBuilder/components/FormBuilderSettings/index.tsx
  front/app/containers/Admin/formBuilder/components/FormBuilderSettings/utils.tsx
  front/app/containers/Admin/formBuilder/components/FormBuilderToolbox/index.tsx
  front/app/containers/Admin/formBuilder/components/FormFields/FieldElement.tsx
  front/app/containers/Admin/formBuilder/components/FormFields/FieldRuleDisplay/index.tsx
  front/app/containers/Admin/formBuilder/components/FormFields/index.tsx
  front/app/containers/Admin/formBuilder/components/FormFields/utils.ts
  front/app/containers/Admin/formBuilder/components/messages.ts
  front/app/containers/Admin/formBuilder/containers/projects/forms/edit/index.tsx
  front/app/services/formCustomFields.ts
  front/app/translations/admin/en.json
  front/app/utils/yup/validateLogic.ts
  front/cypress/e2e/form_builder/create_and_fill_survey.cy.ts
  front/package-lock.json
  front/package.json
Labels: methods
