Repository CitizenLabDotCo/citizenlab, pull requests merged in 2023-05, with the labels that each got.

#4739 CL-3470 Avoid flaky specs by always returning topics by ordering
  back/app/models/idea.rb
  back/app/models/initiative.rb
  back/app/models/project.rb
  back/app/models/static_page.rb
Labels: methods

#4379 Split up invalid data checker for easier debugging in production
  back/app/services/invalid_data_checker.rb
  back/engines/commercial/multi_tenancy/lib/tasks/core/invalid_data_checker.rake
Labels: methods

#4711 Change warning msgs
  front/app/containers/Admin/settings/registration/CustomFieldRoutes/RegistrationCustomFieldEdit/RegistrationCustomFieldOptions.tsx
  front/app/containers/Admin/settings/registration/CustomFieldRoutes/messages.ts
  front/app/containers/Admin/settings/registration/CustomFieldSettings/index.tsx
  front/app/containers/Admin/settings/registration/CustomFieldSettings/messages.ts
  front/app/translations/admin/ar-MA.json
  front/app/translations/admin/ar-SA.json
  front/app/translations/admin/ca-ES.json
  front/app/translations/admin/da-DK.json
  front/app/translations/admin/de-DE.json
  front/app/translations/admin/el-GR.json
  front/app/translations/admin/en-CA.json
  front/app/translations/admin/en-GB.json
  front/app/translations/admin/en.json
  front/app/translations/admin/es-CL.json
  front/app/translations/admin/es-ES.json
  front/app/translations/admin/fr-BE.json
  front/app/translations/admin/fr-FR.json
  front/app/translations/admin/hr-HR.json
  front/app/translations/admin/hu-HU.json
  front/app/translations/admin/it-IT.json
  front/app/translations/admin/kl-GL.json
  front/app/translations/admin/lb-LU.json
  front/app/translations/admin/lv-LV.json
  front/app/translations/admin/mi.json
  front/app/translations/admin/nb-NO.json
  front/app/translations/admin/nl-BE.json
  front/app/translations/admin/nl-NL.json
  front/app/translations/admin/pl-PL.json
  front/app/translations/admin/pt-BR.json
  front/app/translations/admin/ro-RO.json
  front/app/translations/admin/sr-Latn.json
  front/app/translations/admin/sr-SP.json
  front/app/translations/admin/sv-SE.json
  front/app/translations/admin/tr-TR.json
Labels: waiting for translations, structure

#4773 CL-3376 error handling
  front/app/api/authentication/getUserDataFromToken.ts
  front/app/api/authentication/sign_up/createEmailOnlyAccount.ts
  front/app/components/HookForm/PasswordInput/PasswordInput.test.tsx
  front/app/components/UI/Error/index.tsx
  front/app/containers/Authentication/Modal.tsx
  front/app/containers/Authentication/steps/BuiltInFields/index.tsx
  front/app/containers/Authentication/steps/ChangeEmail/index.tsx
  front/app/containers/Authentication/steps/CustomFields/index.tsx
  front/app/containers/Authentication/steps/EmailAndPassword/index.tsx
  front/app/containers/Authentication/steps/EmailAndPasswordSignUp/index.tsx
  front/app/containers/Authentication/steps/EmailConfirmation/index.tsx
  front/app/containers/Authentication/steps/Invitation/index.tsx
  front/app/containers/Authentication/steps/LightFlowStart/index.tsx
  front/app/containers/Authentication/steps/Password/index.tsx
  front/app/containers/Authentication/steps/Policies/EmailPolicies.tsx
  front/app/containers/Authentication/steps/Verification/VerificationSteps.tsx
  front/app/containers/Authentication/steps/Verification/index.tsx
  front/app/containers/Authentication/typings.ts
  front/app/containers/Authentication/useSteps/index.ts
  front/app/containers/Authentication/useSteps/stepConfig/index.ts
  front/app/containers/Authentication/useSteps/stepConfig/missingDataFlow.ts
  front/app/containers/Authentication/useSteps/stepConfig/newLightFlow.ts
  front/app/containers/Authentication/useSteps/stepConfig/oldSignInFlow.ts
  front/app/containers/Authentication/useSteps/stepConfig/oldSignUpFlow.ts
  front/app/containers/Authentication/useSteps/stepConfig/sharedSteps.ts
  front/app/containers/EmailChange/index.tsx
  front/app/services/invites.ts
  front/app/typings.ts
  front/app/utils/errorUtils.ts
  front/app/utils/helperUtils.ts
Labels: methods

#4776 CL3478 Put back success step
  front/app/containers/Authentication/useSteps/stepConfig/newLightFlow.ts
Labels: methods

#4775 CL-3500 SSO errors
  front/app/containers/Authentication/Modal.tsx
  front/app/containers/Authentication/events.ts
  front/app/containers/Authentication/messages.ts
  front/app/containers/Authentication/steps/AuthProviders/index.tsx
  front/app/containers/Authentication/steps/AuthProviders/messages.ts
  front/app/containers/Authentication/typings.ts
  front/app/containers/Authentication/useSteps/index.ts
  front/app/containers/Authentication/useSteps/stepConfig/newLightFlow.ts
  front/app/containers/Authentication/useSteps/stepConfig/sharedSteps.ts
Labels: methods

#4697 [CL-3455] Fix failing e2e tests related to registration i2
  front/app/components/FormBuilder/components/FormBuilderSettings/ConfigSelectWithLocaleSwitcher/index.tsx
  front/app/components/HookForm/Checkbox/index.tsx
  front/app/components/HookForm/Input/index.tsx
  front/app/components/HookForm/InputMultilocWithLocaleSwitcher/index.tsx
  front/app/components/HookForm/OptionList/index.tsx
  front/app/components/HookForm/QuillMultilocWithLocaleSwitcher/index.tsx
  front/app/components/HookForm/RadioGroup/index.tsx
  front/app/components/HookForm/Select/index.tsx
  front/app/components/HookForm/Tabs/index.tsx
  front/app/components/HookForm/TextArea/index.tsx
  front/app/components/HookForm/TextAreaMultilocWithLocaleSwitcher/index.tsx
  front/app/components/HookForm/Toggle/index.tsx
  front/app/components/PostShowComponents/Comments/Comment/CommentVote/UpvoteButton.tsx
  front/app/components/UserCustomFieldsForm/index.tsx
  front/app/components/admin/GranularPermissions/PermissionCardButton/index.tsx
  front/app/containers/Admin/routes.tsx
  front/app/containers/Authentication/steps/EmailConfirmation/index.tsx
  front/app/containers/Authentication/steps/Policies/PoliciesMarkup.tsx
  front/app/containers/Authentication/steps/Success/index.tsx
  front/app/containers/Authentication/steps/VerificationSuccess/index.tsx
  front/app/modules/commercial/granular_permissions/admin/containers/Granular/ActionForm.tsx
  front/cypress/e2e/blocked-users.cy.ts
  front/cypress/e2e/budgeting_permissions.cy.ts
  front/cypress/e2e/comment_voting_permissions.cy.ts
  front/cypress/e2e/email_consent.cy.ts
  front/cypress/e2e/idea_commenting_permissions.cy.ts
  front/cypress/e2e/idea_page_action.cy.ts
  front/cypress/e2e/idea_posting_permissions.cy.ts
  front/cypress/e2e/idea_voting_permissions.cy.ts
  front/cypress/e2e/impact_tracking.cy.ts
  front/cypress/e2e/landing_page.cy.ts
  front/cypress/e2e/native_survey_page_action.cy.ts
  front/cypress/e2e/profile-verification.cy.ts
  front/cypress/e2e/profile_edition.cy.ts
  front/cypress/e2e/project_page_ideas.cy.ts
  front/cypress/e2e/project_page_native_survey.cy.ts
  front/cypress/e2e/project_page_poll.cy.ts
  front/cypress/e2e/proposal_page_action.cy.ts
  front/cypress/e2e/sign_in.cy.ts
  front/cypress/e2e/sign_up_custom_fields.cy.ts
  front/cypress/e2e/sign_up_email_password.cy.ts
  front/cypress/e2e/survey_builder/create_and_fill_survey.cy.ts
  front/cypress/e2e/verification_modal.cy.ts
  front/cypress/support/commands.ts
Labels: methods

#4737 [CL-3501] Serialize new multiloc for weekly campaign schedules
  back/app/services/localization_service.rb
  back/config/locales/en.yml
  back/engines/free/email_campaigns/app/models/concerns/email_campaigns/schedulable.rb
  back/engines/free/email_campaigns/app/serializers/email_campaigns/web_api/v1/campaign_serializer.rb
  back/engines/free/email_campaigns/config/locales/en.yml
  back/spec/services/localization_service_spec.rb
Labels: structure

#4777 [CL-3257] Rake task to update specific custom field title_multiloc value
  back/engines/commercial/multi_tenancy/lib/tasks/core/update_custom_field.rake
Labels: structure

#4787 [CL-3420] Enable 2 skipped tests
  back/spec/services/localization_service_spec.rb
Labels: structure

#4795 CL-3291 - Fix volunteering causes reordering
  front/app/api/causes/useReorderCause.test.ts
  front/app/api/causes/useReorderCause.ts
Labels: methods

#4766 CL-3496: Inconsistent data fix: Blank initiative status change for draft initiatives
  back/app/models/initiative.rb
Labels: methods

#4677 CL-3410 Topics
  front/app/api/topics/__mocks__/useTopics.ts
  front/app/api/topics/keys.ts
  front/app/api/topics/types.ts
  front/app/api/topics/useAddTopic.test.ts
  front/app/api/topics/useAddTopic.ts
  front/app/api/topics/useDeleteTopic.test.ts
  front/app/api/topics/useDeleteTopic.ts
  front/app/api/topics/useTopic.test.ts
  front/app/api/topics/useTopic.ts
  front/app/api/topics/useTopics.test.ts
  front/app/api/topics/useTopics.ts
  front/app/api/topics/useUpdateTopic.test.ts
  front/app/api/topics/useUpdateTopic.ts
  front/app/components/FilterBoxes/TopicsFilter.tsx
  front/app/components/IdeaCards/shared/Filters/TopicFilterDropdown.tsx
  front/app/components/InitiativeForm/index.tsx
  front/app/components/PostShowComponents/Topics.tsx
  front/app/components/ProjectAndFolderCards/ProjectAndFolderCards.test.tsx
  front/app/components/ProjectAndFolderCards/components/Topbar/SelectTopics.tsx
  front/app/components/ProjectAndFolderCards/components/Topbar/index.tsx
  front/app/components/ProjectAndFolderCards/components/Topbar/show.ts
  front/app/components/UI/TopicsPicker/index.tsx
  front/app/components/admin/PostManager/components/FilterSidebar/FilterSidebarTopics.tsx
  front/app/components/admin/PostManager/components/FilterSidebar/FilterSidebarTopicsItem.tsx
  front/app/components/admin/PostManager/components/FilterSidebar/index.tsx
  front/app/components/admin/PostManager/components/PostTable/Row/selectors/TopicsSelector.tsx
  front/app/components/admin/ResourceList/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/CustomPageSettingsForm/CustomPageSettingsForm.test.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/CustomPageSettingsForm/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/Edit/Settings/Settings.test.tsx
  front/app/containers/Admin/projects/project/general/components/TopicInputs.tsx
  front/app/containers/Admin/projects/project/topics/ProjectTopicSelector.tsx
  front/app/containers/Admin/projects/project/topics/SortableProjectTopicList.tsx
  front/app/containers/Admin/settings/topics/Edit/index.tsx
  front/app/containers/Admin/settings/topics/New/index.tsx
  front/app/containers/Admin/settings/topics/all/CustomTopicRow.tsx
  front/app/containers/Admin/settings/topics/all/DefaultTopicRow.tsx
  front/app/containers/Admin/settings/topics/all/TopicsList.tsx
  front/app/containers/Admin/settings/topics/all/index.tsx
  front/app/containers/InitiativesEditPage/InitiativesEditFormWrapper.tsx
  front/app/containers/InitiativesNewPage/InitiativesNewFormWrapper.tsx
  front/app/hooks/useTopic.ts
  front/app/hooks/useTopics.ts
  front/app/modules/commercial/smart_groups/components/UserFilterConditions/ValueSelector/TopicValueSelector.tsx
  front/app/modules/commercial/smart_groups/components/UserFilterConditions/ValueSelector/TopicValuesSelector.tsx
  front/app/resources/GetTopics.tsx
  front/app/services/topics.ts
Labels: platform

#4811 CL-3522/allowed input topics
  front/app/api/project_allowed_input_topics/__mocks__/useProjectAllowedInputTopics.ts
  front/app/api/project_allowed_input_topics/keys.ts
  front/app/api/project_allowed_input_topics/types.ts
  front/app/api/project_allowed_input_topics/useAddProjectAllowedInputTopic.test.ts
  front/app/api/project_allowed_input_topics/useAddProjectAllowedInputTopic.ts
  front/app/api/project_allowed_input_topics/useDeleteProjectAllowedInputTopic.test.ts
  front/app/api/project_allowed_input_topics/useDeleteProjectAllowedInputTopic.ts
  front/app/api/project_allowed_input_topics/useProjectAllowedInputTopics.test.ts
  front/app/api/project_allowed_input_topics/useProjectAllowedInputTopics.ts
  front/app/api/project_allowed_input_topics/useReorderProjectAllowedInputTopics.test.ts
  front/app/api/project_allowed_input_topics/useReorderProjectAllowedInputTopics.ts
  front/app/api/project_allowed_input_topics/util/getProjectTopicsIds.ts
  front/app/components/IdeaCards/shared/Filters/TopicFilterDropdown.tsx
  front/app/components/admin/PostManager/components/PostTable/Row/IdeaRow.tsx
  front/app/components/admin/PostManager/index.tsx
  front/app/containers/Admin/projects/project/topics/ProjectTopicSelector.tsx
  front/app/containers/Admin/projects/project/topics/SortableProjectTopicList.tsx
  front/app/hooks/useProjectAllowedInputTopics.ts
  front/app/resources/GetProjectAllowedInputTopics.tsx
  front/app/services/projectAllowedInputTopics.ts
Labels: platform-week-23Q2

#4756 Remove TSLint
  front/.eslintrc.js
  front/app/modules/commercial/id_auth0/index.tsx
  front/app/modules/commercial/id_bosa_fas/index.tsx
  front/app/modules/commercial/id_clave_unica/index.tsx
  front/app/modules/commercial/id_cow/index.tsx
  front/app/modules/commercial/id_gent_rrn/index.tsx
  front/app/modules/commercial/id_id_card_lookup/index.tsx
  front/app/modules/commercial/id_oostende_rrn/index.tsx
  front/app/resources/GetTopics.tsx
  front/internals/lint/tslint-plugin-cl-custom/noModuleReferencesRule.js
  front/internals/lint/tslint-plugin-cl-custom/noModuleReferencesRule.ts
  front/package-lock.json
  front/package.json
  front/tslint.json
Labels: ts-config, platform-week-23Q2

#4823 Replace react-scroll-to-component + SiteMap component clean-up
  front/app/containers/SiteMap/index.tsx
  front/package-lock.json
  front/package.json
Labels: platform-week-23Q2

#4793 [CL-3385] Hide slug input if page is proposals
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/CustomPageSettingsForm/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/Edit/Settings/index.tsx
Labels: methods

#4826 Replace react-iframe with native iframe
  front/app/containers/ProjectsShowPage/shared/header/ProjectInfo.tsx
  front/app/containers/ProjectsShowPage/shared/survey/SurveyXact.tsx
  front/app/containers/ProjectsShowPage/shared/survey/TypeformSurvey.tsx
  front/package-lock.json
  front/package.json
Labels: platform-week-23Q2

#4828 Fix keys for phase and project permissions api
  front/app/api/phase_permissions/keys.ts
  front/app/api/project_permissions/keys.ts
Labels: platform-week-23Q2

#4834 [CL-3526] Project moderators
  front/app/api/project_moderators/keys.ts
  front/app/api/project_moderators/types.ts
  front/app/api/project_moderators/useAddProjectModerator.test.ts
  front/app/api/project_moderators/useAddProjectModerator.ts
  front/app/api/project_moderators/useDeleteProjectModerator.test.ts
  front/app/api/project_moderators/useDeleteProjectModerator.ts
  front/app/api/project_moderators/useProjectModerators.test.ts
  front/app/api/project_moderators/useProjectModerators.ts
  front/app/containers/Admin/projects/project/permissions/components/ModeratorList.tsx
  front/app/containers/Admin/projects/project/permissions/components/ModeratorListRow.tsx
  front/app/containers/Admin/projects/project/permissions/components/UserSearch.tsx
  front/app/hooks/useProjectModerators.ts
  front/app/services/projectModerators.ts
Labels: platform-week-23Q2

#4696 CL-3430 Groups
  front/app/api/group_memberships/keys.ts
  front/app/api/group_memberships/types.ts
  front/app/api/group_memberships/useAddMembership.test.ts
  front/app/api/group_memberships/useAddMembership.ts
  front/app/api/group_memberships/useDeleteMembership.test.ts
  front/app/api/group_memberships/useDeleteMembership.ts
  front/app/api/group_memberships/useMemberships.test.ts
  front/app/api/group_memberships/useMemberships.ts
  front/app/api/groups/__mocks__/useGroups.ts
  front/app/api/groups/keys.ts
  front/app/api/groups/types.ts
  front/app/api/groups/useAddGroup.test.ts
  front/app/api/groups/useAddGroup.ts
  front/app/api/groups/useDeleteGroup.test.ts
  front/app/api/groups/useDeleteGroup.ts
  front/app/api/groups/useGroup.test.ts
  front/app/api/groups/useGroup.ts
  front/app/api/groups/useGroups.test.ts
  front/app/api/groups/useGroups.ts
  front/app/api/groups/useUpdateGroup.test.ts
  front/app/api/groups/useUpdateGroup.ts
  front/app/containers/Admin/dashboard/components/filters/GroupFilter.tsx
  front/app/containers/Admin/invitations/invite/InvitationOptions.tsx
  front/app/containers/Admin/invitations/invite/index.tsx
  front/app/containers/Admin/messaging/CustomEmails/CampaignForm/index.tsx
  front/app/containers/Admin/projects/project/permissions/containers/ProjectVisibility/GroupAvatar.tsx
  front/app/containers/Admin/projects/project/permissions/containers/ProjectVisibility/ProjectGroupsList.tsx
  front/app/containers/Admin/users/GroupCreationStep1.tsx
  front/app/containers/Admin/users/GroupsListPanel.tsx
  front/app/containers/Admin/users/NoUsers.tsx
  front/app/containers/Admin/users/NormalGroupForm.tsx
  front/app/containers/Admin/users/UserManager.tsx
  front/app/containers/Admin/users/UserTableActions.tsx
  front/app/containers/Admin/users/UsersGroup.tsx
  front/app/containers/Admin/users/UsersGroupHeader.tsx
  front/app/containers/Admin/users/events.ts
  front/app/containers/Admin/users/index.tsx
  front/app/modules/commercial/granular_permissions/admin/containers/Granular/ActionForm.tsx
  front/app/modules/commercial/smart_groups/api/groups/types.ts
  front/app/modules/commercial/smart_groups/components/SmartGroupType/index.tsx
  front/app/modules/commercial/smart_groups/index.tsx
  front/app/resources/GetGroup.tsx
  front/app/resources/GetGroups.tsx
  front/app/services/__mocks__/groups.ts
  front/app/services/groupMemberships.ts
  front/app/services/groups.ts
  front/app/utils/moduleUtils.tsx
Labels: platform

#4833 [CL-3528] Convert project folder files to React Query
  front/app/api/project_folder_files/UseProjectFolderFiles.test.ts
  front/app/api/project_folder_files/__mocks__/useProjectFolderFiles.ts
  front/app/api/project_folder_files/keys.ts
  front/app/api/project_folder_files/types.ts
  front/app/api/project_folder_files/useAddProjectFolderFile.test.ts
  front/app/api/project_folder_files/useAddProjectFolderFile.ts
  front/app/api/project_folder_files/useDeleteProjectFolderFile.test.ts
  front/app/api/project_folder_files/useDeleteProjectFolderFile.ts
  front/app/api/project_folder_files/useProjectFolderFiles.ts
  front/app/containers/Admin/projectFolders/containers/settings/ProjectFolderForm/index.tsx
  front/app/containers/ProjectFolderShowPage/ProjectFolderDescription.tsx
  front/app/hooks/useProjectFolderFiles.ts
  front/app/services/projectFolderFiles.ts
Labels: platform-week-23Q2

#4847 CL-3525 Project images
  front/app/api/project_images/__mocks__/useProjectImages.ts
  front/app/api/project_images/keys.ts
  front/app/api/project_images/types.ts
  front/app/api/project_images/useAddProjectImage.test.ts
  front/app/api/project_images/useAddProjectImage.ts
  front/app/api/project_images/useDeleteProjectImage.test.ts
  front/app/api/project_images/useDeleteProjectImage.ts
  front/app/api/project_images/useProjectImages.test.ts
  front/app/api/project_images/useProjectImages.ts
  front/app/components/ProjectCard/index.tsx
  front/app/containers/Admin/projects/project/general/components/ProjectCardImageDropzone.tsx
  front/app/containers/Admin/projects/project/general/index.tsx
  front/app/hooks/useProjectImages.ts
  front/app/services/projectImages.ts
Labels: platform-week-23Q2

#4841 Cl 3580 remove enzyme part 2
  front/app/components/admin/ResourceList/SortableRow.tsx
  front/app/containers/Admin/projects/project/poll/AdminContinuousProjectPoll.tsx
  front/app/containers/Admin/projects/project/poll/AdminTimelineProjectPoll.tsx
  front/app/containers/Admin/projects/project/poll/FormOptionRow.test.tsx
  front/app/containers/Admin/projects/project/poll/FormOptionRow.tsx
  front/app/containers/Admin/projects/project/poll/FormQuestionRow.test.tsx
  front/app/containers/Admin/projects/project/poll/FormQuestionRow.tsx
  front/app/containers/Admin/projects/project/poll/OptionForm.test.tsx
  front/app/containers/Admin/projects/project/poll/PollAdminForm.test.tsx
  front/app/containers/Admin/projects/project/poll/PollAdminForm.tsx
  front/app/containers/Admin/projects/project/poll/PollAnswerOptions/OptionForm.tsx
  front/app/containers/Admin/projects/project/poll/PollAnswerOptions/OptionFormRow.tsx
  front/app/containers/Admin/projects/project/poll/PollAnswerOptions/OptionRow.tsx
  front/app/containers/Admin/projects/project/poll/PollQuestions/QuestionDetailsFormRow.tsx
  front/app/containers/Admin/projects/project/poll/PollQuestions/QuestionFormRow.tsx
  front/app/containers/Admin/projects/project/poll/PollQuestions/QuestionRow.tsx
  front/app/containers/Admin/projects/project/poll/PollQuestions/WrongMaxChoiceIndicator.tsx
  front/app/containers/Admin/projects/project/poll/PollQuestions/WrongOptionsIndicator.tsx
  front/app/containers/Admin/projects/project/poll/QuestionDetailsForm.test.tsx
  front/app/containers/Admin/projects/project/poll/WrongMaxChoiceIndicator.test.tsx
  front/app/containers/Admin/projects/project/poll/__snapshots__/FormOptionRow.test.tsx.snap
  front/app/containers/Admin/projects/project/poll/index.tsx
  front/app/containers/Admin/projects/project/poll/messages.ts
  front/app/containers/Admin/projects/project/poll/poll.test.tsx
  front/app/services/__mocks__/pollQuestions.ts
  front/app/services/pollOptions.ts
  front/app/services/pollQuestions.ts
  front/app/translations/admin/ar-MA.json
  front/app/translations/admin/ar-SA.json
  front/app/translations/admin/ca-ES.json
  front/app/translations/admin/da-DK.json
  front/app/translations/admin/de-DE.json
  front/app/translations/admin/el-GR.json
  front/app/translations/admin/en-CA.json
  front/app/translations/admin/en-GB.json
  front/app/translations/admin/en.json
  front/app/translations/admin/es-CL.json
  front/app/translations/admin/es-ES.json
  front/app/translations/admin/fr-BE.json
  front/app/translations/admin/fr-FR.json
  front/app/translations/admin/hr-HR.json
  front/app/translations/admin/hu-HU.json
  front/app/translations/admin/it-IT.json
  front/app/translations/admin/kl-GL.json
  front/app/translations/admin/lb-LU.json
  front/app/translations/admin/lv-LV.json
  front/app/translations/admin/mi.json
  front/app/translations/admin/nb-NO.json
  front/app/translations/admin/nl-BE.json
  front/app/translations/admin/nl-NL.json
  front/app/translations/admin/pl-PL.json
  front/app/translations/admin/pt-BR.json
  front/app/translations/admin/ro-RO.json
  front/app/translations/admin/sr-Latn.json
  front/app/translations/admin/sr-SP.json
  front/app/translations/admin/sv-SE.json
  front/app/translations/admin/tr-TR.json
Labels: waiting for translations, platform-week-23Q2

#4856 Cl 3590 remove enzyme part 3
  front/app/components/PostShowComponents/OfficialFeedback/OfficialFeedback.test.tsx
  front/app/components/PostShowComponents/OfficialFeedback/OfficialFeedbackFeed.tsx
  front/app/components/PostShowComponents/OfficialFeedback/OfficialFeedbackForm.tsx
  front/app/components/PostShowComponents/OfficialFeedback/OfficialFeedbackPost.tsx
  front/app/components/PostShowComponents/OfficialFeedback/__snapshots__/OfficialFeedback.test.tsx.snap
  front/app/components/PostShowComponents/OfficialFeedback/index.tsx
  front/app/components/UI/Checkbox/Checkbox.test.tsx
  front/app/components/admin/PostManager/PostManager.test.tsx
  front/app/components/admin/PostManager/components/LazyPostPreview/PostPreview.test.tsx
  front/app/components/admin/PostManager/components/PostTable/PostTable.test.tsx
  front/app/components/admin/PostManager/components/TopLevelFilters/FeedbackToggle.test.tsx
  front/app/components/admin/PostManager/components/TopLevelFilters/__snapshots__/FeedbackToggle.test.tsx.snap
  front/app/containers/Admin/projects/project/AdminProjectsProjectIndex.test.tsx
  front/app/containers/EmailSettingsPage/EmailSettingsPage.test.tsx
  front/app/containers/ProjectsShowPage/shared/poll/PollForm.test.tsx
  front/app/containers/ProjectsShowPage/shared/poll/__snapshots__/PollForm.test.tsx.snap
  front/app/utils/testUtils/withIntl.ts
  front/internals/jest/setup.js
  front/jest.config.js
  front/package-lock.json
  front/package.json
Labels: platform-week-23Q2

#4866 CL-3536 Remove unused whenever gem
  back/Gemfile
  back/Gemfile.lock
  back/config/schedule.rb
Labels: platform-week-23Q2

#4860 [CL-3587] Bugfix & tests for regression
  back/app/policies/project_folders/folder_policy.rb
  back/spec/policies/project_folders/folder_policy_spec.rb
Labels: structure

#4862 [CL-3533] Convert AdminProjectTimelineEdit to functional component
  front/app/containers/Admin/projects/project/participationContext/components/ParticipationMethodPicker.tsx
  front/app/containers/Admin/projects/project/participationContext/index.tsx
  front/app/containers/Admin/projects/project/timeline/edit.tsx
Labels: platform-week-23Q2

#4781 Only allow submitting last name if also submitting first name
  front/app/containers/UsersEditPage/ProfileForm.tsx
  front/app/containers/UsersEditPage/messages.ts
  front/app/translations/en.json
  front/cypress/e2e/profile_edition.cy.ts
Labels: methods

#4718 CL-3319 Volunteering export bug
  back/engines/free/volunteering/app/services/volunteering/xlsx_service.rb
  back/engines/free/volunteering/spec/services/xlsx_service_spec.rb
Labels: methods

#4854 [CL-3529] Convert project folder images to React Query
  front/app/api/project_folder_images/__mocks__/useProjectFolderImages.ts
  front/app/api/project_folder_images/keys.ts
  front/app/api/project_folder_images/types.ts
  front/app/api/project_folder_images/useAddProjectFolderImage.test.ts
  front/app/api/project_folder_images/useAddProjectFolderImage.ts
  front/app/api/project_folder_images/useDeleteProjectFolderImage.test.ts
  front/app/api/project_folder_images/useDeleteProjectFolderImage.ts
  front/app/api/project_folder_images/useProjectFolderImages.test.ts
  front/app/api/project_folder_images/useProjectFolderImages.ts
  front/app/api/project_images/types.ts
  front/app/api/project_images/useAddProjectImage.test.ts
  front/app/components/ProjectAndFolderCards/components/ProjectFolderCard/index.tsx
  front/app/containers/Admin/projectFolders/containers/settings/ProjectFolderForm/ProjectFolderCardImageDropzone.tsx
  front/app/containers/Admin/projectFolders/containers/settings/ProjectFolderForm/index.tsx
  front/app/containers/Admin/projects/project/general/index.tsx
  front/app/containers/ProjectFolderShowPage/ProjectFolderDescription.tsx
  front/app/hooks/useProjectFolderImages.ts
Labels: platform-week-23Q2

#4884 CL-3588 - Fixed invite signup flow where no email is present
  back/app/models/user.rb
Labels: methods

#4786 Rake task to confirm moderators
  back/engines/commercial/multi_tenancy/lib/tasks/core/confirm_moderators.rake
Labels: methods

#4871 CL-3523 Project files
  front/app/api/project_files/__mocks__/useProjectFiles.ts
  front/app/api/project_files/keys.ts
  front/app/api/project_files/types.ts
  front/app/api/project_files/useAddProjectFile.test.ts
  front/app/api/project_files/useAddProjectFile.ts
  front/app/api/project_files/useDeleteProjectFile.test.ts
  front/app/api/project_files/useDeleteProjectFile.ts
  front/app/api/project_files/useProjectFiles.test.ts
  front/app/api/project_files/useProjectFiles.ts
  front/app/components/UI/FileAttachments/FileDisplay/index.tsx
  front/app/components/UI/FileAttachments/index.tsx
  front/app/containers/Admin/projects/project/general/index.tsx
  front/app/containers/ProjectsShowPage/shared/header/ProjectInfo.tsx
  front/app/hooks/useProjectFiles.ts
  front/app/hooks/useRemoteFiles.ts
  front/app/hooks/useResourceFiles.ts
  front/app/modules/commercial/project_description_builder/admin/components/ContentViewer/Viewer/index.tsx
  front/app/services/projectFiles.ts
Labels: platform-week-23Q2

#4872 [CL-3533] Convert phase files to React Query
  front/app/api/phase_files/__mocks__/usePhaseFiles.ts
  front/app/api/phase_files/keys.ts
  front/app/api/phase_files/types.ts
  front/app/api/phase_files/useAddPhaseFile.test.ts
  front/app/api/phase_files/useAddPhaseFile.ts
  front/app/api/phase_files/useDeletePhaseFile.test.ts
  front/app/api/phase_files/useDeletePhaseFile.ts
  front/app/api/phase_files/usePhaseFiles.test.ts
  front/app/api/phase_files/usePhaseFiles.ts
  front/app/components/UI/FileAttachments/FileDisplay/index.tsx
  front/app/components/UI/FileAttachments/index.tsx
  front/app/containers/Admin/projects/project/timeline/edit.tsx
  front/app/containers/IdeasShow/MetaInformation/Attachment.tsx
  front/app/containers/ProjectsShowPage/timeline/PhaseDescription.tsx
  front/app/hooks/useRemoteFiles.ts
  front/app/hooks/useResourceFiles.ts
  front/app/services/phaseFiles.ts
Labels: platform-week-23Q2

#4867 [CL-3537] Remove 'rails-html-sanitizer' dependency
  back/Gemfile
  back/Gemfile.lock
Labels: platform-week-23Q2

#4902 CL-3609 - Added anonymous participation to ideas model
  back/app/controllers/web_api/v1/ideas_controller.rb
  back/app/models/concerns/anonymous_participation.rb
  back/app/models/idea.rb
  back/app/serializers/web_api/v1/idea_serializer.rb
  back/db/migrate/20230516135820_add_anonymous_columns_to_ideas.rb
  back/db/schema.rb
  back/spec/acceptance/ideas_spec.rb
  back/spec/models/idea_spec.rb
Labels: methods

#4857 Don't allow slug editing of FAQ page
  front/app/components/HookForm/SlugInput/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/CustomPageSettingsForm/CustomPageSettingsForm.test.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/CustomPageSettingsForm/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/Edit/Settings/Settings.test.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/Edit/Settings/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/NavigationSettings/HiddenNavbarItemList/index.tsx
  front/app/containers/PlatformFooter/index.tsx
  front/app/containers/SiteMap/index.tsx
  front/app/services/customPages.ts
  front/app/utils/navbar/index.ts
Labels: structure

#4898 CL-3598 Fix registration flow when group membership required
  back/app/services/permissions_service.rb
  back/engines/commercial/granular_permissions/spec/acceptance/permissions_spec.rb
  back/engines/commercial/granular_permissions/spec/services/participation_context_service_spec.rb
  back/engines/commercial/verification/app/services/verification/patches/permissions_service.rb
  back/engines/commercial/verification/spec/services/participation_context_service_spec.rb
  back/engines/commercial/verification/spec/services/permissions_service_spec.rb
  back/spec/acceptance/action_descriptors_spec.rb
  back/spec/services/permissions_service_spec.rb
  front/app/api/authentication/authentication_requirements/__mocks__/getAuthenticationRequirements.ts
  front/app/api/authentication/authentication_requirements/types.ts
  front/app/components/IdeaButton/index.tsx
  front/app/components/PostShowComponents/Comments/Comment/CommentReplyButton.tsx
  front/app/components/PostShowComponents/Comments/CommentingDisabled.tsx
  front/app/components/VoteControl/VoteButton.tsx
  front/app/containers/Authentication/useSteps/index.ts
  front/app/containers/Authentication/useSteps/stepConfig/lightFlow.ts
  front/app/containers/Authentication/useSteps/stepConfig/missingDataFlow.ts
  front/app/containers/Authentication/useSteps/stepConfig/signInFlow.ts
  front/app/containers/Authentication/useSteps/stepConfig/signUpFlow.ts
  front/app/containers/IdeasShowPage/IdeaShowPageTopBar.tsx
  front/app/containers/ProjectsShowPage/shared/poll/index.tsx
  front/app/containers/ProjectsShowPage/shared/survey/index.tsx
  front/app/services/actionTakingRules.ts
  front/app/translations/en.json
  front/app/utils/actionDescriptors.ts
  front/app/utils/messages.ts
  front/cypress/e2e/verification_modal.cy.ts
Labels: methods

#4904 CL-3608 Add anonymous option to idea form
  front/app/api/ideas/__mocks__/useIdeaById.ts
  front/app/api/ideas/__mocks__/useIdeaBySlug.ts
  front/app/api/ideas/types.ts
  front/app/api/ideas/useIdeas.test.ts
  front/app/components/AnonymousParticipationConfirmationModal/AnonymousCookieManagement.ts
  front/app/components/AnonymousParticipationConfirmationModal/index.tsx
  front/app/components/AnonymousParticipationConfirmationModal/messages.ts
  front/app/components/Form/index.tsx
  front/app/components/IdeaCard/index.tsx
  front/app/components/ProfileVisibility/index.tsx
  front/app/components/ProfileVisibility/messages.ts
  front/app/components/UI/UserName/index.tsx
  front/app/components/UI/UserName/messages.ts
  front/app/components/admin/AnonymousPostingToggle/AnonymousPostingToggle.tsx
  front/app/components/admin/AnonymousPostingToggle/messages.ts
  front/app/components/admin/PostManager/components/LazyPostPreview/Idea/IdeaContent.tsx
  front/app/containers/Admin/projects/project/general/index.tsx
  front/app/containers/IdeasEditPage/IdeasEditForm.tsx
  front/app/containers/IdeasEditPage/utils.tsx
  front/app/containers/IdeasNewPage/IdeasNewForm/index.tsx
  front/app/containers/IdeasNewPage/index.tsx
  front/app/containers/IdeasNewPage/utils.tsx
  front/app/containers/IdeasShow/MetaInformation/PostedBy.tsx
  front/app/containers/IdeasShow/MetaInformation/index.tsx
  front/app/containers/IdeasShow/PostedBy.tsx
  front/app/containers/IdeasShow/RightColumnDesktop/index.tsx
  front/app/containers/IdeasShow/index.tsx
  front/app/translations/admin/en.json
  front/app/translations/en.json
  front/cypress/e2e/idea_posting_anonymous.cy.ts
  front/cypress/support/commands.ts
Labels: methods

#4933 [CL-3613] Add anonymous posting option to comment submission
  front/app/api/comments/types.ts
  front/app/components/Author/index.tsx
  front/app/components/PostShowComponents/Comments/ChildCommentForm.tsx
  front/app/components/PostShowComponents/Comments/Comment/CommentHeader.tsx
  front/app/components/PostShowComponents/Comments/Comment/index.tsx
  front/app/components/PostShowComponents/Comments/Comments.tsx
  front/app/components/PostShowComponents/Comments/ParentComment.tsx
  front/app/components/PostShowComponents/Comments/ParentCommentForm.tsx
  front/app/components/PostShowComponents/Comments/index.tsx
  front/app/components/PostShowComponents/Comments/messages.ts
  front/app/components/PostShowComponents/Footer.tsx
  front/app/components/UI/UserName/index.tsx
  front/app/components/UI/UserName/messages.ts
  front/app/components/admin/PostManager/components/LazyPostPreview/Idea/IdeaContent.tsx
  front/app/components/admin/PostManager/components/LazyPostPreview/Initiative/InitiativeContent.tsx
  front/app/containers/IdeasNewPage/IdeasNewForm/index.tsx
  front/app/containers/IdeasShow/index.tsx
  front/app/translations/en.json
Labels: methods

#4922 [CL-3636] email_campaigns_examples storing
  back/.rubocop.yml
  back/db/migrate/20230519085843_create_email_campaigns_examples.email_campaigns.rb
  back/db/schema.rb
  back/engines/free/email_campaigns/app/models/email_campaigns/example.rb
  back/engines/free/email_campaigns/app/models/email_campaigns/user_decorator.rb
  back/engines/free/email_campaigns/app/services/email_campaigns/delivery_service.rb
  back/engines/free/email_campaigns/app/services/email_campaigns/examples_service.rb
  back/engines/free/email_campaigns/db/migrate/20230519085716_create_email_campaigns_examples.rb
  back/engines/free/email_campaigns/spec/factories/examples.rb
  back/engines/free/email_campaigns/spec/services/email_campaigns/examples_service_spec.rb
  back/spec/spec_helper.rb
Labels: structure

#4971 CL-3672 - Fix ideas being able to be changed to anonymous
  back/app/controllers/web_api/v1/ideas_controller.rb
  back/spec/acceptance/ideas_spec.rb
Labels: methods

#4952 CL-3660 - Survey anonymisation backend
  back/app/controllers/web_api/v1/ideas_controller.rb
  back/app/models/concerns/anonymous_participation.rb
  back/app/models/idea.rb
  back/app/services/participation_context_service.rb
  back/db/migrate/20230524085443_add_index_to_ideas_author_hash.rb
  back/db/schema.rb
  back/spec/acceptance/ideas_spec.rb
  back/spec/services/participation_context_service_spec.rb
Labels: methods

#4959 CL-3665 - Make avatars less similar
  back/app/models/concerns/anonymous_participation.rb
  back/spec/models/comment_spec.rb
  back/spec/models/idea_spec.rb
  back/spec/models/initiative_spec.rb
Labels: methods

#4931 CL-3634 No logging anonymous users
  back/app/controllers/web_api/v1/ideas_controller.rb
  back/app/policies/application_policy.rb
  back/app/policies/initiative_policy.rb
  back/app/services/concerns/side_fx_helper.rb
  back/app/services/side_fx_comment_service.rb
  back/app/services/side_fx_idea_service.rb
  back/app/services/side_fx_initiative_service.rb
  back/engines/commercial/idea_assignment/app/services/idea_assignment/patches/side_fx_idea_service.rb
  back/spec/acceptance/idea_comments_spec.rb
  back/spec/acceptance/ideas_spec.rb
  back/spec/acceptance/initiative_comments_spec.rb
  back/spec/acceptance/initiatives_spec.rb
Labels: methods

#4972 CL-3675 - Move author hash salts into env config
  back/app/models/concerns/anonymous_participation.rb
  env_files/back-secret.example.env
Labels: methods

#4950 [CL-3620] Add anonymous posting option to initiative posting
  front/app/api/initiatives/types.ts
  front/app/api/initiatives/useUpdateInitiative.test.ts
  front/app/components/AnonymousParticipationConfirmationModal/AnonymousCookieManagement.ts
  front/app/components/AnonymousParticipationConfirmationModal/index.tsx
  front/app/components/AnonymousParticipationConfirmationModal/messages.ts
  front/app/components/Author/index.tsx
  front/app/components/InitiativeCard/index.tsx
  front/app/components/InitiativeForm/index.tsx
  front/app/components/PostShowComponents/Comments/ChildCommentForm.tsx
  front/app/components/PostShowComponents/Comments/ParentCommentForm.tsx
  front/app/components/PostShowComponents/Comments/messages.ts
  front/app/components/ProfileVisibility/messages.ts
  front/app/components/admin/AnonymousPostingToggle/AnonymousPostingToggle.tsx
  front/app/components/admin/AnonymousPostingToggle/messages.ts
  front/app/components/admin/PostManager/components/LazyPostPreview/Idea/IdeaContent.tsx
  front/app/containers/IdeasEditPage/IdeasEditForm.tsx
  front/app/containers/IdeasNewPage/IdeasNewForm/index.tsx
  front/app/containers/IdeasShow/index.tsx
  front/app/containers/InitiativesEditPage/InitiativesEditFormWrapper.tsx
  front/app/containers/InitiativesNewPage/InitiativesNewFormWrapper.tsx
  front/app/containers/InitiativesShow/PostedBy.tsx
  front/app/containers/InitiativesShow/index.tsx
  front/app/translations/admin/en.json
  front/app/translations/en.json
Labels: methods

#4977 Fix spacing issues in custom fields routes
  front/app/containers/Admin/routes.tsx
  front/app/containers/Admin/settings/registration/CustomFieldRoutes/routes.tsx
  front/app/containers/Admin/settings/registration/routes.tsx
Labels: structure

#4992 CL-3617 - Anonymous author name in xlsx exports
  back/app/services/xlsx_export/input_sheet_generator.rb
  back/app/services/xlsx_service.rb
  back/config/locales/en.yml
  back/spec/fixtures/locales/en.yml
  back/spec/services/xlsx_service_spec.rb
Labels: methods

#4964 CL-2656 - Add anonymous user counts
  back/app/serializers/web_api/v1/project_serializer.rb
  back/app/services/avatars_service.rb
  back/app/services/participants_service.rb
  back/engines/free/email_campaigns/app/models/email_campaigns/campaigns/moderator_digest.rb
  back/spec/services/participants_service_spec.rb
Labels: methods

#4960 CL-3370: Move sub navigations in the input manager to the top
  front/app/containers/Admin/ideas/all/index.tsx
  front/app/containers/Admin/ideas/index.tsx
  front/app/containers/Admin/ideas/messages.ts
  front/app/containers/Admin/index.tsx
  front/app/modules/commercial/bulk_idea_import/admin/containers/Import.tsx
  front/app/translations/admin/ar-MA.json
  front/app/translations/admin/ar-SA.json
  front/app/translations/admin/ca-ES.json
  front/app/translations/admin/da-DK.json
  front/app/translations/admin/de-DE.json
  front/app/translations/admin/el-GR.json
  front/app/translations/admin/en-CA.json
  front/app/translations/admin/en-GB.json
  front/app/translations/admin/en.json
  front/app/translations/admin/es-CL.json
  front/app/translations/admin/es-ES.json
  front/app/translations/admin/fr-BE.json
  front/app/translations/admin/fr-FR.json
  front/app/translations/admin/hr-HR.json
  front/app/translations/admin/hu-HU.json
  front/app/translations/admin/it-IT.json
  front/app/translations/admin/kl-GL.json
  front/app/translations/admin/lb-LU.json
  front/app/translations/admin/lv-LV.json
  front/app/translations/admin/mi.json
  front/app/translations/admin/nb-NO.json
  front/app/translations/admin/nl-BE.json
  front/app/translations/admin/nl-NL.json
  front/app/translations/admin/pl-PL.json
  front/app/translations/admin/pt-BR.json
  front/app/translations/admin/ro-RO.json
  front/app/translations/admin/sr-Latn.json
  front/app/translations/admin/sr-SP.json
  front/app/translations/admin/sv-SE.json
  front/app/translations/admin/tr-TR.json
Labels: structure

#4956 CL-3365: Add statuses tab to the settings page
  front/app/containers/Admin/ideas/all/index.tsx
  front/app/containers/Admin/ideas/index.tsx
  front/app/containers/Admin/ideas/messages.ts
  front/app/containers/Admin/index.tsx
  front/app/containers/Admin/settings/index.tsx
  front/app/containers/Admin/settings/messages.ts
  front/app/modules/commercial/bulk_idea_import/admin/components/Tab.tsx
  front/app/modules/commercial/bulk_idea_import/admin/containers/Import.tsx
  front/app/modules/commercial/custom_idea_statuses/admin/components/Tab.tsx
  front/app/modules/commercial/custom_idea_statuses/admin/components/messages.ts
  front/app/modules/commercial/custom_idea_statuses/admin/containers/edit.tsx
  front/app/modules/commercial/custom_idea_statuses/admin/containers/index.tsx
  front/app/modules/commercial/custom_idea_statuses/admin/containers/messages.ts
  front/app/modules/commercial/custom_idea_statuses/admin/containers/new.tsx
  front/app/modules/commercial/custom_idea_statuses/index.tsx
  front/app/translations/admin/ar-MA.json
  front/app/translations/admin/ar-SA.json
  front/app/translations/admin/ca-ES.json
  front/app/translations/admin/da-DK.json
  front/app/translations/admin/de-DE.json
  front/app/translations/admin/el-GR.json
  front/app/translations/admin/en-CA.json
  front/app/translations/admin/en-GB.json
  front/app/translations/admin/en.json
  front/app/translations/admin/es-CL.json
  front/app/translations/admin/es-ES.json
  front/app/translations/admin/fr-BE.json
  front/app/translations/admin/fr-FR.json
  front/app/translations/admin/hr-HR.json
  front/app/translations/admin/hu-HU.json
  front/app/translations/admin/it-IT.json
  front/app/translations/admin/kl-GL.json
  front/app/translations/admin/lb-LU.json
  front/app/translations/admin/lv-LV.json
  front/app/translations/admin/mi.json
  front/app/translations/admin/nb-NO.json
  front/app/translations/admin/nl-BE.json
  front/app/translations/admin/nl-NL.json
  front/app/translations/admin/pl-PL.json
  front/app/translations/admin/pt-BR.json
  front/app/translations/admin/ro-RO.json
  front/app/translations/admin/sr-Latn.json
  front/app/translations/admin/sr-SP.json
  front/app/translations/admin/sv-SE.json
  front/app/translations/admin/tr-TR.json
Labels: structure

#4988 CL-3686: Fix active state of selected top bar nav when navigating in sub links
  front/app/containers/Admin/dashboard/components/DashboardTabs.tsx
  front/app/containers/Admin/initiatives/index.tsx
  front/app/containers/Admin/messaging/index.tsx
  front/app/containers/Admin/reporting/components/Tabs.tsx
  front/app/containers/Admin/settings/index.tsx
  front/app/utils/helperUtils.test.ts
  front/app/utils/helperUtils.ts
Labels: structure

#4989 [CL-3585] Native survey access rights showing incorrect options
  front/app/modules/commercial/granular_permissions/admin/components/PhaseActionForm.tsx
  front/app/modules/commercial/granular_permissions/admin/containers/Granular/ActionsForm.tsx
  front/app/modules/commercial/granular_permissions/admin/containers/Granular/Timeline.tsx
  front/app/modules/commercial/granular_permissions/admin/containers/Granular/utils.tsx
Labels: methods

#4957 CL-3371: Add edit links from input manager
  front/app/components/admin/PostManager/components/FilterSidebar/FilterSidebarProjects.tsx
  front/app/components/admin/PostManager/components/FilterSidebar/FilterSidebarStatuses.tsx
  front/app/components/admin/PostManager/components/FilterSidebar/FilterSidebarTopics.tsx
  front/app/components/admin/PostManager/messages.ts
  front/app/translations/admin/en.json
Labels: structure

#4991 CL-3668 - Fix for moderators not being able to see ideas in other projects with group visibility
  back/app/controllers/web_api/v1/comments_controller.rb
  back/app/policies/idea_policy.rb
Labels: methods

#5024 CL-3628: Update support link
  front/app/containers/Admin/sideBar/SupportMenu.tsx
  front/app/containers/Admin/sideBar/messages.ts
  front/app/translations/admin/ar-MA.json
  front/app/translations/admin/ar-SA.json
  front/app/translations/admin/ca-ES.json
  front/app/translations/admin/da-DK.json
  front/app/translations/admin/de-DE.json
  front/app/translations/admin/el-GR.json
  front/app/translations/admin/en-CA.json
  front/app/translations/admin/en-GB.json
  front/app/translations/admin/en.json
  front/app/translations/admin/es-CL.json
  front/app/translations/admin/es-ES.json
  front/app/translations/admin/fr-BE.json
  front/app/translations/admin/fr-FR.json
  front/app/translations/admin/hr-HR.json
  front/app/translations/admin/it-IT.json
  front/app/translations/admin/kl-GL.json
  front/app/translations/admin/lb-LU.json
  front/app/translations/admin/lv-LV.json
  front/app/translations/admin/nb-NO.json
  front/app/translations/admin/nl-BE.json
  front/app/translations/admin/nl-NL.json
  front/app/translations/admin/pl-PL.json
  front/app/translations/admin/pt-BR.json
  front/app/translations/admin/ro-RO.json
  front/app/translations/admin/sr-Latn.json
  front/app/translations/admin/sr-SP.json
  front/app/translations/admin/sv-SE.json
  front/app/translations/admin/tr-TR.json
Labels: structure

#4993 [CL-3670] Add anonymous participation e2e tests
  front/app/components/PostShowComponents/Comments/ParentCommentForm.tsx
  front/app/components/ProfileVisibility/index.tsx
  front/app/components/UI/UserName/index.tsx
  front/app/components/admin/AnonymousPostingToggle/AnonymousPostingToggle.tsx
  front/app/containers/Admin/initiatives/settings/SubmitButton.tsx
  front/cypress/e2e/commenting_anonymous.cy.ts
  front/cypress/e2e/idea_posting_anonymous.cy.ts
  front/cypress/e2e/proposal_posting_anonymous.cy.ts
  front/cypress/support/commands.ts
Labels: methods

#4882 [CL-2656] Number of participants and submissions update
  back/app/controllers/web_api/v1/phases_controller.rb
  back/app/controllers/web_api/v1/projects_controller.rb
  back/app/policies/phase_policy.rb
  back/app/policies/project_policy.rb
  back/app/serializers/web_api/v1/project_serializer.rb
  back/spec/acceptance/phases_spec.rb
  back/spec/acceptance/projects_spec.rb
  back/spec/policies/phase_policy_spec.rb
  back/spec/policies/project_policy_spec.rb
  front/app/api/phase_permissions/usePhasePermissions.ts
  front/app/api/phase_permissions/usePhasesPermissions.ts
  front/app/components/ProjectCard/index.tsx
  front/app/containers/ProjectsShowPage/messages.ts
  front/app/containers/ProjectsShowPage/shared/header/ProjectInfoSideBar.tsx
  front/app/containers/ProjectsShowPage/shared/header/utils.ts
  front/app/translations/en.json
  front/app/utils/participationMethodUtils.tsx
Labels: waiting for translations, methods
