Repository CitizenLabDotCo/citizenlab, pull requests merged in 2023-09, with the labels that each got.

#5765 [TAN-331] Don't include current_user in mentions, even if post author
  back/app/controllers/web_api/v1/mentions_controller.rb
  back/app/models/initiative.rb
  back/spec/acceptance/mentions_spec.rb
  back/spec/models/initiative_spec.rb
  back/spec/services/mention_service_spec.rb
Labels: proposals

#5791 [TAN-336] Include cosponsorships invite statuses in export of proposals
  back/app/services/xlsx_service.rb
Labels: co-sponsors

#5800 Cl 4018 fix e 2 e proposal posting anonymous
  front/cypress/e2e/proposal_posting_anonymous.cy.ts
Labels: structure, proposals

#5802 Cl 4018 fix e 2 e ideal posting anonymous 2
  front/cypress/e2e/idea_posting_anonymous.cy.ts
  front/cypress/e2e/proposal_page_action.cy.ts
Labels: structure, proposals

#5803 lCl 4021 fix e 2 e proposal edit page
  front/cypress/e2e/proposal_edit_page.cy.ts
Labels: structure, proposals

#5796 [TAN-340] Improve logo resolution in mails
  back/app/mailers/application_mailer.rb
  back/app/views/application/_logo_medium_top.mjml
Labels: proposals

#5811 Revert "[TAN-340] Improve logo resolution in mails"
  back/app/mailers/application_mailer.rb
  back/app/views/application/_logo_medium_top.mjml
Labels: proposals

#5823 [TAN-340] Improve logo resolution in mails - v2
  back/app/mailers/application_mailer.rb
  back/app/views/application/_logo_medium_top.mjml
  back/engines/free/email_campaigns/app/views/email_campaigns/application/_head.mjml
Labels: proposals

#5809 Add cosponsors min/max requirement to inititiave form
  front/app/components/InitiativeForm/index.tsx
  front/app/components/InitiativeForm/messages.ts
  front/app/translations/en.json
Labels: structure, proposals

#5808 [CL-3971] Do not send digests when no significant stats (activity)
  back/engines/free/email_campaigns/app/models/email_campaigns/campaigns/admin_digest.rb
  back/engines/free/email_campaigns/app/models/email_campaigns/campaigns/moderator_digest.rb
  back/engines/free/email_campaigns/app/views/email_campaigns/admin_digest_mailer/_statistics.mjml
  back/engines/free/email_campaigns/app/views/email_campaigns/moderator_digest_mailer/campaign_mail.mjml
  back/engines/free/email_campaigns/spec/mailers/previews/email_campaigns/admin_digest_mailer_preview.rb
  back/engines/free/email_campaigns/spec/mailers/previews/email_campaigns/moderator_digest_mailer_preview.rb
  back/engines/free/email_campaigns/spec/models/email_campaigns/campaigns/admin_digest_spec.rb
  back/engines/free/email_campaigns/spec/models/email_campaigns/campaigns/moderator_digest_spec.rb
Labels: structure

#5841 CL 4033 add time proposal was created in bo
  front/app/components/admin/PostManager/components/PostTable/Row/InitiativeRow.tsx
  front/app/components/admin/PostManager/components/PostTable/header/IdeaHeaderRow.tsx
  front/app/components/admin/PostManager/components/PostTable/header/InitiativesHeaderRow.tsx
  front/app/components/admin/PostManager/components/PostTable/index.tsx
Labels: structure, proposals

#5816 Cl 4028 proposals reminder to reach required number of cosponsors
  front/app/components/InitiativeForm/CosponsorsFormSection.tsx
  front/app/components/InitiativeForm/ProfileVisibilityFormSection.tsx
  front/app/components/InitiativeForm/SubmitButtonBar.tsx
  front/app/components/InitiativeForm/index.tsx
  front/app/components/UI/UserName/index.tsx
  front/app/components/admin/PostManager/components/PostTable/Row/InitiativeRow.tsx
  front/app/components/admin/PostManager/components/PostTable/header/IdeaHeaderRow.tsx
  front/app/components/admin/PostManager/components/PostTable/header/InitiativesHeaderRow.tsx
  front/app/components/admin/PostManager/components/PostTable/index.tsx
  front/app/containers/InitiativesShow/CosponsorShipReminder.tsx
  front/app/containers/InitiativesShow/Cosponsors/ListOfCosponsors.tsx
  front/app/containers/InitiativesShow/Cosponsors/index.tsx
  front/app/containers/InitiativesShow/CosponsorsSection.tsx
  front/app/containers/InitiativesShow/LargerThanPhone.tsx
  front/app/containers/InitiativesShow/Phone.tsx
  front/app/containers/InitiativesShow/RequestToCosponsor.tsx
  front/app/containers/InitiativesShow/hooks/useInitiativeCosponsorsRequired.ts
  front/app/containers/InitiativesShow/hooks/useInitiativeReviewRequired.ts
  front/app/containers/InitiativesShow/hooks/useShowCosponsorshipReminder.ts
  front/app/containers/InitiativesShow/messages.ts
  front/app/containers/InitiativesShow/modals/index.tsx
  front/app/containers/InitiativesShowPage/InitiativeShowPageTopBar.tsx
  front/app/translations/en.json
Labels: structure, proposals

#5822 Phygital surveys
  back/app/controllers/web_api/v1/phase_custom_fields_controller.rb
  back/app/models/concerns/post.rb
  back/app/models/idea.rb
  back/app/policies/idea_policy.rb
  back/app/services/custom_field_service.rb
  back/app/services/idea_custom_fields_service.rb
  back/app/services/survey_results_generator_service.rb
  back/config/routes.rb
  back/engines/commercial/bulk_import_ideas/app/controllers/bulk_import_ideas/web_api/v1/import_ideas_controller.rb
  back/engines/commercial/bulk_import_ideas/app/policies/bulk_import_ideas/patches/idea_policy.rb
  back/engines/commercial/bulk_import_ideas/app/services/bulk_import_ideas/idea_plaintext_parser_service.rb
  back/engines/commercial/bulk_import_ideas/app/services/bulk_import_ideas/import_global_ideas_service.rb
  back/engines/commercial/bulk_import_ideas/app/services/bulk_import_ideas/import_ideas_service.rb
  back/engines/commercial/bulk_import_ideas/app/services/bulk_import_ideas/import_project_ideas_service.rb
  back/engines/commercial/bulk_import_ideas/config/routes.rb
  back/engines/commercial/bulk_import_ideas/spec/acceptance/import_ideas_spec.rb
  back/engines/commercial/bulk_import_ideas/spec/services/google_form_parser_service_spec.rb
  back/engines/commercial/bulk_import_ideas/spec/services/idea_plaintext_parser_service_spec.rb
  back/engines/commercial/bulk_import_ideas/spec/services/import_global_ideas_service_spec.rb
  back/engines/commercial/bulk_import_ideas/spec/services/import_ideas_service_spec.rb
  back/spec/acceptance/ideas_spec.rb
  front/app/api/import_ideas/types.ts
  front/app/api/import_ideas/useImportedIdeas.ts
  front/app/containers/Admin/projects/project/nativeSurvey/FormActions/index.tsx
  front/app/containers/Admin/projects/project/nativeSurvey/SurveyFormBuilder/index.tsx
  front/app/containers/Admin/projects/project/nativeSurvey/flag.ts
  front/app/containers/Admin/projects/project/nativeSurvey/index.tsx
  front/app/containers/Admin/projects/project/nativeSurvey/messages.ts
  front/app/containers/Admin/projects/project/nativeSurvey/saveSurveyAsPDF.ts
  front/app/containers/Admin/projects/project/nativeSurvey/utils.tsx
  front/app/containers/Admin/projects/project/offlineInputs/ImportModal/ImportSection.tsx
  front/app/containers/Admin/projects/project/offlineInputs/ImportModal/index.tsx
  front/app/containers/Admin/projects/project/offlineInputs/ImportModal/messages.ts
  front/app/containers/Admin/projects/project/offlineInputs/ReviewSection/IdeaForm.tsx
  front/app/containers/Admin/projects/project/offlineInputs/ReviewSection/IdeaList.tsx
  front/app/containers/Admin/projects/project/offlineInputs/ReviewSection/index.tsx
  front/app/containers/Admin/projects/project/offlineInputs/ReviewSection/messages.ts
  front/app/containers/Admin/projects/project/offlineInputs/TopBar/index.tsx
  front/app/containers/Admin/projects/project/offlineInputs/index.tsx
  front/app/containers/Admin/projects/routes.tsx
  front/app/translations/admin/en.json
Labels: methods

#5859 Cl 4036 proposals improve need to verify message
  front/app/api/initiative_action_descriptors/types.ts
  front/app/api/user_custom_fields/useUpdateUserCustomField.ts
  front/app/containers/Admin/settings/registration/CustomFieldSettings/index.tsx
  front/app/containers/Authentication/steps/Verification/VerificationMethods.tsx
  front/app/containers/InitiativesShow/ReactionControl/index.tsx
  front/app/hooks/useInitiativesPermissions.ts
Labels: structure, proposals

#5867 [CL-4025] Fix initiatives filter counts when using search on Proposals page
  back/app/controllers/web_api/v1/initiatives_controller.rb
  back/spec/acceptance/initiatives_spec.rb
Labels: proposals

#5866 Remove participation conditions from verification modal
  front/app/containers/Authentication/Modal.tsx
  front/app/containers/Authentication/steps/AuthProviders/styles.ts
  front/app/containers/Authentication/steps/Verification/VerificationMethods.tsx
  front/app/containers/Authentication/steps/Verification/VerificationSteps.tsx
  front/app/containers/Authentication/steps/Verification/index.tsx
  front/app/containers/Authentication/steps/Verification/messages.ts
  front/app/hooks/useParticipationConditions.ts
  front/app/services/participationConditions.ts
  front/app/translations/ar-MA.json
  front/app/translations/ar-SA.json
  front/app/translations/ca-ES.json
  front/app/translations/da-DK.json
  front/app/translations/de-DE.json
  front/app/translations/el-GR.json
  front/app/translations/en-CA.json
  front/app/translations/en-GB.json
  front/app/translations/en.json
  front/app/translations/es-CL.json
  front/app/translations/es-ES.json
  front/app/translations/fr-BE.json
  front/app/translations/fr-FR.json
  front/app/translations/hr-HR.json
  front/app/translations/hu-HU.json
  front/app/translations/it-IT.json
  front/app/translations/kl-GL.json
  front/app/translations/lb-LU.json
  front/app/translations/lv-LV.json
  front/app/translations/mi.json
  front/app/translations/nb-NO.json
  front/app/translations/nl-BE.json
  front/app/translations/nl-NL.json
  front/app/translations/pl-PL.json
  front/app/translations/pt-BR.json
  front/app/translations/ro-RO.json
  front/app/translations/sr-Latn.json
  front/app/translations/sr-SP.json
  front/app/translations/sv-SE.json
  front/app/translations/tr-TR.json
Labels: structure, proposals

#5869 Cl 4042 custom verification msg
  front/app/containers/Authentication/Modal.tsx
  front/app/containers/Authentication/steps/Verification/VerificationMethods.tsx
Labels: structure, proposals

#5872 Remove width on app container
  front/app/containers/App/index.tsx
Labels: structure

#5861 4036 proposals disabled reason
  front/app/components/PostShowComponents/Comments/CommentingProposalDisabled.tsx
  front/app/containers/InitiativesNewPage/InitiativesNewFormWrapper.tsx
  front/app/containers/InitiativesShow/ReactionControl/ProposedNotReacted.tsx
  front/app/containers/InitiativesShow/ReactionControl/index.tsx
  front/app/hooks/useInitiativesPermissions.ts
  front/app/resources/GetInitiativesPermissions.tsx
  front/app/utils/actionDescriptors.ts
Labels: structure, proposals

#5870 [CL-3994] serialize app_configuration created_at + test
  back/app/serializers/web_api/v1/app_configuration_serializer.rb
  back/spec/acceptance/app_configurations_spec.rb
Labels: structure

#5829 [CL-3985] Delete invites more than 2 weeks old
  back/app/jobs/delete_invites_job.rb
  back/app/models/invite.rb
  back/engines/commercial/multi_tenancy/lib/tasks/core/hourly_jobs.rake
  back/engines/free/email_campaigns/app/mailers/email_campaigns/invite_received_mailer.rb
  back/engines/free/email_campaigns/app/mailers/email_campaigns/invite_reminder_mailer.rb
  back/engines/free/email_campaigns/app/models/email_campaigns/campaigns/invite_reminder.rb
  back/engines/free/email_campaigns/app/views/email_campaigns/invite_received_mailer/campaign_mail.mjml
  back/engines/free/email_campaigns/app/views/email_campaigns/invite_reminder_mailer/campaign_mail.mjml
  back/engines/free/email_campaigns/config/locales/en.yml
  back/engines/free/email_campaigns/spec/fixtures/locales/mailers.en.yml
  back/engines/free/email_campaigns/spec/mailers/invite_received_mailer_spec.rb
  back/engines/free/email_campaigns/spec/mailers/invite_reminder_mailer_spec.rb
  back/engines/free/email_campaigns/spec/mailers/previews/email_campaigns/invite_reminder_mailer_preview.rb
  back/spec/jobs/delete_invites_job_spec.rb
  front/app/containers/Admin/invitations/index.tsx
  front/app/containers/Admin/invitations/messages.ts
  front/app/containers/Authentication/Modal.tsx
  front/app/containers/Authentication/messages.ts
  front/app/containers/Authentication/useSteps/stepConfig/sharedSteps.ts
  front/app/translations/admin/en.json
  front/app/translations/ar-MA.json
  front/app/translations/ar-SA.json
  front/app/translations/ca-ES.json
  front/app/translations/da-DK.json
  front/app/translations/de-DE.json
  front/app/translations/el-GR.json
  front/app/translations/en-CA.json
  front/app/translations/en-GB.json
  front/app/translations/en.json
  front/app/translations/es-CL.json
  front/app/translations/es-ES.json
  front/app/translations/fr-BE.json
  front/app/translations/fr-FR.json
  front/app/translations/hr-HR.json
  front/app/translations/hu-HU.json
  front/app/translations/it-IT.json
  front/app/translations/kl-GL.json
  front/app/translations/lb-LU.json
  front/app/translations/lv-LV.json
  front/app/translations/mi.json
  front/app/translations/nb-NO.json
  front/app/translations/nl-BE.json
  front/app/translations/nl-NL.json
  front/app/translations/pl-PL.json
  front/app/translations/pt-BR.json
  front/app/translations/ro-RO.json
  front/app/translations/sr-Latn.json
  front/app/translations/sr-SP.json
  front/app/translations/sv-SE.json
  front/app/translations/tr-TR.json
Labels: structure

#5897 Show last 3 official updates by default
  front/app/components/PostShowComponents/OfficialFeedback/OfficialFeedbackFeed.tsx
  front/app/components/PostShowComponents/OfficialFeedback/index.tsx
Labels: structure, proposals

#5910 [CL-4059] Serialize initiatives proposed_at
  back/app/models/initiative.rb
  back/app/serializers/web_api/v1/initiative_serializer.rb
  back/spec/models/initiative_spec.rb
  front/app/api/initiatives/__mocks__/useInitiatives.ts
  front/app/api/initiatives/types.ts
  front/app/api/initiatives/useUpdateInitiative.test.ts
  front/app/components/InitiativeCard/index.tsx
  front/app/containers/InitiativesShow/InitiativeMeta.tsx
Labels: structure, proposals

#5955 [CL-4072] Replace inclusion of Disableable
  back/engines/free/email_campaigns/app/models/email_campaigns/campaigns/project_phase_started.rb
  front/app/translations/nl-NL.json
Labels: structure, follows

#5943 [CL-4012] Don't overwrite existing user avatar with SSO avatar
  back/app/controllers/omniauth_callback_controller.rb
  back/spec/requests/google_authentication_spec.rb
Labels: structure

#5953 CL-4058 - Allow duplicate sheet names for long volunteering cause name with similar names
  back/engines/free/volunteering/app/services/volunteering/xlsx_service.rb
  back/engines/free/volunteering/spec/services/xlsx_service_spec.rb
Labels: methods

#5968 CL-3977 - Fix ordering of user custom fields
  back/engines/commercial/user_custom_fields/app/controllers/user_custom_fields/web_api/v1/user_custom_fields_controller.rb
  back/engines/commercial/user_custom_fields/spec/acceptance/user_custom_fields_spec.rb
Labels: methods

#5970 Fix comment sorting causing horizontal scrolling for large fonts
  front/app/components/PostShowComponents/Comments/PublicComments.tsx
Labels: structure, proposals

#5921 CL-3545 - Complete public api endpoints
  back/engines/commercial/public_api/app/controllers/public_api/public_api_controller.rb
  back/engines/commercial/public_api/app/controllers/public_api/v2/basket_ideas_controller.rb
  back/engines/commercial/public_api/app/controllers/public_api/v2/baskets_controller.rb
  back/engines/commercial/public_api/app/controllers/public_api/v2/email_campaign_deliveries_controller.rb
  back/engines/commercial/public_api/app/controllers/public_api/v2/email_campaigns_controller.rb
  back/engines/commercial/public_api/app/controllers/public_api/v2/event_attendances_controller.rb
  back/engines/commercial/public_api/app/controllers/public_api/v2/events_controller.rb
  back/engines/commercial/public_api/app/controllers/public_api/v2/idea_phases_controller.rb
  back/engines/commercial/public_api/app/controllers/public_api/v2/ideas_controller.rb
  back/engines/commercial/public_api/app/controllers/public_api/v2/volunteering_causes_controller.rb
  back/engines/commercial/public_api/app/controllers/public_api/v2/volunteering_volunteers_controller.rb
  back/engines/commercial/public_api/app/finders/public_api/ideas_finder.rb
  back/engines/commercial/public_api/app/serializers/public_api/v2/basket_idea_serializer.rb
  back/engines/commercial/public_api/app/serializers/public_api/v2/basket_serializer.rb
  back/engines/commercial/public_api/app/serializers/public_api/v2/email_campaign_delivery_serializer.rb
  back/engines/commercial/public_api/app/serializers/public_api/v2/email_campaign_serializer.rb
  back/engines/commercial/public_api/app/serializers/public_api/v2/event_attendance_serializer.rb
  back/engines/commercial/public_api/app/serializers/public_api/v2/event_serializer.rb
  back/engines/commercial/public_api/app/serializers/public_api/v2/idea_phase_serializer.rb
  back/engines/commercial/public_api/app/serializers/public_api/v2/idea_serializer.rb
  back/engines/commercial/public_api/app/serializers/public_api/v2/initiative_serializer.rb
  back/engines/commercial/public_api/app/serializers/public_api/v2/phase_serializer.rb
  back/engines/commercial/public_api/app/serializers/public_api/v2/project_serializer.rb
  back/engines/commercial/public_api/app/serializers/public_api/v2/volunteering_cause_serializer.rb
  back/engines/commercial/public_api/app/serializers/public_api/v2/volunteering_volunteer_serializer.rb
  back/engines/commercial/public_api/config/routes.rb
  back/engines/commercial/public_api/spec/acceptance/v2/authentication_spec.rb
  back/engines/commercial/public_api/spec/acceptance/v2/basket_ideas_spec.rb
  back/engines/commercial/public_api/spec/acceptance/v2/baskets_spec.rb
  back/engines/commercial/public_api/spec/acceptance/v2/email_campaign_deliveries_spec.rb
  back/engines/commercial/public_api/spec/acceptance/v2/email_campaigns_spec.rb
  back/engines/commercial/public_api/spec/acceptance/v2/event_attendances_spec.rb
  back/engines/commercial/public_api/spec/acceptance/v2/events_spec.rb
  back/engines/commercial/public_api/spec/acceptance/v2/idea_phases_spec.rb
  back/engines/commercial/public_api/spec/acceptance/v2/idea_topics_spec.rb
  back/engines/commercial/public_api/spec/acceptance/v2/ideas_spec.rb
  back/engines/commercial/public_api/spec/acceptance/v2/initiatives_spec.rb
  back/engines/commercial/public_api/spec/acceptance/v2/project_topics_spec.rb
  back/engines/commercial/public_api/spec/acceptance/v2/reactions_spec.rb
  back/engines/commercial/public_api/spec/acceptance/v2/volunteering_causes_spec.rb
  back/engines/commercial/public_api/spec/acceptance/v2/volunteering_volunteers_spec.rb
  back/engines/free/email_campaigns/app/models/email_campaigns/campaign.rb
Labels: methods

#5986 Fix styles of commenting module
  front/app/components/PostShowComponents/Comments/ParentCommentForm.tsx
  front/app/components/PostShowComponents/Comments/PublicComments.tsx
Labels: structure, proposals

#5994 Don't allow proposal commenting when profile not completed
  front/app/components/PostShowComponents/Comments/PublicComments.tsx
Labels: structure, proposals

#6005 CL-4022 - Allow moderators of imported users to update them
  back/app/policies/user_policy.rb
  back/engines/commercial/bulk_import_ideas/app/policies/bulk_import_ideas/patches/user_policy.rb
  back/engines/commercial/bulk_import_ideas/spec/policies/user_policy_spec.rb
  back/engines/commercial/bulk_import_ideas/spec/services/import_global_ideas_service_spec.rb
Labels: methods

#6007 CL-4022 - Add import column to idea export
  back/app/services/xlsx_service.rb
  back/engines/commercial/bulk_import_ideas/app/services/bulk_import_ideas/patches/xlsx_service.rb
  back/engines/commercial/bulk_import_ideas/spec/services/xlsx_service_spec.rb
  back/engines/commercial/idea_custom_fields/spec/services/xlsx_service_spec.rb
Labels: methods

#6027 Add header_bg E2E test for proposal form
  front/app/containers/InitiativesShow/InitiativeBanner.tsx
  front/cypress/e2e/proposal_edit_page.cy.ts
Labels: structure

#6032 [CL-4045] Revert to previous low-res email logo aproach
  back/app/mailers/application_mailer.rb
  back/app/views/application/_logo_medium_top.mjml
  back/engines/free/email_campaigns/app/views/email_campaigns/application/_head.mjml
Labels: bug, structure
