Repository CitizenLabDotCo/citizenlab, pull requests merged in 2023-02, with the labels that each got.

#3846 CL-1560: fix start from scratch label
  CHANGELOG.md
  front/app/utils/moduleUtils.test.ts
  front/app/utils/moduleUtils.tsx
Labels: methods

#3884 Use right image ratio for project/folder card preview
  front/app/containers/Admin/projectFolders/containers/settings/ProjectFolderForm/ProjectFolderCardImageDropzone.tsx
  front/app/containers/Admin/projectFolders/containers/settings/ProjectFolderForm/index.tsx
  front/app/containers/Admin/projects/project/general/components/ProjectCardImageDropzone.tsx
  front/app/containers/Admin/projects/project/general/index.tsx
Labels: structure

#3903 Ts config no implicit any
  front/app/components/ConsentForm/index.tsx
  front/app/components/FilterSelector/index.tsx
  front/app/components/IdeaCards/TopicFilterDropdown.tsx
  front/app/components/IdeaForm/index.tsx
  front/app/components/InitiativeForm/index.tsx
  front/app/components/UI/Warning/index.tsx
  front/app/components/admin/PostManager/components/FilterSidebar/FilterSidebarPhasesItem.tsx
  front/app/components/admin/PostManager/components/IdeasCount.tsx
  front/app/components/admin/PostManager/components/InfoSidebar/index.tsx
  front/app/components/admin/PostManager/components/InitiativesCount.tsx
  front/app/components/admin/PostManager/components/PostTable/AssigneeSelect.tsx
  front/app/components/admin/PostManager/components/PostTable/Row/IdeaRow.tsx
  front/app/components/admin/PostManager/components/PostTable/Row/InitiativeRow.tsx
  front/app/containers/Admin/dashboard/users/Charts/PieChartByCategory.tsx
  front/app/modules/commercial/smart_groups/components/UserFilterConditions/ValueSelector/AreaValueSelector.tsx
  front/app/modules/commercial/smart_groups/components/UserFilterConditions/ValueSelector/AreaValuesSelector.tsx
  front/app/modules/commercial/smart_groups/components/UserFilterConditions/ValueSelector/CustomFieldOptionValueSelector.tsx
  front/app/modules/commercial/smart_groups/components/UserFilterConditions/ValueSelector/NumberValueSelector.tsx
  front/app/modules/commercial/smart_groups/components/UserFilterConditions/ValueSelector/ProjectValuesSelector.tsx
  front/app/modules/commercial/smart_groups/components/UserFilterConditions/ValueSelector/TextValueSelector.tsx
  front/app/modules/commercial/widgets/admin/containers/WidgetCode.tsx
  front/app/resources/GetCommentsForUser.tsx
  front/app/services/campaignConsents.ts
Labels: ts-config

#3780 [CL2641] Add feature flag for ideation form builder
  back/config/schemas/settings.schema.json.erb
  back/engines/commercial/multi_tenancy/db/seeds/tenants.rb
  back/engines/commercial/multi_tenancy/lib/tasks/core/create_tenant.rake
  front/app/components/FormBuilder/components/FormBuilderToolbox/BuiltInFields.tsx
  front/app/components/FormBuilder/components/FormBuilderToolbox/LayoutFields.tsx
  front/app/components/FormBuilder/components/FormBuilderToolbox/ToolboxItem.tsx
  front/app/components/FormBuilder/components/FormBuilderToolbox/index.tsx
  front/app/components/FormBuilder/components/FormFields/FieldElement.tsx
  front/app/components/FormBuilder/components/messages.ts
  front/app/components/FormBuilder/utils.ts
  front/app/containers/Admin/projects/project/inputForm/messages.ts
  front/app/containers/Admin/projects/project/inputForm/utils.tsx
  front/app/containers/Admin/projects/project/nativeSurvey/utils.tsx
  front/app/services/appConfiguration.ts
  front/app/translations/admin/ar-MA.json
  front/app/translations/admin/ar-SA.json
  front/app/translations/admin/da-DK.json
  front/app/translations/admin/de-DE.json
  front/app/translations/admin/en-CA.json
  front/app/translations/admin/en-GB.json
  front/app/translations/admin/en.json
  front/app/translations/admin/es-CL.json
  front/app/translations/admin/es-ES.json
  front/app/translations/admin/fr-BE.json
  front/app/translations/admin/fr-FR.json
  front/app/translations/admin/hr-HR.json
  front/app/translations/admin/lv-LV.json
  front/app/translations/admin/nb-NO.json
  front/app/translations/admin/nl-BE.json
  front/app/translations/admin/nl-NL.json
  front/app/translations/admin/pl-PL.json
  front/app/translations/admin/pt-BR.json
  front/app/translations/admin/sr-Latn.json
  front/app/translations/admin/sv-SE.json
  front/app/translations/admin/tr-TR.json
  front/app/translations/en.json
Labels: methods

#3850 [CL-1957] Copy content_builder_layouts when copy Project
  back/app/services/project_copy_service.rb
  back/engines/commercial/content_builder/app/models/content_builder/layout_image.rb
  back/spec/fixtures/craftjs_layout_with_2_images.json.erb
  back/spec/services/local_project_copy_service_spec.rb
Labels: structure

#3893 [CL-2618] Remove unnecessary call for slug
  front/app/containers/Admin/projects/components/ProjectRow/ManageButton.test.tsx
  front/app/modules/commercial/matomo/getProjectId.test.ts
  front/app/modules/commercial/matomo/getProjectId.ts
  front/cypress/e2e/admin/projects/edit_project.cy.ts
Labels: structure

#3929 [CL-1957] Move tests into correct scope + remove if Citizenlab.ee?
  back/spec/services/local_project_copy_service_spec.rb
Labels: structure

#3902 [CL-2686] Add validation of image presence & skip validation when applying template
  back/app/models/idea_image.rb
  back/engines/commercial/multi_tenancy/app/services/multi_tenancy/tenant_template_service.rb
  back/spec/acceptance/ideas_spec.rb
Labels: structure

#3854 [CL-2733] Flexible ideation i1 UI tweaks
  back/app/models/custom_field.rb
  back/app/serializers/web_api/v1/custom_field_serializer.rb
  back/app/services/input_ui_schema_generator_service.rb
  back/config/locales/en-CA.yml
  back/config/locales/en-GB.yml
  back/config/locales/en.yml
  back/db/migrate/20230206090743_add_answer_visible_to_custom_fields.rb
  back/db/schema.rb
  back/lib/participation_method/ideation.rb
  back/spec/models/custom_field_spec.rb
  front/app/components/Form/Components/Controls/InputControl.tsx
  front/app/components/Form/Components/Controls/LinearScaleControl.tsx
  front/app/components/Form/Components/Controls/MultiSelectCheckboxControl.tsx
  front/app/components/Form/Components/Controls/SingleSelectRadioControl.tsx
  front/app/components/Form/Components/Controls/TextAreaControl.tsx
  front/app/components/Form/Components/Controls/messages.ts
  front/app/components/FormBuilder/components/FormBuilderSettings/LinearScaleSettings/RangeInput.tsx
  front/app/components/FormBuilder/components/FormBuilderSettings/LinearScaleSettings/ScaleLabelsInput.tsx
  front/app/components/FormBuilder/components/FormBuilderToolbox/BuiltInFields.tsx
  front/app/components/FormBuilder/components/FormBuilderToolbox/ToolboxItem.tsx
  front/app/components/FormBuilder/components/FormBuilderToolbox/index.tsx
  front/app/translations/en.json
Labels: methods

#3918 CL-2446 Schemas
  back/app/controllers/web_api/v1/ideas_controller.rb
  back/app/controllers/web_api/v1/phase_custom_fields_controller.rb
  back/app/controllers/web_api/v1/project_custom_fields_controller.rb
  back/app/services/custom_field_service.rb
  back/app/services/field_visitor_service.rb
  back/app/services/json_forms_service.rb
  back/app/services/xlsx_export/value_visitor.rb
  back/config/locales/en.yml
  back/config/routes.rb
  back/lib/participation_method/base.rb
  back/lib/participation_method/ideation.rb
  back/spec/acceptance/ideas_spec.rb
  back/spec/acceptance/phase_custom_fields_spec.rb
  back/spec/acceptance/project_custom_fields_spec.rb
  back/spec/services/custom_field_service_spec.rb
  back/spec/services/json_forms_service_spec.rb
  back/spec/services/xlsx_export/value_visitor_spec.rb
Labels: methods

#3847 [CL-2673] Survey UI update
  CHANGELOG.md
  front/app/components/Form/Components/Controls/LinearScaleControl.tsx
  front/app/components/Form/Components/Controls/MultiSelectCheckboxControl.tsx
  front/app/components/Form/Components/Controls/SingleSelectRadioControl.tsx
  front/app/components/Form/Components/Layouts/CLPageLayout.tsx
  front/app/components/UI/PageContainer/index.tsx
  front/app/containers/IdeasNewPage/WithJSONForm/Heading.tsx
  front/cypress/e2e/form_builder/create_and_fill_survey.cy.ts
  front/cypress/e2e/form_builder/elements/linear_scale_field.cy.ts
  front/package-lock.json
  front/package.json
Labels: methods

#3911 [CL-2747] custom field answer visible to
  back/app/serializers/web_api/v1/custom_field_serializer.rb
  back/app/services/custom_field_service.rb
  back/app/services/idea_custom_fields_service.rb
  back/app/services/input_ui_schema_generator_service.rb
  back/app/services/json_forms_service.rb
  back/engines/commercial/idea_custom_fields/app/controllers/idea_custom_fields/web_api/v1/admin/idea_custom_fields_controller.rb
  back/engines/commercial/idea_custom_fields/app/serializers/idea_custom_fields/extensions/web_api/v1/idea_serializer.rb
  back/engines/commercial/idea_custom_fields/spec/serializers/web_api/v1/idea_serializer_spec.rb
  back/lib/participation_method/base.rb
  back/lib/participation_method/ideation.rb
  back/spec/models/custom_field_spec.rb
  back/spec/serializers/web_api/v1/custom_field_serializer_spec.rb
  back/spec/services/idea_custom_fields_service_spec.rb
  back/spec/services/input_ui_schema_generator_service_spec.rb
  back/spec/services/json_forms_service_spec.rb
Labels: methods

#3853 [CL-2462] Migrate input form custom fields
  back/engines/commercial/multi_tenancy/lib/tasks/core/migrate_flexible_input_forms.rake
Labels: methods

#3829 [CL-2647] Section and page restrictions
  back/app/services/idea_custom_fields_service.rb
  back/engines/commercial/idea_custom_fields/app/controllers/idea_custom_fields/web_api/v1/admin/idea_custom_fields_controller.rb
  back/engines/commercial/multi_tenancy/lib/tasks/core/migrate_flexible_input_forms.rake
  back/lib/participation_method/base.rb
  back/lib/participation_method/ideation.rb
  back/lib/participation_method/native_survey.rb
  back/spec/services/idea_custom_fields_service_spec.rb
Labels: methods

#3943 CL-2777: Fix multiple calls to complete registration
  front/app/containers/Authentication/SignUpIn/SignUpInModal/SignUp/index.tsx
Labels: structure

#3920 Cl 2672 change text in tooltips
  CHANGELOG.md
  front/app/components/admin/ImageCropper/messages.ts
  front/app/components/admin/ProjectableHeaderBgUploader/index.tsx
  front/app/components/admin/ProjectableHeaderBgUploader/messages.ts
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/BannerImageFields/ImageInfoTooltip.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/BannerImageFields/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/BannerImageFields/messages.ts
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/LayoutSettingField/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/messages.ts
  front/app/containers/Admin/projectFolders/containers/messages.ts
  front/app/containers/Admin/projectFolders/containers/settings/ProjectFolderForm/FolderCardImageTooltip.tsx
  front/app/containers/Admin/projectFolders/containers/settings/ProjectFolderForm/FolderHeaderImageTooltip.tsx
  front/app/containers/Admin/projectFolders/containers/settings/ProjectFolderForm/index.tsx
  front/app/containers/Admin/projectFolders/containers/settings/ProjectFolderForm/messages.ts
  front/app/containers/Admin/projects/project/general/components/ProjectCardImageTooltip.tsx
  front/app/containers/Admin/projects/project/general/components/ProjectHeaderImageTooltip.tsx
  front/app/containers/Admin/projects/project/general/index.tsx
  front/app/containers/Admin/projects/project/general/messages.ts
  front/app/translations/admin/ar-MA.json
  front/app/translations/admin/ar-SA.json
  front/app/translations/admin/da-DK.json
  front/app/translations/admin/de-DE.json
  front/app/translations/admin/en-CA.json
  front/app/translations/admin/en-GB.json
  front/app/translations/admin/en.json
  front/app/translations/admin/es-CL.json
  front/app/translations/admin/es-ES.json
  front/app/translations/admin/fr-BE.json
  front/app/translations/admin/fr-FR.json
  front/app/translations/admin/hr-HR.json
  front/app/translations/admin/lv-LV.json
  front/app/translations/admin/nb-NO.json
  front/app/translations/admin/nl-BE.json
  front/app/translations/admin/nl-NL.json
  front/app/translations/admin/pl-PL.json
  front/app/translations/admin/pt-BR.json
  front/app/translations/admin/sr-Latn.json
  front/app/translations/admin/sv-SE.json
  front/app/translations/admin/tr-TR.json
Labels: structure

#3925 [CL-737] Show login screen after successful password reset
  front/app/containers/PasswordRecovery/index.tsx
  front/app/containers/PasswordRecovery/messages.ts
  front/app/containers/PasswordReset/PasswordReset.test.tsx
  front/app/containers/PasswordReset/PasswordResetSuccess.test.tsx
  front/app/containers/PasswordReset/PasswordResetSuccess.tsx
  front/app/containers/PasswordReset/index.tsx
  front/app/containers/PasswordReset/messages.ts
  front/app/translations/ar-MA.json
  front/app/translations/ar-SA.json
  front/app/translations/ca-ES.json
  front/app/translations/da-DK.json
  front/app/translations/de-DE.json
  front/app/translations/el-GR.json
  front/app/translations/en-CA.json
  front/app/translations/en-GB.json
  front/app/translations/en.json
  front/app/translations/es-CL.json
  front/app/translations/es-ES.json
  front/app/translations/fr-BE.json
  front/app/translations/fr-FR.json
  front/app/translations/hr-HR.json
  front/app/translations/hu-HU.json
  front/app/translations/it-IT.json
  front/app/translations/kl-GL.json
  front/app/translations/lb-LU.json
  front/app/translations/lv-LV.json
  front/app/translations/mi.json
  front/app/translations/nb-NO.json
  front/app/translations/nl-BE.json
  front/app/translations/nl-NL.json
  front/app/translations/pl-PL.json
  front/app/translations/pt-BR.json
  front/app/translations/ro-RO.json
  front/app/translations/sr-Latn.json
  front/app/translations/sr-SP.json
  front/app/translations/sv-SE.json
  front/app/translations/tr-TR.json
  front/cypress/e2e/password-reset.cy.ts
Labels: waiting for translations, structure

#3952 [CL-2783] Ideation form builder UI tweaks
  front/app/components/FormBuilder/components/FormBuilderToolbox/index.tsx
  front/app/components/FormBuilder/edit/index.tsx
  front/app/components/FormBuilder/messages.ts
  front/app/translations/admin/ar-SA.json
  front/app/translations/admin/da-DK.json
  front/app/translations/admin/de-DE.json
  front/app/translations/admin/en-CA.json
  front/app/translations/admin/en-GB.json
  front/app/translations/admin/en.json
  front/app/translations/admin/es-CL.json
  front/app/translations/admin/es-ES.json
  front/app/translations/admin/fr-BE.json
  front/app/translations/admin/fr-FR.json
  front/app/translations/admin/hr-HR.json
  front/app/translations/admin/lv-LV.json
  front/app/translations/admin/nb-NO.json
  front/app/translations/admin/nl-BE.json
  front/app/translations/admin/nl-NL.json
  front/app/translations/admin/pl-PL.json
  front/app/translations/admin/pt-BR.json
  front/app/translations/admin/sr-Latn.json
  front/app/translations/admin/sv-SE.json
  front/app/translations/admin/tr-TR.json
  front/app/translations/en.json
Labels: methods

#3946 Fix flaky e2e tests
  front/cypress/e2e/idea_page_action.cy.ts
  front/cypress/e2e/project_description_builder/project_description_builder_navigation.cy.ts
Labels: methods

#3901 [CL-2683] fix registration chart visitor count
  front/app/modules/commercial/analytics/admin/components/RegistrationsCard/useRegistrations/query.ts
Labels: structure

#3887 [CL-2746] Add content_builder layouts & images to serializer
  CHANGELOG.md
  back/app/models/idea_image.rb
  back/engines/commercial/content_builder/app/models/content_builder/layout_image.rb
  back/engines/commercial/multi_tenancy/app/services/multi_tenancy/templates/serializer.rb
  back/engines/commercial/multi_tenancy/app/services/multi_tenancy/tenant_template_service.rb
Labels: structure

#3960 [CL-2772] Don't copy created_at & updated_at when using LocalProjectCopyService
  back/app/services/project_copy_service.rb
Labels: structure

#3982 [CL-2764] Skip LogActivityJob & DumpTenantJob in apply_template when local_copy
  back/app/services/project_copy_service.rb
  back/engines/commercial/multi_tenancy/app/services/multi_tenancy/tenant_template_service.rb
Labels: structure

#3941 Copy project tests
  front/app/components/Form/Components/Controls/InputControl.test.tsx
  front/app/components/UI/MoreActionsMenu/index.tsx
  front/app/containers/Admin/projects/all/Lists/ModeratorProjectList.tsx
  front/app/containers/Admin/projects/components/ProjectRow/ProjectMoreActionsMenu.test.tsx
  front/app/containers/Admin/projects/components/ProjectRow/ProjectMoreActionsMenu.tsx
  front/app/containers/Admin/projects/components/ProjectRow/ProjectRow.test.tsx
  front/app/containers/Admin/projects/components/ProjectRow/index.tsx
  front/app/containers/Admin/projects/projectFolders/components/ProjectFolderRow/FolderMoreActionsMenu.test.tsx
  front/app/containers/Admin/projects/projectFolders/components/ProjectFolderRow/FolderMoreActionsMenu.tsx
  front/app/containers/Admin/projects/projectFolders/components/ProjectFolderRow/ProjectFolderRow.test.tsx
  front/app/containers/Admin/projects/projectFolders/components/ProjectFolderRow/index.tsx
  front/app/containers/Admin/projects/projectFolders/components/ProjectFolderRow/messages.ts
  front/app/services/users.ts
Labels: structure

#3965 [CL-2792] Add warning to ideation form builder
  front/app/components/FormBuilder/edit/index.tsx
  front/app/components/FormBuilder/utils.ts
  front/app/containers/Admin/projects/project/inputForm/messages.ts
  front/app/containers/Admin/projects/project/inputForm/utils.tsx
  front/app/containers/Admin/projects/project/nativeSurvey/utils.tsx
  front/app/translations/admin/en.json
  front/cypress/e2e/input_form_builder/built-in-fields/attachments.cy.ts
  front/cypress/e2e/input_form_builder/built-in-fields/description.cy.ts
  front/cypress/e2e/input_form_builder/built-in-fields/images.cy.ts
  front/cypress/e2e/input_form_builder/built-in-fields/location.cy.ts
  front/cypress/e2e/input_form_builder/built-in-fields/proposed_budget.cy.ts
  front/cypress/e2e/input_form_builder/built-in-fields/tags.cy.ts
  front/cypress/e2e/input_form_builder/built-in-fields/title.cy.ts
  front/cypress/e2e/input_form_builder/create_and_fill_form.cy.ts
Labels: methods

#3989 Ts config no implicit any
  front/app/components/admin/ContentBuilder/Widgets/Button/index.tsx
  front/app/components/admin/ContentBuilder/Widgets/Iframe/index.tsx
  front/app/components/admin/ContentBuilder/Widgets/Image/index.tsx
  front/app/components/admin/ContentBuilder/Widgets/Text/index.tsx
  front/app/components/admin/ContentBuilder/Widgets/TwoColumn/index.tsx
  front/app/components/admin/ContentBuilder/Widgets/WhiteSpace/index.tsx
  front/app/containers/Admin/messaging/index.tsx
  front/app/containers/Admin/projects/project/participationContext/utils/validate.tsx
  front/app/containers/Admin/projects/project/poll/PollAdminForm.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/_shared/ChartWidgetSettings.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/MostVotedIdeasWidget/Settings/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/SurveyResultsWidget/index.tsx
Labels: ts-config

#3969 CL-2769: Add tests for the folder moderator
  front/app/containers/Admin/projects/components/ProjectRow/ProjectMoreActionsMenu.test.tsx
  front/app/containers/Admin/projects/components/ProjectRow/ProjectMoreActionsMenu.tsx
  front/app/containers/Admin/projects/projectFolders/components/ProjectFolderRow/ProjectFolderRow.test.tsx
  front/app/containers/Admin/projects/projectFolders/components/ProjectFolderRow/index.tsx
  front/app/containers/Admin/projects/projectFolders/components/ProjectFolderRow/messages.ts
Labels: structure

#3988 CL-2778: Add end to end tests covering copying and deleting projects
  front/cypress/e2e/admin/projects/copy_project.cy.ts
  front/cypress/e2e/admin/projects/delete_project.cy.ts
Labels: structure

#3963 [CL-2794] Fix sharing modal not showing on new idea page (PR attempt #2)
  front/app/containers/IdeasShow/index.tsx
  front/cypress/e2e/idea_page_content.cy.ts
Labels: methods

#4004 Cl 2834 fe load projects inside folder row for extra robustness
  front/app/containers/Admin/projects/components/ProjectRow/index.tsx
  front/app/containers/Admin/projects/projectFolders/components/ProjectFolderRow/ProjectFolderRow.test.tsx
  front/app/containers/Admin/projects/projectFolders/components/ProjectFolderRow/index.tsx
Labels: structure

#4015 [CL-2843] Disable franceconnect_login in seeds
  back/engines/commercial/multi_tenancy/db/seeds/tenants.rb
Labels: structure

#4025 [CL-2844] Handle view form button for non-active ideation phases
  front/app/components/FormBuilder/edit/index.tsx
  front/app/components/FormBuilder/utils.ts
  front/app/containers/Admin/projects/project/inputForm/IdeaFormBuilder/index.tsx
  front/app/containers/Admin/projects/project/inputForm/index.tsx
  front/app/containers/Admin/projects/project/inputForm/utils.tsx
  front/app/containers/Admin/projects/project/nativeSurvey/utils.tsx
  front/app/containers/Admin/projects/routes.tsx
Labels: methods

#4021 Cl 2835 fe fix styling of child rows in folder rows test fixes
  front/app/containers/Admin/pagesAndMenu/containers/ProjectsList/ProjectsListContent.tsx
  front/app/containers/Admin/projectFolders/containers/projects/ItemsInFolder.tsx
  front/app/containers/Admin/projectFolders/containers/projects/ItemsNotInFolder.tsx
  front/app/containers/Admin/projects/all/Lists/AdminProjectList.tsx
  front/app/containers/Admin/projects/all/Lists/FolderChildProjects.tsx
  front/app/containers/Admin/projects/all/Lists/NonSortableFolderRow.tsx
  front/app/containers/Admin/projects/all/Lists/SortableFolderRow.tsx
  front/app/containers/Admin/projects/components/ProjectRow/ManageButton.tsx
  front/app/containers/Admin/projects/components/ProjectRow/ProjectMoreActionsMenu.test.tsx
  front/app/containers/Admin/projects/components/ProjectRow/ProjectMoreActionsMenu.tsx
  front/app/containers/Admin/projects/components/ProjectRow/ProjectRow.test.tsx
  front/app/containers/Admin/projects/components/ProjectRow/index.tsx
  front/app/containers/Admin/projects/projectFolders/components/ProjectFolderRow/FolderMoreActionsMenu.tsx
  front/app/containers/Admin/projects/projectFolders/components/ProjectFolderRow/ProjectFolderRow.test.tsx
  front/app/services/adminPublications.ts
Labels: structure

#4030 CL-2839: Add spinner next to project and folder title
  front/app/containers/Admin/projects/components/ProjectRow/ProjectMoreActionsMenu.tsx
  front/app/containers/Admin/projects/components/ProjectRow/index.tsx
  front/app/containers/Admin/projects/projectFolders/components/ProjectFolderRow/FolderMoreActionsMenu.tsx
  front/app/containers/Admin/projects/projectFolders/components/ProjectFolderRow/index.tsx
Labels: structure

#3990 Ts config media
  front/app/components/ConsentManager/Banner.tsx
  front/app/components/IdeasMap/index.tsx
  front/app/components/PageNotFound/index.tsx
  front/app/components/ProjectAndFolderCards/components/Topbar/index.tsx
  front/app/components/UI/FullPageSpinner/index.tsx
  front/app/components/UI/FullscreenModal/index.tsx
  front/app/components/UI/Modal/index.tsx
  front/app/services/actionPermissions.ts
Labels: ts-config

#4008 Cl 2835 fe fix styling of child rows in folder rows
  front/app/containers/Admin/pagesAndMenu/containers/ProjectsList/ProjectsListContent.tsx
  front/app/containers/Admin/projectFolders/containers/projects/ItemsInFolder.tsx
  front/app/containers/Admin/projectFolders/containers/projects/ItemsNotInFolder.tsx
  front/app/containers/Admin/projects/all/Lists/AdminProjectList.tsx
  front/app/containers/Admin/projects/all/Lists/FolderChildProjects.tsx
  front/app/containers/Admin/projects/all/Lists/ModeratorProjectList.tsx
  front/app/containers/Admin/projects/all/Lists/NonSortableFolderRow.test.tsx
  front/app/containers/Admin/projects/all/Lists/NonSortableFolderRow.tsx
  front/app/containers/Admin/projects/all/Lists/SortableFolderRow.tsx
  front/app/containers/Admin/projects/components/ProjectRow/ManageButton.tsx
  front/app/containers/Admin/projects/components/ProjectRow/ProjectMoreActionsMenu.test.tsx
  front/app/containers/Admin/projects/components/ProjectRow/ProjectMoreActionsMenu.tsx
  front/app/containers/Admin/projects/components/ProjectRow/ProjectRow.test.tsx
  front/app/containers/Admin/projects/components/ProjectRow/index.tsx
  front/app/containers/Admin/projects/projectFolders/components/ProjectFolderRow/FolderMoreActionsMenu.tsx
  front/app/containers/Admin/projects/projectFolders/components/ProjectFolderRow/ProjectFolderRow.test.tsx
  front/app/containers/Admin/projects/projectFolders/components/ProjectFolderRow/index.tsx
  front/app/services/adminPublications.ts
Labels: structure

#4023 Cl 2815/segment
  front/app/components/ConsentManager/PreferencesModal/Preferences.test.tsx
  front/app/modules/commercial/segment/index.tsx
Labels: platform

#4044 [CL-2894] Preserve Acts::List ordering field source values when applying template
  back/engines/commercial/multi_tenancy/app/services/multi_tenancy/tenant_template_service.rb
  back/engines/commercial/multi_tenancy/spec/services/multi_tenancy/templates/serializer_spec.rb
  back/spec/services/local_project_copy_service_spec.rb
  back/spec/services/project_copy_service_spec.rb
Labels: structure

#4036 [CL-2842] Store original image URLs temporarily in new project
  back/app/jobs/image_assignment_job.rb
  back/app/jobs/save_temp_remote_file_job.rb
  back/app/models/app_configuration.rb
  back/app/services/local_project_copy_service.rb
  back/app/services/project_copy_service.rb
  back/app/uploaders/base_image_uploader.rb
  back/app/uploaders/base_uploader.rb
  back/engines/commercial/multi_tenancy/app/services/multi_tenancy/tenant_template_service.rb
  back/lib/carrierwave_temp_remote.rb
  back/spec/lib/carrierwave_temp_remote_spec.rb
  back/spec/uploaders/base_uploader_spec.rb
  env_files/back-safe.env
Labels: structure

#4068 [CL-2918] Remove double border for folder moderators
  front/app/containers/Admin/projects/all/Lists/FolderChildProjects.tsx
  front/app/containers/Admin/projects/all/Lists/NonSortableFolderRow.tsx
  front/app/containers/Admin/projects/all/Lists/SortableFolderRow.tsx
Labels: structure

#4069 Cl 2799 log in window UI glitches
  front/app/containers/Authentication/SignUpIn/SignUpInModal/SignIn/PasswordSignin.tsx
  front/app/containers/Authentication/SignUpIn/SignUpInModal/SignUp/messages.ts
  front/app/translations/ar-MA.json
  front/app/translations/ar-SA.json
  front/app/translations/ca-ES.json
  front/app/translations/da-DK.json
  front/app/translations/de-DE.json
  front/app/translations/el-GR.json
  front/app/translations/en-CA.json
  front/app/translations/en-GB.json
  front/app/translations/en.json
  front/app/translations/es-CL.json
  front/app/translations/es-ES.json
  front/app/translations/fr-BE.json
  front/app/translations/fr-FR.json
  front/app/translations/hr-HR.json
  front/app/translations/hu-HU.json
  front/app/translations/it-IT.json
  front/app/translations/kl-GL.json
  front/app/translations/lb-LU.json
  front/app/translations/lv-LV.json
  front/app/translations/mi.json
  front/app/translations/nb-NO.json
  front/app/translations/nl-BE.json
  front/app/translations/nl-NL.json
  front/app/translations/pl-PL.json
  front/app/translations/pt-BR.json
  front/app/translations/ro-RO.json
  front/app/translations/sr-Latn.json
  front/app/translations/sr-SP.json
  front/app/translations/sv-SE.json
  front/app/translations/tr-TR.json
  front/package-lock.json
  front/package.json
Labels: structure

#4050 [CL-2790] Add tests to cover deleting and copying failure
  front/app/containers/Admin/projects/components/ProjectRow/ProjectMoreActionsMenu.test.tsx
  front/app/containers/Admin/projects/projectFolders/components/ProjectFolderRow/FolderMoreActionsMenu.test.tsx
Labels: structure

#4077 [CL-2927] Fix refresh issue on deletion of project in folder
  front/app/containers/Admin/projects/all/Lists/FolderChildProjects.tsx
Labels: structure

#3928 [CL-2753] Task to destroy orphaned layout_images & text_images records
  back/engines/commercial/content_builder/app/services/content_builder/layout_service.rb
  back/engines/commercial/multi_tenancy/lib/tasks/core/clean_up_orphaned_image_records.rake
  back/engines/commercial/multi_tenancy/spec/tasks/clean_up_orphaned_image_records_task_spec.rb
  back/spec/services/local_project_copy_service_spec.rb
Labels: structure

#4085 Cl 2173 project admins shouldnt be able to send emails to the whole platform
  CHANGELOG.md
  front/app/containers/Admin/messaging/CustomEmails/All/NewCampaignButton.tsx
  front/app/containers/Admin/messaging/CustomEmails/All/index.tsx
  front/app/containers/Admin/projects/project/permissions/components/ModeratorList.tsx
  front/app/services/permissions/rules/routePermissions.ts
Labels: structure

#4080 Align text of Statistic to the left
  CHANGELOG.md
  front/app/components/admin/Graphs/Statistic/index.tsx
Labels: structure

#4089 use useFeatureFlag
  front/app/containers/Admin/reporting/components/Tabs.tsx
  front/app/containers/Admin/reporting/containers/ReportBuilderPage/index.tsx
  front/app/translations/admin/en.json
Labels: structure

#4088 CL-2916 Custom idea statuses
  front/app/api/idea_statuses/__mocks__/useIdeaStatuses.ts
  front/app/api/idea_statuses/keys.ts
  front/app/api/idea_statuses/types.ts
  front/app/api/idea_statuses/useAddIdeaStatus.test.ts
  front/app/api/idea_statuses/useAddIdeaStatus.ts
  front/app/api/idea_statuses/useDeleteIdeaStatus.test.ts
  front/app/api/idea_statuses/useDeleteIdeaStatus.ts
  front/app/api/idea_statuses/useIdeaStatus.test.ts
  front/app/api/idea_statuses/useIdeaStatus.ts
  front/app/api/idea_statuses/useIdeaStatuses.test.ts
  front/app/api/idea_statuses/useIdeaStatuses.ts
  front/app/api/idea_statuses/useUpdateIdeaStatus.test.ts
  front/app/api/idea_statuses/useUpdateIdeaStatus.ts
  front/app/components/FilterBoxes/StatusFilter.tsx
  front/app/components/StatusBadge/index.tsx
  front/app/components/admin/PostManager/components/FilterSidebar/FilterSidebarStatuses.tsx
  front/app/components/admin/PostManager/components/FilterSidebar/FilterSidebarStatusesItem.tsx
  front/app/components/admin/PostManager/components/FilterSidebar/index.tsx
  front/app/components/admin/PostManager/components/PostTable/PostTable.test.tsx
  front/app/components/admin/PostManager/components/PostTable/Row/IdeaRow.tsx
  front/app/components/admin/PostManager/components/PostTable/Row/SubRow.tsx
  front/app/components/admin/PostManager/components/PostTable/Row/index.tsx
  front/app/components/admin/PostManager/components/PostTable/Row/selectors/IdeasStatusSelector.tsx
  front/app/components/admin/PostManager/components/PostTable/index.tsx
  front/app/containers/IdeasShow/MetaInformation/Status.tsx
  front/app/hooks/useIdeaStatus.ts
  front/app/hooks/useIdeaStatuses.ts
  front/app/modules/commercial/custom_idea_statuses/admin/components/IdeaStatusForm.tsx
  front/app/modules/commercial/custom_idea_statuses/admin/containers/edit.tsx
  front/app/modules/commercial/custom_idea_statuses/admin/containers/index.tsx
  front/app/modules/commercial/custom_idea_statuses/admin/containers/new.tsx
  front/app/modules/commercial/smart_groups/components/UserFilterConditions/ValueSelector/IdeaStatusValueSelector.tsx
  front/app/modules/commercial/smart_groups/components/UserFilterConditions/ValueSelector/IdeaStatusValuesSelector.tsx
  front/app/resources/GetIdeaStatuses.tsx
  front/app/services/ideaStatuses.ts
Labels: platform

#3971 [CL-2766] Add new email and confirmation option to action permissions
  front/app/modules/commercial/granular_permissions/admin/containers/Granular/ActionForm.tsx
  front/app/modules/commercial/granular_permissions/admin/containers/Granular/messages.ts
  front/app/services/actionPermissions.ts
  front/app/translations/admin/en.json
Labels: methods

#4118 use useIdea inside GetIdea
  front/app/resources/GetIdea.tsx
Labels: platform-week-23Q1

#4121 Cl 2975 replace get idea images with hook or use hook inside
  front/app/components/admin/PostManager/components/LazyPostPreview/Idea/IdeaContent.test.tsx
  front/app/components/admin/PostManager/components/LazyPostPreview/Idea/IdeaContent.tsx
  front/app/components/admin/PostManager/components/LazyPostPreview/Idea/__snapshots__/IdeaContent.test.tsx.snap
  front/app/containers/IdeasShow/IdeaMeta.tsx
  front/app/containers/IdeasShow/index.tsx
  front/app/resources/GetIdeaImages.tsx
Labels: platform-week-23Q1

#4122 CL-2980 Refactor GetIdeasCount
  front/app/components/admin/PostManager/components/IdeasCount.tsx
  front/app/components/admin/PostManager/index.tsx
  front/app/hooks/useIdeasCount.ts
  front/app/resources/GetIdeasCount.test.tsx
  front/app/resources/GetIdeasCount.tsx
  front/app/services/stats.ts
Labels: platform-week-23Q1

#4139 Add type and correct data
  front/app/api/idea_statuses/__mocks__/useIdeaStatuses.ts
Labels: platform-week-23Q1

#4135 CL-2906 Skip tests on production
  .circleci/config.yml
Labels: platform-week-23Q1
