Repository CitizenLabDotCo/citizenlab, pull requests merged in 2023-04, with the labels that each got.

#4478 Cl 3194 2 fix data freshness issue
  front/app/components/UI/UserSelect/index.tsx
  front/app/containers/Admin/projects/project/permissions/components/UserSearch.tsx
  front/app/services/projectFolderModerators.ts
  front/app/services/projectModerators.ts
Labels: structure

#4382 Cl 3194 fe dont show admins in project moderator lists
  front/app/components/Form/Components/Controls/UserPickerControl.tsx
  front/app/components/SeatInfo/index.tsx
  front/app/components/UI/UserSelect/Avatar.tsx
  front/app/components/UI/UserSelect/index.tsx
  front/app/components/admin/AddCollaboratorsModal/AddCollaboratorsModal.test.tsx
  front/app/components/admin/AddCollaboratorsModal/index.tsx
  front/app/components/admin/AddCollaboratorsModal/messages.ts
  front/app/containers/Admin/projectFolders/containers/permissions/index.tsx
  front/app/containers/Admin/projects/project/index.tsx
  front/app/containers/Admin/projects/project/permissions/components/UserSearch.tsx
  front/app/containers/Admin/projects/project/permissions/containers/ProjectManagement/index.tsx
  front/app/containers/Admin/projects/project/permissions/index.tsx
  front/app/resources/GetUsers.tsx
  front/app/services/groupMemberships.ts
  front/app/services/projectFolderModerators.ts
  front/app/services/projectModerators.ts
  front/app/translations/admin/en.json
Labels: structure

#4409 CTA component clean-up
  front/app/containers/HomePage/SignedInHeader/CTA.tsx
  front/app/containers/HomePage/SignedInHeader/FallbackStep.tsx
  front/app/containers/HomePage/SignedOutHeader/CTA.tsx
  front/app/containers/HomePage/SignedOutHeader/HeaderContent.tsx
Labels: structure

#4404 CL-3197: Show confirmation screen in modal after buying seat
  front/app/components/admin/AddCollaboratorsModal/index.tsx
  front/app/components/admin/AddCollaboratorsModal/messages.ts
  front/app/components/admin/InviteUsersWithSeatsModal/InviteUsersWithSeatsModal.test.tsx
  front/app/components/admin/InviteUsersWithSeatsModal/index.tsx
  front/app/components/admin/SeatSetSuccess/index.tsx
  front/app/components/admin/SeatSetSuccess/messages.ts
  front/app/containers/Admin/users/ChangeSeatModal.tsx
  front/app/translations/admin/en.json
Labels: structure

#4440 CL-3169 Idea images and files
  front/app/api/idea_files/__mocks__/useIdeaFiles.ts
  front/app/api/idea_files/keys.ts
  front/app/api/idea_files/types.ts
  front/app/api/idea_files/useAddIdeaFile.test.ts
  front/app/api/idea_files/useAddIdeaFile.ts
  front/app/api/idea_files/useDeleteIdeaFile.test.ts
  front/app/api/idea_files/useDeleteIdeaFile.ts
  front/app/api/idea_files/useIdeaFiles.test.ts
  front/app/api/idea_files/useIdeaFiles.ts
  front/app/api/idea_images/__mocks__/ideaImages.ts
  front/app/api/idea_images/keys.ts
  front/app/api/idea_images/types.ts
  front/app/api/idea_images/useDeleteIdeaImage.test.ts
  front/app/api/idea_images/useDeleteIdeaImage.ts
  front/app/api/idea_images/useIdeaImage.test.ts
  front/app/api/idea_images/useIdeaImage.ts
  front/app/api/idea_images/useIdeaImages.test.ts
  front/app/api/idea_images/useIdeaImages.ts
  front/app/api/ideas/useAddIdea.ts
  front/app/api/ideas/useDeleteIdea.ts
  front/app/api/ideas/useUpdateIdea.ts
  front/app/api/initiative_files/keys.ts
  front/app/components/Form/Components/Controls/AttachmentsControl.tsx
  front/app/components/IdeaCard/index.tsx
  front/app/components/UI/FileAttachments/FileDisplay/index.tsx
  front/app/components/UI/FileAttachments/index.tsx
  front/app/components/admin/PostManager/components/LazyPostPreview/Idea/AdminIdeaEdit.tsx
  front/app/components/admin/PostManager/components/LazyPostPreview/Idea/IdeaContent.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/MostVotedIdeasWidget/Ideas/IdeaCard.tsx
  front/app/containers/IdeasEditPage/IdeasEditForm.tsx
  front/app/containers/IdeasShow/IdeaMeta.tsx
  front/app/containers/IdeasShow/MetaInformation/Attachment.tsx
  front/app/containers/IdeasShow/MetaInformation/Attachments.tsx
  front/app/containers/IdeasShow/index.tsx
  front/app/hooks/useIdeaImage.ts
  front/app/hooks/useIdeaImages.ts
  front/app/hooks/useRemoteFiles.ts
  front/app/hooks/useResourceFiles.ts
  front/app/modules/commercial/bulk_idea_import/admin/containers/Import.tsx
  front/app/modules/commercial/bulk_idea_import/api/import_ideas/useImportIdeas.tsx
  front/app/resources/GetResourceFiles.tsx
  front/app/services/ideaFiles.ts
  front/app/services/ideaImages.ts
Labels: platform

#4491 Only show billing success when feature flag is enabled
  front/app/components/SeatInfo/index.tsx
  front/app/components/admin/SeatSetSuccess/index.tsx
  front/app/containers/Admin/users/ChangeSeatModal.tsx
  front/app/services/projectFolderModerators.ts
  front/app/services/projectModerators.ts
Labels: structure

#4487 Disable seat based billing by deafult
  back/config/schemas/settings.schema.json.erb
  back/engines/commercial/multi_tenancy/lib/tasks/core/create_tenant.rake
Labels: structure

#4468 [CL-2735] Remove stats dead code 💀
  back/app/controllers/web_api/v1/stats_comments_controller.rb
  back/app/controllers/web_api/v1/stats_ideas_controller.rb
  back/app/controllers/web_api/v1/stats_initiatives_controller.rb
  back/app/controllers/web_api/v1/stats_users_controller.rb
  back/app/controllers/web_api/v1/stats_votes_controller.rb
  back/app/policies/stat_comment_policy.rb
  back/app/policies/stat_idea_policy.rb
  back/app/policies/stat_initiative_policy.rb
  back/app/policies/stat_user_policy.rb
  back/app/policies/stat_vote_policy.rb
  back/app/services/xlsx_service.rb
  back/config/routes.rb
  back/spec/acceptance/stats_comments_spec.rb
  back/spec/acceptance/stats_ideas_spec.rb
  back/spec/acceptance/stats_initiatives_spec.rb
  back/spec/acceptance/stats_users_spec.rb
  back/spec/acceptance/stats_votes_spec.rb
Labels: structure

#4490 CL-3222 Remove hardcoded fallback title custom page
  front/app/containers/CustomPageShow/CustomPageHeader/HeaderContent.tsx
Labels: structure

#4488 CL-3149 Error corrections
  front/app/containers/IdeasNewPage/messages.ts
  front/app/translations/ar-MA.json
  front/app/translations/ar-SA.json
  front/app/translations/ca-ES.json
  front/app/translations/da-DK.json
  front/app/translations/de-DE.json
  front/app/translations/el-GR.json
  front/app/translations/en-CA.json
  front/app/translations/en-GB.json
  front/app/translations/en.json
  front/app/translations/es-CL.json
  front/app/translations/es-ES.json
  front/app/translations/fr-BE.json
  front/app/translations/fr-FR.json
  front/app/translations/hr-HR.json
  front/app/translations/hu-HU.json
  front/app/translations/it-IT.json
  front/app/translations/kl-GL.json
  front/app/translations/lb-LU.json
  front/app/translations/lv-LV.json
  front/app/translations/mi.json
  front/app/translations/nb-NO.json
  front/app/translations/nl-BE.json
  front/app/translations/nl-NL.json
  front/app/translations/pl-PL.json
  front/app/translations/pt-BR.json
  front/app/translations/ro-RO.json
  front/app/translations/sr-Latn.json
  front/app/translations/sr-SP.json
  front/app/translations/sv-SE.json
  front/app/translations/tr-TR.json
Labels: waiting for translations

#4510 [CL-3287] Show additional seats when feature flag is off
  front/app/components/SeatInfo/index.tsx
Labels: structure

#4505 Make tooltip fully visible inside modal
  front/app/components/SeatInfo/index.tsx
Labels: structure

#4513 Fix bug with not showing filter options on hitting more than 1 char
  front/app/components/UI/UserSelect/index.tsx
Labels: structure

#4498 CL-3167 Official feedback
  front/app/api/idea_official_feedback/keys.ts
  front/app/api/idea_official_feedback/types.ts
  front/app/api/idea_official_feedback/useAddIdeaOfficialFeedback.test.ts
  front/app/api/idea_official_feedback/useAddIdeaOfficialFeedback.ts
  front/app/api/idea_official_feedback/useDeleteIdeaOfficialFeedback.test.ts
  front/app/api/idea_official_feedback/useDeleteIdeaOfficialFeedback.ts
  front/app/api/idea_official_feedback/useIdeaOfficialFeedback.test.ts
  front/app/api/idea_official_feedback/useIdeaOfficialFeedback.ts
  front/app/api/idea_official_feedback/useUpdateIdeaOfficialFeedback.test.ts
  front/app/api/idea_official_feedback/useUpdateIdeaOfficialFeedback.ts
  front/app/api/initiative_action_descriptors/useInitiativeActionDescriptors.ts
  front/app/api/initiative_allowed_transitions/useInitiativeAllowedTransitions.ts
  front/app/api/initiative_markers/useInitiativeMarkers.ts
  front/app/api/initiative_official_feedback/keys.ts
  front/app/api/initiative_official_feedback/types.ts
  front/app/api/initiative_official_feedback/useAddInitiativeOfficialFeedback.test.ts
  front/app/api/initiative_official_feedback/useAddInitiativeOfficialFeedback.ts
  front/app/api/initiative_official_feedback/useDeleteInitiativeOfficialFeedback.test.ts
  front/app/api/initiative_official_feedback/useDeleteInitiativeOfficialFeedback.ts
  front/app/api/initiative_official_feedback/useInitiativeOfficialFeedback.test.ts
  front/app/api/initiative_official_feedback/useInitiativeOfficialFeedback.ts
  front/app/api/initiative_official_feedback/useUpdateInitiativeOfficialFeedback.test.ts
  front/app/api/initiative_official_feedback/useUpdateInitiativeOfficialFeedback.ts
  front/app/components/PostShowComponents/OfficialFeedback/OfficialFeedbackFeed.tsx
  front/app/components/PostShowComponents/OfficialFeedback/OfficialFeedbackForm.tsx
  front/app/components/PostShowComponents/OfficialFeedback/OfficialFeedbackPost.test.tsx
  front/app/components/PostShowComponents/OfficialFeedback/OfficialFeedbackPost.tsx
  front/app/components/PostShowComponents/OfficialFeedback/__snapshots__/OfficialFeedbackPost.test.tsx.snap
  front/app/components/admin/PostManager/PostManager.test.tsx
  front/app/components/admin/PostManager/components/StatusChangeModal/StatusChangeForm.tsx
  front/app/components/admin/PostManager/components/StatusChangeModal/StatusChangeFormWrapper.tsx
  front/app/containers/IdeasShow/index.tsx
  front/app/containers/InitiativesShow/index.tsx
  front/app/hooks/useInitiativesPermissions.ts
  front/app/resources/GetInitiativeAllowedTransitions.tsx
  front/app/resources/GetInitiativeMarkers.tsx
  front/app/resources/GetOfficialFeedbacks.tsx
  front/app/services/__mocks__/ideaStatus.ts
  front/app/services/__mocks__/ideaStatuses.ts
  front/app/services/__mocks__/officialFeedback.ts
  front/app/services/__mocks__/proposalStatuses.ts
  front/app/services/officialFeedback.ts
Labels: platform

#4514 [CL-3258] Update SeatInfo
  front/app/components/SeatInfo/BillingInfo.test.tsx
  front/app/components/SeatInfo/BillingInfo.tsx
  front/app/components/SeatInfo/SeatInfo.test.tsx
  front/app/components/SeatInfo/TrackerInfo.test.tsx
  front/app/components/SeatInfo/TrackerInfo.tsx
  front/app/components/SeatInfo/index.tsx
  front/app/components/SeatInfo/messages.ts
  front/app/translations/en.json
Labels: structure

#4555 Cl 3294 rename collaborator and manager to moderator in the fe code
  front/app/components/ConsentManager/ConsentManager.test.tsx
  front/app/components/ConsentManager/utils.test.ts
  front/app/components/SeatInfo/BillingInfo.test.tsx
  front/app/components/SeatInfo/BillingInfo.tsx
  front/app/components/SeatInfo/TrackerInfo.test.tsx
  front/app/components/SeatInfo/TrackerInfo.tsx
  front/app/components/SeatInfo/index.tsx
  front/app/components/SeatInfo/messages.ts
  front/app/components/admin/AddModeratorsModal/AddModeratorsModal.test.tsx
  front/app/components/admin/AddModeratorsModal/index.tsx
  front/app/components/admin/AddModeratorsModal/messages.ts
  front/app/components/admin/InviteUsersWithSeatsModal/InviteUsersWithSeatsModal.test.tsx
  front/app/components/admin/InviteUsersWithSeatsModal/index.tsx
  front/app/components/admin/InviteUsersWithSeatsModal/messages.ts
  front/app/components/admin/SeatSetSuccess/index.tsx
  front/app/components/admin/SeatSetSuccess/messages.ts
  front/app/containers/Admin/invitations/invite/index.tsx
  front/app/containers/Admin/projectFolders/containers/permissions/index.tsx
  front/app/containers/Admin/projects/project/permissions/components/UserSearch.tsx
  front/app/containers/Admin/projects/project/permissions/containers/ProjectManagement/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/AboutReportWidget/index.tsx
  front/app/containers/Admin/routes.tsx
  front/app/containers/Admin/users/AdminsAndModerators.tsx
  front/app/containers/Admin/users/ChangeSeatModal.tsx
  front/app/containers/Admin/users/UserTableRow.tsx
  front/app/containers/Admin/users/routes.tsx
  front/app/containers/IdeasNewPage/IdeasNewForm/index.tsx
  front/app/containers/InitiativesEditPage/index.tsx
  front/app/modules/commercial/intercom/index.ts
  front/app/modules/commercial/posthog_integration/index.ts
  front/app/modules/commercial/satismeter/index.ts
  front/app/modules/commercial/segment/index.tsx
  front/app/services/permissions/roles.test.ts
  front/app/services/permissions/roles.ts
  front/app/services/permissions/rules/routePermissions.ts
Labels: structure

#4436 CL-3034 - Delete unconfirmed users without passwords
  back/app/interactors/schedule_code_expiration.rb
  back/app/jobs/expire_confirmation_code_or_delete_job.rb
  back/spec/factories/users.rb
  back/spec/interactors/schedule_code_expiration_spec.rb
  back/spec/jobs/expire_confirmation_code_job_spec.rb
  back/spec/jobs/expire_confirmation_code_or_delete_job_spec.rb
Labels: methods

#4457 Fix and re-enable skipped test
  front/app/components/IdeaButton/index.tsx
  front/app/containers/Admin/messaging/CustomEmails/CampaignForm/index.tsx
  front/cypress/e2e/email_consent.cy.ts
  front/cypress/e2e/idea_posting_permissions.cy.ts
  front/cypress/e2e/sign_up_email_password.cy.ts
Labels: methods

#4531 CL-3292 - Ensure correct sso_flow param returned from SSO
  back/app/controllers/omniauth_callback_controller.rb
  back/db/schema.rb
Labels: methods

#4563 [CL-3315] Fixed invited users not setting registration_completed_at
  back/app/models/user.rb
  back/spec/acceptance/invites_spec.rb
  back/spec/models/user_spec.rb
Labels: methods

#4460 CL-3229 Permissions schemas
  back/.rubocop_todo.yml
  back/app/controllers/web_api/v1/permissions_controller.rb
  back/app/controllers/web_api/v1/users_controller.rb
  back/app/models/permission.rb
  back/app/policies/permission_policy.rb
  back/app/serializers/web_api/v1/permission_serializer.rb
  back/app/serializers/web_api/v1/user_serializer.rb
  back/app/services/permissions_service.rb
  back/app/services/project_copy_service.rb
  back/db/migrate/20230403145652_add_global_custom_fields_to_permissions.rb
  back/db/schema.rb
  back/engines/commercial/granular_permissions/config/routes.rb
  back/engines/commercial/granular_permissions/spec/acceptance/permissions_spec.rb
  back/engines/commercial/multi_tenancy/app/services/multi_tenancy/templates/serializer.rb
  back/engines/commercial/smart_groups/spec/models/permission_spec.rb
  back/spec/acceptance/users_spec.rb
  back/spec/factories/permissions.rb
  back/spec/models/permission_spec.rb
  back/spec/policies/permission_policy_spec.rb
  back/spec/services/permissions_service_spec.rb
Labels: methods

#4589 [CL-3293] Rake task to insert key-values into User custom_field_values
  back/engines/commercial/multi_tenancy/lib/tasks/core/insert_user_custom_field_key_values.rake
Labels: structure

#4577 Cl 3286 fe info box at bottom of modal
  front/app/components/SeatInfo/BillingWarning.tsx
  front/app/components/SeatInfo/messages.ts
  front/app/components/admin/AddModeratorsModal/index.tsx
  front/app/components/admin/InviteUsersWithSeatsModal/index.tsx
  front/app/containers/Admin/users/ChangeSeatModal.tsx
  front/app/translations/en.json
Labels: waiting for translations, structure

#4315 [CL-3145] Calculate extra invitation seats
  back/app/controllers/web_api/v1/invites_controller.rb
  back/app/controllers/web_api/v1/users_controller.rb
  back/app/policies/invite_policy.rb
  back/app/services/invites/seats_counter.rb
  back/app/services/invites/service.rb
  back/app/services/invites/xlsx_processor.rb
  back/config/routes.rb
  back/spec/acceptance/invites_spec.rb
  back/spec/services/invites/service_spec.rb
  back/spec/spec_helper.rb
Labels: structure

#4585 [CL-3335] Don't delete User.custom_field_values data when non-user-related custom fields or options deleted
  back/app/services/user_custom_field_service.rb
  back/engines/commercial/idea_custom_fields/spec/acceptance/idea_custom_fields/project_context/update_all_native_survey_spec.rb
  back/spec/services/side_fx_custom_field_option_service_spec.rb
  back/spec/services/side_fx_custom_field_service_spec.rb
Labels: bug, structure

#4558 CL-3288 - Verification attribute on requirements
  back/app/services/permissions_service.rb
  back/engines/commercial/granular_permissions/spec/acceptance/permissions_spec.rb
  back/engines/commercial/verification/app/services/verification/patches/permissions_service.rb
  back/engines/commercial/verification/spec/services/permissions_service_spec.rb
  back/spec/services/permissions_service_spec.rb
Labels: methods

#4381 CL-3072 Avoid mailing no info/content in user digest
  back/engines/free/email_campaigns/app/models/email_campaigns/campaigns/user_digest.rb
  back/engines/free/email_campaigns/app/views/email_campaigns/user_digest_mailer/campaign_mail.mjml
  back/engines/free/email_campaigns/spec/models/email_campaigns/campaigns/user_digest_spec.rb
  back/spec/services/trending_idea_service_spec.rb
Labels: structure

#4575 CL-3181 - Project relationship in custom fields
  back/app/services/permissions_service.rb
  back/engines/commercial/granular_permissions/spec/acceptance/permissions_spec.rb
  back/engines/commercial/user_custom_fields/app/controllers/user_custom_fields/web_api/v1/user_custom_fields_controller.rb
  back/engines/commercial/user_custom_fields/app/serializers/user_custom_fields/web_api/v1/user_custom_field_serializer.rb
  back/engines/commercial/user_custom_fields/spec/acceptance/user_custom_fields_spec.rb
  back/spec/jobs/expire_confirmation_code_or_delete_job_spec.rb
Labels: methods

#4581 Fix validation issue when adding user field
  front/app/components/HookForm/OptionList/index.tsx
  front/app/modules/commercial/granular_permissions/admin/components/UserFieldSelection/FieldSelectionModal.tsx
  front/app/modules/commercial/granular_permissions/admin/components/UserFieldSelection/screens/AddFieldScreen.tsx
  front/app/modules/commercial/granular_permissions/admin/containers/Granular/messages.ts
  front/app/translations/admin/en.json
Labels: methods

#4608 Task/fix condition to show billing warning
  front/app/components/SeatInfo/BillingWarning.tsx
  front/app/components/admin/AddModeratorsModal/index.tsx
  front/app/components/admin/InviteUsersWithSeatsModal/index.tsx
  front/app/containers/Admin/users/ChangeSeatModal.tsx
Labels: structure

#4583 [CL-3218] Sort by new admin before calculating additional seats
  back/app/services/invites/service.rb
  back/app/services/invites/xlsx_processor.rb
Labels: structure

#4516 CL-3261 - Change email in temporary column until confirmed
  back/app/controllers/omniauth_callback_controller.rb
  back/app/controllers/web_api/v1/users_controller.rb
  back/app/interactors/reset_user_email.rb
  back/app/mailers/confirmations_mailer.rb
  back/app/models/user.rb
  back/db/migrate/20230405162820_add_new_email_to_users.rb
  back/engines/commercial/granular_permissions/spec/acceptance/permissions_spec.rb
  back/spec/acceptance/users_spec.rb
  back/spec/interactors/deliver_confirmation_code_spec.rb
  back/spec/interactors/reset_user_email_spec.rb
  back/spec/models/user_spec.rb
Labels: methods

#4556 [CL-3029] Show email confirmation modal if email updated
  front/app/containers/Authentication/SignUpIn/SignUpInModal/SignUp/ConfirmationSignupStep/FooterNotes.tsx
  front/app/containers/EmailChange/CancelUpdate.tsx
  front/app/containers/EmailChange/UpdateEmailForm.tsx
  front/app/containers/EmailChange/index.tsx
  front/app/containers/EmailChange/messages.ts
  front/app/containers/NewAuthModal/Modal.tsx
  front/app/containers/NewAuthModal/steps/EmailConfirmation/index.tsx
  front/app/containers/PasswordChange/index.tsx
  front/app/containers/UsersEditPage/LoginCredentials.tsx
  front/app/containers/UsersEditPage/ProfileForm.tsx
  front/app/containers/UsersEditPage/index.tsx
  front/app/containers/UsersEditPage/messages.ts
  front/app/routes.tsx
  front/app/services/users.ts
  front/app/translations/ar-MA.json
  front/app/translations/ar-SA.json
  front/app/translations/ca-ES.json
  front/app/translations/da-DK.json
  front/app/translations/de-DE.json
  front/app/translations/el-GR.json
  front/app/translations/en-CA.json
  front/app/translations/en-GB.json
  front/app/translations/en.json
  front/app/translations/es-CL.json
  front/app/translations/es-ES.json
  front/app/translations/fr-BE.json
  front/app/translations/fr-FR.json
  front/app/translations/hr-HR.json
  front/app/translations/it-IT.json
  front/app/translations/lb-LU.json
  front/app/translations/lv-LV.json
  front/app/translations/nb-NO.json
  front/app/translations/nl-BE.json
  front/app/translations/nl-NL.json
  front/app/translations/pl-PL.json
  front/app/translations/pt-BR.json
  front/app/translations/ro-RO.json
  front/app/translations/sr-Latn.json
  front/app/translations/sr-SP.json
  front/app/translations/sv-SE.json
  front/app/translations/tr-TR.json
Labels: methods

#4611 [No ticket] Bump comp lib to 0.10.33
  front/package-lock.json
  front/package.json
Labels: structure

#4617 CL-3339 Multiple fixes to moderator digest
  back/engines/free/email_campaigns/app/models/email_campaigns/campaigns/moderator_digest.rb
  back/engines/free/email_campaigns/app/views/email_campaigns/moderator_digest_mailer/campaign_mail.mjml
  back/engines/free/email_campaigns/config/locales/en.yml
  back/engines/free/email_campaigns/spec/mailers/previews/email_campaigns/moderator_digest_mailer_preview.rb
Labels: structure

#4622 CL-3354: Add link to front office in top left corner
  front/app/components/admin/NavigationTabs/Tab.tsx
  front/app/containers/Admin/sideBar/index.tsx
  front/app/containers/Admin/sideBar/messages.ts
  front/app/translations/admin/en.json
Labels: structure

#4572 Fix failing idea creation E2E test
  front/cypress/e2e/create_idea_in_any_phase.cy.ts
Labels: methods

#4656 CL-3395 - Issue with confirmation code reset
  back/app/models/user.rb
  back/app/services/side_fx_user_service.rb
  back/spec/acceptance/users_spec.rb
  back/spec/models/user_spec.rb
Labels: methods

#4582 [CL-3218] Add logic to set and increment additional seats
  back/app/services/additional_seats_incrementer.rb
  back/app/services/invites/service.rb
  back/app/services/invites/xlsx_processor.rb
  back/app/services/side_fx_user_service.rb
  back/spec/acceptance/project_moderators_spec.rb
  back/spec/acceptance/users_spec.rb
  back/spec/services/additional_seats_incrementer_spec.rb
  back/spec/services/invites/service_spec.rb
Labels: structure

#4634 [CL-3358] Do not assign survey responses (Ideas) to admins (Idea.assignee.id)
  back/engines/commercial/idea_assignment/app/services/idea_assignment/idea_assignment_service.rb
  back/engines/commercial/idea_assignment/spec/services/idea_assignment/idea_assignment_service_spec.rb
  back/engines/commercial/multi_tenancy/lib/tasks/idea_assignment/fix_assignees.rake
  back/engines/commercial/multi_tenancy/spec/tasks/fix_assignees_task_spec.rb
  back/spec/acceptance/ideas_spec.rb
Labels: structure

#4650 recommended-requiring-type-checking automatic corrections
  front/app/components/Form/Components/Controls/AttachmentsControl.tsx
  front/app/components/Form/Components/Controls/visibilityUtils.ts
  front/app/components/FormBuilder/components/FormFields/utils.ts
  front/app/components/IdeaCards/shared/Filters/TopicFilterBox.tsx
  front/app/components/InitiativeCards/TopicFilterBox.tsx
  front/app/components/InitiativeForm/index.tsx
  front/app/components/SeatInfo/BillingInfo.test.tsx
  front/app/components/SeatInfo/TrackerInfo.test.tsx
  front/app/components/T/index.tsx
  front/app/components/admin/ContentBuilder/Editor/RenderNode/index.tsx
  front/app/components/admin/PostManager/components/LazyPostPreview/Initiative/InitiativeEdit.tsx
  front/app/containers/Admin/projectFolders/containers/settings/ProjectFolderForm/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Editor/RenderNode/index.tsx
  front/app/containers/Authentication/SignUpIn/SignUpInModal/SignUp/ConfirmationSignupStep/index.tsx
  front/app/containers/InitiativesEditPage/index.tsx
  front/app/containers/InitiativesNewPage/index.tsx
  front/app/containers/MainHeader/NotificationMenu/components/Notification/index.tsx
  front/app/containers/ProjectsShowPage/shared/survey/SmartSurvey.test.tsx
  front/app/hooks/useExceedsSeats.ts
  front/app/modules/commercial/insights/admin/containers/Reports/ProjectReport.tsx
  front/app/modules/commercial/insights/api/category_suggestions/useScanForCategorySuggestions.ts
  front/app/resources/GetInitiatives.tsx
  front/app/utils/map.ts
  front/app/utils/testUtils/withIntl.ts
Labels: ts-config

#4660 CL-3357: Move invitations link to the users page
  front/app/containers/Admin/invitations/index.tsx
  front/app/containers/Admin/invitations/routes.tsx
  front/app/containers/Admin/sideBar/index.tsx
  front/app/containers/Admin/sideBar/messages.ts
  front/app/containers/Admin/users/GroupsListPanel.tsx
  front/app/containers/Admin/users/index.tsx
  front/app/containers/Admin/users/messages.ts
  front/app/translations/admin/ar-MA.json
  front/app/translations/admin/ar-SA.json
  front/app/translations/admin/ca-ES.json
  front/app/translations/admin/da-DK.json
  front/app/translations/admin/de-DE.json
  front/app/translations/admin/el-GR.json
  front/app/translations/admin/en-CA.json
  front/app/translations/admin/en-GB.json
  front/app/translations/admin/en.json
  front/app/translations/admin/es-CL.json
  front/app/translations/admin/es-ES.json
  front/app/translations/admin/fr-BE.json
  front/app/translations/admin/fr-FR.json
  front/app/translations/admin/hr-HR.json
  front/app/translations/admin/hu-HU.json
  front/app/translations/admin/it-IT.json
  front/app/translations/admin/kl-GL.json
  front/app/translations/admin/lb-LU.json
  front/app/translations/admin/lv-LV.json
  front/app/translations/admin/mi.json
  front/app/translations/admin/nb-NO.json
  front/app/translations/admin/nl-BE.json
  front/app/translations/admin/nl-NL.json
  front/app/translations/admin/pl-PL.json
  front/app/translations/admin/pt-BR.json
  front/app/translations/admin/ro-RO.json
  front/app/translations/admin/sr-Latn.json
  front/app/translations/admin/sr-SP.json
  front/app/translations/admin/sv-SE.json
  front/app/translations/admin/tr-TR.json
Labels: structure

#4653 canAdmin can only be true
  front/app/containers/Admin/users/UserManager.tsx
  front/app/resources/GetUsers.tsx
Labels: structure

#4674 CL-3361: Move links in the proposal page to the top bar
  front/app/containers/Admin/index.tsx
  front/app/containers/Admin/initiatives/index.tsx
  front/app/containers/Admin/initiatives/manage/index.tsx
  front/app/containers/Admin/initiatives/manage/tracks.ts
  front/app/containers/Admin/initiatives/messages.ts
  front/app/containers/Admin/initiatives/routes.tsx
  front/app/containers/Admin/initiatives/settings/index.tsx
  front/app/containers/MainHeader/NotificationMenu/components/InitiativeAssignedToYouNotification/index.tsx
  front/app/modules/commercial/granular_permissions/admin/components/InitiativeSettingsTab.tsx
  front/app/modules/commercial/granular_permissions/admin/components/messages.ts
  front/app/modules/commercial/granular_permissions/admin/containers/permissions/index.tsx
  front/app/modules/commercial/granular_permissions/admin/containers/permissions/messages.ts
  front/app/translations/admin/ar-MA.json
  front/app/translations/admin/ar-SA.json
  front/app/translations/admin/ca-ES.json
  front/app/translations/admin/da-DK.json
  front/app/translations/admin/de-DE.json
  front/app/translations/admin/el-GR.json
  front/app/translations/admin/en-CA.json
  front/app/translations/admin/en-GB.json
  front/app/translations/admin/en.json
  front/app/translations/admin/es-CL.json
  front/app/translations/admin/es-ES.json
  front/app/translations/admin/fr-BE.json
  front/app/translations/admin/fr-FR.json
  front/app/translations/admin/hr-HR.json
  front/app/translations/admin/hu-HU.json
  front/app/translations/admin/it-IT.json
  front/app/translations/admin/kl-GL.json
  front/app/translations/admin/lb-LU.json
  front/app/translations/admin/lv-LV.json
  front/app/translations/admin/mi.json
  front/app/translations/admin/nb-NO.json
  front/app/translations/admin/nl-BE.json
  front/app/translations/admin/nl-NL.json
  front/app/translations/admin/pl-PL.json
  front/app/translations/admin/pt-BR.json
  front/app/translations/admin/ro-RO.json
  front/app/translations/admin/sr-Latn.json
  front/app/translations/admin/sr-SP.json
  front/app/translations/admin/sv-SE.json
  front/app/translations/admin/tr-TR.json
  front/cypress/e2e/admin/initiative_manager.cy.ts
Labels: structure

#4628 CL-3382 Mentions
  front/app/api/blocked_users/keys.ts
  front/app/api/mentions/getMentions.test.ts
  front/app/api/mentions/getMentions.ts
  front/app/api/mentions/keys.ts
  front/app/api/mentions/types.ts
  front/app/components/UI/MentionsTextArea/index.tsx
  front/app/services/mentions.ts
Labels: platform

#4681 CL-3429 - Allow fields not enabled at global level to be persisted and returned
  back/app/policies/user_policy.rb
  back/app/serializers/web_api/v1/user_serializer.rb
  back/engines/commercial/verification/app/policies/verification/patches/user_policy.rb
  back/spec/acceptance/users_spec.rb
Labels: methods

#4679 Codeless confirmation mails
  back/app/interactors/deliver_confirmation_code.rb
  back/app/interactors/reset_user_confirmation_code.rb
  back/spec/acceptance/resend_codes_spec.rb
  back/spec/acceptance/users_spec.rb
  back/spec/interactors/deliver_confirmation_code_spec.rb
  back/spec/interactors/send_confirmation_code_spec.rb
  back/spec/mailers/confirmations_mailer_spec.rb
Labels: methods

#4687 Don't set additional seats value in front-end
  front/app/components/admin/SeatBasedBilling/SeatInfo/BillingInfo.tsx
Labels: structure

#4499 Remove broken timezone task
  back/engines/commercial/multi_tenancy/lib/tasks/core/fix_timezones.rake
Labels: methods

#4685 [CL-3402] Add password page not updating to "change password" until refresh
  front/app/containers/PasswordChange/ChangePassword.test.tsx
  front/app/containers/PasswordChange/index.tsx
  front/app/services/users.ts
Labels: methods

#4688 CL-3433 native survey e2e
  back/app/interactors/confirm_user.rb
  back/config/tenant_templates/e2etests_template.yml
  back/spec/interactors/confirm_user_spec.rb
Labels: methods

#4654 [CL-3328] invalidate cache on delete user field
  front/app/containers/Admin/settings/registration/CustomFieldSettings/index.tsx
Labels: methods

#4692 [CL-3445] Remove required badge from user field selection modal in access rights
  front/app/modules/commercial/granular_permissions/admin/components/UserFieldSelection/screens/SelectionScreen.tsx
Labels: methods

#4690 CL-3362: Move links in the messaging page to the top bar
  front/app/containers/Admin/index.tsx
  front/app/containers/Admin/messaging/AutomatedEmails/index.tsx
  front/app/containers/Admin/messaging/CustomEmails/All/index.tsx
  front/app/containers/Admin/messaging/CustomEmails/Edit/index.tsx
  front/app/containers/Admin/messaging/CustomEmails/New/index.tsx
  front/app/containers/Admin/messaging/CustomEmails/Show/index.tsx
  front/app/containers/Admin/messaging/index.tsx
  front/app/containers/Admin/messaging/messages.ts
  front/app/containers/Admin/messaging/texting/CampaignList/index.tsx
  front/app/containers/Admin/messaging/texting/ExistingSMSCampaign/index.tsx
  front/app/containers/Admin/messaging/texting/NewSMSCampaign/index.tsx
  front/app/containers/Admin/messaging/texting/SMSCampaignPreview/index.tsx
  front/app/translations/admin/ar-MA.json
  front/app/translations/admin/ar-SA.json
  front/app/translations/admin/ca-ES.json
  front/app/translations/admin/da-DK.json
  front/app/translations/admin/de-DE.json
  front/app/translations/admin/el-GR.json
  front/app/translations/admin/en-CA.json
  front/app/translations/admin/en-GB.json
  front/app/translations/admin/en.json
  front/app/translations/admin/es-CL.json
  front/app/translations/admin/es-ES.json
  front/app/translations/admin/fr-BE.json
  front/app/translations/admin/fr-FR.json
  front/app/translations/admin/hr-HR.json
  front/app/translations/admin/hu-HU.json
  front/app/translations/admin/it-IT.json
  front/app/translations/admin/kl-GL.json
  front/app/translations/admin/lb-LU.json
  front/app/translations/admin/lv-LV.json
  front/app/translations/admin/mi.json
  front/app/translations/admin/nb-NO.json
  front/app/translations/admin/nl-BE.json
  front/app/translations/admin/nl-NL.json
  front/app/translations/admin/pl-PL.json
  front/app/translations/admin/pt-BR.json
  front/app/translations/admin/ro-RO.json
  front/app/translations/admin/sr-Latn.json
  front/app/translations/admin/sr-SP.json
  front/app/translations/admin/sv-SE.json
  front/app/translations/admin/tr-TR.json
Labels: structure

#4659 CL-3387 - Only return enabled actions
  back/app/controllers/web_api/v1/permissions_controller.rb
  back/app/models/permission.rb
  back/engines/commercial/granular_permissions/spec/acceptance/permissions_spec.rb
  back/spec/models/permission_spec.rb
  front/app/containers/Admin/projects/project/general/index.tsx
Labels: methods

#4689 CL-3400 - Disable global registration fields toggle for moderators
  front/app/modules/commercial/granular_permissions/admin/components/UserFieldSelection/UserFieldSelection.tsx
  front/app/modules/commercial/granular_permissions/admin/containers/Granular/ActionsForm.tsx
  front/app/modules/commercial/granular_permissions/admin/containers/Granular/messages.ts
  front/app/translations/admin/en.json
Labels: methods

#4693 CL-3418 Remove FirstIdeaPublished mail
  back/app/services/side_fx_idea_service.rb
  back/app/services/side_fx_initiative_service.rb
  back/engines/commercial/multi_tenancy/config/intercom-event-whitelist.txt
  back/engines/free/email_campaigns/app/mailers/email_campaigns/first_idea_published_mailer.rb
  back/engines/free/email_campaigns/app/models/email_campaigns/campaigns/first_idea_published.rb
  back/engines/free/email_campaigns/app/services/email_campaigns/delivery_service.rb
  back/engines/free/email_campaigns/spec/factories/campaigns.rb
  back/engines/free/email_campaigns/spec/mailers/first_idea_published_mailer_spec.rb
  back/engines/free/email_campaigns/spec/mailers/previews/email_campaigns/first_idea_published_mailer_preview.rb
  back/engines/free/email_campaigns/spec/models/email_campaigns/campaigns/first_idea_published_spec.rb
  back/spec/services/side_fx_idea_spec.rb
Labels: structure

#4698 CL-3444 Ideas by basket bug
  back/.rubocop_todo.yml
  back/app/finders/ideas_finder.rb
  back/engines/commercial/multi_tenancy/lib/tasks/core/create_tenant.rake
  back/spec/acceptance/ideas_spec.rb
  back/spec/finders/ideas_finder_spec.rb
Labels: methods

#4706 Some minor UI changes
  front/app/containers/Admin/users/NoUsers.tsx
  front/app/containers/Admin/users/UserManager.tsx
Labels: structure

#4676 Delete global state service
  front/app/components/admin/PostManager/PostManager.test.tsx
  front/app/components/admin/PostManager/components/PostTable/PostTable.test.tsx
  front/app/components/admin/PostManager/index.tsx
  front/app/containers/Admin/index.tsx
  front/app/containers/Admin/users/index.tsx
  front/app/services/__mocks__/globalState.ts
  front/app/services/globalState.ts
Labels: platform

#4700 [CL-849] Small improvement to test description
  back/engines/free/email_campaigns/spec/models/email_campaigns/campaigns/moderator_digest_spec.rb
Labels: structure

#4662 CL-3409 Areas
  front/app/api/areas/__mocks__/useAreas.ts
  front/app/api/areas/keys.ts
  front/app/api/areas/types.ts
  front/app/api/areas/useAddArea.test.ts
  front/app/api/areas/useAddArea.ts
  front/app/api/areas/useArea.test.ts
  front/app/api/areas/useArea.ts
  front/app/api/areas/useAreas.test.ts
  front/app/api/areas/useAreas.ts
  front/app/api/areas/useDeleteArea.test.ts
  front/app/api/areas/useDeleteArea.ts
  front/app/api/areas/useUpdateArea.test.ts
  front/app/api/areas/useUpdateArea.ts
  front/app/components/ProjectAndFolderCards/ProjectAndFolderCards.test.tsx
  front/app/components/ProjectAndFolderCards/components/Topbar/SelectAreas.tsx
  front/app/components/ProjectAndFolderCards/components/Topbar/index.tsx
  front/app/components/ProjectAndFolderCards/components/Topbar/show.ts
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/CustomPageSettingsForm/CustomPageSettingsForm.test.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/CustomPageSettingsForm/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/Edit/Settings/Settings.test.tsx
  front/app/containers/Admin/projects/project/general/components/GeographicAreaInputs.tsx
  front/app/containers/Admin/settings/areas/Edit/index.tsx
  front/app/containers/Admin/settings/areas/New/index.tsx
  front/app/containers/Admin/settings/areas/all/index.tsx
  front/app/hooks/useAreas.ts
  front/app/modules/commercial/smart_groups/components/UserFilterConditions/ValueSelector/AreaValueSelector.tsx
  front/app/modules/commercial/smart_groups/components/UserFilterConditions/ValueSelector/AreaValuesSelector.tsx
  front/app/resources/GetArea.integration.test.tsx
  front/app/resources/GetArea.test.tsx
  front/app/resources/GetArea.tsx
  front/app/resources/GetAreas.tsx
  front/app/resources/GetSerieFromStream.test.tsx
  front/app/services/__mocks__/areas.ts
  front/app/services/areas.ts
  front/app/services/projects.ts
  front/tmp/churn/6a48a280de62c41b8133fd2b969ad243982090ec.json
Labels: platform

#4641 CL-3392 Skip checkbox step based on check endpoint
  back/app/controllers/web_api/v1/users_controller.rb
  back/spec/acceptance/users_spec.rb
  front/app/api/users/checkUser.ts
  front/app/api/users/types.ts
  front/app/containers/Authentication/steps/LightFlowStart/index.tsx
  front/app/containers/Authentication/useSteps/stepConfig/newLightFlow.ts
Labels: methods

#4686 [CL-3432] Show billing info component if additional seats field is empty
  back/config/schemas/settings.schema.json.erb
  front/app/components/admin/SeatBasedBilling/SeatInfo/BillingInfo.test.tsx
  front/app/components/admin/SeatBasedBilling/SeatInfo/BillingInfo.tsx
  front/app/containers/Admin/users/NoUsers.tsx
  front/app/containers/Admin/users/UserManager.tsx
Labels: structure

#4699 User refactor
  back/app/models/user.rb
Labels: methods

#4715 CL-3458 Include disabled fields in exports
  back/app/services/xlsx_export/input_sheet_generator.rb
  back/app/services/xlsx_service.rb
  back/spec/acceptance/phases_spec.rb
  back/spec/services/xlsx_service_spec.rb
Labels: methods

#4713 [CL-3348] Remove fetching of env vars in mail campaigns
  back/engines/free/email_campaigns/app/models/email_campaigns/campaigns/admin_digest.rb
  back/engines/free/email_campaigns/app/models/email_campaigns/campaigns/assignee_digest.rb
  back/engines/free/email_campaigns/app/models/email_campaigns/campaigns/moderator_digest.rb
  back/engines/free/email_campaigns/app/models/email_campaigns/campaigns/user_digest.rb
Labels: structure

#4734 CL-3469 - Profile page bug
  front/app/components/UserCustomFieldsForm/index.tsx
Labels: methods

#4726 CL-3458 Make names private attributes
  back/app/services/xlsx_export/input_sheet_generator.rb
  back/app/services/xlsx_service.rb
  back/engines/commercial/idea_custom_fields/spec/services/xlsx_service_spec.rb
  back/spec/acceptance/phases_spec.rb
  back/spec/services/xlsx_service_spec.rb
Labels: methods

#4735 [CL-3451] Update copy when light user is missing data
  front/app/components/PostShowComponents/Comments/CommentingDisabled.tsx
  front/app/components/PostShowComponents/Comments/CommentingInitiativeDisabled.tsx
  front/app/components/PostShowComponents/Comments/messages.ts
  front/app/components/VoteControl/VoteButton.tsx
  front/app/components/VoteControl/messages.ts
  front/app/translations/en.json
Labels: methods

#4741 [CL-3468] Fix instances where /sign-in or /sign-up route is being used
  front/app/containers/PasswordReset/PasswordResetSuccess.test.tsx
  front/app/containers/PasswordReset/PasswordResetSuccess.tsx
  front/app/containers/SiteMap/index.tsx
Labels: methods

#4727 CL-3463 - Premium lock on custom fields
  front/app/containers/Admin/projects/project/permissions/index.tsx
  front/app/containers/Admin/projects/project/permissions/messages.ts
  front/app/modules/commercial/granular_permissions/admin/components/UserFieldSelection/UserFieldSelection.tsx
  front/app/modules/commercial/granular_permissions/admin/containers/Granular/ActionForm.tsx
  front/app/modules/commercial/granular_permissions/admin/containers/Granular/ActionsForm.tsx
  front/app/modules/commercial/granular_permissions/admin/containers/Granular/messages.ts
  front/app/translations/admin/en.json
Labels: methods
