Repository CitizenLabDotCo/citizenlab, pull requests merged in 2023-01, with the labels that each got.

#3464 Cl 2215 signed in banner
  front/app/components/LandingPages/citizen/FullWidthBannerLayout.ts
  front/app/containers/Admin/pagesAndMenu/EditHomepage/HeroBanner/index.tsx
  front/app/containers/Admin/pagesAndMenu/components/StickyContainer.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/Edit/HeroBanner/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/EditHomepage/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/BannerImageFields/BannerImageFields.test.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/BannerImageFields/ImageUploader.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/BannerImageFields/OverlayControls.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/BannerImageFields/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/HeaderImageDropzone.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/messages.ts
  front/app/containers/Admin/projects/project/general/components/styling.ts
  front/app/containers/CustomPageShow/CustomPageHeader/FullWidthBannerLayout.tsx
  front/app/containers/HomePage/SignedInHeader/HeaderImage.tsx
  front/app/containers/HomePage/SignedInHeader/index.tsx
  front/app/containers/HomePage/SignedOutHeader/FullWidthBannerLayout.tsx
  front/app/containers/HomePage/SignedOutHeader/TwoColumnLayout.tsx
  front/app/containers/HomePage/SignedOutHeader/TwoRowLayout.tsx
  front/app/containers/HomePage/SignedOutHeader/index.tsx
  front/app/translations/admin/en.json
Labels: structure

#3555 [CL-2328] Remove banner_signed_in_image_enabled columns & related code
  back/app/controllers/web_api/v1/home_pages_controller.rb
  back/app/models/home_page.rb
  back/app/models/static_page.rb
  back/app/policies/static_page_policy.rb
  back/app/serializers/web_api/v1/home_page_serializer.rb
  back/app/serializers/web_api/v1/static_page_serializer.rb
  back/db/migrate/20221208093437_add_banner_image_enabled_to_home_pages.rb
  back/db/migrate/20221208093814_add_banner_image_enabled_to_static_pages.rb
  back/db/schema.rb
  back/engines/commercial/multi_tenancy/app/services/multi_tenancy/templates/serializer.rb
  back/spec/acceptance/home_pages_spec.rb
  back/spec/acceptance/static_pages_spec.rb
  back/spec/models/home_page_spec.rb
  back/spec/models/static_page_spec.rb
Labels: structure

#3537 [CL-2310] Display folder/project banners as fixed-height
  front/app/containers/ProjectFolderShowPage/ProjectFolderHeader.tsx
  front/app/containers/ProjectFolderShowPage/index.tsx
  front/app/containers/ProjectsShowPage/shared/header/ProjectHeader.tsx
Labels: structure

#3570 [CL-2289] Remove confusing unused onboarding attributes
  front/app/containers/HomePage/SignedInHeader/index.tsx
  front/app/services/appConfiguration.ts
Labels: structure

#3572 React helmet types
  front/app/containers/IdeasNewPage/IdeasNewMeta.tsx
  front/package-lock.json
  front/package.json
Labels: ts-config

#3573 Enfore strict types in navbar files
  front/app/components/admin/ResourceList/SortableList.tsx
  front/app/containers/Admin/pagesAndMenu/containers/NavigationSettings/VisibleNavbarItemList/index.tsx
  front/app/services/navbar.ts
Labels: ts-config

#3575 Messages.js => ts
  front/app/components/ProjectArchivedIndicator/messages.ts
  front/app/containers/Admin/favicon/messages.ts
  front/app/containers/Admin/projects/project/events/messages.ts
Labels: ts-config

#3576 Click handlers strict types
  front/app/components/UI/FullscreenModal/index.tsx
  front/app/components/admin/PostManager/components/FilterSidebar/FilterSidebarTopics.tsx
  front/app/components/admin/PostManager/components/PostTable/Row/IdeaRow.tsx
  front/app/components/admin/PostManager/components/PostTable/Row/InitiativeRow.tsx
  front/app/components/admin/PostManager/components/PostTable/Row/index.tsx
  front/app/components/admin/PostManager/components/PostTable/Row/selectors/IdeasStatusSelector.tsx
  front/app/components/admin/PostManager/components/PostTable/Row/selectors/InitiativesStatusSelector.tsx
  front/app/components/admin/PostManager/components/PostTable/Row/selectors/PhasesSelector.tsx
  front/app/containers/Admin/projects/project/volunteering/AllCauses.tsx
  front/app/containers/Admin/settings/registration/CustomFieldSettings/index.tsx
  front/app/typings.ts
  front/app/utils/containers/clickOutside/index.tsx
Labels: ts-config

#3578 Accordion types
  front/app/components/admin/ContentBuilder/Widgets/Accordion/index.tsx
  front/app/modules/commercial/content_builder/admin/components/ContentBuilderToolbox/index.tsx
  front/app/modules/commercial/content_builder/admin/components/CraftSections/InfoWithAccordions/index.tsx
Labels: ts-config

#3579 Sortable list strict types
  front/app/components/admin/ResourceList/SortableList.test.tsx
  front/app/components/admin/ResourceList/SortableList.tsx
Labels: ts-config

#3574 Children strict types
  front/app/containers/OutletsProvider/index.tsx
  front/app/modules/commercial/analytics/admin/components/VisitorsTrafficSourcesCard/Table.tsx
  front/app/modules/commercial/flag_inappropriate_content/index.tsx
  front/app/utils/testUtils/rtl.tsx
Labels: ts-config

#3528 CL-2226 Project selection up front and template
  front/app/components/admin/ContentBuilder/Frame/index.tsx
  front/app/components/admin/ContentBuilder/Widgets/Title/index.tsx
  front/app/components/admin/ContentBuilder/Widgets/Title/messages.ts
  front/app/components/admin/ContentBuilder/Widgets/TwoColumn/index.tsx
  front/app/components/admin/ContentBuilder/typings.ts
  front/app/containers/Admin/dashboard/users/Charts/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Editor/RenderNode/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Editor/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Templates/ProjectTemplate.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Templates/messages.ts
  front/app/containers/Admin/reporting/components/ReportBuilder/Toolbox/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/TopBar/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/AboutReportWidget/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/AgeWidget/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/GenderWidget/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/VisitorsWidget/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/typings.ts
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/TwoColumn/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilderPage/CreateReportModal.tsx
  front/app/containers/Admin/reporting/components/ReportBuilderPage/messages.ts
  front/app/containers/Admin/reporting/containers/ReportBuilder/index.tsx
  front/app/containers/Admin/reporting/containers/ReportBuilderPage/ReportBuilderPage.test.tsx
  front/app/containers/Admin/reporting/utils/getProjectPeriod.ts
  front/app/services/reports.ts
  front/app/translations/admin/en.json
Labels: insights

#3589 CL-2528 Remove external tooling modules
  front/app/components/ConsentManager/ConsentManager.test.tsx
  front/app/components/ConsentManager/destinations.ts
  front/app/components/ConsentManager/index.tsx
  front/app/hooks/useAdminPublication.ts
  front/app/modules/commercial/google_analytics/index.ts
  front/app/modules/commercial/google_tag_manager/index.tsx
  front/app/modules/commercial/google_tag_manager/messages.ts
  front/app/modules/commercial/intercom/index.ts
  front/app/modules/commercial/matomo/actions.test.ts
  front/app/modules/commercial/matomo/actions.ts
  front/app/modules/commercial/matomo/getProjectId.test.ts
  front/app/modules/commercial/matomo/getProjectId.ts
  front/app/modules/commercial/matomo/index.test.ts
  front/app/modules/commercial/matomo/index.ts
  front/app/modules/commercial/matomo/matchPath.test.ts
  front/app/modules/commercial/matomo/matchPath.ts
  front/app/modules/commercial/matomo/mockRoutes.mock.ts
  front/app/modules/commercial/matomo/setup.ts
  front/app/modules/commercial/satismeter/index.ts
  front/app/modules/commercial/segment/index.tsx
  front/app/modules/index.ts
  front/app/services/__mocks__/appConfiguration.ts
  front/app/services/appConfiguration.ts
  front/app/translations/ar-MA.json
  front/app/translations/ar-SA.json
  front/app/translations/ca-ES.json
  front/app/translations/da-DK.json
  front/app/translations/de-DE.json
  front/app/translations/el-GR.json
  front/app/translations/en-CA.json
  front/app/translations/en-GB.json
  front/app/translations/en.json
  front/app/translations/es-CL.json
  front/app/translations/es-ES.json
  front/app/translations/fr-BE.json
  front/app/translations/fr-FR.json
  front/app/translations/hr-HR.json
  front/app/translations/hu-HU.json
  front/app/translations/it-IT.json
  front/app/translations/kl-GL.json
  front/app/translations/lb-LU.json
  front/app/translations/lv-LV.json
  front/app/translations/mi.json
  front/app/translations/nb-NO.json
  front/app/translations/nl-BE.json
  front/app/translations/nl-NL.json
  front/app/translations/pl-PL.json
  front/app/translations/pt-BR.json
  front/app/translations/ro-RO.json
  front/app/translations/sr-Latn.json
  front/app/translations/sr-SP.json
  front/app/translations/sv-SE.json
  front/app/translations/tr-TR.json
  front/app/utils/analytics.ts
Labels: platform

#3638 Folder UI fixes
  front/app/containers/ProjectFolderShowPage/ProjectFolderDescription.tsx
  front/app/containers/ProjectFolderShowPage/index.tsx
  front/app/routes.tsx
Labels: structure

#3595 [CL-2361] Move custom topics to the core
  back/Gemfile
  back/Gemfile.lock
  back/app/controllers/web_api/v1/topics_controller.rb
  back/app/models/topic.rb
  back/app/policies/topic_policy.rb
  back/config/routes.rb
  back/engines/commercial/custom_topics/README.md
  back/engines/commercial/custom_topics/app/controllers/custom_topics/web_api/v1/topics_controller.rb
  back/engines/commercial/custom_topics/app/models/custom_topics/patches/topic.rb
  back/engines/commercial/custom_topics/app/policies/custom_topics/extensions/topic_policy.rb
  back/engines/commercial/custom_topics/config/routes.rb
  back/engines/commercial/custom_topics/custom_topics.gemspec
  back/engines/commercial/custom_topics/lib/custom_topics.rb
  back/engines/commercial/custom_topics/lib/custom_topics/engine.rb
  back/engines/commercial/custom_topics/lib/custom_topics/feature_specification.rb
  back/engines/commercial/custom_topics/lib/custom_topics/version.rb
  back/engines/commercial/custom_topics/spec/acceptance/topics_spec.rb
  back/engines/commercial/custom_topics/spec/factories/topics.rb
  back/engines/commercial/custom_topics/spec/lib/settings_spec.rb
  back/engines/commercial/multi_tenancy/db/seeds/tenants.rb
  back/engines/commercial/multi_tenancy/lib/tasks/core/create_tenant.rake
  back/spec/acceptance/topics_spec.rb
  back/spec/factories/topics.rb
Labels: platform

#3521 [CL-2255] Display invite pending in user lists
  CHANGELOG.md
  front/app/containers/Admin/users/UserTableRow.tsx
  front/app/containers/Admin/users/messages.ts
  front/app/translations/admin/en.json
Labels: structure

#3631 React select types
  front/package-lock.json
  front/package.json
Labels: ts-config

#3624 CL-2339: Show attachments without downloading them
  CHANGELOG.md
  front/app/components/UI/FileUploader/FileDisplay.tsx
  front/app/components/UI/FileUploader/index.tsx
  front/app/containers/Admin/projects/project/timeline/edit.tsx
Labels: methods

#3659 [CL-2570] Remove impact tracking
  front/app/modules/commercial/impact_tracking/index.ts
  front/app/modules/index.ts
  front/cypress/e2e/impact_tracking.cy.ts
Labels: platform

#3660 [CL-2568] Remove idea assignment
  front/app/components/admin/PostManager/components/PostTable/Row/IdeaRow.tsx
  front/app/components/admin/PostManager/components/PostTable/header/IdeaHeaderRow.tsx
  front/app/components/admin/PostManager/index.tsx
  front/app/containers/Admin/projects/project/permissions/index.tsx
  front/app/modules/commercial/idea_assignment/admin/components/AssigneeFilter.test.tsx
  front/app/modules/commercial/idea_assignment/admin/components/AssigneeFilter.tsx
  front/app/modules/commercial/idea_assignment/admin/components/AssigneeSelector.tsx
  front/app/modules/commercial/idea_assignment/admin/components/IdeaHeaderCell.tsx
  front/app/modules/commercial/idea_assignment/admin/components/IdeaRowCell.tsx
  front/app/modules/commercial/idea_assignment/admin/components/Tab.tsx
  front/app/modules/commercial/idea_assignment/admin/components/__snapshots__/AssigneeFilter.test.tsx.snap
  front/app/modules/commercial/idea_assignment/admin/components/messages.ts
  front/app/modules/commercial/idea_assignment/admin/components/tracks.ts
  front/app/modules/commercial/idea_assignment/admin/containers/index.tsx
  front/app/modules/commercial/idea_assignment/admin/containers/messages.ts
  front/app/modules/commercial/idea_assignment/index.tsx
  front/app/modules/index.ts
  front/app/services/appConfiguration.ts
  front/app/translations/admin/ar-MA.json
  front/app/translations/admin/ar-SA.json
  front/app/translations/admin/ca-ES.json
  front/app/translations/admin/da-DK.json
  front/app/translations/admin/de-DE.json
  front/app/translations/admin/el-GR.json
  front/app/translations/admin/en-CA.json
  front/app/translations/admin/en-GB.json
  front/app/translations/admin/en.json
  front/app/translations/admin/es-CL.json
  front/app/translations/admin/es-ES.json
  front/app/translations/admin/fr-BE.json
  front/app/translations/admin/fr-FR.json
  front/app/translations/admin/hr-HR.json
  front/app/translations/admin/hu-HU.json
  front/app/translations/admin/it-IT.json
  front/app/translations/admin/kl-GL.json
  front/app/translations/admin/lb-LU.json
  front/app/translations/admin/lv-LV.json
  front/app/translations/admin/mi.json
  front/app/translations/admin/nb-NO.json
  front/app/translations/admin/nl-BE.json
  front/app/translations/admin/nl-NL.json
  front/app/translations/admin/pl-PL.json
  front/app/translations/admin/pt-BR.json
  front/app/translations/admin/ro-RO.json
  front/app/translations/admin/sr-Latn.json
  front/app/translations/admin/sv-SE.json
  front/app/translations/admin/tr-TR.json
  front/app/utils/moduleUtils.tsx
Labels: platform

#3663 Cl 2565/remove custom maps fe
  front/app/components/Map/index.tsx
  front/app/modules/commercial/custom_maps/admin/components/Tab.tsx
  front/app/modules/commercial/custom_maps/admin/components/messages.ts
  front/app/modules/commercial/custom_maps/admin/containers/ProjectCustomMapConfigPage/GeoJsonImportButton.tsx
  front/app/modules/commercial/custom_maps/admin/containers/ProjectCustomMapConfigPage/MapCenterAndZoomConfig.tsx
  front/app/modules/commercial/custom_maps/admin/containers/ProjectCustomMapConfigPage/MapConfigOverview.tsx
  front/app/modules/commercial/custom_maps/admin/containers/ProjectCustomMapConfigPage/MapLayerConfig.tsx
  front/app/modules/commercial/custom_maps/admin/containers/ProjectCustomMapConfigPage/MapLayersList.tsx
  front/app/modules/commercial/custom_maps/admin/containers/ProjectCustomMapConfigPage/addOrderingToLayers.ts
  front/app/modules/commercial/custom_maps/admin/containers/ProjectCustomMapConfigPage/index.tsx
  front/app/modules/commercial/custom_maps/admin/containers/ProjectCustomMapConfigPage/messages.ts
  front/app/modules/commercial/custom_maps/hooks/useMapConfig.ts
  front/app/modules/commercial/custom_maps/index.tsx
  front/app/modules/commercial/custom_maps/services/mapConfigs.ts
  front/app/modules/commercial/custom_maps/services/mapLayers.ts
  front/app/modules/commercial/custom_maps/shared/components/Map/LeafletConfig.tsx
  front/app/modules/commercial/custom_maps/shared/components/Map/Legend.tsx
  front/app/modules/commercial/custom_maps/shared/components/Map/idea-marker.svg
  front/app/modules/commercial/custom_maps/shared/components/Map/legend-marker.svg
  front/app/modules/commercial/custom_maps/utils/map.ts
  front/app/modules/commercial/custom_maps/utils/tileProviderDefaultOptions.ts
  front/app/modules/index.ts
  front/app/services/appConfiguration.ts
  front/app/translations/admin/ar-MA.json
  front/app/translations/admin/ar-SA.json
  front/app/translations/admin/ca-ES.json
  front/app/translations/admin/da-DK.json
  front/app/translations/admin/de-DE.json
  front/app/translations/admin/el-GR.json
  front/app/translations/admin/en-CA.json
  front/app/translations/admin/en-GB.json
  front/app/translations/admin/en.json
  front/app/translations/admin/es-CL.json
  front/app/translations/admin/es-ES.json
  front/app/translations/admin/fr-BE.json
  front/app/translations/admin/fr-FR.json
  front/app/translations/admin/hr-HR.json
  front/app/translations/admin/hu-HU.json
  front/app/translations/admin/it-IT.json
  front/app/translations/admin/kl-GL.json
  front/app/translations/admin/lb-LU.json
  front/app/translations/admin/lv-LV.json
  front/app/translations/admin/mi.json
  front/app/translations/admin/nb-NO.json
  front/app/translations/admin/nl-BE.json
  front/app/translations/admin/nl-NL.json
  front/app/translations/admin/pl-PL.json
  front/app/translations/admin/pt-BR.json
  front/app/translations/admin/ro-RO.json
  front/app/translations/admin/sr-Latn.json
  front/app/translations/admin/sv-SE.json
  front/app/translations/admin/tr-TR.json
  front/app/utils/moduleUtils.tsx
Labels: platform

#3568 [CL-2320] Folder and project banner image changes
  front/app/components/ProjectableHeader/index.tsx
  front/app/components/UI/ImagesDropzone/index.tsx
  front/app/components/admin/ImageCropper/Container.tsx
  front/app/components/admin/ImageCropper/ImageCropper.test.tsx
  front/app/components/admin/ImageCropper/ImageInfoTooltip.tsx
  front/app/components/admin/ImageCropper/index.tsx
  front/app/components/admin/ImageCropper/messages.ts
  front/app/components/admin/ProjectableHeaderBgUploader/ProjectableHeaderBgUploader.test.tsx
  front/app/components/admin/ProjectableHeaderBgUploader/index.tsx
  front/app/components/admin/ProjectableHeaderBgUploader/messages.ts
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/BannerImageFields/ImageUploader.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/BannerImageFields/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/LayoutSettingField/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/messages.ts
  front/app/containers/Admin/projectFolders/containers/messages.ts
  front/app/containers/Admin/projectFolders/containers/settings/ProjectFolderForm.tsx
  front/app/containers/Admin/projects/project/general/components/HeaderImageDropzone.tsx
  front/app/containers/Admin/projects/project/general/index.tsx
  front/app/containers/Admin/projects/project/general/messages.ts
  front/app/containers/ProjectFolderShowPage/ProjectFolderDescription.tsx
  front/app/containers/ProjectFolderShowPage/ProjectFolderHeader.tsx
  front/app/containers/ProjectFolderShowPage/index.tsx
  front/app/containers/ProjectsShowPage/shared/header/ProjectHeader.tsx
  front/app/routes.tsx
  front/app/services/projects.ts
  front/app/translations/admin/ar-MA.json
  front/app/translations/admin/ar-SA.json
  front/app/translations/admin/ca-ES.json
  front/app/translations/admin/da-DK.json
  front/app/translations/admin/de-DE.json
  front/app/translations/admin/el-GR.json
  front/app/translations/admin/en-CA.json
  front/app/translations/admin/en-GB.json
  front/app/translations/admin/en.json
  front/app/translations/admin/es-CL.json
  front/app/translations/admin/es-ES.json
  front/app/translations/admin/fr-BE.json
  front/app/translations/admin/fr-FR.json
  front/app/translations/admin/hr-HR.json
  front/app/translations/admin/hu-HU.json
  front/app/translations/admin/it-IT.json
  front/app/translations/admin/kl-GL.json
  front/app/translations/admin/lb-LU.json
  front/app/translations/admin/lv-LV.json
  front/app/translations/admin/mi.json
  front/app/translations/admin/nb-NO.json
  front/app/translations/admin/nl-BE.json
  front/app/translations/admin/nl-NL.json
  front/app/translations/admin/pl-PL.json
  front/app/translations/admin/pt-BR.json
  front/app/translations/admin/ro-RO.json
  front/app/translations/admin/sr-Latn.json
  front/app/translations/admin/sv-SE.json
  front/app/translations/admin/tr-TR.json
Labels: structure

#3667 CL-2564 Remove custom idea statuses front-end
  front/app/containers/Admin/ideas/index.tsx
  front/app/modules/commercial/custom_idea_statuses/admin/components/IdeaStatusForm.tsx
  front/app/modules/commercial/custom_idea_statuses/admin/components/Tab.tsx
  front/app/modules/commercial/custom_idea_statuses/admin/components/messages.ts
  front/app/modules/commercial/custom_idea_statuses/admin/containers/edit.tsx
  front/app/modules/commercial/custom_idea_statuses/admin/containers/index.tsx
  front/app/modules/commercial/custom_idea_statuses/admin/containers/messages.ts
  front/app/modules/commercial/custom_idea_statuses/admin/containers/new.tsx
  front/app/modules/commercial/custom_idea_statuses/index.tsx
  front/app/modules/index.ts
  front/app/services/ideaStatuses.ts
  front/app/translations/admin/ar-MA.json
  front/app/translations/admin/ar-SA.json
  front/app/translations/admin/ca-ES.json
  front/app/translations/admin/da-DK.json
  front/app/translations/admin/de-DE.json
  front/app/translations/admin/el-GR.json
  front/app/translations/admin/en-CA.json
  front/app/translations/admin/en-GB.json
  front/app/translations/admin/en.json
  front/app/translations/admin/es-CL.json
  front/app/translations/admin/es-ES.json
  front/app/translations/admin/fr-BE.json
  front/app/translations/admin/fr-FR.json
  front/app/translations/admin/hr-HR.json
  front/app/translations/admin/hu-HU.json
  front/app/translations/admin/it-IT.json
  front/app/translations/admin/kl-GL.json
  front/app/translations/admin/lb-LU.json
  front/app/translations/admin/lv-LV.json
  front/app/translations/admin/mi.json
  front/app/translations/admin/nb-NO.json
  front/app/translations/admin/nl-BE.json
  front/app/translations/admin/nl-NL.json
  front/app/translations/admin/pl-PL.json
  front/app/translations/admin/pt-BR.json
  front/app/translations/admin/ro-RO.json
  front/app/translations/admin/sr-Latn.json
  front/app/translations/admin/sv-SE.json
  front/app/translations/admin/tr-TR.json
  front/app/utils/moduleUtils.tsx
Labels: platform

#3567 Changes to useUrlQuery hook
  front/app/components/ProjectAndFolderCards/components/Topbar/index.tsx
  front/app/containers/Admin/formBuilder/components/FormResults/index.tsx
  front/app/containers/Authentication/VerificationModal/index.tsx
  front/app/containers/IdeasNewPage/WithJSONForm/Heading.tsx
  front/app/containers/IdeasNewPage/WithJSONForm/index.tsx
  front/app/containers/IdeasShow/index.tsx
  front/app/containers/ProjectsShowPage/index.tsx
  front/app/utils/cl-router/useUrlQuery.test.ts
  front/app/utils/cl-router/useUrlQuery.ts
Labels: platform

#3673 CL2351 Remove granular permissions fe
  front/app/containers/Admin/initiatives/index.tsx
  front/app/containers/Admin/projects/project/index.tsx
  front/app/containers/Admin/projects/project/permissions/index.tsx
  front/app/modules/commercial/granular_permissions/admin/components/InitiativeSettingsTab.tsx
  front/app/modules/commercial/granular_permissions/admin/components/ProjectSettingsTab.tsx
  front/app/modules/commercial/granular_permissions/admin/components/messages.ts
  front/app/modules/commercial/granular_permissions/admin/containers/Granular/ActionForm.tsx
  front/app/modules/commercial/granular_permissions/admin/containers/Granular/ActionsForm.tsx
  front/app/modules/commercial/granular_permissions/admin/containers/Granular/Continuous.tsx
  front/app/modules/commercial/granular_permissions/admin/containers/Granular/Timeline.tsx
  front/app/modules/commercial/granular_permissions/admin/containers/Granular/index.tsx
  front/app/modules/commercial/granular_permissions/admin/containers/Granular/messages.ts
  front/app/modules/commercial/granular_permissions/admin/containers/permissions/index.tsx
  front/app/modules/commercial/granular_permissions/admin/containers/permissions/messages.ts
  front/app/modules/commercial/granular_permissions/index.tsx
  front/app/modules/index.ts
  front/app/resources/GetGlobalPermissions.tsx
  front/app/resources/GetPhasePermissions.tsx
  front/app/resources/GetProjectPermissions.tsx
  front/app/services/actionPermissions.ts
  front/app/translations/admin/ar-MA.json
  front/app/translations/admin/ar-SA.json
  front/app/translations/admin/ca-ES.json
  front/app/translations/admin/da-DK.json
  front/app/translations/admin/de-DE.json
  front/app/translations/admin/el-GR.json
  front/app/translations/admin/en-CA.json
  front/app/translations/admin/en-GB.json
  front/app/translations/admin/en.json
  front/app/translations/admin/es-CL.json
  front/app/translations/admin/es-ES.json
  front/app/translations/admin/fr-BE.json
  front/app/translations/admin/fr-FR.json
  front/app/translations/admin/hr-HR.json
  front/app/translations/admin/hu-HU.json
  front/app/translations/admin/it-IT.json
  front/app/translations/admin/kl-GL.json
  front/app/translations/admin/lb-LU.json
  front/app/translations/admin/lv-LV.json
  front/app/translations/admin/mi.json
  front/app/translations/admin/nb-NO.json
  front/app/translations/admin/nl-BE.json
  front/app/translations/admin/nl-NL.json
  front/app/translations/admin/pl-PL.json
  front/app/translations/admin/pt-BR.json
  front/app/translations/admin/ro-RO.json
  front/app/translations/admin/sr-Latn.json
  front/app/translations/admin/sv-SE.json
  front/app/translations/admin/tr-TR.json
  front/app/utils/moduleUtils.tsx
Labels: platform

#3639 CL-2439: Add section element with settings fe
  front/app/components/FormBuilder/components/FormBuilderSettings/ContentSettings/index.tsx
  front/app/components/FormBuilder/components/FormBuilderSettings/FieldGroupSettings/index.tsx
  front/app/components/FormBuilder/components/FormBuilderSettings/FieldGroupSettings/messages.ts
  front/app/components/FormBuilder/components/FormBuilderSettings/index.tsx
  front/app/components/FormBuilder/components/FormBuilderSettings/utils.tsx
  front/app/components/FormBuilder/components/FormBuilderToolbox/index.tsx
  front/app/components/FormBuilder/components/FormFields/FieldElement.tsx
  front/app/components/FormBuilder/components/FormFields/index.tsx
  front/app/components/FormBuilder/components/FormFields/utils.ts
  front/app/components/FormBuilder/components/messages.ts
  front/app/components/FormBuilder/edit/index.tsx
  front/app/components/FormBuilder/edit/utils.ts
  front/app/components/FormBuilder/utils.ts
  front/app/containers/Admin/projects/project/inputForm/IdeaFormBuilder/index.tsx
  front/app/containers/Admin/projects/project/inputForm/utils.tsx
  front/app/containers/Admin/projects/project/nativeSurvey/utils.tsx
  front/app/services/formCustomFields.ts
  front/app/translations/en.json
  front/app/utils/yup/validateElementTitle.test.ts
  front/app/utils/yup/validateElementTitle.ts
  front/cypress/e2e/form_builder/create_and_fill_survey.cy.ts
  front/cypress/e2e/form_builder/elements/page_element.cy.ts
  front/package-lock.json
  front/package.json
Labels: methods

#3679 CL-2614 Remove widgets
  front/app/containers/Admin/settings/index.tsx
  front/app/modules/commercial/widgets/admin/components/Tab.tsx
  front/app/modules/commercial/widgets/admin/containers/IdeasWidget/Form.tsx
  front/app/modules/commercial/widgets/admin/containers/IdeasWidget/index.tsx
  front/app/modules/commercial/widgets/admin/containers/IdeasWidget/tracks.ts
  front/app/modules/commercial/widgets/admin/containers/WidgetCode.tsx
  front/app/modules/commercial/widgets/admin/containers/WidgetPreview.tsx
  front/app/modules/commercial/widgets/admin/containers/index.tsx
  front/app/modules/commercial/widgets/admin/messages.ts
  front/app/modules/commercial/widgets/index.tsx
  front/app/modules/index.ts
  front/app/translations/admin/ar-MA.json
  front/app/translations/admin/ar-SA.json
  front/app/translations/admin/ca-ES.json
  front/app/translations/admin/da-DK.json
  front/app/translations/admin/de-DE.json
  front/app/translations/admin/el-GR.json
  front/app/translations/admin/en-CA.json
  front/app/translations/admin/en-GB.json
  front/app/translations/admin/en.json
  front/app/translations/admin/es-CL.json
  front/app/translations/admin/es-ES.json
  front/app/translations/admin/fr-BE.json
  front/app/translations/admin/fr-FR.json
  front/app/translations/admin/hr-HR.json
  front/app/translations/admin/hu-HU.json
  front/app/translations/admin/it-IT.json
  front/app/translations/admin/kl-GL.json
  front/app/translations/admin/lb-LU.json
  front/app/translations/admin/lv-LV.json
  front/app/translations/admin/mi.json
  front/app/translations/admin/nb-NO.json
  front/app/translations/admin/nl-BE.json
  front/app/translations/admin/nl-NL.json
  front/app/translations/admin/pl-PL.json
  front/app/translations/admin/pt-BR.json
  front/app/translations/admin/ro-RO.json
  front/app/translations/admin/sr-Latn.json
  front/app/translations/admin/sv-SE.json
  front/app/translations/admin/tr-TR.json
  front/app/utils/moduleUtils.tsx
Labels: platform

#3678 [No ticket] - fix Carrierwave download error in dev environment
  back/config/initializers/carrierwave.rb
Labels: structure

#3685 CL-2566 Remove event widget
  front/app/components/Avatar/index.tsx
  front/app/containers/Admin/sideBar/index.tsx
  front/app/containers/Admin/users/UsersGroup.tsx
  front/app/containers/Admin/users/index.tsx
  front/app/containers/IdeasShow/index.tsx
  front/app/containers/MainHeader/UserMenu/User.tsx
  front/app/containers/MainHeader/UserMenu/VerificationBadge.tsx
  front/app/containers/UsersEditPage/VerificationStatus/index.tsx
  front/app/containers/UsersEditPage/index.tsx
  front/app/services/appConfiguration.ts
Labels: platform

#3686 CL-2566 Remove event widget module
  front/app/containers/Admin/pagesAndMenu/containers/EditHomepage/index.tsx
  front/app/containers/HomePage/MainContent.tsx
  front/app/hooks/useFeatureFlag.ts
  front/app/hooks/useHomepageSettingsFeatureFlag.test.ts
  front/app/hooks/useHomepageSettingsFeatureFlag.ts
  front/app/modules/commercial/events_widget/admin/SectionToggle.tsx
  front/app/modules/commercial/events_widget/admin/messages.ts
  front/app/modules/commercial/events_widget/index.tsx
  front/app/modules/commercial/events_widget/services/appConfiguration.ts
  front/app/modules/commercial/events_widget/services/homepageSettings.ts
  front/app/modules/index.ts
  front/app/services/appConfiguration.ts
  front/app/services/homepageSettings.ts
  front/app/translations/admin/ar-SA.json
  front/app/translations/admin/ca-ES.json
  front/app/translations/admin/da-DK.json
  front/app/translations/admin/de-DE.json
  front/app/translations/admin/el-GR.json
  front/app/translations/admin/en-CA.json
  front/app/translations/admin/en-GB.json
  front/app/translations/admin/en.json
  front/app/translations/admin/es-CL.json
  front/app/translations/admin/es-ES.json
  front/app/translations/admin/fr-BE.json
  front/app/translations/admin/fr-FR.json
  front/app/translations/admin/hr-HR.json
  front/app/translations/admin/kl-GL.json
  front/app/translations/admin/lv-LV.json
  front/app/translations/admin/nb-NO.json
  front/app/translations/admin/nl-BE.json
  front/app/translations/admin/nl-NL.json
  front/app/translations/admin/pl-PL.json
  front/app/translations/admin/pt-BR.json
  front/app/translations/admin/sr-Latn.json
  front/app/translations/admin/sv-SE.json
  front/app/translations/admin/tr-TR.json
  front/app/utils/moduleUtils.tsx
Labels: platform

#3687 Cl 2612 Remove moderation
  front/app/components/Outlet/index.tsx
  front/app/components/ProjectAndFolderCards/ProjectAndFolderCards.test.tsx
  front/app/components/admin/PostManager/PostManager.test.tsx
  front/app/containers/Admin/projects/project/AdminProjectsProjectIndex.test.tsx
  front/app/containers/Admin/settings/general/index.tsx
  front/app/containers/Admin/sideBar/index.tsx
  front/app/containers/PlatformFooter/index.tsx
  front/app/containers/UsersShowPage/UserComments.test.tsx
  front/app/containers/UsersShowPage/UsersShowPage.test.tsx
  front/app/modules/commercial/moderation/admin/components/NavItem.tsx
  front/app/modules/commercial/moderation/admin/containers/ModerationContentCell.tsx
  front/app/modules/commercial/moderation/admin/containers/ModerationRow.tsx
  front/app/modules/commercial/moderation/admin/containers/SelectProject.tsx
  front/app/modules/commercial/moderation/admin/containers/SelectType.tsx
  front/app/modules/commercial/moderation/admin/containers/index.tsx
  front/app/modules/commercial/moderation/admin/containers/messages.ts
  front/app/modules/commercial/moderation/admin/containers/tracks.ts
  front/app/modules/commercial/moderation/hooks/useModerations.ts
  front/app/modules/commercial/moderation/index.tsx
  front/app/modules/commercial/moderation/services/moderations.ts
  front/app/modules/index.ts
  front/app/services/appConfiguration.ts
  front/app/services/verificationMethods.ts
  front/app/translations/admin/ar-MA.json
  front/app/translations/admin/ar-SA.json
  front/app/translations/admin/ca-ES.json
  front/app/translations/admin/da-DK.json
  front/app/translations/admin/de-DE.json
  front/app/translations/admin/el-GR.json
  front/app/translations/admin/en-CA.json
  front/app/translations/admin/en-GB.json
  front/app/translations/admin/en.json
  front/app/translations/admin/es-CL.json
  front/app/translations/admin/es-ES.json
  front/app/translations/admin/fr-BE.json
  front/app/translations/admin/fr-FR.json
  front/app/translations/admin/hr-HR.json
  front/app/translations/admin/hu-HU.json
  front/app/translations/admin/it-IT.json
  front/app/translations/admin/kl-GL.json
  front/app/translations/admin/lb-LU.json
  front/app/translations/admin/lv-LV.json
  front/app/translations/admin/mi.json
  front/app/translations/admin/nb-NO.json
  front/app/translations/admin/nl-BE.json
  front/app/translations/admin/nl-NL.json
  front/app/translations/admin/pl-PL.json
  front/app/translations/admin/pt-BR.json
  front/app/translations/admin/ro-RO.json
  front/app/translations/admin/sr-Latn.json
  front/app/translations/admin/sv-SE.json
  front/app/translations/admin/tr-TR.json
  front/app/utils/moduleUtils.tsx
Labels: platform

#3640 CL-2360/remove onboarding campaign full-stack
  back/.rubocop_todo.yml
  back/Gemfile.lock
  back/app/models/user.rb
  back/app/services/user_reduce_service.rb
  back/config/routes.rb
  back/db/schema.rb
  back/doc/dependency_decisions.yml
  back/engines/free/onboarding/.gitignore
  back/engines/free/onboarding/README.md
  back/engines/free/onboarding/app/controllers/onboarding/onboarding_controller.rb
  back/engines/free/onboarding/app/controllers/onboarding/web_api/v1/campaign_dismissals_controller.rb
  back/engines/free/onboarding/app/controllers/onboarding/web_api/v1/campaigns_controller.rb
  back/engines/free/onboarding/app/models/onboarding/campaign_dismissal.rb
  back/engines/free/onboarding/app/models/onboarding/user_decorator.rb
  back/engines/free/onboarding/app/serializers/onboarding/web_api/v1/campaign_serializer.rb
  back/engines/free/onboarding/app/services/onboarding/onboarding_service.rb
  back/engines/free/onboarding/config/routes.rb
  back/engines/free/onboarding/db/migrate/20190107130853_create_campaign_dismissals.rb
  back/engines/free/onboarding/lib/onboarding.rb
  back/engines/free/onboarding/lib/onboarding/engine.rb
  back/engines/free/onboarding/lib/onboarding/version.rb
  back/engines/free/onboarding/onboarding.gemspec
  back/engines/free/onboarding/spec/acceptance/onboarding_campaigns_spec.rb
  back/engines/free/onboarding/spec/services/onboarding_service_spec.rb
  front/app/containers/HomePage/SignedInHeader/AcceptButton.tsx
  front/app/containers/HomePage/SignedInHeader/CompleteProfileStep.tsx
  front/app/containers/HomePage/SignedInHeader/CustomCTAStep.tsx
  front/app/containers/HomePage/SignedInHeader/FallbackStep.tsx
  front/app/containers/HomePage/SignedInHeader/SkipButton.tsx
  front/app/containers/HomePage/SignedInHeader/VerificationOnboardingStep.tsx
  front/app/containers/HomePage/SignedInHeader/index.tsx
  front/app/containers/UsersEditPage/ProfileForm.tsx
  front/app/hooks/useCurrentOnboardingCampaign.ts
  front/app/services/confirmation.ts
  front/app/services/onboardingCampaigns.ts
  front/app/utils/streams/index.ts
Labels: platform

#3509 Cl 2326 fe unit integration tests for layout settings
  front/app/components/Form/Components/Controls/ImageControl.tsx
  front/app/components/UI/ImagesDropzone/index.tsx
  front/app/components/admin/ImageCropper/ImageCropper.test.tsx
  front/app/components/admin/ImageCropper/index.tsx
  front/app/components/admin/ProjectableHeaderBgUploader/index.tsx
  front/app/containers/Admin/pagesAndMenu/EditHomepage/HeroBanner/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/Edit/HeroBanner/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/BannerImageFields/BannerImageFields.test.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/BannerImageFields/ImageUploader.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/BannerImageFields/OverlayControls.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/BannerImageFields/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/HeaderImageDropzone.test.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/HeaderImageDropzone.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/LayoutSettingField/index.tsx
  front/app/containers/Admin/projects/project/general/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/ActiveUsersWidget/ChartWidgetSettings.tsx
  front/app/containers/HomePage/HomePage.test.tsx
  front/app/services/customPages.ts
  front/app/services/homepageSettings.ts
  front/app/typings.ts
  front/app/utils/fileUtils.ts
  front/cypress/e2e/admin/pages_and_menu/update_homepage_hero_banner_content.cy.ts
  front/package-lock.json
  front/package.json
Labels: structure

#3689 CL-2617: Fix showing native survey submission modal numerously
  CHANGELOG.md
  front/app/containers/ProjectsShowPage/index.tsx
Labels: methods

#3712 Two column layout: ensure min width of 50%
  CHANGELOG.md
  front/app/components/LandingPages/citizen/TwoColumnLayout.ts
Labels: structure

#3694 CL-2622 Signed in banner image unit test
  front/app/containers/HomePage/SignedInHeader/HeaderImage.test.tsx
  front/app/containers/HomePage/SignedInHeader/HeaderImage.tsx
  front/app/services/__mocks__/homepageSettings.ts
Labels: structure

#3713 CL-171 Status of sent emails fix
  CHANGELOG.md
  front/app/containers/Admin/messaging/CustomEmails/Show/RecipientsTable.tsx
  front/app/containers/Admin/messaging/CustomEmails/Show/index.tsx
Labels: structure

#3621 CL-2542 BE New project copy functionality
  back/app/controllers/web_api/v1/projects_controller.rb
  back/app/policies/project_policy.rb
  back/app/services/local_project_copy_service.rb
  back/config/locales/en.yml
  back/config/routes.rb
  back/engines/commercial/admin_api/app/services/admin_api/project_copy_service.rb
  back/engines/commercial/admin_api/spec/acceptance/projects_spec.rb
  back/engines/commercial/multi_tenancy/app/services/multi_tenancy/tenant_template_service.rb
  back/spec/acceptance/projects_spec.rb
  back/spec/services/local_project_copy_service_spec.rb
Labels: structure

#3729 Ts config missing library type declarations
  front/package-lock.json
  front/package.json
Labels: ts-config

#3715 [CL-2649] ideation form builder UI tweaks
  front/app/components/FormBuilder/components/FormBuilderSettings/ContentSettings/index.tsx
  front/app/components/FormBuilder/components/FormBuilderSettings/index.tsx
  front/app/components/FormBuilder/components/FormBuilderToolbox/BuiltInFields.tsx
  front/app/components/FormBuilder/components/FormBuilderToolbox/ToolboxItem.tsx
  front/app/components/FormBuilder/components/FormFields/FieldElement.tsx
  front/app/components/FormBuilder/utils.ts
  front/app/containers/Admin/projects/project/inputForm/IdeaFormBuilder/index.tsx
  front/app/containers/Admin/projects/project/inputForm/utils.tsx
  front/app/containers/Admin/projects/project/nativeSurvey/utils.tsx
Labels: methods

#3714 [CL-2605] Use WYSIWYG for all form builder field descriptions
  front/app/components/Form/Components/Controls/AttachmentsControl.tsx
  front/app/components/Form/Components/Controls/CheckboxControl.tsx
  front/app/components/Form/Components/Controls/DateControl.tsx
  front/app/components/Form/Components/Controls/DescriptionControl.tsx
  front/app/components/Form/Components/Controls/ImageControl.tsx
  front/app/components/Form/Components/Controls/InputControl.tsx
  front/app/components/Form/Components/Controls/LinearScaleControl.tsx
  front/app/components/Form/Components/Controls/LocationControl.tsx
  front/app/components/Form/Components/Controls/MultiSelectCheckboxControl.tsx
  front/app/components/Form/Components/Controls/MultiSelectControl.tsx
  front/app/components/Form/Components/Controls/SingleAttachmentControl.tsx
  front/app/components/Form/Components/Controls/SingleSelectControl.tsx
  front/app/components/Form/Components/Controls/SingleSelectRadioControl.tsx
  front/app/components/Form/Components/Controls/TextAreaControl.tsx
  front/app/components/Form/Components/Controls/TitleControl.tsx
  front/app/components/Form/Components/Controls/TopicsControl.tsx
  front/app/components/Form/Components/Controls/UserPickerControl.tsx
  front/app/components/Form/Components/Controls/WYSIWYGControl.tsx
  front/app/components/Form/Components/Controls/controlUtils.tsx
  front/app/components/FormBuilder/components/FormBuilderSettings/ContentSettings/index.tsx
  front/app/containers/Admin/projects/project/inputForm/IdeaFormBuilder/index.tsx
Labels: methods

#3716 CL-2645 - Field Locks
  back/app/models/custom_field.rb
  back/app/serializers/web_api/v1/custom_field_serializer.rb
  back/lib/participation_method/base.rb
  back/lib/participation_method/ideation.rb
  back/spec/lib/participation_method/ideation_spec.rb
  back/spec/models/custom_field_spec.rb
Labels: methods

#3744 [CL-2666] Fix overflowing locales quill editor
  front/app/components/UI/QuillEditor/QuillMultilocWithLocaleSwitcher.tsx
Labels: methods

#3735 CL-2620 add tests of existing functionality
  back/spec/services/local_project_copy_service_spec.rb
Labels: structure

#3766 CL-2661 fix for topic ids
  back/app/models/custom_field.rb
  back/lib/participation_method/ideation.rb
  back/spec/models/custom_field_spec.rb
Labels: methods

#3736 Cl 2557 improve home page signed out header tests further
  front/app/components/LandingPages/citizen/TwoColumnLayout.ts
  front/app/containers/CustomPageShow/CustomPageHeader/TwoColumnLayout.tsx
  front/app/containers/HomePage/HomePage.test.tsx
  front/app/containers/HomePage/SignedOutHeader/FixedRatioLayout.tsx
  front/app/containers/HomePage/SignedOutHeader/FullWidthBannerLayout.tsx
  front/app/containers/HomePage/SignedOutHeader/SignedOutHeader.test.tsx
  front/app/containers/HomePage/SignedOutHeader/TwoColumnLayout.tsx
  front/app/containers/HomePage/SignedOutHeader/TwoRowLayout.tsx
  front/app/services/__mocks__/homepageSettings.ts
Labels: structure

#3776 Bump component library version
  CHANGELOG.md
  front/package-lock.json
  front/package.json
Labels: structure

#3758 Cl 2706 use large image in desktop tablet preview
  front/app/containers/Admin/projectFolders/containers/settings/ProjectFolderForm/index.tsx
  front/app/containers/Admin/projects/project/general/index.tsx
Labels: structure

#3577 Notification menu functional
  front/app/containers/MainHeader/NotificationMenu/NotificationMenu.test.tsx
  front/app/containers/MainHeader/NotificationMenu/NotificationsDropdown.tsx
  front/app/containers/MainHeader/NotificationMenu/__snapshots__/NotificationMenu.test.tsx.snap
  front/app/containers/MainHeader/NotificationMenu/components/NotificationCount/index.tsx
  front/app/containers/MainHeader/NotificationMenu/index.tsx
  front/app/services/users.ts
  front/package-lock.json
  front/package.json
Labels: ts-config

#3755 Cl 2574 image preview still crops
  front/app/components/LandingPages/citizen/FixedRatioLayout.ts
  front/app/components/LandingPages/citizen/FullWidthBannerLayout.ts
  front/app/components/LandingPages/citizen/TwoRowLayout.ts
  front/app/components/ProjectableHeader/index.tsx
  front/app/components/admin/ProjectableHeaderBgUploader/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/BannerImageFields/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/HeaderImageDropzone.tsx
  front/app/containers/Admin/projects/project/general/components/ProjectCardImageDropzone.tsx
  front/app/containers/Admin/projects/project/general/index.tsx
  front/app/containers/CustomPageShow/CustomPageHeader/FixedRatioLayout.tsx
  front/app/containers/HomePage/SignedOutHeader/FixedRatioLayout.tsx
  front/app/containers/HomePage/SignedOutHeader/HeaderContent.tsx
  front/app/services/projects.ts
Labels: structure

#3781 [CL-2716] Exclude languages from crowdin config
  crowdin.yml
Labels: structure

#3793 CL-2717 Revert remaining unwanted fe translation file changes
  front/app/translations/admin/ar-MA.json
  front/app/translations/admin/ca-ES.json
  front/app/translations/admin/el-GR.json
  front/app/translations/admin/it-IT.json
  front/app/translations/admin/kl-GL.json
  front/app/translations/admin/lb-LU.json
  front/app/translations/admin/ro-RO.json
  front/app/translations/admin/sr-SP.json
  front/app/translations/kl-GL.json
Labels: structure

#3796 [CL-2719] Revert greenlandic back/config/locales file
  back/config/locales/kl-GL.yml
Labels: structure

#3797 [CL-2620] Comment out flaky test for now
  back/spec/services/local_project_copy_service_spec.rb
Labels: structure

#3721 CL-2658 Most voted ideas widget
  front/app/components/admin/GraphCards/ActiveUsersCard/Chart.tsx
  front/app/components/admin/GraphCards/typings.ts
  front/app/containers/Admin/dashboard/components/filters/ProjectFilter.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Editor/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Toolbox/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/ActiveUsersWidget/ActiveUsersCard.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/ActiveUsersWidget/ActiveUsersWidget.test.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/ActiveUsersWidget/ChartWidgetSettings.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/ActiveUsersWidget/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/AgeWidget/AgeCard.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/AgeWidget/AgeWidget.test.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/AgeWidget/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/GenderWidget/GenderCard.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/GenderWidget/GenderWidget.test.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/GenderWidget/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/NoChartData.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/VisitorsTrafficSourcesWidget/VisitorTrafficSourcesCard.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/VisitorsTrafficSourcesWidget/VisitorsTrafficSourcesWidget.test.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/VisitorsTrafficSourcesWidget/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/VisitorsWidget/VisitorsCard.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/VisitorsWidget/VisitorsWidget.test.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/VisitorsWidget/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/ChartWidgets/_shared/ChartWidgetSettings.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/MostVotedIdeasWidget/Ideas/IdeaCard.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/MostVotedIdeasWidget/Ideas/checkTextOverflow.ts
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/MostVotedIdeasWidget/Ideas/gradient.svg
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/MostVotedIdeasWidget/Ideas/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/MostVotedIdeasWidget/ProjectInfo.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/MostVotedIdeasWidget/Settings/CollapseLongTextToggle.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/MostVotedIdeasWidget/Settings/NumberOfIdeasDropdown.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/MostVotedIdeasWidget/Settings/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/MostVotedIdeasWidget/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/MostVotedIdeasWidget/messages.ts
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/MostVotedIdeasWidget/typings.ts
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/SurveyResultsWidget/NoResults.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/SurveyResultsWidget/ProjectFilter.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/SurveyResultsWidget/SurveyResults.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/SurveyResultsWidget/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/_shared/Card.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/_shared/NoData.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/_shared/PhaseFilter.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/_shared/ProjectFilter.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/messages.ts
  front/app/containers/Admin/reporting/hooks/useMostVotedIdeas.ts
  front/app/containers/Admin/reporting/messages.ts
  front/app/hooks/usePhases.ts
  front/app/hooks/useProjects.ts
  front/app/translations/admin/en.json
Labels: insights

#3792 CL-2580-add-comment-to-fe-code-explaining-different-user-group-behaviour-with-unregistered-users
  front/app/containers/Admin/users/UserTableRow.tsx
Labels: structure

#3734 [CL-2661] Remove hardcoded dummy data
  front/app/components/FormBuilder/components/FormBuilderToolbox/index.tsx
  front/app/components/FormBuilder/edit/index.tsx
  front/app/components/FormBuilder/utils.ts
  front/app/containers/Admin/projects/project/inputForm/IdeaFormBuilder/index.tsx
  front/app/containers/Admin/projects/project/inputForm/utils.tsx
  front/app/containers/Admin/projects/project/nativeSurvey/utils.tsx
  front/app/services/formCustomFields.ts
Labels: methods

#3756 Cl 2671 section and lock tests
  back/app/models/custom_field.rb
  back/app/serializers/web_api/v1/custom_field_serializer.rb
  back/app/services/idea_custom_fields_service.rb
  back/config/locales/en.yml
  back/engines/commercial/idea_custom_fields/app/controllers/idea_custom_fields/web_api/v1/admin/idea_custom_fields_controller.rb
  back/lib/participation_method/ideation.rb
  back/spec/lib/participation_method/budgeting_spec.rb
  back/spec/lib/participation_method/ideation_spec.rb
  back/spec/models/custom_field_spec.rb
  back/spec/services/idea_custom_fields_service_spec.rb
  back/spec/services/input_ui_schema_generator_service_spec.rb
Labels: methods

#3769 CL-2651: Fix survey top bar issue on mobile
  CHANGELOG.md
  front/app/containers/IdeasNewPage/WithJSONForm/Heading.tsx
Labels: methods

#3770 [CL-2699] Transform volunteering form
  front/app/containers/Admin/projects/project/volunteering/CauseForm.test.tsx
  front/app/containers/Admin/projects/project/volunteering/CauseForm.tsx
  front/app/containers/Admin/projects/project/volunteering/EditCause.tsx
  front/app/containers/Admin/projects/project/volunteering/NewCause.tsx
  front/app/containers/Admin/projects/project/volunteering/messages.ts
  front/app/translations/admin/en.json
Labels: waiting for translations, platform

#3825 Remove feature flag for activity warnings tab
  CHANGELOG.md
  front/app/modules/commercial/flag_inappropriate_content/index.tsx
Labels: structure

#3805 CL-2620 Fix flaky test
  back/spec/services/local_project_copy_service_spec.rb
Labels: structure

#3591 CL-1703: default CTA banner within project pages
  front/app/components/IdeaButton/index.tsx
  front/app/components/IdeaButton/utils.ts
  front/app/components/IdeasMap/index.tsx
  front/app/components/ParticipationCTABars/BudgetingCTABar/index.tsx
  front/app/components/ParticipationCTABars/EmbeddedSurveyCTABar/index.tsx
  front/app/components/ParticipationCTABars/IdeationCTABar/index.tsx
  front/app/components/ParticipationCTABars/NativeSurveyCTABar/index.tsx
  front/app/components/ParticipationCTABars/ParticipationCTAContent/index.tsx
  front/app/components/ParticipationCTABars/VolunteeringCTABar/index.tsx
  front/app/components/ParticipationCTABars/messages.ts
  front/app/components/ParticipationCTABars/utils.ts
  front/app/components/admin/PostManager/components/LazyPostPreview/Initiative/InitiativeContent.tsx
  front/app/components/admin/PostManager/components/PostTable/Row/InitiativeRow.tsx
  front/app/containers/InitiativesShow/VoteControl/ProposedNotVoted.tsx
  front/app/containers/InitiativesShow/VoteControl/ProposedVoted.tsx
  front/app/containers/ProjectsShowPage/ProjectCTABar/index.tsx
  front/app/containers/ProjectsShowPage/index.tsx
  front/app/containers/ProjectsShowPage/shared/header/ProjectActionBar.tsx
  front/app/containers/ProjectsShowPage/shared/header/ProjectActionButtons.tsx
  front/app/containers/ProjectsShowPage/shared/header/ProjectInfoSideBar.tsx
  front/app/containers/ProjectsShowPage/shared/pb/PBExpenses.tsx
  front/app/containers/ProjectsShowPage/shared/volunteering/index.tsx
  front/app/translations/en.json
  front/app/utils/dateUtils.ts
  front/app/utils/participationMethodUtils.tsx
  front/cypress/e2e/project_page_ideas.cy.ts
  front/cypress/e2e/project_page_native_survey.cy.ts
  front/cypress/e2e/project_page_pb.cy.ts
  front/cypress/e2e/project_page_survey.cy.ts
  front/cypress/e2e/project_page_volunteering.cy.ts
  front/cypress/support/commands.ts
Labels: waiting for translations, methods

#3767 Get image url in same way in front/back office
  front/app/components/ProjectAndFolderCards/components/ProjectFolderCard/index.tsx
  front/app/components/ProjectCard/index.tsx
  front/app/components/admin/SelectPreviewDevice/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/BannerImageFields/ImageUploader.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/BannerImageFields/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/HeaderImageDropzone.tsx
  front/app/containers/Admin/projectFolders/containers/settings/ProjectFolderForm/ProjectFolderCardImageDropzone.tsx
  front/app/containers/Admin/projectFolders/containers/settings/ProjectFolderForm/index.tsx
  front/app/containers/Admin/projects/project/general/components/ProjectCardImageDropzone.tsx
  front/app/containers/Admin/projects/project/general/index.tsx
  front/app/services/projectFolders.ts
  front/app/services/projects.ts
Labels: structure

#3821 Don't reset device preview type on image remove
  front/app/containers/Admin/projectFolders/containers/settings/ProjectFolderForm/index.tsx
  front/app/containers/Admin/projects/project/general/index.tsx
Labels: structure

#3849 Fix and sort types
  front/app/components/ProjectAndFolderCards/components/ProjectFolderCard/index.tsx
  front/app/components/ProjectAndFolderCards/components/ProjectsTabPanel.tsx
  front/app/components/ProjectAndFolderCards/components/PublicationStatusTabs.tsx
  front/app/components/ProjectAndFolderCards/components/getCardSizes.ts
  front/app/components/ProjectAndFolderCards/index.tsx
  front/app/components/ProjectCard/index.tsx
  front/app/containers/Admin/projectFolders/containers/settings/ProjectFolderForm/ProjectFolderCardImageDropzone.tsx
  front/app/containers/Admin/projectFolders/containers/settings/ProjectFolderForm/index.tsx
  front/app/containers/Admin/projects/project/general/components/ProjectCardImageDropzone.tsx
  front/app/containers/Admin/projects/project/general/index.tsx
  front/app/services/projectFolderImages.ts
  front/app/services/projectFolders.ts
  front/app/services/projectImages.ts
  front/app/services/projects.ts
Labels: structure

#3813 [CL-2724] Ignore code & input_type params on update only
  back/app/services/idea_custom_fields_service.rb
  back/engines/commercial/idea_custom_fields/app/controllers/idea_custom_fields/web_api/v1/admin/idea_custom_fields_controller.rb
  back/spec/services/idea_custom_fields_service_spec.rb
Labels: methods
