Repository CitizenLabDotCo/citizenlab, pull requests merged in 2023-06, with the labels that each got.

#5045 [CL-3689] Fix auto start date in new phase form
  front/app/containers/Admin/projects/project/timeline/edit.tsx
Labels: methods

#5049 [CL-3712] Improve save_examples in light of recent bugfix
  back/engines/free/email_campaigns/app/services/email_campaigns/examples_service.rb
  back/engines/free/email_campaigns/spec/services/email_campaigns/examples_service_spec.rb
Labels: structure

#5008 [CL-3694] Custom from email setting
  back/app/mailers/application_mailer.rb
  back/config/schemas/settings.schema.json.erb
Labels: structure

#5060 Revert "[CL-3694] Custom from email setting"
  back/app/mailers/application_mailer.rb
  back/config/schemas/settings.schema.json.erb
Labels: structure

#5114 [CL-3784] Bugfix: Mentions endpoint no longer returns inactive users
  back/app/controllers/web_api/v1/mentions_controller.rb
  back/spec/acceptance/mentions_spec.rb
Labels: bug, structure

#5056 Add support article link for user anonymity
  front/app/components/admin/AnonymousPostingToggle/AnonymousPostingToggle.tsx
  front/app/components/admin/AnonymousPostingToggle/messages.ts
  front/app/translations/admin/en.json
Labels: methods

#5094 Update empty preview text
  front/app/components/UI/MentionsTextArea/index.tsx
  front/app/containers/Admin/messaging/AutomatedEmails/ExampleModal/EmptyState.tsx
  front/app/containers/Admin/messaging/messages.ts
  front/app/translations/admin/ar-SA.json
  front/app/translations/admin/da-DK.json
  front/app/translations/admin/de-DE.json
  front/app/translations/admin/en-CA.json
  front/app/translations/admin/en-GB.json
  front/app/translations/admin/en.json
  front/app/translations/admin/es-CL.json
  front/app/translations/admin/es-ES.json
  front/app/translations/admin/fr-BE.json
  front/app/translations/admin/fr-FR.json
  front/app/translations/admin/hr-HR.json
  front/app/translations/admin/lv-LV.json
  front/app/translations/admin/nb-NO.json
  front/app/translations/admin/nl-BE.json
  front/app/translations/admin/nl-NL.json
  front/app/translations/admin/pl-PL.json
  front/app/translations/admin/pt-BR.json
  front/app/translations/admin/sr-Latn.json
  front/app/translations/admin/sr-SP.json
  front/app/translations/admin/sv-SE.json
  front/app/translations/admin/tr-TR.json
  front/package-lock.json
  front/package.json
Labels: waiting for translations, structure

#5129 Cl 3783 default value comments sorting
  front/app/api/comments/types.ts
  front/app/components/PostShowComponents/Comments/CommentSorting.tsx
  front/app/components/PostShowComponents/Comments/index.tsx
  front/app/components/PostShowComponents/Comments/messages.ts
  front/app/translations/en.json
Labels: waiting for translations, structure

#5137 [No-ticket] Use to_i to avoid rounding errors causing test to fail
  back/spec/models/user_spec.rb
Labels: structure

#5125 Cl 3793 fix tech debt in comments
  front/app/api/comments/types.ts
  front/app/api/comments/useMarkForDeletion.ts
  front/app/components/PostShowComponents/Comments/Comment/AdminBadge.tsx
  front/app/components/PostShowComponents/Comments/Comment/CommentFooter.tsx
  front/app/components/PostShowComponents/Comments/Comment/CommentHeader.tsx
  front/app/components/PostShowComponents/Comments/Comment/CommentReplyButton.tsx
  front/app/components/PostShowComponents/Comments/Comment/CommentsMoreActions.tsx
  front/app/components/PostShowComponents/Comments/Comment/index.tsx
  front/app/components/PostShowComponents/Comments/CommentingProposalDisabled.tsx
  front/app/components/PostShowComponents/Comments/CommentsAdminDeletionModal.tsx
  front/app/components/PostShowComponents/Comments/CommetingIdeaDisabled.tsx
  front/app/components/PostShowComponents/Comments/ParentComment.tsx
  front/app/components/PostShowComponents/Comments/ParentCommentForm.tsx
  front/app/components/PostShowComponents/Comments/events.ts
  front/app/components/PostShowComponents/Comments/index.tsx
  front/app/components/admin/PostManager/components/LazyPostPreview/Idea/IdeaContent.tsx
  front/app/components/admin/PostManager/components/LazyPostPreview/Initiative/InitiativeContent.tsx
  front/app/containers/Admin/sideBar/index.tsx
  front/app/modules/commercial/machine_translations/citizen/components/CommentTranslateButton.tsx
  front/app/resources/GetComment.tsx
  front/app/utils/moduleUtils.tsx
Labels: structure

#5126 CL-3714 Remove guard clause cop
  back/.rubocop.yml
  back/app/services/side_fx_idea_service.rb
  back/engines/commercial/multi_tenancy/app/services/multi_tenancy/tenant_service.rb
Labels: methods

#5134 Cl 3793 fix tech debt in comments part 2
  front/app/components/PostShowComponents/Comments/ChildCommentForm.tsx
  front/app/components/PostShowComponents/Comments/Comment/CommentBody.tsx
  front/app/components/PostShowComponents/Comments/Comment/CommentFooter.tsx
  front/app/components/PostShowComponents/Comments/Comment/CommentReplyButton.tsx
  front/app/components/PostShowComponents/Comments/Comment/CommentVote/index.tsx
  front/app/components/PostShowComponents/Comments/Comment/CommentsMoreActions.tsx
  front/app/components/PostShowComponents/Comments/Comment/index.tsx
  front/app/components/PostShowComponents/Comments/Comment/utils.ts
  front/app/components/PostShowComponents/Comments/CommentingDisabled.tsx
  front/app/components/PostShowComponents/Comments/Comments.tsx
  front/app/components/PostShowComponents/Comments/ParentComment.tsx
  front/app/components/PostShowComponents/Comments/ParentCommentForm.tsx
  front/app/components/PostShowComponents/Comments/events.ts
  front/app/components/PostShowComponents/Comments/index.tsx
  front/app/containers/Authentication/SuccessActions/actions/replyToComment.ts
  front/app/containers/UsersShowPage/PostCommentGroup.tsx
Labels: structure

#5113 CL-3508: upgrade react mentions library
  front/app/components/UI/MentionsTextArea/index.tsx
  front/package-lock.json
  front/package.json
Labels: structure

#5157 CL-3806-dont-show-reply-button-when-commenting-is-disabled
  front/app/components/PostShowComponents/Comments/Comment/CommentReplyButton.tsx
Labels: structure

#5156 Fix colors of comment voting
  front/app/components/PostShowComponents/Comments/Comment/CommentVote/UpvoteButton.tsx
Labels: structure

#5153 fixes-to-dropdown-test
  front/app/api/me/__mocks__/useAuthUser.ts
  front/app/containers/MainHeader/NotificationMenu/NotificationMenu.test.tsx
  front/app/containers/MainHeader/NotificationMenu/NotificationsDropdown.tsx
Labels: structure

#5158 Cl 3807 comments code clean up part 3
  front/app/api/comments/__mocks__/useComments.ts
  front/app/api/comments/types.ts
  front/app/components/PostShowComponents/Comments/Comment/CommentHeader.test.tsx
  front/app/components/PostShowComponents/Comments/Comment/CommentHeader.tsx
  front/app/components/PostShowComponents/Comments/Comment/index.tsx
  front/app/components/PostShowComponents/Comments/ParentComment.tsx
  front/app/containers/UsersShowPage/PostCommentGroup.tsx
Labels: structure

#5168 CL-3826: Fix reordering projects in a folder
  front/app/containers/Admin/projectFolders/containers/projects/ItemsInFolder.tsx
Labels: structure

#5164 Cl 3812 fe add internal comments
  front/app/components/PostShowComponents/Comments/ChildCommentForm.tsx
  front/app/components/PostShowComponents/Comments/Comment/CommentReplyButton.tsx
  front/app/components/PostShowComponents/Comments/CommentingIdeaDisabled.tsx
  front/app/components/PostShowComponents/Comments/ParentComment.tsx
  front/app/components/PostShowComponents/Comments/ParentCommentForm.tsx
  front/app/components/PostShowComponents/Comments/index.tsx
  front/app/components/admin/InternalComments/ChildCommentForm.tsx
  front/app/components/admin/InternalComments/Comment/CommentBody.tsx
  front/app/components/admin/InternalComments/Comment/CommentFooter.tsx
  front/app/components/admin/InternalComments/Comment/CommentHeader.tsx
  front/app/components/admin/InternalComments/Comment/CommentReplyButton.tsx
  front/app/components/admin/InternalComments/Comment/CommentVote/UpvoteButton.tsx
  front/app/components/admin/InternalComments/Comment/CommentVote/index.tsx
  front/app/components/admin/InternalComments/Comment/CommentVote/trackVote.ts
  front/app/components/admin/InternalComments/Comment/CommentsMoreActions.tsx
  front/app/components/admin/InternalComments/Comment/index.tsx
  front/app/components/admin/InternalComments/CommentSorting.tsx
  front/app/components/admin/InternalComments/CommentingDisabled.tsx
  front/app/components/admin/InternalComments/CommentingProposalDisabled.tsx
  front/app/components/admin/InternalComments/Comments.tsx
  front/app/components/admin/InternalComments/CommentsAdminDeletionModal.tsx
  front/app/components/admin/InternalComments/CommetingIdeaDisabled.tsx
  front/app/components/admin/InternalComments/LoadingComments.tsx
  front/app/components/admin/InternalComments/ParentComment.tsx
  front/app/components/admin/InternalComments/ParentCommentForm.tsx
  front/app/components/admin/InternalComments/events.ts
  front/app/components/admin/InternalComments/index.tsx
  front/app/components/admin/InternalComments/messages.ts
  front/app/components/admin/InternalComments/tracks.ts
Labels: structure

#5173 Test for cl 3826
  front/app/api/admin_publications/__mocks__/useAdminPublications.ts
  front/app/api/admin_publications/useAdminPublication.test.ts
  front/app/api/admin_publications/useAdminPublications.test.ts
  front/app/api/admin_publications/useReorderAdminPublication.test.ts
  front/app/containers/Admin/projectFolders/containers/projects/ItemsInFolder.test.tsx
  front/app/containers/Admin/projectFolders/containers/projects/ItemsInFolder.tsx
  front/app/containers/Admin/projects/all/Lists/NonSortableFolderRow.test.tsx
Labels: structure

#5177 [No ticket] Correct proposal vs idea feature names
  back/config/schemas/settings.schema.json.erb
Labels: structure

#5176 CL-3809 - Fix to produce a consistent numeric last name across different servers
  back/app/models/user.rb
Labels: methods

#5179 CL-3813 and CL-3814
  front/app/components/PostShowComponents/Comments/ParentCommentForm.tsx
  front/app/components/PostShowComponents/Comments/PublicComments.tsx
  front/app/components/PostShowComponents/Comments/index.tsx
  front/app/components/PostShowComponents/Comments/messages.ts
  front/app/components/admin/InternalComments/ParentCommentForm.tsx
  front/app/components/admin/InternalComments/index.tsx
  front/app/components/admin/PostManager/components/LazyPostPreview/Idea/IdeaContent.tsx
  front/app/components/admin/PostManager/components/LazyPostPreview/Initiative/InitiativeContent.tsx
  front/app/translations/en.json
Labels: structure

#5181 Fix schema error when too many options
  back/app/services/json_schema_generator_service.rb
  back/app/services/ui_schema_generator_service.rb
  back/app/services/user_json_schema_generator_service.rb
  back/spec/services/input_ui_schema_generator_service_spec.rb
  back/spec/services/json_forms_service_spec.rb
  back/spec/services/json_schema_generator_service_spec.rb
  back/spec/services/ui_schema_generator_service_spec.rb
  back/spec/services/user_json_schema_generator_service_spec.rb
  front/app/components/Form/Components/Controls/SingleSelectEnumControl.tsx
  front/app/components/Form/Components/Controls/SingleSelectRadioEnumControl.tsx
  front/app/components/Form/Components/Controls/controlUtils.tsx
  front/app/components/Form/Components/Controls/index.tsx
  front/app/components/Form/formConfig.tsx
Labels: methods

#5189 CL-3837: Add feature flag for internal commenting
  back/config/schemas/settings.schema.json.erb
  back/engines/commercial/multi_tenancy/db/seeds/tenants.rb
  back/engines/commercial/multi_tenancy/lib/tasks/core/create_tenant.rake
  front/app/api/app_configuration/types.ts
  front/app/components/PostShowComponents/Comments/index.tsx
Labels: structure

#4851 CL-3548 - Scaffold public api v2
  back/app/uploaders/idea_file_uploader.rb
  back/engines/commercial/public_api/app/controllers/public_api/public_api_controller.rb
  back/engines/commercial/public_api/app/controllers/public_api/public_api_controller/invalid_enum_parameter_value_error.rb
  back/engines/commercial/public_api/app/controllers/public_api/v2/api_token_controller.rb
  back/engines/commercial/public_api/app/controllers/public_api/v2/comments_controller.rb
  back/engines/commercial/public_api/app/controllers/public_api/v2/ideas_controller.rb
  back/engines/commercial/public_api/app/controllers/public_api/v2/initiatives_controller.rb
  back/engines/commercial/public_api/app/controllers/public_api/v2/phases_controller.rb
  back/engines/commercial/public_api/app/controllers/public_api/v2/projects_controller.rb
  back/engines/commercial/public_api/app/controllers/public_api/v2/reactions_controller.rb
  back/engines/commercial/public_api/app/controllers/public_api/v2/topics_controller.rb
  back/engines/commercial/public_api/app/controllers/public_api/v2/users_controller.rb
  back/engines/commercial/public_api/app/finders/public_api/reactions_finder.rb
  back/engines/commercial/public_api/app/serializers/public_api/v2/base_serializer.rb
  back/engines/commercial/public_api/app/serializers/public_api/v2/comment_serializer.rb
  back/engines/commercial/public_api/app/serializers/public_api/v2/idea_serializer.rb
  back/engines/commercial/public_api/app/serializers/public_api/v2/initiative_serializer.rb
  back/engines/commercial/public_api/app/serializers/public_api/v2/phase_serializer.rb
  back/engines/commercial/public_api/app/serializers/public_api/v2/project_serializer.rb
  back/engines/commercial/public_api/app/serializers/public_api/v2/reaction_serializer.rb
  back/engines/commercial/public_api/app/serializers/public_api/v2/topic_serializer.rb
  back/engines/commercial/public_api/app/serializers/public_api/v2/user_serializer.rb
  back/engines/commercial/public_api/config/open_api/open_api.yml
  back/engines/commercial/public_api/config/routes.rb
  back/engines/commercial/public_api/lib/tasks/rspec_api_docs.rake
  back/engines/commercial/public_api/spec/acceptance/v1/authentication_spec.rb
  back/engines/commercial/public_api/spec/acceptance/v1/ideas_spec.rb
  back/engines/commercial/public_api/spec/acceptance/v1/phases_spec.rb
  back/engines/commercial/public_api/spec/acceptance/v1/projects_spec.rb
  back/engines/commercial/public_api/spec/acceptance/v2/authentication_spec.rb
  back/engines/commercial/public_api/spec/acceptance/v2/comments_spec.rb
  back/engines/commercial/public_api/spec/acceptance/v2/ideas_spec.rb
  back/engines/commercial/public_api/spec/acceptance/v2/initiatives_spec.rb
  back/engines/commercial/public_api/spec/acceptance/v2/phases_spec.rb
  back/engines/commercial/public_api/spec/acceptance/v2/projects_spec.rb
  back/engines/commercial/public_api/spec/acceptance/v2/reactions_spec.rb
  back/engines/commercial/public_api/spec/acceptance/v2/support/shared.rb
  back/engines/commercial/public_api/spec/acceptance/v2/topics_spec.rb
  back/engines/commercial/public_api/spec/acceptance/v2/users_spec.rb
  back/spec/factories/comments.rb
  back/spec/factories/reactions.rb
  back/spec/spec_helper.rb
  docker-compose.yml
Labels: platform-week-23Q2

#5174 Cl 3827 fe add data loading hooks
  front/app/api/comments/types.ts
  front/app/api/comments/useAddCommentToIdea.ts
  front/app/api/comments/useAddCommentToInitiative.ts
  front/app/api/comments/useComments.test.ts
  front/app/api/comments/useComments.ts
  front/app/api/comments/useMarkCommentForDeletion.test.ts
  front/app/api/comments/useMarkCommentForDeletion.ts
  front/app/api/internal_comments/__mocks__/useInternalComments.ts
  front/app/api/internal_comments/keys.ts
  front/app/api/internal_comments/types.ts
  front/app/api/internal_comments/useAddCommentToIdea.ts
  front/app/api/internal_comments/useAddCommentToInitiative.ts
  front/app/api/internal_comments/useAddInternalCommentToIdea.test.ts
  front/app/api/internal_comments/useAddInternalCommentToIdea.ts
  front/app/api/internal_comments/useAddInternalCommentToInitiative.test.ts
  front/app/api/internal_comments/useAddInternalCommentToInitiative.ts
  front/app/api/internal_comments/useComment.ts
  front/app/api/internal_comments/useComments.ts
  front/app/api/internal_comments/useInternalComment.test.ts
  front/app/api/internal_comments/useInternalComment.ts
  front/app/api/internal_comments/useInternalComments.test.ts
  front/app/api/internal_comments/useInternalComments.ts
  front/app/api/internal_comments/useMarkForDeletion.ts
  front/app/api/internal_comments/useMarkInternalCommentForDeletion.test.ts
  front/app/api/internal_comments/useMarkInternalCommentForDeletion.ts
  front/app/api/internal_comments/useUpdateComment.ts
  front/app/api/internal_comments/useUpdateInternalComment.test.ts
  front/app/api/internal_comments/useUpdateInternalComment.ts
  front/app/components/PostShowComponents/Comments/Comment/CommentsMoreActions.tsx
  front/app/components/admin/InternalComments/InternalChildCommentForm.tsx
  front/app/components/admin/InternalComments/InternalComment/CommentHeader.test.tsx
  front/app/components/admin/InternalComments/InternalComment/InternalCommentBody.tsx
  front/app/components/admin/InternalComments/InternalComment/InternalCommentFooter.tsx
  front/app/components/admin/InternalComments/InternalComment/InternalCommentHeader.tsx
  front/app/components/admin/InternalComments/InternalComment/InternalCommentReplyButton.tsx
  front/app/components/admin/InternalComments/InternalComment/InternalCommentsMoreActions.tsx
  front/app/components/admin/InternalComments/InternalComment/index.tsx
  front/app/components/admin/InternalComments/InternalCommentSorting.tsx
  front/app/components/admin/InternalComments/InternalComments.tsx
  front/app/components/admin/InternalComments/InternalParentComment.tsx
  front/app/components/admin/InternalComments/InternalParentCommentForm.tsx
  front/app/components/admin/InternalComments/index.tsx
  front/app/containers/UsersShowPage/UserComments.tsx
  front/app/utils/cl-react-query/fetcher.ts
Labels: structure

#5122 [CL-3602] Change message in participation bar when survey submission disabled
  front/app/components/ParticipationCTABars/BudgetingCTABar/index.tsx
  front/app/components/ParticipationCTABars/DocumentAnnotationCTABar/index.tsx
  front/app/components/ParticipationCTABars/EmbeddedSurveyCTABar/index.tsx
  front/app/components/ParticipationCTABars/IdeationCTABar/index.tsx
  front/app/components/ParticipationCTABars/NativeSurveyCTABar/index.tsx
  front/app/components/ParticipationCTABars/ParticipationCTAContent/index.tsx
  front/app/components/ParticipationCTABars/PollCTABar/index.tsx
  front/app/components/ParticipationCTABars/VolunteeringCTABar/index.tsx
  front/app/components/ParticipationCTABars/messages.ts
  front/app/translations/en.json
  front/app/utils/participationMethodUtils.tsx
Labels: methods

#5187 CL-3815: Add comment count on both internal and public tabs
  front/app/api/comments/useMarkCommentForDeletion.ts
  front/app/api/ideas/__mocks__/useIdeaById.ts
  front/app/api/ideas/__mocks__/useIdeaBySlug.ts
  front/app/api/ideas/types.ts
  front/app/api/ideas/useIdeas.test.ts
  front/app/api/initiatives/types.ts
  front/app/api/initiatives/useUpdateInitiative.test.ts
  front/app/api/internal_comments/useMarkInternalCommentForDeletion.ts
  front/app/components/PostShowComponents/Comments/ChildCommentForm.tsx
  front/app/components/PostShowComponents/Comments/ParentCommentForm.tsx
  front/app/components/PostShowComponents/Comments/PublicComments.tsx
  front/app/components/PostShowComponents/Comments/index.tsx
  front/app/components/admin/InternalComments/InternalChildCommentForm.tsx
  front/app/components/admin/InternalComments/index.tsx
Labels: structure

#5046 CL-3585 - Show access permissions for surveys even if posting disabled
  back/app/models/permission.rb
  back/lib/participation_method/base.rb
  back/lib/participation_method/native_survey.rb
  back/spec/lib/participation_method/budgeting_spec.rb
  back/spec/lib/participation_method/ideation_spec.rb
  back/spec/lib/participation_method/information_spec.rb
  back/spec/lib/participation_method/native_survey_spec.rb
  back/spec/lib/participation_method/none_spec.rb
  back/spec/lib/participation_method/poll_spec.rb
  back/spec/lib/participation_method/survey_spec.rb
  back/spec/lib/participation_method/volunteering_spec.rb
  back/spec/models/permission_spec.rb
Labels: methods

#5202 CL-3790 - Exclude surveys from analytics stats on dashboard
  back/db/migrate/20230620114801_analytics_posts_exclude_surveys.analytics.rb
  back/db/schema.rb
  back/db/views/analytics_fact_posts_v05.sql
  back/engines/commercial/analytics/db/migrate/20230620121811_analytics_posts_exclude_surveys.rb
  back/engines/commercial/analytics/db/views/analytics_fact_posts_v05.sql
  back/engines/commercial/analytics/spec/acceptance/analytics_posts_spec.rb
Labels: methods

#5184 CL-3745 - Rename budgeting permissions and action_descriptors to voting
  back/app/models/concerns/participation_context.rb
  back/app/models/permission.rb
  back/app/policies/basket_policy.rb
  back/app/serializers/web_api/v1/idea_serializer.rb
  back/app/services/participants_service.rb
  back/app/services/participation_context_service.rb
  back/config/tenant_templates/e2etests_template.yml
  back/db/migrate/20230616134441_change_budgeting_permission.rb
  back/db/schema.rb
  back/engines/commercial/granular_permissions/spec/policies/basket_policy_spec.rb
  back/engines/commercial/granular_permissions/spec/services/participation_context_service_spec.rb
  back/engines/commercial/multi_tenancy/db/seeds/baskets.rb
  back/engines/commercial/smart_groups/app/lib/smart_groups/rules/participated_in_project.rb
  back/engines/commercial/smart_groups/config/locales/en.yml
  back/engines/commercial/smart_groups/spec/fixtures/locales/en.yml
  back/engines/commercial/smart_groups/spec/rules/participated_in_project_spec.rb
  back/engines/commercial/verification/spec/services/participation_context_service_spec.rb
  back/spec/acceptance/idea_comments_spec.rb
  back/spec/acceptance/ideas_spec.rb
  back/spec/services/participants_service_spec.rb
  back/spec/services/participation_context_service_spec.rb
  front/app/api/ideas/__mocks__/useIdeaById.ts
  front/app/api/ideas/__mocks__/useIdeaBySlug.ts
  front/app/api/ideas/types.ts
  front/app/api/ideas/useIdeas.test.ts
  front/app/components/AssignBudgetControl/index.tsx
  front/app/modules/commercial/granular_permissions/admin/containers/Granular/utils.tsx
  front/app/services/actionPermissions.ts
  front/cypress/e2e/admin/projects/edit_project_timeline.cy.ts
Labels: methods

#5192 Cl 3845 fe prep for notifications linking
  front/app/components/InitiativesMap/InitiativePreview.tsx
  front/app/components/PostShowComponents/Body.tsx
  front/app/components/admin/PostManager/components/IdeaPreviewIndex.tsx
  front/app/components/admin/PostManager/components/InitiativePreviewIndex.tsx
  front/app/components/admin/PostManager/components/LazyPostPreview/Idea/IdeaContent.tsx
  front/app/components/admin/PostManager/components/LazyPostPreview/Idea/LazyAdminIdeaEdit.tsx
  front/app/components/admin/PostManager/components/LazyPostPreview/Idea/LazyIdeaContent.ts
  front/app/components/admin/PostManager/components/LazyPostPreview/Initiative/LazyInitiativeContent.ts
  front/app/components/admin/PostManager/components/LazyPostPreview/Initiative/LazyInitiativeEdit.ts
  front/app/components/admin/PostManager/components/LazyPostPreview/PostPreview.tsx
  front/app/components/admin/PostManager/components/LazyPostPreview/index.tsx
  front/app/components/admin/PostManager/components/PostPreview/Idea/AdminIdeaContent.tsx
  front/app/components/admin/PostManager/components/PostPreview/Idea/AdminIdeaEdit.tsx
  front/app/components/admin/PostManager/components/PostPreview/Idea/FeedbackSettings.tsx
  front/app/components/admin/PostManager/components/PostPreview/Idea/IdeaPostPreview.tsx
  front/app/components/admin/PostManager/components/PostPreview/Idea/ReactionPreview.tsx
  front/app/components/admin/PostManager/components/PostPreview/Initiative/AdminInitiativeContent.tsx
  front/app/components/admin/PostManager/components/PostPreview/Initiative/AdminInitiativeEdit.tsx
  front/app/components/admin/PostManager/components/PostPreview/Initiative/FeedbackSettings.tsx
  front/app/components/admin/PostManager/components/PostPreview/Initiative/InitiativePostPreview.tsx
  front/app/components/admin/PostManager/components/PostPreview/index.tsx
  front/app/components/admin/PostManager/components/PostPreview/messages.ts
  front/app/components/admin/PostManager/index.tsx
  front/app/containers/Admin/ideas/routes.tsx
  front/app/containers/Admin/initiatives/routes.tsx
  front/app/containers/Admin/projects/AdminProjectIdeaPreviewIndex.tsx
  front/app/containers/Admin/projects/routes.tsx
  front/app/containers/IdeasShow/index.tsx
  front/app/containers/InitiativesEditPage/InitiativesEditFormWrapper.tsx
  front/app/containers/InitiativesEditPage/index.tsx
  front/app/containers/InitiativesShow/index.tsx
  front/app/modules/commercial/machine_translations/citizen/components/IdeasShowTranslateButton.tsx
  front/app/resources/GetIdeaById.tsx
  front/app/utils/moduleUtils.tsx
Labels: structure

#5214 Revert "Revert "[CL-3694] Custom from email setting""
  back/app/mailers/application_mailer.rb
  back/config/schemas/settings.schema.json.erb
Labels: structure

#5216 No ticket - fix custom from address
  back/app/mailers/application_mailer.rb
Labels: structure

#5210 CL-3818: Add notifications for internal comments
  front/app/api/notifications/types.ts
  front/app/containers/MainHeader/NotificationMenu/components/InternalCommentNotification/index.tsx
  front/app/containers/MainHeader/NotificationMenu/components/Notification/index.tsx
  front/app/containers/MainHeader/NotificationMenu/messages.ts
  front/app/translations/en.json
Labels: structure

#5170 CL-3830 Posting inputs
  back/app/services/participation_context_service.rb
  back/lib/participation_method/base.rb
  back/lib/participation_method/ideation.rb
  back/lib/participation_method/native_survey.rb
  back/lib/participation_method/voting.rb
  back/spec/lib/participation_method/ideation_spec.rb
  back/spec/lib/participation_method/information_spec.rb
  back/spec/lib/participation_method/native_survey_spec.rb
  back/spec/lib/participation_method/none_spec.rb
  back/spec/lib/participation_method/poll_spec.rb
  back/spec/lib/participation_method/survey_spec.rb
  back/spec/lib/participation_method/volunteering_spec.rb
  back/spec/lib/participation_method/voting_spec.rb
  back/spec/services/participation_context_service_spec.rb
Labels: methods

#5171 [CL-3823] Add new notifications for internal commenting
  back/app/models/notifications/internal_comments/internal_comment_on_idea_assigned_to_you.rb
  back/app/models/notifications/internal_comments/internal_comment_on_idea_you_commented_internally_on.rb
  back/app/models/notifications/internal_comments/internal_comment_on_idea_you_moderate.rb
  back/app/models/notifications/internal_comments/internal_comment_on_initiative_assigned_to_you.rb
  back/app/models/notifications/internal_comments/internal_comment_on_initiative_you_commented_internally_on.rb
  back/app/models/notifications/internal_comments/internal_comment_on_unassigned_initiative.rb
  back/app/models/notifications/internal_comments/internal_comment_on_unassigned_unmoderated_idea.rb
  back/app/models/notifications/internal_comments/internal_comment_on_your_internal_comment.rb
  back/app/models/notifications/internal_comments/mention_in_internal_comment.rb
  back/app/serializers/web_api/v1/notifications/internal_comment_notification_serializer.rb
  back/app/serializers/web_api/v1/notifications/internal_comment_on_idea_assigned_to_you_serializer.rb
  back/app/serializers/web_api/v1/notifications/internal_comment_on_idea_you_commented_internally_on_serializer.rb
  back/app/serializers/web_api/v1/notifications/internal_comment_on_idea_you_moderate_serializer.rb
  back/app/serializers/web_api/v1/notifications/internal_comment_on_initiative_assigned_to_you_serializer.rb
  back/app/serializers/web_api/v1/notifications/internal_comment_on_initiative_you_commented_internally_on_serializer.rb
  back/app/serializers/web_api/v1/notifications/internal_comment_on_unassigned_initiative_serializer.rb
  back/app/serializers/web_api/v1/notifications/internal_comment_on_unassigned_unmoderated_idea_serializer.rb
  back/app/serializers/web_api/v1/notifications/internal_comment_on_your_internal_comment_serializer.rb
  back/app/serializers/web_api/v1/notifications/mention_in_internal_comment_serializer.rb
  back/app/services/mention_service.rb
  back/app/services/notification_service.rb
  back/app/services/notifications/internal_comments/base_notification_builder.rb
  back/app/services/notifications/internal_comments/internal_comment_on_idea_assigned_to_you_builder.rb
  back/app/services/notifications/internal_comments/internal_comment_on_idea_you_commented_internally_on_builder.rb
  back/app/services/notifications/internal_comments/internal_comment_on_idea_you_moderate_builder.rb
  back/app/services/notifications/internal_comments/internal_comment_on_initiative_assigned_to_you_builder.rb
  back/app/services/notifications/internal_comments/internal_comment_on_initiative_you_commented_internally_on_builder.rb
  back/app/services/notifications/internal_comments/internal_comment_on_unassigned_initiative_builder.rb
  back/app/services/notifications/internal_comments/internal_comment_on_unassigned_unmoderated_idea_builder.rb
  back/app/services/notifications/internal_comments/internal_comment_on_your_internal_comment_builder.rb
  back/app/services/notifications/internal_comments/mention_in_internal_comment_builder.rb
  back/spec/factories/internal_comments.rb
  back/spec/factories/notifications.rb
  back/spec/models/notifications/internal_comments/internal_comment_on_idea_assigned_to_you_spec.rb
  back/spec/models/notifications/internal_comments/internal_comment_on_idea_you_commented_internally_on_spec.rb
  back/spec/models/notifications/internal_comments/internal_comment_on_idea_you_moderate_spec.rb
  back/spec/models/notifications/internal_comments/internal_comment_on_initiative_assigned_to_you_spec.rb
  back/spec/models/notifications/internal_comments/internal_comment_on_initiative_you_commented_internally_on_spec.rb
  back/spec/models/notifications/internal_comments/internal_comment_on_unassigned_initiative_spec.rb
  back/spec/models/notifications/internal_comments/internal_comment_on_unassigned_unmoderated_idea_spec.rb
  back/spec/models/notifications/internal_comments/internal_comment_on_your_internal_comment_spec.rb
  back/spec/models/notifications/internal_comments/mention_in_internal_comment_spec.rb
  back/spec/models/notifications/mention_in_comment_spec.rb
Labels: structure

#5228 [CL-3823] Serialize internal_comment_id in responses
  back/app/serializers/web_api/v1/notifications/internal_comment_notification_serializer.rb
Labels: structure

#5230 CL-2964 - Fix Matomo visit data import when date dimensions do not exist
  back/engines/commercial/analytics/app/services/analytics/matomo_data_importer.rb
  back/engines/commercial/analytics/app/services/analytics/populate_dimensions_service.rb
  back/engines/commercial/analytics/spec/services/analytics/matomo_data_importer_spec.rb
Labels: methods

#5234 [CL-3694] Use raw_from_email in ManualCampaignMailer
  back/app/mailers/application_mailer.rb
  back/engines/free/email_campaigns/app/mailers/email_campaigns/manual_campaign_mailer.rb
Labels: structure

#5239 CL-3744 - Update budgeted_in smart groups to voted_in
  back/engines/commercial/multi_tenancy/lib/tasks/core/migrate_budgeting_smart_groups.rake
  back/engines/commercial/public_api/app/serializers/public_api/v2/phase_serializer.rb
  back/engines/commercial/public_api/app/serializers/public_api/v2/project_serializer.rb
  front/app/modules/commercial/smart_groups/components/UserFilterConditions/PredicateSelector.tsx
  front/app/modules/commercial/smart_groups/components/UserFilterConditions/messages.ts
  front/app/modules/commercial/smart_groups/components/UserFilterConditions/rules.ts
  front/app/translations/ar-MA.json
  front/app/translations/ar-SA.json
  front/app/translations/ca-ES.json
  front/app/translations/da-DK.json
  front/app/translations/de-DE.json
  front/app/translations/el-GR.json
  front/app/translations/en-CA.json
  front/app/translations/en-GB.json
  front/app/translations/en.json
  front/app/translations/es-CL.json
  front/app/translations/es-ES.json
  front/app/translations/fr-BE.json
  front/app/translations/fr-FR.json
  front/app/translations/hr-HR.json
  front/app/translations/hu-HU.json
  front/app/translations/it-IT.json
  front/app/translations/kl-GL.json
  front/app/translations/lb-LU.json
  front/app/translations/lv-LV.json
  front/app/translations/mi.json
  front/app/translations/nb-NO.json
  front/app/translations/nl-BE.json
  front/app/translations/nl-NL.json
  front/app/translations/pl-PL.json
  front/app/translations/pt-BR.json
  front/app/translations/ro-RO.json
  front/app/translations/sr-Latn.json
  front/app/translations/sr-SP.json
  front/app/translations/sv-SE.json
  front/app/translations/tr-TR.json
Labels: methods

#5182 CL-3684 Folder participation
  back/app/controllers/web_api/v1/avatars_controller.rb
  back/app/serializers/web_api/v1/folder_serializer.rb
  back/app/services/avatars_service.rb
  back/app/services/participants_service.rb
  back/spec/acceptance/avatars_spec.rb
  back/spec/acceptance/project_folders_spec.rb
  back/spec/services/avatars_service_spec.rb
  back/spec/services/participants_service_spec.rb
  front/app/api/project_folders/types.ts
  front/app/components/ProjectAndFolderCards/components/ProjectFolderCard/index.tsx
  front/app/components/ProjectAndFolderCards/components/ProjectFolderCard/messages.ts
  front/app/translations/en.json
Labels: methods

#5191 CL-3832 Ordering inputs
  back/app/controllers/web_api/v1/events_controller.rb
  back/app/controllers/web_api/v1/ideas_controller.rb
  back/app/controllers/web_api/v1/initiatives_controller.rb
  back/app/controllers/web_api/v1/stats_ideas_controller.rb
  back/app/finders/activities_finder.rb
  back/app/finders/events_finder.rb
  back/app/finders/ideas_finder.rb
  back/app/finders/initiatives_finder.rb
  back/app/models/concerns/participation_context.rb
  back/app/models/concerns/post.rb
  back/app/models/idea.rb
  back/app/services/random_ordering_service.rb
  back/app/services/sort_by_params_service.rb
  back/db/migrate/20230622132238_fix_ideas_order.rb
  back/db/schema.rb
  back/engines/commercial/insights/app/services/insights/topic_import_service.rb
  back/lib/finder/base.rb
  back/lib/finder/sortable.rb
  back/lib/participation_method/base.rb
  back/lib/participation_method/ideation.rb
  back/lib/participation_method/voting.rb
  back/spec/acceptance/initiatives_spec.rb
  back/spec/acceptance/phases_spec.rb
  back/spec/acceptance/projects_spec.rb
  back/spec/finders/ideas_finder_spec.rb
  back/spec/finders/initiatives_finder_spec.rb
  back/spec/lib/participation_method/ideation_spec.rb
  back/spec/lib/participation_method/information_spec.rb
  back/spec/lib/participation_method/native_survey_spec.rb
  back/spec/lib/participation_method/none_spec.rb
  back/spec/lib/participation_method/poll_spec.rb
  back/spec/lib/participation_method/survey_spec.rb
  back/spec/lib/participation_method/volunteering_spec.rb
  back/spec/lib/participation_method/voting_spec.rb
  back/spec/models/phase_spec.rb
  back/spec/models/project_spec.rb
  back/spec/services/sort_by_params_service_spec.rb
Labels: methods

#5229 CL-3871: link to specific comment
  front/app/api/notifications/types.ts
  front/app/components/admin/InternalComments/InternalComment/index.tsx
  front/app/components/admin/InternalComments/InternalParentComment.tsx
  front/app/containers/MainHeader/NotificationMenu/components/InternalCommentNotification/index.tsx
Labels: structure

#5226 CL-3750 Baskets api with votes
  back/app/controllers/web_api/v1/baskets_controller.rb
  back/app/models/basket.rb
  back/app/models/baskets_idea.rb
  back/app/models/notifications/internal_comments/internal_comment_on_idea_assigned_to_you.rb
  back/app/models/notifications/internal_comments/internal_comment_on_idea_you_commented_internally_on.rb
  back/app/models/notifications/internal_comments/internal_comment_on_idea_you_moderate.rb
  back/app/models/notifications/internal_comments/internal_comment_on_initiative_assigned_to_you.rb
  back/app/models/notifications/internal_comments/internal_comment_on_initiative_you_commented_internally_on.rb
  back/app/models/notifications/internal_comments/internal_comment_on_unassigned_initiative.rb
  back/app/models/notifications/internal_comments/internal_comment_on_unassigned_unmoderated_idea.rb
  back/app/models/notifications/internal_comments/internal_comment_on_your_internal_comment.rb
  back/app/models/notifications/internal_comments/mention_in_internal_comment.rb
  back/app/serializers/web_api/v1/basket_serializer.rb
  back/app/serializers/web_api/v1/baskets_idea_serializer.rb
  back/db/migrate/20230623085057_add_votes_to_baskets_ideas.rb
  back/db/schema.rb
  back/spec/acceptance/baskets_spec.rb
Labels: methods

#5242 [CL-3828] Voting participation method changes
  back/lib/participation_method/voting.rb
  back/spec/lib/participation_method/voting_spec.rb
Labels: methods

#5225 CL-3743 - Add baskets count to project, phase & ideas_phase
  back/app/controllers/web_api/v1/ideas_controller.rb
  back/app/models/basket.rb
  back/app/models/ideas_phase.rb
  back/app/models/phase.rb
  back/app/models/project.rb
  back/app/serializers/web_api/v1/idea_serializer.rb
  back/app/serializers/web_api/v1/ideas_phase_serializer.rb
  back/app/serializers/web_api/v1/participation_context_serializer.rb
  back/app/services/side_fx_basket_service.rb
  back/db/migrate/20230621144312_add_basket_count_to_context.rb
  back/db/schema.rb
  back/spec/acceptance/ideas_spec.rb
  back/spec/acceptance/phases_spec.rb
  back/spec/acceptance/projects_spec.rb
  back/spec/factories/projects.rb
  back/spec/services/side_fx_basket_spec.rb
Labels: methods

#5258 CL-3842 - Voting action descriptor on projects
  back/app/serializers/web_api/v1/project_serializer.rb
  back/app/services/participation_context_service.rb
  back/engines/commercial/granular_permissions/spec/services/participation_context_service_spec.rb
  back/spec/acceptance/projects_spec.rb
Labels: methods

#5257 CL-3876 - Additional voting methods
  back/app/models/concerns/participation_context.rb
  back/config/locales/en.yml
  back/lib/factory.rb
  back/lib/participation_method/voting.rb
  back/lib/voting_method/multiple_voting.rb
  back/lib/voting_method/single_voting.rb
  back/spec/acceptance/phases_spec.rb
  back/spec/acceptance/projects_spec.rb
  back/spec/factories/projects.rb
  back/spec/fixtures/locales/en.yml
  back/spec/lib/participation_method/voting_spec.rb
  back/spec/lib/voting_method/multiple_voting_spec.rb
  back/spec/lib/voting_method/single_voting_spec.rb
Labels: methods

#5252 CL-3754 Basket submission
  back/app/controllers/web_api/v1/baskets_controller.rb
  back/app/models/basket.rb
  back/app/models/baskets_idea.rb
  back/app/models/concerns/participation_context.rb
  back/app/models/project.rb
  back/app/serializers/web_api/v1/basket_serializer.rb
  back/app/services/json_forms_service.rb
  back/lib/participation_method/base.rb
  back/lib/participation_method/ideation.rb
  back/lib/participation_method/voting.rb
  back/lib/voting_method/base.rb
  back/lib/voting_method/budgeting.rb
  back/lib/voting_method/multiple_voting.rb
  back/lib/voting_method/single_voting.rb
  back/spec/acceptance/baskets_spec.rb
  back/spec/factories/baskets_ideas.rb
  back/spec/lib/participation_method/ideation_spec.rb
  back/spec/lib/participation_method/information_spec.rb
  back/spec/lib/participation_method/native_survey_spec.rb
  back/spec/lib/participation_method/none_spec.rb
  back/spec/lib/participation_method/poll_spec.rb
  back/spec/lib/participation_method/survey_spec.rb
  back/spec/lib/participation_method/volunteering_spec.rb
  back/spec/lib/participation_method/voting_spec.rb
  back/spec/lib/voting_method/budgeting_spec.rb
  back/spec/lib/voting_method/multiple_voting_spec.rb
  back/spec/lib/voting_method/single_voting_spec.rb
  back/spec/models/basket_spec.rb
Labels: methods

#5265 CL-3884 - Remove reaction config
  front/app/containers/Admin/projects/project/participationContext/components/inputs/IdeationInputs/index.tsx
Labels: methods

#5250 CL-3878: Fix cursor jumping to the end
  front/app/components/PostShowComponents/Comments/ChildCommentForm.tsx
  front/app/components/PostShowComponents/Comments/Comment/CommentBody.tsx
  front/app/components/PostShowComponents/Comments/utils.ts
  front/app/components/admin/InternalComments/InternalChildCommentForm.tsx
  front/app/components/admin/InternalComments/InternalComment/InternalCommentBody.tsx
Labels: structure

#5277 [CL-3894] Disable similar_ideas in localhost seeds & create_tenant task
  back/engines/commercial/multi_tenancy/db/seeds/tenants.rb
  back/engines/commercial/multi_tenancy/lib/tasks/core/create_tenant.rake
Labels: structure, 10%-project

#5275 CL-3890 - Users thrown out of sign-up flow when content builder used for description
  back/app/serializers/web_api/v1/project_serializer.rb
  back/engines/commercial/content_builder/app/models/content_builder/patches/project.rb
  back/engines/commercial/content_builder/app/serializers/content_builder/extensions/web_api/v1/project_serializer.rb
  back/engines/commercial/content_builder/spec/models/content_builder/patches/project_spec.rb
  front/app/api/projects/__mocks__/useProjects.ts
  front/app/api/projects/types.ts
  front/app/modules/commercial/project_description_builder/hooks/useProjectDescriptionBuilderLayout.test.ts
  front/app/modules/commercial/project_description_builder/hooks/useProjectDescriptionBuilderLayout.ts
Labels: methods
