Repository CitizenLabDotCo/citizenlab, pull requests merged in 2023-07, with the labels that each got.

#5298 [CL-3898] Use without_campaign_names query param to filter out consents
  back/engines/free/email_campaigns/app/controllers/email_campaigns/web_api/v1/consents_controller.rb
  back/engines/free/email_campaigns/spec/acceptance/consents_spec.rb
Labels: structure

#5299 CL-3834 - Votes count for input manager and results
  back/app/models/idea.rb
  back/app/models/ideas_phase.rb
  back/app/models/phase.rb
  back/app/models/project.rb
  back/app/serializers/web_api/v1/idea_serializer.rb
  back/app/serializers/web_api/v1/ideas_phase_serializer.rb
  back/app/serializers/web_api/v1/participation_context_serializer.rb
  back/app/services/side_fx_basket_service.rb
  back/db/migrate/20230703112343_add_votes_count_to_context.rb
  back/db/schema.rb
  back/spec/services/side_fx_basket_spec.rb
Labels: methods

#5292 CL-3895: Feature flag internal comments emails and notifications
  front/app/api/campaign_consents/types.ts
  front/app/api/campaign_consents/useCampaignConsents.ts
  front/app/api/campaigns/types.ts
  front/app/api/notifications/types.ts
  front/app/components/CampaignConsentForm/index.tsx
  front/app/containers/Admin/messaging/AutomatedEmails/index.tsx
Labels: structure

#5314 Cl 3882 add username email split for konveio method
  front/app/components/ErrorBoundary/index.tsx
  front/app/components/admin/PostManager/components/PostPreview/Idea/FeedbackSettings.tsx
  front/app/components/admin/PostManager/components/PostPreview/Initiative/FeedbackSettings.tsx
  front/app/components/admin/SeatBasedBilling/ChangeSeatModal/index.tsx
  front/app/components/admin/UserBlockModals/BlockUser.tsx
  front/app/components/admin/UserBlockModals/UnblockUser.tsx
  front/app/containers/Admin/invitations/all/TableRow.tsx
  front/app/containers/Admin/messaging/CustomEmails/CampaignForm/index.tsx
  front/app/containers/Admin/messaging/CustomEmails/Show/RecipientsTable.tsx
  front/app/containers/Admin/messaging/CustomEmails/Show/index.tsx
  front/app/containers/Admin/projectFolders/containers/permissions/index.tsx
  front/app/containers/Admin/reporting/components/ReportBuilder/Widgets/AboutReportWidget/index.tsx
  front/app/containers/Admin/sideBar/UserMenu.tsx
  front/app/containers/Admin/users/UserTableRow.tsx
  front/app/containers/IdeasShow/IdeaMeta.tsx
  front/app/containers/InitiativesShow/InitiativeMeta.tsx
  front/app/containers/ProjectsShowPage/shared/document_annotation/Konveio.test.tsx
  front/app/containers/ProjectsShowPage/shared/document_annotation/Konveio.tsx
  front/app/containers/ProjectsShowPage/shared/document_annotation/index.tsx
  front/app/containers/UsersShowPage/UserHeader.tsx
  front/app/modules/commercial/idea_assignment/admin/components/AssigneeFilter.tsx
  front/app/modules/commercial/idea_assignment/admin/components/AssigneeSelector.tsx
  front/app/modules/commercial/intercom/index.ts
  front/app/modules/commercial/posthog_integration/index.ts
  front/app/modules/commercial/satismeter/index.ts
  front/app/utils/textUtils.ts
Labels: structure

#5294 CL-3843 - User custom field ordering
  back/engines/commercial/idea_custom_fields/app/controllers/idea_custom_fields/web_api/v1/admin/idea_custom_fields_controller.rb
  back/engines/commercial/multi_tenancy/lib/tasks/core/fix_user_custom_field_order.rake
  back/engines/commercial/multi_tenancy/spec/tasks/fix_user_custom_field_order_task_spec.rb
  back/engines/commercial/user_custom_fields/spec/acceptance/user_custom_fields_spec.rb
Labels: methods

#5312 CL-3833 - Deleting users, deletes baskets
  back/app/models/basket.rb
  back/app/models/concerns/participation_context.rb
  back/app/models/user.rb
  back/app/services/side_fx_basket_service.rb
  back/app/services/timeline_service.rb
  back/db/migrate/20230703175732_update_basket_user_foreign_key.rb
  back/db/schema.rb
  back/spec/models/basket_spec.rb
  back/spec/services/side_fx_basket_spec.rb
Labels: methods

#5115 CL-3774 remove pt pt
  front/app/containers/App/constants.js
  front/app/containers/App/constants.ts
Labels: structure

#5329 Remove unused description_multiloc of areas
  front/app/api/areas/__mocks__/useAreas.ts
  front/app/api/areas/types.ts
  front/app/api/areas/useAddArea.test.ts
  front/app/containers/Admin/settings/areas/AreaForm/index.tsx
  front/app/containers/Admin/settings/areas/Edit/index.tsx
Labels: structure

#5342 Don't show slug input field when creating a new custom page
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/New/NewCustomPage.test.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/New/NewCustomPage.tsx
Labels: structure

#5349 Cl 3913 convert homepage settings service to react query
  front/app/api/app_configuration/types.ts
  front/app/api/custom_pages/types.ts
  front/app/api/home_page/__mocks__/useHomepageSettings.ts
  front/app/api/home_page/keys.ts
  front/app/api/home_page/types.ts
  front/app/api/home_page/useHomepageSettings.test.ts
  front/app/api/home_page/useHomepageSettings.ts
  front/app/api/home_page/useUpdateHomepageSettings.test.ts
  front/app/api/home_page/useUpdateHomepageSettings.ts
  front/app/components/CityLogoSection/index.tsx
  front/app/components/LandingPages/admin/CTARadioButtons.tsx
  front/app/containers/Admin/pagesAndMenu/EditHomepage/BottomInfoSection/index.tsx
  front/app/containers/Admin/pagesAndMenu/EditHomepage/HeroBanner/index.tsx
  front/app/containers/Admin/pagesAndMenu/EditHomepage/TopInfoSection/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/EditHomepage/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericBottomInfoSection/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/BannerHeaderFields.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/BannerImageFields/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/CTASettings.test.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/CTASettings.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/HeaderImageDropzone.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericHeroBannerForm/LayoutSettingField/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/GenericTopInfoSection/index.tsx
  front/app/containers/App/Meta.tsx
  front/app/containers/HomePage/Footer.tsx
  front/app/containers/HomePage/HomePage.test.tsx
  front/app/containers/HomePage/SignedInHeader/CTA.tsx
  front/app/containers/HomePage/SignedInHeader/FallbackStep.tsx
  front/app/containers/HomePage/SignedInHeader/HeaderImage.test.tsx
  front/app/containers/HomePage/SignedInHeader/HeaderImage.tsx
  front/app/containers/HomePage/SignedOutHeader/CTA.tsx
  front/app/containers/HomePage/SignedOutHeader/FixedRatioLayout.tsx
  front/app/containers/HomePage/SignedOutHeader/FullWidthBannerLayout.tsx
  front/app/containers/HomePage/SignedOutHeader/HeaderContent.tsx
  front/app/containers/HomePage/SignedOutHeader/SignedOutHeader.test.tsx
  front/app/containers/HomePage/SignedOutHeader/TwoColumnLayout.tsx
  front/app/containers/HomePage/SignedOutHeader/TwoRowLayout.tsx
  front/app/containers/HomePage/SignedOutHeader/index.tsx
  front/app/containers/HomePage/index.tsx
  front/app/hooks/useHomepageSettings.ts
  front/app/modules/commercial/events_widget/hooks/useHomepageSettingsFeatureFlag.test.ts
  front/app/modules/commercial/events_widget/hooks/useHomepageSettingsFeatureFlag.ts
  front/app/modules/commercial/events_widget/index.tsx
  front/app/modules/commercial/events_widget/services/homepageSettings.ts
  front/cypress/e2e/admin/pages_and_menu/update_homepage_hero_banner_content.cy.ts
Labels: structure

#5370 Remove wrongly positioned button state checks from E2E
  front/cypress/e2e/admin/pages_and_menu/update_homepage_hero_banner_content.cy.ts
Labels: structure

#5365 CL-3920 Validate max votes per idea
  back/.rubocop.yml
  back/app/models/basket.rb
  back/spec/acceptance/baskets_ideas_spec.rb
  back/spec/acceptance/baskets_spec.rb
  back/spec/factories/phases.rb
  back/spec/lib/voting_method/single_voting_spec.rb
  back/spec/models/basket_spec.rb
  back/spec/models/baskets_idea_spec.rb
Labels: methods

#5374 CL-3925 - Minor changes to baskets_idea upsert endpoint
  back/app/controllers/web_api/v1/baskets_ideas_controller.rb
  back/app/policies/basket_policy.rb
  back/spec/acceptance/baskets_ideas_spec.rb
  back/spec/factories/phases.rb
Labels: methods

#5352 [CL-3874] Toggle project phase campaign at phase level
  back/app/controllers/web_api/v1/phases_controller.rb
  back/app/models/phase.rb
  back/app/serializers/web_api/v1/phase_serializer.rb
  back/app/services/project_copy_service.rb
  back/config/tenant_templates/e2etests_template.yml
  back/db/migrate/20230710143815_add_campaigns_settings_to_phases.rb
  back/db/schema.rb
  back/engines/commercial/multi_tenancy/app/services/multi_tenancy/templates/serializers/phase.rb
  back/engines/commercial/multi_tenancy/db/seeds/projects.rb
  back/engines/commercial/public_api/app/models/public_api/api_client.rb
  back/engines/free/email_campaigns/app/models/email_campaigns/campaigns/project_phase_started.rb
  back/engines/free/email_campaigns/app/services/email_campaigns/side_fx_campaign_service.rb
  back/engines/free/email_campaigns/spec/acceptance/campaigns_spec.rb
  back/engines/free/email_campaigns/spec/models/email_campaigns/campaigns/project_phase_started_spec.rb
  back/lib/utils.rb
  back/spec/acceptance/phases_spec.rb
  back/spec/factories/phases.rb
  back/spec/models/phase_spec.rb
Labels: structure

#5380 [CL-3874] Refactor after_update to use new method
  back/engines/free/email_campaigns/app/services/email_campaigns/side_fx_campaign_service.rb
Labels: structure

#5359 Cl 3797 BO nav i2: remaining issues
  front/app/components/admin/PageTitle/index.tsx
  front/app/components/admin/PostManager/components/FilterSidebar/FilterSidebarStatuses.tsx
  front/app/components/admin/PostManager/components/FilterSidebar/index.tsx
  front/app/components/admin/PostManager/index.tsx
  front/app/containers/Admin/ideas/all/index.tsx
  front/app/containers/Admin/ideas/index.tsx
  front/app/containers/Admin/ideas/messages.ts
  front/app/containers/Admin/initiatives/index.tsx
  front/app/containers/Admin/initiatives/manage/index.tsx
  front/app/containers/Admin/initiatives/messages.ts
  front/app/containers/Admin/projects/all/index.tsx
  front/app/containers/Admin/sideBar/MenuItem.tsx
  front/app/containers/Admin/sideBar/NotificationsPopup.tsx
  front/app/containers/Admin/sideBar/SupportMenu.tsx
  front/app/containers/Admin/sideBar/UserMenu.tsx
  front/app/containers/Admin/sideBar/index.tsx
  front/app/containers/Admin/sideBar/styles.ts
  front/app/containers/MainHeader/NotificationMenu/components/Notifications.tsx
  front/app/modules/commercial/bulk_idea_import/admin/containers/Import.tsx
  front/app/modules/commercial/insights/admin/containers/Insights/List/InsightsList.tsx
  front/app/translations/admin/ar-MA.json
  front/app/translations/admin/ar-SA.json
  front/app/translations/admin/ca-ES.json
  front/app/translations/admin/da-DK.json
  front/app/translations/admin/de-DE.json
  front/app/translations/admin/el-GR.json
  front/app/translations/admin/en-CA.json
  front/app/translations/admin/en-GB.json
  front/app/translations/admin/en.json
  front/app/translations/admin/es-CL.json
  front/app/translations/admin/es-ES.json
  front/app/translations/admin/fr-BE.json
  front/app/translations/admin/fr-FR.json
  front/app/translations/admin/hr-HR.json
  front/app/translations/admin/hu-HU.json
  front/app/translations/admin/it-IT.json
  front/app/translations/admin/kl-GL.json
  front/app/translations/admin/lb-LU.json
  front/app/translations/admin/lv-LV.json
  front/app/translations/admin/mi.json
  front/app/translations/admin/nb-NO.json
  front/app/translations/admin/nl-BE.json
  front/app/translations/admin/nl-NL.json
  front/app/translations/admin/pl-PL.json
  front/app/translations/admin/pt-BR.json
  front/app/translations/admin/ro-RO.json
  front/app/translations/admin/sr-Latn.json
  front/app/translations/admin/sr-SP.json
  front/app/translations/admin/sv-SE.json
  front/app/translations/admin/tr-TR.json
Labels: waiting for translations, structure

#5382 [CL-3874] Temporary fix
  back/app/models/phase.rb
Labels: structure

#5274 CL-3831 - Editing & deleting inputs
  back/spec/acceptance/ideas_spec.rb
  back/spec/models/basket_spec.rb
  front/app/containers/Admin/projects/project/messages.ts
  front/app/translations/admin/en.json
Labels: methods

#5371 CL-3760 - Voting input manager changes
  back/app/models/phase.rb
  back/app/services/sort_by_params_service.rb
  back/db/schema.rb
  back/engines/commercial/public_api/app/models/public_api/api_client.rb
  back/spec/acceptance/ideas_spec.rb
  back/spec/services/sort_by_params_service_spec.rb
  front/app/api/ideas/types.ts
  front/app/components/admin/PostManager/components/PostTable/Row/IdeaRow.tsx
  front/app/components/admin/PostManager/components/PostTable/Row/index.tsx
  front/app/components/admin/PostManager/components/PostTable/header/IdeaHeaderRow.tsx
  front/app/components/admin/PostManager/components/PostTable/index.tsx
  front/app/components/admin/PostManager/index.tsx
  front/app/components/admin/PostManager/messages.ts
  front/app/hooks/usePostManagerColumnFilter.ts
  front/app/translations/admin/en.json
Labels: methods

#5377 CL-2884: Convert machine translations module to react query
  front/app/modules/commercial/machine_translations/api/__mocks__/useMachineTranslationByCommentId.ts
  front/app/modules/commercial/machine_translations/api/keys.ts
  front/app/modules/commercial/machine_translations/api/types.ts
  front/app/modules/commercial/machine_translations/api/useMachineTranslationByCommentId.test.ts
  front/app/modules/commercial/machine_translations/api/useMachineTranslationByCommentId.ts
  front/app/modules/commercial/machine_translations/api/useMachineTranslationByIdeaId.test.ts
  front/app/modules/commercial/machine_translations/api/useMachineTranslationByIdeaId.ts
  front/app/modules/commercial/machine_translations/api/useMachineTranslationByInitiativeId.test.ts
  front/app/modules/commercial/machine_translations/api/useMachineTranslationByInitiativeId.ts
  front/app/modules/commercial/machine_translations/citizen/components/PostShowTranslatedCommentBody.tsx
  front/app/modules/commercial/machine_translations/citizen/components/PostShowTranslatedTitle.tsx
  front/app/modules/commercial/machine_translations/hooks/useTranslation.ts
  front/app/modules/commercial/machine_translations/resources/GetMachineTranslation.tsx
  front/app/modules/commercial/machine_translations/services/machineTranslations.ts
Labels: platform

#5375 CL-3923 Voting terms for all
  back/app/models/concerns/participation_context.rb
  back/app/serializers/web_api/v1/participation_context_serializer.rb
  back/app/serializers/web_api/v1/phase_serializer.rb
  back/app/serializers/web_api/v1/project_serializer.rb
  back/lib/participation_method/voting.rb
  back/lib/voting_method/base.rb
  back/lib/voting_method/multiple_voting.rb
  back/lib/voting_method/single_voting.rb
  back/spec/acceptance/phases_spec.rb
  back/spec/acceptance/projects_spec.rb
  back/spec/fixtures/locales/en.yml
  back/spec/fixtures/locales/fr-FR.yml
  back/spec/fixtures/locales/nl-NL.yml
  back/spec/lib/participation_method/voting_spec.rb
  back/spec/lib/voting_method/budgeting_spec.rb
  back/spec/lib/voting_method/multiple_voting_spec.rb
  back/spec/lib/voting_method/single_voting_spec.rb
  back/spec/models/phase_spec.rb
  back/spec/serializers/web_api/v1/participation_context_serializer_spec.rb
Labels: methods

#5266 [CL-3862] Add internal_comments to tenant serializer
  back/engines/commercial/multi_tenancy/app/services/multi_tenancy/templates/serializers/internal_comment.rb
  back/engines/commercial/multi_tenancy/app/services/multi_tenancy/templates/tenant_serializer.rb
  back/engines/commercial/multi_tenancy/spec/services/multi_tenancy/templates/tenant_serializer_spec.rb
Labels: structure

#5398 CL-3715 - Phase voting counts
  back/app/controllers/web_api/v1/ideas_controller.rb
  back/app/services/sort_by_params_service.rb
  back/spec/acceptance/ideas_spec.rb
  back/spec/factories/ideas_phases.rb
  back/spec/services/sort_by_params_service_spec.rb
Labels: methods

#5403 [CL-3874] Remove temporary fix of project_phase_started phase toggle feature
  back/app/models/phase.rb
Labels: structure

#5356 [CL-3926] Toggle new phase email on phase level
  back/app/models/phase.rb
  front/app/api/phases/__mocks__/usePhases.ts
  front/app/api/phases/types.ts
  front/app/containers/Admin/messaging/AutomatedEmails/CampaignDescription.tsx
  front/app/containers/Admin/messaging/AutomatedEmails/CampaignRow.tsx
  front/app/containers/Admin/messaging/AutomatedEmails/NewProjectPhaseModal/index.tsx
  front/app/containers/Admin/messaging/AutomatedEmails/NewProjectPhaseModal/messages.ts
  front/app/containers/Admin/messaging/AutomatedEmails/index.tsx
  front/app/containers/Admin/messaging/AutomatedEmails/utils.ts
  front/app/containers/Admin/projects/project/timeline/CampaignRow.tsx
  front/app/containers/Admin/projects/project/timeline/edit.tsx
  front/app/containers/Admin/projects/project/timeline/messages.ts
  front/app/containers/Admin/settings/registration/CustomFieldSettings/index.tsx
  front/app/services/__mocks__/phases.ts
  front/app/translations/admin/en.json
Labels: structure

#5408 CL-3715 - Changed xlsx export columns to match input manager voting columns
  back/app/services/xlsx_export/input_sheet_generator.rb
  back/config/locales/en.yml
  back/lib/participation_method/base.rb
  back/lib/participation_method/ideation.rb
  back/lib/participation_method/voting.rb
  back/lib/voting_method/base.rb
  back/lib/voting_method/budgeting.rb
  back/lib/voting_method/multiple_voting.rb
  back/lib/voting_method/single_voting.rb
  back/spec/acceptance/projects_spec.rb
  back/spec/fixtures/locales/en.yml
  back/spec/lib/participation_method/ideation_spec.rb
  back/spec/lib/participation_method/information_spec.rb
  back/spec/lib/participation_method/native_survey_spec.rb
  back/spec/lib/participation_method/none_spec.rb
  back/spec/lib/participation_method/poll_spec.rb
  back/spec/lib/participation_method/survey_spec.rb
  back/spec/lib/participation_method/volunteering_spec.rb
  back/spec/lib/participation_method/voting_spec.rb
  back/spec/services/xlsx_export/input_sheet_generator_spec.rb
Labels: methods

#5386 CL-3835 - Include baskets with no users in templates
  back/app/services/project_copy_service.rb
  back/engines/commercial/multi_tenancy/app/services/multi_tenancy/templates/serializers/baskets_idea.rb
  back/engines/commercial/multi_tenancy/app/services/multi_tenancy/templates/serializers/idea.rb
  back/engines/commercial/multi_tenancy/app/services/multi_tenancy/templates/serializers/ideas_phase.rb
  back/engines/commercial/multi_tenancy/app/services/multi_tenancy/templates/serializers/participation_context.rb
  back/engines/commercial/multi_tenancy/db/seeds/baskets.rb
  back/engines/commercial/multi_tenancy/spec/services/multi_tenancy/templates/tenant_serializer_spec.rb
Labels: methods

#5425 CL-3715 - Voting e2e tests
  front/app/components/ParticipationCTABars/VotingCTABar/index.tsx
  front/app/components/StatusModule/index.tsx
  front/app/components/VoteInputs/multiple/AssignMultipleVotesInput/index.tsx
  front/app/components/VoteInputs/single/AssignSingleVoteButton/index.tsx
  front/app/containers/ProjectsShowPage/continuous/Ideas.tsx
  front/cypress/e2e/budgeting_permissions.cy.ts
  front/cypress/e2e/project_page_ideas.cy.ts
  front/cypress/e2e/project_page_pb.cy.ts
  front/cypress/e2e/project_page_voting_budgeting.cy.ts
  front/cypress/e2e/project_page_voting_mulitple.cy.ts
  front/cypress/e2e/project_page_voting_single.cy.ts
  front/cypress/support/commands.ts
Labels: methods

#5442 [CL-3953] Fix for activities service
  back/app/services/activities_service.rb
  back/spec/services/activities_service_spec.rb
Labels: methods

#5439 Fix test for adding stuff to the map as an admin if phase is not active
  front/app/components/IdeasMap/index.tsx
  front/app/components/IdeasMap/messages.ts
  front/app/translations/en.json
Labels: waiting for translations

#5472 [CL-3956] Bugfix: Permit moderator to index any automated campaigns
  back/engines/free/email_campaigns/app/policies/email_campaigns/campaign_policy.rb
  back/engines/free/email_campaigns/spec/policies/campaign_policy_spec.rb
Labels: structure

#5318 CL-3196 List unassigned ideas
  back/app/finders/initiatives_finder.rb
  back/engines/commercial/analysis/app/models/analysis/tagging.rb
  back/engines/commercial/idea_assignment/app/finders/idea_assignment/extensions/ideas_finder.rb
  back/engines/commercial/idea_assignment/spec/acceptance/ideas_spec.rb
  back/engines/commercial/idea_assignment/spec/factories/assigned_ideas.rb
  back/engines/commercial/idea_assignment/spec/finders/ideas_finder_spec.rb
  back/engines/commercial/idea_assignment/spec/mailers/idea_assigned_to_you_mailer_spec.rb
  back/engines/free/email_campaigns/spec/mailers/assignee_digest_mailer_spec.rb
  back/engines/free/email_campaigns/spec/mailers/initiative_assigned_to_you_mailer_spec.rb
  back/engines/free/email_campaigns/spec/mailers/your_proposed_initiatives_digest_mailer_spec.rb
  back/spec/acceptance/initiatives_spec.rb
  back/spec/factories/initiatives.rb
  back/spec/finders/initiatives_finder_spec.rb
Labels: methods
