Repository CitizenLabDotCo/citizenlab, pull requests merged in 2023-08, with the labels that each got.

#5478 [TAN-58] Initial work for new event page
  front/app/components/PostShowComponents/Comments/PublicComments.tsx
  front/app/components/ReadMoreWrapper/ReadMoreWrapper.tsx
  front/app/containers/App/index.tsx
  front/app/containers/EventsShowPage/components/Container.tsx
  front/app/containers/EventsShowPage/components/DesktopTopBar.tsx
  front/app/containers/EventsShowPage/components/EventDescription.tsx
  front/app/containers/EventsShowPage/components/EventTopBarMobile.tsx
  front/app/containers/EventsShowPage/components/InformationSectionMobile.tsx
  front/app/containers/EventsShowPage/components/MetadataInformation/EventDateStylized/SingleDateStylized.tsx
  front/app/containers/EventsShowPage/components/MetadataInformation/EventDateStylized/index.tsx
  front/app/containers/EventsShowPage/components/MetadataInformation/EventTimeTextual.tsx
  front/app/containers/EventsShowPage/components/MetadataInformation/Location.tsx
  front/app/containers/EventsShowPage/components/MetadataInformation/MetadataInformationStyles.tsx
  front/app/containers/EventsShowPage/components/RightColumnDesktop.tsx
  front/app/containers/EventsShowPage/index.tsx
  front/app/containers/EventsShowPage/styleConstants.ts
  front/app/containers/ProjectsShowPage/shared/header/ProjectInfo.tsx
  front/app/containers/ProjectsShowPage/timeline/PhaseDescription.tsx
  front/app/routes.tsx
  front/app/translations/en.json
  front/app/utils/dateUtils.ts
  front/app/utils/helperUtils.ts
  front/app/utils/messages.ts
  front/cypress/e2e/events/event_show_page.cy.ts
Labels: waiting for translations

#5490 [TAN-89] Add sharing options to event page
  front/app/components/Sharing/SharingButtons/index.tsx
  front/app/components/Sharing/messages.ts
  front/app/containers/EventsShowPage/components/EventSharingButtons/index.tsx
  front/app/containers/EventsShowPage/components/EventSharingButtons/messages.ts
  front/app/containers/EventsShowPage/components/RightColumnDesktop.tsx
  front/app/translations/en.json
Labels: waiting for translations

#5524 [TAN-151] Add cosponsors_initiatives table, model, etc.
  back/app/controllers/web_api/v1/initiatives_controller.rb
  back/app/models/cosponsors_initiative.rb
  back/app/models/initiative.rb
  back/app/serializers/web_api/v1/initiative_serializer.rb
  back/app/services/xlsx_service.rb
  back/db/migrate/20230801141534_create_cosponsors_initiatives.rb
  back/db/schema.rb
  back/engines/commercial/analysis/app/models/analysis/auto_tagging_task.rb
  back/engines/commercial/analysis/app/models/analysis/background_task.rb
  back/engines/commercial/analysis/app/models/analysis/tagging.rb
  back/spec/factories/cosponsors_initiatives.rb
  back/spec/serializers/web_api/v1/initiative_serializer_spec.rb
Labels: proposals, co-sponsors

#5562 [TAN-199] Update cosponsorships when PATCH initiative
  back/app/models/initiative.rb
  back/app/policies/initiative_policy.rb
  back/spec/acceptance/initiatives_spec.rb
  back/spec/models/initiative_spec.rb
Labels: co-sponsors

#5571 TAN-206 Change inititative_statuses colors and initiative_status name
  back/app/models/initiative_status.rb
  back/app/models/notifications/initiative_resubmitted_for_review.rb
  back/app/services/initiative_status_service.rb
  back/app/services/side_fx_initiative_service.rb
  back/config/locales/en.yml
  back/config/tenant_templates/base.yml
  back/config/tenant_templates/e2etests_template.yml
  back/db/migrate/20230718214736_add_two_initiative_statuses.rb
  back/db/migrate/20230718214736_add_two_initiative_statuses_and_update_colors.rb
  back/db/schema.rb
  back/db/seeds/citizenlab.rb
  back/engines/commercial/analysis/app/models/analysis/auto_tagging_task.rb
  back/engines/commercial/analysis/app/models/analysis/background_task.rb
  back/spec/factories/initiative_statuses.rb
  back/spec/models/notifications/initiative_resubmitted_for_review_spec.rb
  back/spec/policies/initiative_status_policy_spec.rb
  back/spec/services/initiative_status_service_spec.rb
  back/spec/services/side_fx_initiative_service_spec.rb
  front/app/api/initiative_statuses/types.ts
  front/app/containers/InitiativesShow/ReactionControl/ChangesRequested.tsx
  front/app/containers/InitiativesShow/ReactionControl/index.tsx
  front/app/containers/InitiativesShow/ReactionControl/messages.ts
  front/app/translations/en.json
Labels: approval

#5575 [TAN-206] Reorder initiative_statuses
  back/config/tenant_templates/base.yml
  back/config/tenant_templates/e2etests_template.yml
  back/db/migrate/20230718214736_add_two_initiative_statuses_and_update_colors_and_ordering.rb
  back/db/seeds/citizenlab.rb
Labels: proposals, approval

#5557 add support for konveio.site
  back/engines/free/document_annotation/app/models/document_annotation/document_annotation_participation_context.rb
Labels: structure

#5578 [TAN-157] Remove unused scope from cosponsors_initiative policy
  back/app/policies/cosponsors_initiative_policy.rb
  back/spec/policies/cosponsors_initiative_policy_spec.rb
Labels: proposals, co-sponsors

#5580 [TAN-209] Add cosponsors_initiatives to tenant template (de)serialization
  back/engines/commercial/multi_tenancy/app/services/multi_tenancy/templates/serializers/cosponsors_initiative.rb
  back/engines/commercial/multi_tenancy/app/services/multi_tenancy/templates/tenant_serializer.rb
  back/engines/commercial/multi_tenancy/spec/services/multi_tenancy/templates/tenant_serializer_spec.rb
Labels: proposals, co-sponsors

#5581 [TAN-210] Include initiative editing_locked in tenant serializer
  back/engines/commercial/multi_tenancy/app/services/multi_tenancy/templates/serializers/initiative.rb
Labels: proposals, approval

#5584 TAN-231 Cosponsor also receives initiative status change notification and mail
  back/app/models/notifications/status_change_of_your_initiative.rb
  back/engines/free/email_campaigns/spec/models/email_campaigns/campaigns/status_change_of_your_initiative_spec.rb
Labels: proposals, co-sponsors

#5586 [TAN-157] Add test of unauthorized PATCH request
  back/spec/acceptance/cosponsors_initiatives_spec.rb
Labels: proposals, co-sponsors

#5471 [TAN-106] Add input for initiative cosponsors
  back/config/schemas/settings.schema.json.erb
  front/app/api/app_configuration/types.ts
  front/app/api/initiatives/types.ts
  front/app/api/initiatives/useUpdateInitiative.test.ts
  front/app/components/InitiativeForm/index.tsx
  front/app/components/InitiativeForm/messages.ts
  front/app/components/UI/MentionsTextArea/index.tsx
  front/app/components/admin/AnonymousPostingToggle/AnonymousPostingToggle.tsx
  front/app/containers/Admin/initiatives/messages.ts
  front/app/containers/Admin/initiatives/settings/Cosponsors.tsx
  front/app/containers/Admin/initiatives/settings/ProposalsFeatureToggle.tsx
  front/app/containers/Admin/initiatives/settings/ReactingLimit.tsx
  front/app/containers/Admin/initiatives/settings/ReactingThreshold.tsx
  front/app/containers/Admin/initiatives/settings/RequireReviewToggle.tsx
  front/app/containers/Admin/initiatives/settings/Thresholds.tsx
  front/app/containers/Admin/initiatives/settings/index.tsx
  front/app/containers/Admin/projects/project/participationContext/components/inputs/IdeationInputs/index.tsx
  front/app/containers/Admin/projects/project/participationContext/components/inputs/NativeSurveyInputs.tsx
  front/app/containers/InitiativesEditPage/InitiativesEditFormWrapper.tsx
  front/app/containers/InitiativesNewPage/InitiativesNewFormWrapper.tsx
  front/app/hooks/useInitiativeCosponsorsRequired.ts
  front/app/translations/admin/ar-MA.json
  front/app/translations/admin/ar-SA.json
  front/app/translations/admin/ca-ES.json
  front/app/translations/admin/da-DK.json
  front/app/translations/admin/de-DE.json
  front/app/translations/admin/el-GR.json
  front/app/translations/admin/en-CA.json
  front/app/translations/admin/en-GB.json
  front/app/translations/admin/en.json
  front/app/translations/admin/es-CL.json
  front/app/translations/admin/es-ES.json
  front/app/translations/admin/fr-BE.json
  front/app/translations/admin/fr-FR.json
  front/app/translations/admin/hr-HR.json
  front/app/translations/admin/hu-HU.json
  front/app/translations/admin/it-IT.json
  front/app/translations/admin/kl-GL.json
  front/app/translations/admin/lb-LU.json
  front/app/translations/admin/lv-LV.json
  front/app/translations/admin/mi.json
  front/app/translations/admin/nb-NO.json
  front/app/translations/admin/nl-BE.json
  front/app/translations/admin/nl-NL.json
  front/app/translations/admin/pl-PL.json
  front/app/translations/admin/pt-BR.json
  front/app/translations/admin/ro-RO.json
  front/app/translations/admin/sr-Latn.json
  front/app/translations/admin/sr-SP.json
  front/app/translations/admin/sv-SE.json
  front/app/translations/admin/tr-TR.json
  front/app/translations/en.json
  front/package-lock.json
  front/package.json
Labels: proposals, co-sponsors

#5596 [TAN-234] Include cosponsor in initiative policy
  back/app/policies/initiative_policy.rb
  back/spec/policies/initiative_policy_spec.rb
Labels: proposals, co-sponsors

#5599 [TAN-157] Rename endpoint to accept_cosponsorship_invite
  back/app/controllers/web_api/v1/initiatives_controller.rb
  back/app/policies/initiative_policy.rb
  back/config/routes.rb
  back/spec/acceptance/initiatives_spec.rb
  back/spec/policies/initiative_policy_spec.rb
Labels: proposals, co-sponsors

#5613 [TAN-157] Return initiative data in reponse to accept_cosponsorship_i…
  back/app/controllers/web_api/v1/initiatives_controller.rb
  back/spec/acceptance/initiatives_spec.rb
Labels: proposals, co-sponsors

#5618 [TAN-222] Add FE for two new cosponsorship notifications
  back/app/serializers/web_api/v1/notifications/cosponsor_of_your_initiative_serializer.rb
  back/app/serializers/web_api/v1/notifications/invitation_to_cosponsor_initiative_serializer.rb
  front/app/api/notifications/types.ts
  front/app/containers/MainHeader/NotificationMenu/components/CosponsorOfYourInitiativeNotification/index.tsx
  front/app/containers/MainHeader/NotificationMenu/components/InvitationToCosponsorInitiativeNotification/index.tsx
  front/app/containers/MainHeader/NotificationMenu/components/Notification/index.tsx
  front/app/containers/MainHeader/NotificationMenu/messages.ts
  front/app/translations/en.json
Labels: proposals, co-sponsors

#5621 [TAN-222] Add two new cosponsorship email campaigns
  back/app/models/cosponsors_initiative.rb
  back/app/models/initiative.rb
  back/app/services/side_fx_initiative_service.rb
  back/engines/free/email_campaigns/app/mailers/email_campaigns/cosponsor_of_your_initiative_mailer.rb
  back/engines/free/email_campaigns/app/mailers/email_campaigns/invitation_to_cosponsor_initiative_mailer.rb
  back/engines/free/email_campaigns/app/models/email_campaigns/campaigns/cosponsor_of_your_initiative.rb
  back/engines/free/email_campaigns/app/models/email_campaigns/campaigns/invitation_to_cosponsor_initiative.rb
  back/engines/free/email_campaigns/app/services/email_campaigns/delivery_service.rb
  back/engines/free/email_campaigns/app/views/email_campaigns/cosponsor_of_your_initiative_mailer/campaign_mail.mjml
  back/engines/free/email_campaigns/app/views/email_campaigns/invitation_to_cosponsor_initiative_mailer/campaign_mail.mjml
  back/engines/free/email_campaigns/app/views/email_campaigns/posts/_post_with_image.mjml
  back/engines/free/email_campaigns/config/locales/en.yml
  back/engines/free/email_campaigns/spec/factories/campaigns.rb
  back/engines/free/email_campaigns/spec/fixtures/locales/mailers.en.yml
  back/engines/free/email_campaigns/spec/mailers/cosponsor_of_your_initiative_mailer_spec.rb
  back/engines/free/email_campaigns/spec/mailers/invitation_to_cosponsor_initiative_mailer_spec.rb
  back/engines/free/email_campaigns/spec/mailers/previews/email_campaigns/cosponsor_of_your_initiative_preview.rb
  back/engines/free/email_campaigns/spec/mailers/previews/email_campaigns/invitation_to_cosponsor_initiative_mailer_preview.rb
  back/spec/acceptance/initiatives_spec.rb
  back/spec/models/initiative_spec.rb
Labels: proposals, co-sponsors

#5626 Hide anonymous posting toggle when cosponsorsing is enabled
  front/app/components/InitiativeForm/index.tsx
Labels: proposals, co-sponsors

#5635 [CL-3983] New rake task to update custom_field_option title_multiloc for specific locale, regardless of existing value
  back/engines/commercial/multi_tenancy/lib/tasks/core/update_custom_field_option.rake
Labels: structure

#5642 [No-ticket] Correct a comment about new rake task
  back/engines/commercial/multi_tenancy/lib/tasks/core/update_custom_field_option.rake
Labels: structure

#5631 [TAN-248] Use new Initiative 'proposed' activity to trigger InitiativePublished campaign
  back/app/services/side_fx_initiative_service.rb
  back/app/services/side_fx_initiative_status_change_service.rb
  back/engines/free/email_campaigns/app/models/email_campaigns/campaigns/initiative_published.rb
  back/spec/acceptance/initiative_status_changes_spec.rb
  back/spec/services/side_fx_initiative_service_spec.rb
  back/spec/services/side_fx_initiative_status_change_service_spec.rb
Labels: proposals, co-sponsors

#5655 [TAN-272] Use InitiativeStatusChange to 'proposed' created_at scope in digest campaigns
  back/app/models/initiative.rb
  back/engines/free/email_campaigns/app/models/email_campaigns/campaigns/admin_digest.rb
  back/engines/free/email_campaigns/app/models/email_campaigns/campaigns/user_digest.rb
  back/engines/free/email_campaigns/spec/models/email_campaigns/campaigns/admin_digest_spec.rb
  back/engines/free/email_campaigns/spec/models/email_campaigns/campaigns/user_digest_spec.rb
Labels: proposals

#5669 [TAN-274] Use initiative policy in scope of initiative_comment policy
  back/app/policies/initiative_comment_policy.rb
  back/spec/policies/initiative_comment_policy_spec.rb
Labels: proposals

#5674 Tan 276 fix e2e tests 2
  front/app/components/PostShowComponents/Topics.tsx
  front/app/containers/InitiativesShow/LargerThanPhone.tsx
  front/app/containers/InitiativesShow/Phone.tsx
  front/app/containers/InitiativesShow/index.tsx
  front/cypress/e2e/proposal_page_action.cy.ts
Labels: proposals

#5692 [TAN-288] Bugfix: Always permit editing proposal by admins
  back/app/policies/initiative_policy.rb
  back/spec/policies/initiative_policy_spec.rb
  front/app/components/admin/PostManager/components/PostPreview/Initiative/AdminInitiativeContent.tsx
Labels: proposals

#5705 [TAN-296] Bugfix: Permit destruction of user record when user is cosponsor of initiative
  back/app/models/user.rb
Labels: proposals

#5683 Tan 276 fix e2e tests 3
  front/app/api/initiative_images/keys.ts
  front/app/api/initiative_images/useInitiativeImage.ts
  front/app/components/InitiativeCard/index.tsx
  front/app/components/InitiativeForm/FormSubmitFooter.tsx
  front/app/components/InitiativeForm/SubmitFooter.tsx
  front/app/components/InitiativeForm/index.tsx
  front/app/components/UI/QuillEditedContent/index.tsx
  front/app/containers/HomePage/InitiativesCTABox.tsx
  front/app/containers/InitiativesNewPage/InitiativesNewFormWrapper.tsx
  front/cypress/e2e/proposal_edit_page.cy.ts
  front/cypress/e2e/proposal_new_page.cy.ts
  front/cypress/e2e/proposal_posting_anonymous.cy.ts
Labels: proposals

#5644 CL-3708 Bulk import tool confirmation
  .gitignore
  front/app/modules/commercial/bulk_idea_import/admin/containers/Import.tsx
  front/app/modules/commercial/bulk_idea_import/admin/containers/messages.ts
  front/app/translations/admin/en.json
  front/app/utils/cl-react-query/fetcher.ts
Labels: waiting for translations

#5708 [TAN-295] Bugfix: Do not automatically add vote for initiative author who should not be able to vote
  back/app/services/side_fx_initiative_service.rb
  back/spec/services/side_fx_initiative_service_spec.rb
Labels: proposals

#5725 [TAN-304] Remove unused email copy from cosponsor_of_your_initiative mail
  back/engines/free/email_campaigns/config/locales/en.yml
  back/engines/free/email_campaigns/spec/fixtures/locales/mailers.en.yml
Labels: proposals

#5433 [TAN-45] Make it possible to skip feedback when approving proposal
  back/app/services/initiative_status_service.rb
  front/app/api/initiative_allowed_transitions/types.ts
  front/app/components/admin/PostManager/components/PostPreview/Initiative/FeedbackSettings.tsx
  front/app/components/admin/PostManager/components/StatusChangeModal/StatusChangeFormWrapper.tsx
  front/app/components/admin/PostManager/components/StatusChangeModal/index.tsx
  front/app/components/admin/PostManager/events.ts
Labels: proposals, approval

#5736 [TAN-321] Add new paragraph to invitation_to_cosponsor_initiative mail
  back/engines/free/email_campaigns/app/views/email_campaigns/invitation_to_cosponsor_initiative_mailer/campaign_mail.mjml
  back/engines/free/email_campaigns/config/locales/en.yml
  back/engines/free/email_campaigns/spec/fixtures/locales/mailers.en.yml
Labels: co-sponsors

#5757 [TAN-328] Revise side_fx_initiatives_service to handle new React form approach
  back/app/models/cosponsors_initiative.rb
  back/app/models/initiative.rb
  back/app/services/side_fx_initiative_service.rb
  back/spec/acceptance/initiatives_spec.rb
  back/spec/models/initiative_spec.rb
  back/spec/services/side_fx_initiative_service_spec.rb
Labels: proposals
