Repository CitizenLabDotCo/citizenlab, pull requests merged in 2023-10, with the labels that each got.

#5976 CL-4080 Prevent user account hijacking through SSO
  back/app/controllers/omniauth_callback_controller.rb
  back/app/services/authentication_service.rb
  back/spec/requests/google_authentication_spec.rb
  back/spec/services/authentication_service_spec.rb
Labels: methods

#5875 [TAN-244] Deny Copenhagen validation for under 15s
  back/engines/commercial/id_nemlog_in/app/lib/id_nemlog_in/nemlog_in_verification.rb
  back/engines/commercial/id_nemlog_in/spec/requests/nemlog_in_verification_spec.rb
  back/engines/commercial/verification/app/controllers/verification/patches/omniauth_callback_controller.rb
  front/app/containers/Authentication/Modal.tsx
  front/app/containers/Authentication/messages.ts
  front/app/containers/Authentication/typings.ts
  front/app/containers/Authentication/useSteps/index.ts
  front/app/containers/Authentication/useSteps/stepConfig/sharedSteps.ts
  front/app/translations/en.json
Labels: proposals

#6061 Cl 4055 remove participation conditions endpoints
  back/app/controllers/web_api/v1/permissions_controller.rb
  back/app/models/permission.rb
  back/app/policies/permission_policy.rb
  back/engines/commercial/granular_permissions/config/routes.rb
  back/engines/commercial/granular_permissions/spec/acceptance/permissions_spec.rb
  back/engines/commercial/smart_groups/app/models/smart_groups/patches/permission.rb
  back/engines/commercial/smart_groups/spec/models/permission_spec.rb
  back/spec/policies/permission_policy_spec.rb
Labels: structure

#6059 Password reset: prevent user enumeration
  back/app/controllers/web_api/v1/reset_password_controller.rb
  back/app/models/user.rb
  back/spec/acceptance/reset_password_spec.rb
Labels: structure

#6067 Raise page size of ideas for voting contexts
  front/app/containers/ProjectsShowPage/continuous/Ideas.tsx
  front/app/containers/ProjectsShowPage/timeline/Ideas.tsx
  front/app/utils/configs/participationMethodConfig/index.tsx
Labels: methods

#5810 [CL-4024] Make profanity errors work again on initiative form
  back/app/controllers/concerns/blocking_profanity.rb
  back/app/controllers/web_api/v1/initiatives_controller.rb
  back/spec/acceptance/initiatives_spec.rb
  front/app/components/Form/index.tsx
  front/app/components/InitiativeForm/index.tsx
  front/app/components/UI/Error/index.tsx
  front/app/components/UI/Error/messages.ts
  front/app/containers/InitiativesNewPage/InitiativesNewFormWrapper.tsx
  front/app/translations/en.json
  front/app/typings.ts
  front/app/utils/errorUtils.ts
  front/app/utils/messages.ts
Labels: waiting for translations, structure, proposals

#6074 Separate terms and privacy checkbox copy into two messages
  front/app/containers/Authentication/steps/AuthProviders/Consent.tsx
  front/app/containers/Authentication/steps/AuthProviders/messages.ts
  front/app/containers/Authentication/steps/Policies/PoliciesMarkup.tsx
  front/app/translations/ar-MA.json
  front/app/translations/ar-SA.json
  front/app/translations/ca-ES.json
  front/app/translations/da-DK.json
  front/app/translations/de-DE.json
  front/app/translations/el-GR.json
  front/app/translations/en-CA.json
  front/app/translations/en-GB.json
  front/app/translations/en.json
  front/app/translations/es-CL.json
  front/app/translations/es-ES.json
  front/app/translations/fr-BE.json
  front/app/translations/fr-FR.json
  front/app/translations/hr-HR.json
  front/app/translations/hu-HU.json
  front/app/translations/it-IT.json
  front/app/translations/kl-GL.json
  front/app/translations/lb-LU.json
  front/app/translations/lv-LV.json
  front/app/translations/mi.json
  front/app/translations/nb-NO.json
  front/app/translations/nl-BE.json
  front/app/translations/nl-NL.json
  front/app/translations/pl-PL.json
  front/app/translations/pt-BR.json
  front/app/translations/ro-RO.json
  front/app/translations/sr-Latn.json
  front/app/translations/sr-SP.json
  front/app/translations/sv-SE.json
  front/app/translations/tr-TR.json
Labels: waiting for translations, methods

#6084 CL4095 - Project user create endpoint
  back/engines/commercial/bulk_import_ideas/app/controllers/bulk_import_ideas/web_api/v1/project_users_controller.rb
  back/engines/commercial/bulk_import_ideas/app/policies/bulk_import_ideas/patches/project_policy.rb
  back/engines/commercial/bulk_import_ideas/app/services/bulk_import_ideas/import_ideas_service.rb
  back/engines/commercial/bulk_import_ideas/config/routes.rb
  back/engines/commercial/bulk_import_ideas/spec/acceptance/project_custom_fields_spec.rb
  back/engines/commercial/bulk_import_ideas/spec/acceptance/project_users_spec.rb
  back/engines/commercial/bulk_import_ideas/spec/services/import_global_ideas_service_spec.rb
  front/app/containers/IdeasShow/components/MetaInformation/PostedBy.tsx
Labels: methods

#6099 [CL-4010] Fix for official feedbacks containing links when displayed in mails
  back/engines/free/email_campaigns/app/views/email_campaigns/official_feedbacks/_card.mjml
Labels: platform-week-23Q4

#5501 Add new min and max multiselect constraints for native survey
  back/app/models/custom_field.rb
  back/app/serializers/web_api/v1/custom_field_serializer.rb
  back/app/services/json_schema_generator_service.rb
  back/app/services/project_copy_service.rb
  back/db/migrate/20230728130913_add_multiselect_minimum_maximum.rb
  back/db/schema.rb
  back/engines/commercial/idea_custom_fields/app/controllers/idea_custom_fields/web_api/v1/admin/idea_custom_fields_controller.rb
  back/engines/commercial/idea_custom_fields/spec/acceptance/idea_custom_fields/phase_context/update_all_native_survey_spec.rb
  back/engines/commercial/multi_tenancy/app/services/multi_tenancy/templates/serializers/custom_field.rb
  back/spec/factories/custom_fields.rb
  back/spec/models/custom_field_spec.rb
  back/spec/services/input_json_schema_generator_service_spec.rb
  back/spec/services/json_forms_service_spec.rb
  back/spec/services/json_schema_generator_service_spec.rb
  front/app/api/custom_fields/types.ts
  front/app/components/Form/Components/Controls/MultiSelectCheckboxControl.tsx
  front/app/components/Form/Components/Controls/messages.ts
  front/app/components/Form/index.tsx
  front/app/components/FormBuilder/components/FormBuilderSettings/MultiselectSettings/index.tsx
  front/app/components/FormBuilder/components/FormBuilderSettings/MultiselectSettings/messages.ts
  front/app/components/FormBuilder/components/FormBuilderSettings/utils.tsx
  front/app/components/FormBuilder/edit/index.tsx
  front/app/translations/en.json
Labels: methods

#6091 [CL-4022] Stats added to import activity
  back/engines/commercial/bulk_import_ideas/app/controllers/bulk_import_ideas/web_api/v1/import_ideas_controller.rb
  back/engines/commercial/bulk_import_ideas/app/services/bulk_import_ideas/google_form_parser_service.rb
  back/engines/commercial/bulk_import_ideas/app/services/bulk_import_ideas/import_ideas_service.rb
  back/engines/commercial/bulk_import_ideas/app/services/bulk_import_ideas/import_project_ideas_service.rb
  back/engines/commercial/bulk_import_ideas/app/services/bulk_import_ideas/side_fx_import_ideas_service.rb
  back/engines/commercial/bulk_import_ideas/spec/services/google_form_parser_service_spec.rb
  back/engines/commercial/bulk_import_ideas/spec/services/import_project_ideas_service_spec.rb
  back/engines/commercial/bulk_import_ideas/spec/services/side_fx_import_ideas_service_spec.rb
Labels: methods

#6113 [CL-4155] Avoid truncating multiloc strings mid-link
  back/app/mailers/application_mailer.rb
  back/engines/free/email_campaigns/app/views/email_campaigns/comment_deleted_by_admin_mailer/campaign_mail.mjml
  back/engines/free/email_campaigns/app/views/email_campaigns/comment_marked_as_spam_mailer/campaign_mail.mjml
  back/engines/free/email_campaigns/app/views/email_campaigns/comment_on_idea_you_follow_mailer/campaign_mail.mjml
  back/engines/free/email_campaigns/app/views/email_campaigns/comment_on_initiative_you_follow_mailer/campaign_mail.mjml
  back/engines/free/email_campaigns/app/views/email_campaigns/comment_on_your_comment_mailer/campaign_mail.mjml
  back/engines/free/email_campaigns/app/views/email_campaigns/comments/_card.mjml
  back/engines/free/email_campaigns/app/views/email_campaigns/new_comment_for_admin_mailer/campaign_mail.mjml
  back/engines/free/email_campaigns/app/views/email_campaigns/official_feedbacks/_card.mjml
  back/engines/free/email_campaigns/app/views/email_campaigns/user_digest_mailer/campaign_mail.mjml
  back/spec/mailers/application_mailer_spec.rb
Labels: platform-week-23Q4

#6047 Change behaviour on volunteering and polls for signed out users
  front/app/api/poll_responses/useAddPollResponse.ts
  front/app/containers/Authentication/SuccessActions/actions/index.ts
  front/app/containers/Authentication/SuccessActions/actions/submitPoll.tsx
  front/app/containers/ProjectsShowPage/shared/poll/PollForm.tsx
  front/app/containers/ProjectsShowPage/shared/poll/index.tsx
  front/app/containers/ProjectsShowPage/shared/poll/messages.ts
  front/app/containers/ProjectsShowPage/shared/volunteering/CauseCard.tsx
  front/app/containers/ProjectsShowPage/shared/volunteering/index.tsx
  front/app/containers/ProjectsShowPage/shared/volunteering/messages.ts
  front/app/translations/ar-MA.json
  front/app/translations/ar-SA.json
  front/app/translations/ca-ES.json
  front/app/translations/da-DK.json
  front/app/translations/de-DE.json
  front/app/translations/el-GR.json
  front/app/translations/en-CA.json
  front/app/translations/en-GB.json
  front/app/translations/en.json
  front/app/translations/es-CL.json
  front/app/translations/es-ES.json
  front/app/translations/fr-BE.json
  front/app/translations/fr-FR.json
  front/app/translations/hr-HR.json
  front/app/translations/hu-HU.json
  front/app/translations/it-IT.json
  front/app/translations/kl-GL.json
  front/app/translations/lb-LU.json
  front/app/translations/lv-LV.json
  front/app/translations/mi.json
  front/app/translations/nb-NO.json
  front/app/translations/nl-BE.json
  front/app/translations/nl-NL.json
  front/app/translations/pl-PL.json
  front/app/translations/pt-BR.json
  front/app/translations/ro-RO.json
  front/app/translations/sr-Latn.json
  front/app/translations/sr-SP.json
  front/app/translations/sv-SE.json
  front/app/translations/tr-TR.json
  front/cypress/e2e/project_page_poll.cy.ts
Labels: methods

#6116 Replace old react intersection observer
  front/app/components/PostShowComponents/Comments/PublicComments.tsx
  front/app/components/ProjectCard/index.tsx
  front/app/components/UI/Image/index.tsx
  front/app/components/UI/ProgressBar/index.tsx
  front/app/components/admin/InternalComments/index.tsx
  front/package-lock.json
  front/package.json
Labels: platform-week-23Q4

#6098 Remove react-adopt
  front/app/api/projects/__mocks__/useProjects.ts
  front/app/components/admin/PostManager/components/PostTable/Row/selectors/ProjectSelector.tsx
  front/app/containers/Admin/projects/project/surveyResults/index.tsx
  front/app/containers/Admin/projects/project/volunteering/index.tsx
  front/app/containers/IdeasShow/index.tsx
  front/app/containers/ProjectsShowPage/shared/volunteering/index.tsx
  front/app/containers/ProjectsShowPage/timeline/Volunteering.tsx
  front/app/containers/SiteMap/TimelineProject.tsx
  front/app/containers/UsersShowPage/UsersShowPageMeta.tsx
  front/app/modules/commercial/idea_assignment/admin/components/AssigneeFilter.tsx
  front/app/modules/commercial/idea_assignment/admin/components/AssigneeSelector.tsx
  front/app/modules/commercial/insights/admin/containers/Insights/List/CreateInsightView.test.tsx
  front/app/modules/commercial/insights/admin/containers/Insights/List/CreateInsightsView.tsx
  front/app/modules/commercial/insights/admin/containers/Reports/PollReport.tsx
  front/app/modules/commercial/insights/admin/containers/Reports/ProjectReport.tsx
  front/app/resources/GetPhase.tsx
Labels: platform-week-23Q4

#6134 [CL-4165] Fixed PDF form printing where a project has no current phase
  back/engines/commercial/bulk_import_ideas/app/controllers/bulk_import_ideas/web_api/v1/project_custom_fields_controller.rb
  back/engines/commercial/bulk_import_ideas/spec/acceptance/project_custom_fields_spec.rb
Labels: methods

#6124 [CL-4152] Include hidden fields in Typeform survey results export
  back/engines/free/surveys/app/services/surveys/typeform_api_parser.rb
  back/engines/free/surveys/spec/services/typeform_api_parser_spec.rb
Labels: platform-week-23Q4

#6044 TAN-358 Sense making translations
  front/app/containers/Admin/projects/project/analysis/Demographics/AuthorsByAge.tsx
  front/app/containers/Admin/projects/project/analysis/Demographics/AuthorsByDomicile.tsx
  front/app/containers/Admin/projects/project/analysis/Demographics/index.tsx
  front/app/containers/Admin/projects/project/analysis/Demographics/messages.ts
  front/app/containers/Admin/projects/project/analysis/FilterItems/AuthorFieldFilterItem.tsx
  front/app/containers/Admin/projects/project/analysis/FilterItems/InputFieldFilterItem.tsx
  front/app/containers/Admin/projects/project/analysis/FilterItems/index.tsx
  front/app/containers/Admin/projects/project/analysis/FilterItems/messages.ts
  front/app/containers/Admin/projects/project/analysis/InputPreview/LongFieldValue.tsx
  front/app/containers/Admin/projects/project/analysis/InputPreview/index.tsx
  front/app/containers/Admin/projects/project/analysis/InputPreview/messages.ts
  front/app/containers/Admin/projects/project/analysis/InputsList/InputListItem.tsx
  front/app/containers/Admin/projects/project/analysis/InputsList/index.tsx
  front/app/containers/Admin/projects/project/analysis/InputsList/messages.ts
  front/app/containers/Admin/projects/project/analysis/Insights/Question.tsx
  front/app/containers/Admin/projects/project/analysis/Insights/QuestionButton.tsx
  front/app/containers/Admin/projects/project/analysis/Insights/QuestionInput.tsx
  front/app/containers/Admin/projects/project/analysis/Insights/Rate.tsx
  front/app/containers/Admin/projects/project/analysis/Insights/SummarizeButton.tsx
  front/app/containers/Admin/projects/project/analysis/Insights/Summary.tsx
  front/app/containers/Admin/projects/project/analysis/Insights/index.tsx
  front/app/containers/Admin/projects/project/analysis/Insights/messages.ts
  front/app/containers/Admin/projects/project/analysis/LaunchModal/index.tsx
  front/app/containers/Admin/projects/project/analysis/LaunchModal/messages.ts
  front/app/containers/Admin/projects/project/analysis/LaunchModal/translations.ts
  front/app/containers/Admin/projects/project/analysis/Tags/AddTag.tsx
  front/app/containers/Admin/projects/project/analysis/Tags/AutoTaggingModal/Step1.tsx
  front/app/containers/Admin/projects/project/analysis/Tags/AutoTaggingModal/Step2FewShotClassification.tsx
  front/app/containers/Admin/projects/project/analysis/Tags/AutoTaggingModal/Step2LabelClassification.tsx
  front/app/containers/Admin/projects/project/analysis/Tags/RenameTagModal.tsx
  front/app/containers/Admin/projects/project/analysis/Tags/TagActions.tsx
  front/app/containers/Admin/projects/project/analysis/Tags/TagAssistance.tsx
  front/app/containers/Admin/projects/project/analysis/Tags/index.tsx
  front/app/containers/Admin/projects/project/analysis/Tags/messages.ts
  front/app/containers/Admin/projects/project/analysis/Tasks/index.tsx
  front/app/containers/Admin/projects/project/analysis/Tasks/messages.ts
  front/app/containers/Admin/projects/project/analysis/TopBar/Filters/AuthorFilters.tsx
  front/app/containers/Admin/projects/project/analysis/TopBar/Filters/EngagementFilter.tsx
  front/app/containers/Admin/projects/project/analysis/TopBar/Filters/index.tsx
  front/app/containers/Admin/projects/project/analysis/TopBar/index.tsx
  front/app/containers/Admin/projects/project/analysis/TopBar/messages.ts
  front/app/containers/Admin/projects/project/analysis/components/ShortInputFieldValue.tsx
  front/app/containers/Admin/projects/project/analysis/components/ShortUserFieldValue.tsx
  front/app/containers/Admin/projects/project/analysis/messages.ts
  front/app/translations/admin/en.json
Labels: waiting for translations

#6149 [CL-4128] Delete initiatives votes, for initiatives with 'voteable' status, when user deleted
  back/app/jobs/delete_user_job.rb
  back/app/models/initiative.rb
  back/app/services/side_fx_user_service.rb
  back/spec/services/side_fx_user_service_spec.rb
  front/app/containers/Admin/users/UserTableRow.tsx
  front/app/containers/Admin/users/messages.ts
  front/app/containers/UsersEditPage/DeletionDialog.tsx
  front/app/containers/UsersEditPage/messages.ts
  front/app/translations/admin/en.json
  front/app/translations/en.json
Labels: structure, proposals

#6221 [TAN-446] Filter base64 encoding from production Rails logs
  back/config/initializers/filter_parameter_logging.rb
Labels: consistent hosting
