Repository CitizenLabDotCo/citizenlab, pull requests merged in 2023-03, with the labels that each got.

#4131 CL-2987: Convert initiative images to react query
  front/app/api/initiative_images/__mocks__/initiativeImages.ts
  front/app/api/initiative_images/keys.ts
  front/app/api/initiative_images/types.ts
  front/app/api/initiative_images/useAddInitiativeImage.test.ts
  front/app/api/initiative_images/useAddInitiativeImage.ts
  front/app/api/initiative_images/useDeleteInitiativeImage.test.ts
  front/app/api/initiative_images/useDeleteInitiativeImage.ts
  front/app/api/initiative_images/useInitiativeImage.test.ts
  front/app/api/initiative_images/useInitiativeImage.ts
  front/app/api/initiative_images/useInitiativeImages.test.ts
  front/app/api/initiative_images/useInitiativeImages.ts
  front/app/components/InitiativeCard/index.tsx
  front/app/components/admin/PostManager/components/LazyPostPreview/Initiative/InitiativeContent.tsx
  front/app/containers/InitiativesEditPage/InitiativesEditFormWrapper.tsx
  front/app/containers/InitiativesNewPage/InitiativesNewFormWrapper.test.tsx
  front/app/containers/InitiativesNewPage/InitiativesNewFormWrapper.tsx
  front/app/containers/InitiativesShow/index.tsx
  front/app/resources/GetInitiativeImage.tsx
  front/app/resources/GetInitiativeImages.tsx
  front/app/services/initiativeImages.ts
Labels: platform-week-23Q1

#3996 [CL-2737] CTA banner tweaks
  front/app/components/ParticipationCTABars/ParticipationCTAContent/index.tsx
  front/app/components/ParticipationCTABars/PollCTABar/index.tsx
  front/app/components/ParticipationCTABars/messages.ts
  front/app/containers/App/PostPageFullscreenModal.tsx
  front/app/translations/ar-MA.json
  front/app/translations/ar-SA.json
  front/app/translations/ca-ES.json
  front/app/translations/da-DK.json
  front/app/translations/de-DE.json
  front/app/translations/el-GR.json
  front/app/translations/en-CA.json
  front/app/translations/en-GB.json
  front/app/translations/en.json
  front/app/translations/es-CL.json
  front/app/translations/es-ES.json
  front/app/translations/fr-BE.json
  front/app/translations/fr-FR.json
  front/app/translations/hr-HR.json
  front/app/translations/it-IT.json
  front/app/translations/kl-GL.json
  front/app/translations/lb-LU.json
  front/app/translations/lv-LV.json
  front/app/translations/nb-NO.json
  front/app/translations/nl-BE.json
  front/app/translations/nl-NL.json
  front/app/translations/pl-PL.json
  front/app/translations/pt-BR.json
  front/app/translations/ro-RO.json
  front/app/translations/sr-Latn.json
  front/app/translations/sr-SP.json
  front/app/translations/sv-SE.json
  front/app/translations/tr-TR.json
  front/app/utils/participationMethodUtils.tsx
  front/cypress/e2e/project_page_poll.cy.ts
Labels: methods

#4155 [CL-2992] Remove useRemoteFiles from FileUploader
  front/app/components/HookForm/FileUploader/FileUploader.test.tsx
  front/app/components/HookForm/FileUploader/index.tsx
  front/app/components/PageForm/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/Attachments/index.tsx
Labels: platform-week-23Q1

#4117 [CL-2908] Reduce n of docs generated from acceptance tests
  back/engines/commercial/admin_api/spec/acceptance/tenants_spec.rb
  back/engines/commercial/custom_idea_statuses/spec/acceptance/idea_statuses_spec.rb
  back/engines/commercial/flag_inappropriate_content/spec/acceptance/spam_reports_spec.rb
  back/engines/commercial/insights/spec/acceptance/categories_spec.rb
  back/engines/commercial/insights/spec/acceptance/category_assignments_spec.rb
  back/engines/commercial/insights/spec/acceptance/category_suggestions_spec.rb
  back/engines/commercial/insights/spec/acceptance/inputs_spec.rb
  back/engines/commercial/insights/spec/acceptance/stats_inputs_spec.rb
  back/engines/commercial/insights/spec/acceptance/views_spec.rb
  back/engines/commercial/user_custom_fields/spec/acceptance/user_custom_field_options_spec.rb
  back/engines/commercial/user_custom_fields/spec/acceptance/user_custom_fields_spec.rb
  back/engines/free/email_campaigns/spec/acceptance/campaigns_spec.rb
  back/engines/free/email_campaigns/spec/acceptance/consents_spec.rb
  back/engines/free/polls/spec/acceptance/responses_spec.rb
  back/engines/free/surveys/spec/acceptance/responses_spec.rb
  back/engines/free/volunteering/spec/acceptance/volunteers_spec.rb
  back/spec/acceptance/admin_publications_spec.rb
  back/spec/acceptance/comment_votes_spec.rb
  back/spec/acceptance/folder_moderators_spec.rb
  back/spec/acceptance/groups_spec.rb
  back/spec/acceptance/idea_comments_spec.rb
  back/spec/acceptance/idea_statuses_spec.rb
  back/spec/acceptance/ideas_spec.rb
  back/spec/acceptance/initiative_comments_spec.rb
  back/spec/acceptance/initiatives_spec.rb
  back/spec/acceptance/invites_spec.rb
  back/spec/acceptance/memberships_spec.rb
  back/spec/acceptance/phases_spec.rb
  back/spec/acceptance/project_moderators_spec.rb
  back/spec/acceptance/static_pages_spec.rb
  back/spec/acceptance/stats_comments_spec.rb
  back/spec/acceptance/users_spec.rb
Labels: structure, platform-week-23Q1

#4129 [CL-2908] Improve back-web-api-docs CI job - Part 1
  .circleci/config.yml
  back/lib/tasks/rspec_api_docs.rake
Labels: structure, platform-week-23Q1

#4083 CL-2952: Show tease for report creator
  front/app/containers/Admin/reporting/components/ReportBuilderPage/EmptyState.test.tsx
  front/app/containers/Admin/reporting/components/ReportBuilderPage/EmptyState.tsx
  front/app/containers/Admin/reporting/components/Tabs.tsx
  front/app/containers/Admin/reporting/containers/ReportBuilderPage/index.tsx
  front/app/containers/Admin/reporting/messages.ts
  front/app/translations/admin/en.json
Labels: waiting for translations, structure

#4094 CL-2953: Show tease for linked projects
  front/app/components/UI/Tabs/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/CustomPageSettingsForm/index.tsx
  front/app/containers/Admin/pagesAndMenu/containers/CustomPages/messages.ts
  front/app/translations/admin/en.json
Labels: waiting for translations, structure

#4151 CL-2986: Convert initiative files to use react query
  front/app/api/initiative_files/__mocks__/initiativeFiles.ts
  front/app/api/initiative_files/keys.ts
  front/app/api/initiative_files/types.ts
  front/app/api/initiative_files/useAddInitiativeFile.test.ts
  front/app/api/initiative_files/useAddInitiativeFile.ts
  front/app/api/initiative_files/useDeleteInitiativeFile.test.ts
  front/app/api/initiative_files/useDeleteInitiativeFile.ts
  front/app/api/initiative_files/useInitiativeFiles.test.ts
  front/app/api/initiative_files/useInitiativeFiles.ts
  front/app/components/UI/FileAttachments/index.tsx
  front/app/components/admin/PostManager/components/LazyPostPreview/Initiative/InitiativeContent.tsx
  front/app/components/admin/PostManager/components/LazyPostPreview/Initiative/InitiativeEdit.tsx
  front/app/containers/InitiativesEditPage/InitiativesEditFormWrapper.tsx
  front/app/containers/InitiativesEditPage/index.tsx
  front/app/containers/InitiativesNewPage/InitiativesNewFormWrapper.tsx
  front/app/containers/InitiativesShow/index.tsx
  front/app/hooks/useRemoteFiles.ts
  front/app/hooks/useResourceFiles.ts
  front/app/resources/GetRemoteFiles.tsx
  front/app/resources/GetResourceFiles.tsx
  front/app/services/initiativeFiles.ts
Labels: platform-week-23Q1

#4142 [CL-2908] Improve back-web-api-docs CI job - Part 2
  .circleci/config.yml
  back/lib/tasks/rspec_api_docs.rake
Labels: structure, platform-week-23Q1

#4140 Remove GetIdeaVotesCount
  front/app/components/VoteControl/index.tsx
  front/app/components/admin/PostManager/components/LazyPostPreview/Idea/VotePreview.tsx
  front/app/resources/GetIdeaVotesCount.tsx
  front/app/services/ideaVotes.ts
Labels: platform-week-23Q1

#4133 Cl 2976 replace get idea custom fields schemas with hook
  front/app/components/IdeaCards/IdeasWithoutFiltersSidebar.tsx
  front/app/components/IdeaCards/index.tsx
  front/app/containers/IdeasIndexPage/index.tsx
  front/app/containers/ProjectsShowPage/continuous/Ideas.tsx
  front/app/containers/ProjectsShowPage/timeline/Ideas.tsx
  front/app/containers/UsersShowPage/__snapshots__/UsersShowPage.test.tsx.snap
  front/app/containers/UsersShowPage/index.tsx
  front/app/resources/GetIdeaCustomFieldsSchemas.tsx
Labels: platform-week-23Q1

#4136 Replace GetIdeaList with hook
  back/app/finders/ideas_finder.rb
  back/spec/acceptance/ideas_spec.rb
  back/spec/finders/ideas_finder_spec.rb
  front/app/components/admin/PostManager/components/LazyPostPreview/Idea/IdeaContent.test.tsx
  front/app/containers/ProjectsShowPage/shared/pb/PBBasket.tsx
  front/app/resources/GetIdeaList.tsx
  front/app/resources/GetIdeas.tsx
  front/app/services/ideas.ts
Labels: platform-week-23Q1

#4165 [CL-2912] Combine all back tests into one CI job
  .circleci/config.yml
  back/engines/commercial/analytics/spec/jobs/analytics/import_latest_matomo_data_job_spec.rb
  back/engines/commercial/multi_tenancy/spec/db/seedfile_spec.rb
  back/engines/commercial/multi_tenancy/spec/services/multi_tenancy/templates/serializer_spec.rb
  back/engines/commercial/multi_tenancy/spec/services/multi_tenancy/tenant_template_service_spec.rb
  back/spec/db/seedfile_spec.rb
  back/spec/models/user_spec.rb
  back/spec/services/local_project_copy_service_spec.rb
  back/spec/services/project_copy_service_spec.rb
  back/spec/spec_helper.rb
Labels: structure, platform-week-23Q1

#4115 CL-2864 Convert events to react query
  front/app/api/event_files/__mocks__/useAddEvent.ts
  front/app/api/event_files/__mocks__/useEventFiles.ts
  front/app/api/event_files/keys.ts
  front/app/api/event_files/types.ts
  front/app/api/event_files/useAddEventFile.test.ts
  front/app/api/event_files/useAddEventFile.ts
  front/app/api/event_files/useDeleteEventFile.test.ts
  front/app/api/event_files/useDeleteEventFile.ts
  front/app/api/event_files/useEventFiles.test.ts
  front/app/api/event_files/useEventFiles.ts
  front/app/api/events/__mocks__/useEvent.ts
  front/app/api/events/__mocks__/useEvents.ts
  front/app/api/events/keys.ts
  front/app/api/events/types.ts
  front/app/api/events/useAddEvent.test.ts
  front/app/api/events/useAddEvent.ts
  front/app/api/events/useDeleteEvent.test.ts
  front/app/api/events/useDeleteEvent.ts
  front/app/api/events/useEvent.test.ts
  front/app/api/events/useEvent.ts
  front/app/api/events/useEvents.test.ts
  front/app/api/events/useEvents.ts
  front/app/api/events/useUpdateEvent.test.ts
  front/app/api/events/useUpdateEvent.ts
  front/app/components/EventCard/EventInformation/index.tsx
  front/app/components/EventCard/index.tsx
  front/app/components/LandingPages/citizen/EventsWidget.tsx
  front/app/components/UI/FileAttachments/FileDisplay/index.tsx
  front/app/components/UI/FileAttachments/index.tsx
  front/app/components/UI/Tabs/index.tsx
  front/app/containers/Admin/projects/project/events/edit.tsx
  front/app/containers/Admin/projects/project/events/index.tsx
  front/app/containers/EventsPage/EventsViewer/index.tsx
  front/app/containers/IdeasShow/MetaInformation/Attachment.tsx
  front/app/containers/ProjectsShowPage/index.tsx
  front/app/containers/ProjectsShowPage/shared/header/ProjectInfoSideBar.tsx
  front/app/containers/SiteMap/Project.tsx
  front/app/hooks/useEvents.ts
  front/app/hooks/useRemoteFiles.ts
  front/app/hooks/useResourceFiles.ts
  front/app/resources/GetRemoteFiles.tsx
  front/app/resources/GetResourceFiles.tsx
  front/app/services/eventFiles.ts
  front/app/services/events.ts
  front/app/utils/unsubscribe.ts
Labels: platform-week-23Q1

#4167 CL-3003: Convert initiative by id stream and initiative by slug stream to react query
  front/app/api/initiatives/__mocks__/initiatives.ts
  front/app/api/initiatives/useInitiativeById.test.ts
  front/app/api/initiatives/useInitiativeById.ts
  front/app/api/initiatives/useInitiativeBySlug.test.ts
  front/app/api/initiatives/useInitiativeBySlug.ts
  front/app/components/InitiativeCard/VoteIndicator.tsx
  front/app/components/InitiativeCard/index.tsx
  front/app/components/InitiativesMap/InitiativePreview.tsx
  front/app/components/PostShowComponents/ActionBar.tsx
  front/app/components/PostShowComponents/Comments/CommentFooter.tsx
  front/app/components/PostShowComponents/Comments/CommentReplyButton.tsx
  front/app/components/PostShowComponents/Comments/CommentVote.tsx
  front/app/components/PostShowComponents/Comments/ParentComment.tsx
  front/app/components/PostShowComponents/Comments/ParentCommentForm.tsx
  front/app/components/PostShowComponents/Comments/index.tsx
  front/app/components/PostShowComponents/SharingModalContent/index.tsx
  front/app/components/admin/PostManager/components/FilterSidebar/FilterSidebarStatusesItem.tsx
  front/app/components/admin/PostManager/components/FilterSidebar/FilterSidebarTopics.tsx
  front/app/components/admin/PostManager/components/FilterSidebar/FilterSidebarTopicsItem.tsx
  front/app/components/admin/PostManager/components/LazyPostPreview/Initiative/FeedbackSettings.tsx
  front/app/components/admin/PostManager/components/LazyPostPreview/Initiative/InitiativeContent.tsx
  front/app/components/admin/PostManager/components/LazyPostPreview/Initiative/InitiativeEdit.tsx
  front/app/components/admin/PostManager/components/PostTable/Row/InitiativeRow.tsx
  front/app/components/admin/PostManager/components/StatusChangeModal/StatusChangeFormWrapper.tsx
  front/app/components/admin/PostManager/index.tsx
  front/app/containers/InitiativesEditPage/index.tsx
  front/app/containers/InitiativesShow/ActionBar/index.tsx
  front/app/containers/InitiativesShow/InitiativeMeta.tsx
  front/app/containers/InitiativesShow/VoteControl/index.tsx
  front/app/containers/InitiativesShow/index.tsx
  front/app/containers/InitiativesShowPage/index.tsx
  front/app/containers/UsersShowPage/PostCommentGroup.tsx
  front/app/modules/commercial/machine_translations/citizen/components/ActionBarTranslateButton.tsx
  front/app/modules/commercial/machine_translations/citizen/components/InitiativesTranslateButton.tsx
  front/app/resources/GetInitiative.tsx
  front/app/resources/GetInitiativeImage.tsx
  front/app/resources/GetPost.tsx
  front/app/services/initiatives.ts
  front/app/utils/moduleUtils.tsx
  front/internals/webpack/webpack.config.js
  front/jest.config.js
  front/package-lock.json
  front/package.json
Labels: platform-week-23Q1

#4178 CL-3010 Create useIdeasInBasket
  front/app/containers/ProjectsShowPage/shared/pb/PBBasket.tsx
  front/app/resources/GetBasket.tsx
  front/app/resources/GetIdeas.tsx
Labels: platform-week-23Q1

#4164 useIdea replace streams
  front/app/api/ideas/keys.ts
  front/app/api/ideas/types.ts
  front/app/api/ideas/useUpdateIdea.test.ts
  front/app/api/ideas/useUpdateIdea.ts
  front/app/components/admin/PostManager/components/LazyPostPreview/Idea/FeedbackSettings.tsx
  front/app/components/admin/PostManager/components/LazyPostPreview/Idea/IdeaContent.tsx
  front/app/components/admin/PostManager/components/PostTable/Row/IdeaRow.tsx
  front/app/containers/IdeasEditPage/WithJSONForm/index.tsx
  front/app/modules/commercial/idea_assignment/admin/components/IdeaRowCell.tsx
Labels: platform-week-23Q1

#4188 Cl 3020 delete idea
  front/app/api/ideas/useDeleteIdea.test.ts
  front/app/api/ideas/useDeleteIdea.ts
  front/app/components/admin/PostManager/components/ActionBar/ActionBarMulti.tsx
  front/app/components/admin/PostManager/components/ActionBar/ActionBarSingle.tsx
  front/app/components/admin/PostManager/components/LazyPostPreview/Idea/IdeaContent.tsx
  front/app/containers/IdeasShow/IdeaMoreActions.tsx
  front/app/services/ideas.ts
Labels: platform-week-23Q1

#4204 CL-3045 Add feature settings (User banning)
  back/config/schemas/settings.schema.json.erb
  back/engines/commercial/multi_tenancy/db/seeds/tenants.rb
  back/engines/commercial/multi_tenancy/lib/tasks/core/create_tenant.rake
Labels: structure, user blocking

#4183 Convert use idea hook streams update admin idea edit
  front/app/components/admin/PostManager/components/LazyPostPreview/Idea/AdminIdeaEdit.tsx
Labels: platform-week-23Q1

#4112 [CL-2539] Use image files on s3 for anonymized user initials_avatars
  back/app/services/anonymize_user_service.rb
Labels: structure, 10%-project

#4182 IdeasEditPage to functional
  front/app/api/ideas/useAddIdea.test.ts
  front/app/api/ideas/useAddIdea.ts
  front/app/api/ideas/useDeleteIdea.ts
  front/app/api/ideas/useUpdateIdea.ts
  front/app/containers/IdeasEditPage/WithJSONForm/index.tsx
  front/app/containers/IdeasEditPage/index.tsx
  front/app/services/ideas.ts
Labels: platform-week-23Q1

#4173 Convert use idea hook streams update idearow
  front/app/components/admin/PostManager/components/FilterSidebar/FilterSidebarPhases.tsx
  front/app/components/admin/PostManager/components/FilterSidebar/index.tsx
  front/app/components/admin/PostManager/components/PostTable/AssigneeSelect.tsx
  front/app/components/admin/PostManager/components/PostTable/Row/IdeaRow.tsx
  front/package-lock.json
  front/package.json
Labels: platform-week-23Q1

#4220 [CL-3064] Add new columns to template serializers & UserSerializer
  back/app/services/project_copy_service.rb
  back/engines/commercial/multi_tenancy/app/services/multi_tenancy/templates/serializer.rb
Labels: structure, user blocking

#4207 CL-3030: Create component with seats info
  front/app/api/app_configuration/types.ts
  front/app/api/app_configuration/useAppConfiguration.test.tsx
  front/app/api/seats/keys.ts
  front/app/api/seats/types.ts
  front/app/api/seats/useSeats.test.ts
  front/app/api/seats/useSeats.ts
  front/app/components/SeatInfo/SeatInfo.test.tsx
  front/app/components/SeatInfo/index.tsx
  front/app/components/SeatInfo/messages.ts
  front/app/translations/en.json
Labels: structure

#4098 [CL-2945] Log details of task actions to Sentry event
  back/engines/commercial/multi_tenancy/lib/tasks/core/clean_up_orphaned_image_records.rake
  back/engines/commercial/multi_tenancy/spec/tasks/clean_up_orphaned_image_records_task_spec.rb
  back/lib/error_reporter.rb
Labels: structure

#4205 [CL-2802] Email confirmation UI update
  back/app/views/confirmations_mailer/send_confirmation_code.mjml
  back/config/locales/en.yml
Labels: methods

#4223 [CL-3048] BE Return blocked user related data in user related responses
  back/app/controllers/web_api/v1/users_controller.rb
  back/app/models/user.rb
  back/app/policies/user_policy.rb
  back/app/serializers/web_api/v1/user_serializer.rb
  back/config/routes.rb
  back/spec/acceptance/users_spec.rb
Labels: structure, user blocking

#4230 [CL-3048] Remove unused permitted attributes
  back/app/policies/user_policy.rb
Labels: structure, user blocking

#4233 [CL-3075] Add seat info component to folder page
  front/app/containers/Admin/projectFolders/containers/permissions/index.tsx
Labels: structure

#4074 CL-2806 - Return fake names when no name present
  back/app/models/user.rb
  back/app/serializers/web_api/v1/user_serializer.rb
  back/app/services/user_display_name_service.rb
  back/spec/models/user_spec.rb
  back/spec/services/user_display_name_service_spec.rb
Labels: methods

#4210 [CL-3041] Add feature flag for new email confirmation permissions option
  back/config/schemas/settings.schema.json.erb
  back/engines/commercial/multi_tenancy/db/seeds/tenants.rb
  front/app/api/app_configuration/types.ts
  front/app/modules/commercial/granular_permissions/admin/containers/Granular/ActionForm.tsx
Labels: methods

#4103 CL-2766 permission requirements
  back/app/controllers/web_api/v1/permissions_controller.rb
  back/app/models/custom_field.rb
  back/app/models/permission.rb
  back/app/models/user.rb
  back/app/policies/permission_policy.rb
  back/app/services/anonymize_user_service.rb
  back/app/services/permissions_service.rb
  back/engines/commercial/granular_permissions/app/controllers/granular_permissions/patches/web_api/v1/action_descriptors_controller.rb
  back/engines/commercial/granular_permissions/app/policies/granular_permissions/patches/comment_vote_policy.rb
  back/engines/commercial/granular_permissions/app/policies/granular_permissions/patches/initiative_comment_policy.rb
  back/engines/commercial/granular_permissions/app/policies/granular_permissions/patches/initiative_policy.rb
  back/engines/commercial/granular_permissions/app/policies/granular_permissions/patches/initiative_vote_policy.rb
  back/engines/commercial/granular_permissions/app/services/granular_permissions/patches/participation_context_service.rb
  back/engines/commercial/granular_permissions/config/routes.rb
  back/engines/commercial/granular_permissions/lib/citizen_lab/permissions/scope_types/global.rb
  back/engines/commercial/granular_permissions/lib/citizen_lab/permissions/scope_types/mixins/participation_context.rb
  back/engines/commercial/granular_permissions/lib/citizen_lab/permissions/scope_types/phase.rb
  back/engines/commercial/granular_permissions/lib/citizen_lab/permissions/scope_types/project.rb
  back/engines/commercial/granular_permissions/lib/granular_permissions/engine.rb
  back/engines/commercial/granular_permissions/spec/acceptance/ideas_spec.rb
  back/engines/commercial/granular_permissions/spec/acceptance/permissions_spec.rb
  back/engines/commercial/granular_permissions/spec/factories/phases.rb
  back/engines/commercial/granular_permissions/spec/factories/projects.rb
  back/engines/commercial/granular_permissions/spec/policies/basket_policy_spec.rb
  back/engines/commercial/granular_permissions/spec/policies/comment_vote_policy_spec.rb
  back/engines/commercial/granular_permissions/spec/policies/idea_comment_policy_spec.rb
  back/engines/commercial/granular_permissions/spec/policies/idea_policy_spec.rb
  back/engines/commercial/granular_permissions/spec/policies/idea_vote_policy_spec.rb
  back/engines/commercial/granular_permissions/spec/policies/permission_policy_spec.rb
  back/engines/commercial/granular_permissions/spec/policies/response_policy_spec.rb
  back/engines/commercial/granular_permissions/spec/services/participation_context_service_spec.rb
  back/engines/commercial/smart_groups/spec/models/permission_spec.rb
  back/engines/commercial/verification/app/models/verification/patches/permission.rb
  back/engines/commercial/verification/app/services/verification/patches/permissions_service.rb
  back/engines/commercial/verification/spec/services/participation_context_service_spec.rb
  back/engines/commercial/verification/spec/services/permissions_service_spec.rb
  back/spec/acceptance/action_descriptors_spec.rb
  back/spec/acceptance/idea_votes_spec.rb
  back/spec/acceptance/ideas_spec.rb
  back/spec/acceptance/initiative_votes_spec.rb
  back/spec/acceptance/phases_spec.rb
  back/spec/acceptance/users_spec.rb
  back/spec/factories/phases.rb
  back/spec/factories/projects.rb
  back/spec/models/permission_spec.rb
  back/spec/models/user_spec.rb
  back/spec/policies/permission_policy_spec.rb
  back/spec/services/local_project_copy_service_spec.rb
  back/spec/services/permissions_service_spec.rb
Labels: methods

#4231 [CL-3074] Add block & unblock user endpoints & related functionality
  back/app/controllers/web_api/v1/users_controller.rb
  back/app/models/user.rb
  back/app/policies/user_policy.rb
  back/app/serializers/web_api/v1/user_serializer.rb
  back/app/services/side_fx_user_service.rb
  back/config/routes.rb
  back/config/schemas/settings.schema.json.erb
  back/spec/acceptance/users_spec.rb
  back/spec/models/user_spec.rb
  back/spec/policies/application_policy_spec.rb
  back/spec/policies/basket_policy_spec.rb
  back/spec/policies/comment_vote_policy_spec.rb
  back/spec/policies/idea_comment_policy_spec.rb
  back/spec/policies/idea_policy_spec.rb
  back/spec/policies/idea_vote_policy_spec.rb
  back/spec/policies/initiative_comment_policy_spec.rb
  back/spec/policies/initiative_vote_policy_spec.rb
  back/spec/policies/user_policy_spec.rb
  back/spec/services/side_fx_user_spec.rb
  back/spec/support/shared_contexts/when_user_blocking_90_days.rb
  back/spec/support/shared_examples/policy_for_blocked_user.rb
Labels: structure, user blocking

#4239 Cl 3087 review fixes 1
  front/app/components/SeatInfo/index.tsx
  front/app/components/SeatInfo/messages.ts
  front/app/containers/Admin/projectFolders/containers/permissions/index.tsx
  front/app/containers/Admin/users/ChangeSeatModal.tsx
  front/app/containers/Admin/users/UserTableRow.tsx
  front/app/containers/Admin/users/messages.ts
  front/app/translations/admin/en.json
  front/app/translations/en.json
Labels: structure

#4251 CL-3104: Do not show seat tracker if admins or managers are unlimited
  front/app/api/app_configuration/types.ts
  front/app/components/SeatInfo/SeatInfo.test.tsx
  front/app/components/SeatInfo/index.tsx
  front/app/containers/Admin/users/ChangeSeatModal.tsx
Labels: structure

#4218 [CL-3049] Remove validation on first and last names
  front/app/containers/UsersEditPage/ProfileForm.tsx
  front/cypress/e2e/profile_edition.cy.ts
Labels: methods

#4234 [CL-1928] Remove sorting options for participatory budgeting methods
  back/app/models/concerns/participation_context.rb
  back/engines/commercial/multi_tenancy/lib/tasks/core/remove_budgeting_sort_options.rake
  front/app/components/FilterSelector/valuesList.tsx
  front/app/components/IdeaCards/IdeasWithoutFiltersSidebar.tsx
  front/app/components/IdeaCards/SortFilterDropdown.tsx
  front/app/components/IdeaCards/index.tsx
  front/app/components/InitiativeCards/SortFilterDropdown.tsx
  front/app/containers/Admin/projects/project/participationContext/components/IdeationInputs.tsx
  front/app/containers/Admin/projects/project/participationContext/components/ParticipatoryBudgetingInputs.tsx
  front/app/containers/Admin/projects/project/participationContext/components/SortingPicker.tsx
  front/app/containers/Admin/projects/project/participationContext/index.tsx
  front/app/services/participationContexts.ts
  front/app/translations/en.json
  front/app/utils/messages.ts
  front/app/utils/participationMethodUtils.tsx
  front/cypress/e2e/project_page_ideas.cy.ts
  front/cypress/e2e/project_page_pb.cy.ts
Labels: waiting for translations, methods

#4250 CL-3110: Copy changes
  front/app/components/SeatInfo/SeatInfo.test.tsx
  front/app/components/SeatInfo/index.tsx
  front/app/components/SeatInfo/messages.ts
  front/app/containers/Admin/projectFolders/containers/permissions/index.tsx
  front/app/containers/Admin/users/AdminsAndManagers.tsx
  front/app/translations/en.json
Labels: structure

#4256 [CL-3071] Increase max length to 25 characters
  front/app/services/navbar.ts
Labels: structure

#4283 [CL-3138] Add copy for additional seats tooltip
  front/app/components/SeatInfo/index.tsx
  front/app/components/SeatInfo/messages.ts
  front/app/translations/en.json
Labels: structure

#4287 Remove unnecessary useState/useEffect
  front/app/containers/Admin/users/UserTableRow.tsx
Labels: structure

#4284 [CL-3139] Add buy copy in set admin modal
  front/app/containers/Admin/users/ChangeSeatModal.test.tsx
  front/app/containers/Admin/users/ChangeSeatModal.tsx
  front/app/containers/Admin/users/UserTableRow.tsx
  front/app/containers/Admin/users/messages.ts
  front/app/translations/admin/en.json
Labels: structure

#4289 3014 review
  front/app/containers/Admin/users/GroupsListPanel.tsx
  front/app/containers/Admin/users/UserManager.tsx
  front/app/containers/Admin/users/UserTable.tsx
  front/app/containers/Admin/users/routes.tsx
Labels: structure

#4240 [CL-3101] Disable email confirmation toggle if email-only permissions allowed
  front/app/containers/Admin/settings/registration/ToggleUserConfirmation/index.tsx
  front/app/containers/Admin/settings/registration/index.tsx
  front/app/modules/commercial/granular_permissions/admin/containers/Granular/ActionForm.tsx
Labels: methods

#4294 [CL-3157] Error & 401 response to any request if current_user blocked
  back/app/controllers/application_controller.rb
Labels: structure, user blocking

#4280 [CL-3080] Added translation for fake first name
  back/app/models/user.rb
  back/config/locales/en.yml
  back/spec/fixtures/locales/en.yml
Labels: methods

#4310 CL-3157 Respond to all requests with 401 and error if user blocked
  back/app/controllers/application_controller.rb
Labels: structure, user blocking

#4252 [CL-3116] Use block_end_at for blocked? status and realign/adjust user scopes
  back/app/controllers/web_api/v1/users_controller.rb
  back/app/models/group.rb
  back/app/models/membership.rb
  back/app/models/user.rb
  back/app/services/avatars_service.rb
  back/app/services/project_copy_service.rb
  back/app/services/side_fx_user_service.rb
  back/config/schemas/settings.schema.json.erb
  back/db/migrate/20230314110825_add_block_end_at_to_users.rb
  back/db/schema.rb
  back/engines/commercial/multi_tenancy/app/services/multi_tenancy/templates/serializer.rb
  back/engines/commercial/multi_tenancy/lib/tasks/core/migrate.rake
  back/engines/commercial/smart_groups/app/models/smart_groups/patches/group.rb
  back/spec/acceptance/users_spec.rb
  back/spec/factories/users.rb
  back/spec/models/user_spec.rb
  back/spec/policies/application_policy_spec.rb
  back/spec/policies/basket_policy_spec.rb
  back/spec/policies/comment_vote_policy_spec.rb
  back/spec/policies/idea_comment_policy_spec.rb
  back/spec/policies/idea_policy_spec.rb
  back/spec/policies/idea_vote_policy_spec.rb
  back/spec/policies/initiative_comment_policy_spec.rb
  back/spec/policies/initiative_vote_policy_spec.rb
  back/spec/policies/user_policy_spec.rb
  back/spec/services/side_fx_user_spec.rb
  back/spec/support/shared_contexts/when_user_blocking_90_days.rb
  back/spec/support/shared_examples/policy_for_blocked_user.rb
Labels: structure, user blocking

#4249 [CL-3085] Send email to user when user is blocked
  back/app/mailers/user_blocked_mailer.rb
  back/app/services/side_fx_user_service.rb
  back/app/views/user_blocked_mailer/send_user_blocked_email.mjml
  back/config/locales/en.yml
  back/engines/free/email_campaigns/spec/mailers/previews/user_blocking/user_blocked_mailer_preview.rb
  back/engines/free/email_campaigns/spec/mailers/previews/user_confirmation/confirmations_mailer_preview.rb
  back/spec/mailers/user_blocked_mailer_spec.rb
  back/spec/services/side_fx_user_spec.rb
Labels: structure, user blocking

#4282 CL-3081 - Remove custom field required validation
  back/app/models/user.rb
  back/app/services/custom_field_service.rb
  back/spec/acceptance/users_spec.rb
Labels: methods

#4333 CL-3063 Remove WIP message for user blocking from settings.schema
  back/config/schemas/settings.schema.json.erb
Labels: structure, user blocking

#4355 [CL-2623] Remove whitespace
  back/app/controllers/web_api/v1/users_controller.rb
Labels: structure, user blocking

#4357 [CL-3157] 401 includes block_end_at
  back/app/controllers/application_controller.rb
Labels: structure, user blocking

#4362 CL-3190 Revert to blocking specific actions and add error message
  back/app/controllers/application_controller.rb
Labels: structure, user blocking

#4328 CL-3142 and CL-3143: Show confirmation modal when adding project / folder managers
  front/app/api/app_configuration/types.ts
  front/app/api/seats/types.ts
  front/app/api/seats/useSeats.ts
  front/app/components/InitiativeCard/VoteIndicator.tsx
  front/app/components/SeatInfo/SeatInfo.test.tsx
  front/app/components/SeatInfo/index.tsx
  front/app/components/SeatInfo/messages.ts
  front/app/components/admin/AddCollaboratorsModal/AddCollaboratorsModal.test.tsx
  front/app/components/admin/AddCollaboratorsModal/index.tsx
  front/app/components/admin/AddCollaboratorsModal/messages.ts
  front/app/components/admin/PostManager/components/ActionBar/ActionBarMulti.tsx
  front/app/components/admin/PostManager/components/ActionBar/ActionBarSingle.tsx
  front/app/containers/Admin/invitations/invite/index.tsx
  front/app/containers/Admin/projectFolders/containers/permissions/index.tsx
  front/app/containers/Admin/projects/project/permissions/components/UserSearch.tsx
  front/app/containers/Admin/projects/project/permissions/containers/ProjectManagement/index.tsx
  front/app/containers/Admin/users/AdminsAndManagers.tsx
  front/app/containers/Admin/users/ChangeSeatModal.test.tsx
  front/app/containers/Admin/users/ChangeSeatModal.tsx
  front/app/services/groupMemberships.ts
  front/app/services/projectFolderModerators.ts
  front/app/translations/admin/en.json
  front/app/translations/ar-MA.json
  front/app/translations/ar-SA.json
  front/app/translations/ca-ES.json
  front/app/translations/da-DK.json
  front/app/translations/de-DE.json
  front/app/translations/el-GR.json
  front/app/translations/en-CA.json
  front/app/translations/en-GB.json
  front/app/translations/en.json
  front/app/translations/es-CL.json
  front/app/translations/es-ES.json
  front/app/translations/fr-BE.json
  front/app/translations/fr-FR.json
  front/app/translations/hr-HR.json
  front/app/translations/it-IT.json
  front/app/translations/lb-LU.json
  front/app/translations/lv-LV.json
  front/app/translations/nb-NO.json
  front/app/translations/nl-BE.json
  front/app/translations/nl-NL.json
  front/app/translations/pl-PL.json
  front/app/translations/pt-BR.json
  front/app/translations/ro-RO.json
  front/app/translations/sr-Latn.json
  front/app/translations/sv-SE.json
  front/app/translations/tr-TR.json
Labels: structure

#4337 CL-3140: Show additional seats usage vis a vis additional seats on tenants
  front/app/api/app_configuration/types.ts
  front/app/api/app_configuration/useAppConfiguration.test.tsx
  front/app/components/SeatInfo/SeatInfo.test.tsx
  front/app/components/SeatInfo/index.tsx
Labels: structure

#4367 Update copy
  front/app/components/SeatInfo/messages.ts
  front/app/translations/ar-MA.json
  front/app/translations/ar-SA.json
  front/app/translations/ca-ES.json
  front/app/translations/da-DK.json
  front/app/translations/de-DE.json
  front/app/translations/el-GR.json
  front/app/translations/en-CA.json
  front/app/translations/en-GB.json
  front/app/translations/en.json
  front/app/translations/es-CL.json
  front/app/translations/es-ES.json
  front/app/translations/fr-BE.json
  front/app/translations/fr-FR.json
  front/app/translations/hr-HR.json
  front/app/translations/it-IT.json
  front/app/translations/lb-LU.json
  front/app/translations/lv-LV.json
  front/app/translations/nb-NO.json
  front/app/translations/nl-BE.json
  front/app/translations/nl-NL.json
  front/app/translations/pl-PL.json
  front/app/translations/pt-BR.json
  front/app/translations/ro-RO.json
  front/app/translations/sr-Latn.json
  front/app/translations/sv-SE.json
  front/app/translations/tr-TR.json
Labels: structure

#4286 [CL-3040] Fix Clave Unica verification
  back/Gemfile
  back/Gemfile.lock
  back/engines/commercial/id_clave_unica/app/lib/id_clave_unica/clave_unica_omniauth.rb
  back/engines/commercial/id_clave_unica/id_clave_unica.gemspec
Labels: structure

#4335 CL-3161 - Prevent email change for user with no password in resend code endpoint
  back/app/interactors/reset_user_email.rb
  back/spec/factories/users.rb
  back/spec/interactors/reset_user_email_spec.rb
Labels: methods

#4390 [No ticket] fix Rubocop unnecessary disabling
  back/app/models/user.rb
Labels: structure, user blocking

#4391 CL-3209 Show correct email version when block reason blank
  back/app/views/user_blocked_mailer/send_user_blocked_email.mjml
Labels: structure, user blocking

#4375 Cl 3198 fe fix project moderator rights
  front/app/containers/Admin/projectFolders/containers/permissions/index.tsx
  front/app/containers/Admin/projects/project/permissions/components/ModeratorList.tsx
  front/app/containers/Admin/projects/project/permissions/components/ModeratorListRow.test.tsx
  front/app/containers/Admin/projects/project/permissions/components/ModeratorListRow.tsx
  front/app/containers/Admin/projects/project/permissions/components/messages.ts
  front/app/services/__mocks__/users.ts
  front/app/translations/admin/ar-MA.json
  front/app/translations/admin/ar-SA.json
  front/app/translations/admin/ca-ES.json
  front/app/translations/admin/da-DK.json
  front/app/translations/admin/de-DE.json
  front/app/translations/admin/el-GR.json
  front/app/translations/admin/en-CA.json
  front/app/translations/admin/en-GB.json
  front/app/translations/admin/en.json
  front/app/translations/admin/es-CL.json
  front/app/translations/admin/es-ES.json
  front/app/translations/admin/fr-BE.json
  front/app/translations/admin/fr-FR.json
  front/app/translations/admin/hr-HR.json
  front/app/translations/admin/hu-HU.json
  front/app/translations/admin/it-IT.json
  front/app/translations/admin/kl-GL.json
  front/app/translations/admin/lb-LU.json
  front/app/translations/admin/lv-LV.json
  front/app/translations/admin/mi.json
  front/app/translations/admin/nb-NO.json
  front/app/translations/admin/nl-BE.json
  front/app/translations/admin/nl-NL.json
  front/app/translations/admin/pl-PL.json
  front/app/translations/admin/pt-BR.json
  front/app/translations/admin/ro-RO.json
  front/app/translations/admin/sr-Latn.json
  front/app/translations/admin/sr-SP.json
  front/app/translations/admin/sv-SE.json
  front/app/translations/admin/tr-TR.json
Labels: structure

#4383 [CL-3207] Prevent blocked user submitting survey
  back/app/policies/application_policy.rb
  back/app/policies/idea_policy.rb
  back/engines/free/polls/spec/policies/response_policy_spec.rb
  back/spec/policies/idea_policy_spec.rb
Labels: structure, user blocking

#4370 Fix broken events link in project info
  front/app/containers/EventsPage/EventsViewer/index.tsx
  front/app/containers/ProjectsShowPage/shared/header/ProjectInfoSideBar.tsx
Labels: methods

#4292 CL-3028 - Reset confirmation code when email is changed
  back/app/controllers/web_api/v1/users_controller.rb
  back/app/interactors/reset_user_email.rb
  back/app/models/user.rb
  back/app/services/side_fx_user_service.rb
  back/spec/acceptance/users_spec.rb
Labels: methods

#4405 [CL-2945] Remove rake task and related spec
  back/engines/commercial/multi_tenancy/lib/tasks/core/clean_up_orphaned_image_records.rake
  back/engines/commercial/multi_tenancy/spec/tasks/clean_up_orphaned_image_records_task_spec.rb
Labels: structure

#4373 [CL-3203] Fix bug with idea title in notifications
  front/app/containers/MainHeader/NotificationMenu/components/StatusChangeOfYourIdeaNotification/index.tsx
  front/app/containers/MainHeader/NotificationMenu/components/StatusChangeOfYourInitiativeNotification/index.tsx
  front/app/containers/MainHeader/NotificationMenu/messages.ts
  front/app/translations/ar-MA.json
  front/app/translations/ar-SA.json
  front/app/translations/ca-ES.json
  front/app/translations/da-DK.json
  front/app/translations/de-DE.json
  front/app/translations/el-GR.json
  front/app/translations/en-CA.json
  front/app/translations/en-GB.json
  front/app/translations/en.json
  front/app/translations/es-CL.json
  front/app/translations/es-ES.json
  front/app/translations/fr-BE.json
  front/app/translations/fr-FR.json
  front/app/translations/hr-HR.json
  front/app/translations/hu-HU.json
  front/app/translations/it-IT.json
  front/app/translations/kl-GL.json
  front/app/translations/lb-LU.json
  front/app/translations/lv-LV.json
  front/app/translations/mi.json
  front/app/translations/nb-NO.json
  front/app/translations/nl-BE.json
  front/app/translations/nl-NL.json
  front/app/translations/pl-PL.json
  front/app/translations/pt-BR.json
  front/app/translations/ro-RO.json
  front/app/translations/sr-Latn.json
  front/app/translations/sr-SP.json
  front/app/translations/sv-SE.json
  front/app/translations/tr-TR.json
Labels: methods

#4415 [CL-3228] Seed additional seats values for localhost
  back/engines/commercial/multi_tenancy/db/seeds/tenants.rb
Labels: structure

#4332 Fix bug where events not showing on draft projects
  front/app/containers/EventsPage/CurrentAndUpcomingEvents.tsx
  front/app/containers/EventsPage/EventsViewer/index.tsx
  front/app/containers/EventsPage/PastEvents.tsx
  front/app/containers/ProjectsShowPage/index.tsx
  front/cypress/e2e/project_page_timeline.cy.ts
Labels: methods

#4430 [CL-3214] Remove WIP copy from feature description
  back/engines/commercial/report_builder/lib/report_builder/feature_specification.rb
Labels: structure

#4427 [CL-3232] Rake task to update specific custom field option
  back/engines/commercial/multi_tenancy/lib/tasks/core/update_custom_field_option.rake
Labels: structure

#4424 [CL-3160] Add feature flag for seat based billing
  back/config/schemas/settings.schema.json.erb
  back/engines/commercial/multi_tenancy/db/seeds/tenants.rb
  back/engines/commercial/multi_tenancy/lib/tasks/core/create_tenant.rake
  front/app/api/app_configuration/types.ts
  front/app/components/SeatInfo/SeatInfo.test.tsx
  front/app/components/SeatInfo/index.tsx
  front/app/components/SeatInfo/messages.ts
  front/app/containers/Admin/invitations/invite/index.tsx
  front/app/containers/Admin/projectFolders/containers/permissions/index.tsx
  front/app/containers/Admin/projects/project/permissions/components/UserSearch.tsx
  front/app/containers/Admin/projects/project/permissions/containers/ProjectManagement/index.tsx
  front/app/containers/Admin/users/ChangeSeatModal.test.tsx
  front/app/containers/Admin/users/ChangeSeatModal.tsx
  front/app/translations/ar-MA.json
  front/app/translations/ar-SA.json
  front/app/translations/ca-ES.json
  front/app/translations/da-DK.json
  front/app/translations/de-DE.json
  front/app/translations/el-GR.json
  front/app/translations/en-CA.json
  front/app/translations/en-GB.json
  front/app/translations/en.json
  front/app/translations/es-CL.json
  front/app/translations/es-ES.json
  front/app/translations/fr-BE.json
  front/app/translations/fr-FR.json
  front/app/translations/hr-HR.json
  front/app/translations/it-IT.json
  front/app/translations/lb-LU.json
  front/app/translations/lv-LV.json
  front/app/translations/nb-NO.json
  front/app/translations/nl-BE.json
  front/app/translations/nl-NL.json
  front/app/translations/pl-PL.json
  front/app/translations/pt-BR.json
  front/app/translations/ro-RO.json
  front/app/translations/sr-Latn.json
  front/app/translations/sv-SE.json
  front/app/translations/tr-TR.json
Labels: structure

#4432 [CL-3293] Improve scopes and controller filters for not project / folder mods
  back/app/controllers/web_api/v1/users_controller.rb
  back/app/models/user.rb
  back/spec/models/user_spec.rb
Labels: structure

#4438 CL-2809 - SSO permissions fix
  back/app/models/user.rb
  back/app/services/permissions_service.rb
  back/engines/commercial/granular_permissions/spec/acceptance/permissions_spec.rb
  back/spec/services/permissions_service_spec.rb
Labels: methods

#4444 Add feature flag for permissions_custom_fields
  back/config/schemas/settings.schema.json.erb
  back/engines/commercial/multi_tenancy/db/seeds/tenants.rb
  front/app/api/app_configuration/types.ts
  front/app/modules/commercial/granular_permissions/admin/containers/Granular/ActionsForm.tsx
Labels: methods

#4439 CL-2654 - Flexible registration i3
  back/app/controllers/web_api/v1/users_controller.rb
  back/app/interactors/reset_user_email.rb
  back/app/models/user.rb
  back/app/services/side_fx_user_service.rb
  back/spec/acceptance/users_spec.rb
Labels: methods

#4221 [CL-3039] Update password change for light users
  back/app/controllers/web_api/v1/users_controller.rb
  back/spec/acceptance/users_spec.rb
  front/app/containers/PasswordChange/ChangePassword.test.tsx
  front/app/containers/PasswordChange/index.tsx
  front/app/containers/PasswordChange/messages.ts
  front/app/containers/UsersEditPage/PasswordChange.tsx
  front/app/containers/UsersEditPage/index.tsx
  front/app/containers/UsersEditPage/messages.ts
  front/app/services/users.ts
  front/app/translations/ar-MA.json
  front/app/translations/ar-SA.json
  front/app/translations/ca-ES.json
  front/app/translations/da-DK.json
  front/app/translations/de-DE.json
  front/app/translations/el-GR.json
  front/app/translations/en-CA.json
  front/app/translations/en-GB.json
  front/app/translations/en.json
  front/app/translations/es-CL.json
  front/app/translations/es-ES.json
  front/app/translations/fr-BE.json
  front/app/translations/fr-FR.json
  front/app/translations/hr-HR.json
  front/app/translations/it-IT.json
  front/app/translations/lb-LU.json
  front/app/translations/lv-LV.json
  front/app/translations/nb-NO.json
  front/app/translations/nl-BE.json
  front/app/translations/nl-NL.json
  front/app/translations/pl-PL.json
  front/app/translations/pt-BR.json
  front/app/translations/ro-RO.json
  front/app/translations/sr-Latn.json
  front/app/translations/sr-SP.json
  front/app/translations/sv-SE.json
  front/app/translations/tr-TR.json
Labels: methods

#4403 [CL-2628] Update existing users in bulk invite
  back/app/services/invites/service.rb
  back/engines/commercial/admin_api/app/controllers/admin_api/invites_controller.rb
  back/spec/services/invites/service_spec.rb
Labels: structure

#4402 [CL-3145] Refactor invites service
  back/.rubocop_todo.yml
  back/app/controllers/web_api/v1/invites_controller.rb
  back/app/models/invite.rb
  back/app/services/invites/error_storage.rb
  back/app/services/invites/failed_error.rb
  back/app/services/invites/invite_error.rb
  back/app/services/invites/service.rb
  back/app/services/invites/xlsx_processor.rb
  back/app/services/invites_service.rb
  back/engines/commercial/admin_api/app/controllers/admin_api/invites_controller.rb
  back/engines/free/email_campaigns/spec/mailers/invite_received_mailer_spec.rb
  back/engines/free/email_campaigns/spec/mailers/invite_reminder_mailer_spec.rb
  back/engines/free/email_campaigns/spec/mailers/previews/email_campaigns/invite_received_mailer_preview.rb
  back/engines/free/email_campaigns/spec/mailers/previews/email_campaigns/invite_reminder_mailer_preview.rb
  back/lib/utils.rb
  back/spec/acceptance/invites_spec.rb
  back/spec/services/invites/service_spec.rb
Labels: structure

#4443 CL-3237 Remove sorting on user role/status
  front/app/containers/Admin/users/UserTable.tsx
Labels: structure

#4455 CL-3240 Clarify can_moderate query params
  back/spec/acceptance/users_spec.rb
  back/spec/models/user_spec.rb
Labels: structure

#4360 PermissionsCustomFields
  back/app/controllers/web_api/v1/permissions_controller.rb
  back/app/controllers/web_api/v1/permissions_custom_fields_controller.rb
  back/app/models/custom_field.rb
  back/app/models/permission.rb
  back/app/models/permissions_custom_field.rb
  back/app/policies/permission_policy.rb
  back/app/policies/permissions_custom_field_policy.rb
  back/app/serializers/web_api/v1/permission_serializer.rb
  back/app/serializers/web_api/v1/permissions_custom_field_serializer.rb
  back/app/services/permissions_service.rb
  back/app/services/side_fx_permissions_custom_field_service.rb
  back/app/services/user_role_service.rb
  back/db/migrate/20230321153659_create_permissions_custom_fields.rb
  back/db/schema.rb
  back/engines/commercial/granular_permissions/config/routes.rb
  back/engines/commercial/granular_permissions/spec/acceptance/permissions_spec.rb
  back/spec/acceptance/permissions_custom_fields_spec.rb
  back/spec/factories/permissions_custom_fields.rb
  back/spec/policies/permissions_custom_field_policy_spec.rb
Labels: methods

#4462 CL-3259 Acceptance tests of not moderator filters
  back/spec/acceptance/users_spec.rb
Labels: structure

#4456 CL-3244 update copy
  back/config/locales/en.yml
  front/app/components/admin/UserBlockModals/messages.ts
  front/app/containers/DisabledAccount/messages.ts
  front/app/translations/admin/en.json
Labels: structure, user blocking
