Repository CitizenLabDotCo/citizenlab, pull requests merged in 2024-04, with the labels that each got.

#7510 Add proposals countdown screenreader text translation
  front/app/containers/InitiativesShow/ReactionControl/Status/index.tsx
  front/app/containers/InitiativesShow/ReactionControl/messages.ts
  front/app/translations/en.json
Labels: waiting for translations

#7484 [TAN-1476] Add follow button tooltip
  front/app/components/FollowUnfollow/index.tsx
  front/app/components/FollowUnfollow/messages.ts
  front/app/components/IdeaCard/index.tsx
  front/app/components/InitiativeCard/index.tsx
  front/app/components/ProjectAndFolderCards/components/ProjectFolderCard/index.tsx
  front/app/components/ProjectCard/index.tsx
  front/app/containers/IdeasShow/components/RightColumnDesktop/index.tsx
  front/app/containers/IdeasShow/index.tsx
  front/app/containers/InitiativesShow/ReactionControl/index.tsx
  front/app/containers/ProjectFolderShowPage/index.tsx
  front/app/containers/ProjectsShowPage/shared/header/ProjectHeader.tsx
  front/app/translations/en.json
Labels: waiting for translations

#7555 TAN-1513 Allow project moderators to manage phase custom fields
  front/app/containers/Admin/projects/project/permissions/granular_permissions/components/UserFieldSelection/UserFieldSelection.tsx
  front/app/containers/Admin/projects/project/permissions/granular_permissions/components/UserFieldSelection/screens/SelectionScreen.tsx
  front/app/containers/Admin/projects/project/permissions/granular_permissions/containers/Granular/messages.ts
  front/app/translations/admin/ar-SA.json
  front/app/translations/admin/ca-ES.json
  front/app/translations/admin/da-DK.json
  front/app/translations/admin/de-DE.json
  front/app/translations/admin/el-GR.json
  front/app/translations/admin/en-CA.json
  front/app/translations/admin/en-GB.json
  front/app/translations/admin/en-IE.json
  front/app/translations/admin/en.json
  front/app/translations/admin/es-CL.json
  front/app/translations/admin/es-ES.json
  front/app/translations/admin/fi-FI.json
  front/app/translations/admin/fr-BE.json
  front/app/translations/admin/fr-FR.json
  front/app/translations/admin/hr-HR.json
  front/app/translations/admin/it-IT.json
  front/app/translations/admin/lv-LV.json
  front/app/translations/admin/nb-NO.json
  front/app/translations/admin/nl-BE.json
  front/app/translations/admin/nl-NL.json
  front/app/translations/admin/pl-PL.json
  front/app/translations/admin/pt-BR.json
  front/app/translations/admin/sr-Latn.json
  front/app/translations/admin/sr-SP.json
  front/app/translations/admin/sv-SE.json
  front/app/translations/admin/tr-TR.json
Labels: waiting for translations

#7548 TAN-1499 Metrics
  front/app/containers/Admin/projects/project/events/edit.tsx
  front/app/containers/Admin/projects/project/events/index.tsx
  front/app/containers/Admin/projects/project/index.tsx
  front/app/containers/Admin/projects/project/messages.ts
  front/app/containers/Admin/projects/project/participation/ParticipationDateRange.tsx
  front/app/containers/Admin/projects/project/participation/ParticipationReportPreview.tsx
  front/app/containers/Admin/projects/project/participation/index.tsx
  front/app/containers/Admin/projects/project/participation/messages.ts
  front/app/containers/Admin/projects/project/phase/index.tsx
  front/app/containers/Admin/projects/project/settings/index.tsx
  front/app/containers/Admin/projects/project/traffic/TrafficDatesRange.tsx
  front/app/containers/Admin/projects/project/traffic/TrafficReportPreview.tsx
  front/app/containers/Admin/projects/project/traffic/index.tsx
  front/app/containers/Admin/projects/project/traffic/messages.ts
  front/app/containers/Admin/projects/routes.tsx
  front/app/containers/Admin/reporting/context/ReportContext.tsx
  front/app/containers/EventsShowPage/components/DesktopTopBar.tsx
  front/app/translations/admin/en.json
Labels: waiting for translations

#7598 [TAN-1592] Serialize stats with campaign response if manual and sent
  back/engines/free/email_campaigns/app/models/email_campaigns/campaign.rb
  back/engines/free/email_campaigns/app/models/email_campaigns/campaigns/manual.rb
  back/engines/free/email_campaigns/app/serializers/email_campaigns/web_api/v1/campaign_serializer.rb
  back/engines/free/email_campaigns/spec/acceptance/campaigns_spec.rb
Labels: PM autonomy

#7616 [TAN-1575] Export event attendees as XLSX
  back/app/controllers/web_api/v1/events_controller.rb
  back/app/policies/event_policy.rb
  back/app/services/xlsx_service.rb
  back/config/routes.rb
  back/spec/acceptance/events_spec.rb
  back/spec/services/xlsx_service_spec.rb
Labels: PM autonomy

#7618 Remove idea_custom_copy feature flag
  back/config/schemas/settings.schema.json.erb
  back/engines/commercial/multi_tenancy/db/seeds/tenants.rb
  back/engines/commercial/multi_tenancy/lib/tasks/core/create_tenant.rake
  front/app/api/app_configuration/types.ts
  front/app/containers/Admin/projects/project/phase/phaseParticipationConfig/components/inputs/IdeationInputs/index.tsx
  front/app/containers/Admin/projects/project/phase/phaseParticipationConfig/index.tsx
Labels: pricing plans

#7617 Remove all social sharing flow feature flag code
  back/config/schemas/settings.schema.json.erb
  back/engines/commercial/multi_tenancy/db/seeds/tenants.rb
  back/engines/commercial/multi_tenancy/lib/tasks/core/create_tenant.rake
  front/app/api/app_configuration/types.ts
  front/app/containers/IdeasShow/components/Container.tsx
  front/app/containers/InitiativesShow/modals/index.tsx
Labels: pricing plans

#7605 Remove 'volunteering' feature flag
  back/engines/commercial/multi_tenancy/db/seeds/tenants.rb
  back/engines/commercial/multi_tenancy/lib/tasks/core/create_tenant.rake
  front/app/api/app_configuration/types.ts
  front/app/containers/Admin/projects/project/phase/phaseParticipationConfig/components/ParticipationMethodPicker.tsx
  front/app/containers/Admin/projects/project/tabs.ts
Labels: pricing plans

#7599 Remove private_projects feature flag
  back/config/schemas/settings.schema.json.erb
  back/engines/commercial/multi_tenancy/db/seeds/tenants.rb
  back/engines/commercial/multi_tenancy/lib/tasks/core/create_tenant.rake
  front/app/api/app_configuration/types.ts
  front/app/containers/Admin/projects/project/settings/index.tsx
  front/app/modules/commercial/idea_assignment/admin/components/Tab.tsx
  front/app/modules/commercial/idea_assignment/admin/components/messages.ts
  front/app/modules/commercial/idea_assignment/index.tsx
  front/app/translations/admin/ar-MA.json
  front/app/translations/admin/ar-SA.json
  front/app/translations/admin/ca-ES.json
  front/app/translations/admin/da-DK.json
  front/app/translations/admin/de-DE.json
  front/app/translations/admin/el-GR.json
  front/app/translations/admin/en-CA.json
  front/app/translations/admin/en-GB.json
  front/app/translations/admin/en-IE.json
  front/app/translations/admin/en.json
  front/app/translations/admin/es-CL.json
  front/app/translations/admin/es-ES.json
  front/app/translations/admin/fi-FI.json
  front/app/translations/admin/fr-BE.json
  front/app/translations/admin/fr-FR.json
  front/app/translations/admin/hr-HR.json
  front/app/translations/admin/hu-HU.json
  front/app/translations/admin/it-IT.json
  front/app/translations/admin/kl-GL.json
  front/app/translations/admin/lb-LU.json
  front/app/translations/admin/lv-LV.json
  front/app/translations/admin/mi.json
  front/app/translations/admin/nb-NO.json
  front/app/translations/admin/nl-BE.json
  front/app/translations/admin/nl-NL.json
  front/app/translations/admin/pl-PL.json
  front/app/translations/admin/pt-BR.json
  front/app/translations/admin/ro-RO.json
  front/app/translations/admin/sr-Latn.json
  front/app/translations/admin/sr-SP.json
  front/app/translations/admin/sv-SE.json
  front/app/translations/admin/tr-TR.json
  front/app/utils/moduleUtils.tsx
Labels: pricing plans

#7608 Remove all manual & automated mailing feature flag code
  back/config/schemas/settings.schema.json.erb
  back/engines/commercial/multi_tenancy/db/seeds/tenants.rb
  back/engines/commercial/multi_tenancy/lib/tasks/core/create_tenant.rake
  front/app/api/app_configuration/types.ts
  front/app/containers/Admin/messaging/index.tsx
  front/app/containers/Admin/sideBar/navItems.ts
Labels: pricing plans

#7571 Add multi_language_platform flag to FE (app config) & BE
  back/config/schemas/settings.schema.json.erb
  back/engines/commercial/multi_tenancy/db/seeds/tenants.rb
  back/engines/commercial/multi_tenancy/lib/tasks/core/create_tenant.rake
  front/app/api/app_configuration/types.ts
  front/app/containers/Admin/settings/general/Form.tsx
Labels: pricing plans

#7626 [TAN-1622] Extend volunteers XLSX export data
  back/engines/free/volunteering/app/controllers/volunteering/web_api/v1/volunteers_controller.rb
  back/engines/free/volunteering/app/policies/volunteering/volunteer_policy.rb
  back/engines/free/volunteering/app/services/volunteering/xlsx_service.rb
  back/engines/free/volunteering/spec/acceptance/volunteers_spec.rb
  back/engines/free/volunteering/spec/policies/volunteer_policy_spec.rb
Labels: PM autonomy

#7635 [TAN-1629] Remove PII restrictions for Project Moderators on survey & ideation XLSX exports
  back/app/controllers/web_api/v1/comments_controller.rb
  back/app/controllers/web_api/v1/ideas_controller.rb
  back/app/controllers/web_api/v1/phases_controller.rb
  back/app/controllers/web_api/v1/projects_controller.rb
  back/engines/free/volunteering/app/controllers/volunteering/web_api/v1/volunteers_controller.rb
  back/engines/free/volunteering/app/services/volunteering/xlsx_service.rb
  back/spec/acceptance/phases_spec.rb
  back/spec/acceptance/projects_spec.rb
  back/spec/policies/idea_comment_policy_spec.rb
  back/spec/policies/idea_policy_spec.rb
  back/spec/policies/phase_policy_spec.rb
  back/spec/policies/project_policy_spec.rb
Labels: PM autonomy

#7636 TAN-1576 Events export
  front/app/api/events/util.ts
  front/app/containers/Admin/projects/project/events/index.tsx
  front/app/containers/Admin/projects/project/events/messages.ts
  front/app/translations/admin/ar-SA.json
  front/app/translations/admin/da-DK.json
  front/app/translations/admin/de-DE.json
  front/app/translations/admin/en-CA.json
  front/app/translations/admin/en-GB.json
  front/app/translations/admin/en-IE.json
  front/app/translations/admin/en.json
  front/app/translations/admin/es-CL.json
  front/app/translations/admin/es-ES.json
  front/app/translations/admin/fi-FI.json
  front/app/translations/admin/fr-BE.json
  front/app/translations/admin/fr-FR.json
  front/app/translations/admin/hr-HR.json
  front/app/translations/admin/lv-LV.json
  front/app/translations/admin/nb-NO.json
  front/app/translations/admin/nl-BE.json
  front/app/translations/admin/nl-NL.json
  front/app/translations/admin/pl-PL.json
  front/app/translations/admin/pt-BR.json
  front/app/translations/admin/sr-Latn.json
  front/app/translations/admin/sr-SP.json
  front/app/translations/admin/sv-SE.json
  front/app/translations/admin/tr-TR.json
Labels: waiting for translations

#7694 Tan 1579/1.3.1 main landmark part 4
  front/app/containers/DisabledAccount/index.tsx
  front/app/containers/EmailSettingsPage/index.tsx
  front/app/containers/EmailSettingsPage/messages.ts
  front/app/containers/SubscriptionEndedPage/index.tsx
  front/app/routes.tsx
  front/app/translations/en.json
Labels: a11y

#7693 Tan 1579/1.3.1 main landmark part 3
  front/app/containers/AccessibilityStatement/index.tsx
  front/app/containers/CookiePolicy/index.tsx
  front/app/containers/CustomPageShow/index.tsx
  front/app/containers/DisabledAccount/index.tsx
  front/app/containers/EmailSettingsPage/index.tsx
  front/app/containers/EmailSettingsPage/messages.ts
  front/app/containers/EventsShowPage/components/Container.tsx
  front/app/containers/EventsShowPage/components/DesktopTopBar.tsx
  front/app/containers/EventsShowPage/index.tsx
  front/app/containers/PasswordRecovery/index.tsx
  front/app/containers/PasswordReset/PasswordResetSuccess.test.tsx
  front/app/containers/PasswordReset/PasswordResetSuccess.tsx
  front/app/containers/PasswordReset/index.tsx
  front/app/containers/SubscriptionEndedPage/index.tsx
  front/app/routes.tsx
  front/app/translations/en.json
Labels: a11y

#7679 Tan 1579/1.3.1 main landmark part 2
  front/app/containers/AccessibilityStatement/index.tsx
  front/app/containers/CookiePolicy/index.tsx
  front/app/containers/CustomPageShow/index.tsx
  front/app/containers/DisabledAccount/index.tsx
  front/app/containers/EmailSettingsPage/index.tsx
  front/app/containers/EmailSettingsPage/messages.ts
  front/app/containers/EventsPage/index.tsx
  front/app/containers/EventsShowPage/components/Container.tsx
  front/app/containers/EventsShowPage/components/DesktopTopBar.tsx
  front/app/containers/EventsShowPage/index.tsx
  front/app/containers/InitiativesShow/LargerThanPhone.tsx
  front/app/containers/InitiativesShow/Phone.tsx
  front/app/containers/InitiativesShow/index.tsx
  front/app/containers/InitiativesShowPage/index.tsx
  front/app/containers/PasswordRecovery/index.tsx
  front/app/containers/PasswordReset/PasswordResetSuccess.test.tsx
  front/app/containers/PasswordReset/PasswordResetSuccess.tsx
  front/app/containers/PasswordReset/index.tsx
  front/app/containers/ProjectFolderShowPage/index.tsx
  front/app/containers/ProjectsShowPage/index.tsx
  front/app/containers/ProjectsShowPage/shared/header/ProjectShowPageMeta.tsx
  front/app/containers/SubscriptionEndedPage/index.tsx
  front/app/routes.tsx
  front/app/translations/en.json
Labels: a11y

#7699 Tan 1579/1.3.1 main landmark part 6
  front/app/containers/UsersShowPage/UserEvents.tsx
  front/app/containers/UsersShowPage/UserHeader.tsx
  front/app/containers/UsersShowPage/index.tsx
  front/app/containers/UsersShowPage/messages.ts
  front/app/translations/ar-MA.json
  front/app/translations/ar-SA.json
  front/app/translations/ca-ES.json
  front/app/translations/da-DK.json
  front/app/translations/de-DE.json
  front/app/translations/el-GR.json
  front/app/translations/en-CA.json
  front/app/translations/en-GB.json
  front/app/translations/en-IE.json
  front/app/translations/en.json
  front/app/translations/es-CL.json
  front/app/translations/es-ES.json
  front/app/translations/fi-FI.json
  front/app/translations/fr-BE.json
  front/app/translations/fr-FR.json
  front/app/translations/hr-HR.json
  front/app/translations/hu-HU.json
  front/app/translations/it-IT.json
  front/app/translations/kl-GL.json
  front/app/translations/lb-LU.json
  front/app/translations/lv-LV.json
  front/app/translations/mi.json
  front/app/translations/nb-NO.json
  front/app/translations/nl-BE.json
  front/app/translations/nl-NL.json
  front/app/translations/pl-PL.json
  front/app/translations/pt-BR.json
  front/app/translations/ro-RO.json
  front/app/translations/sr-Latn.json
  front/app/translations/sr-SP.json
  front/app/translations/sv-SE.json
  front/app/translations/tr-TR.json
Labels: a11y

#7651 Tan 1579/1.3.1 idea form
  front/app/components/Form/Components/Wrapper.tsx
  front/app/components/Form/index.tsx
  front/app/components/UI/GoBackButton/GoBackButtonSolid.tsx
  front/app/containers/IdeasEditPage/GoBackToIdeaPage.tsx
  front/app/containers/IdeasEditPage/IdeasEditForm.tsx
  front/app/containers/IdeasNewPage/IdeasNewIdeationForm/index.tsx
  front/app/containers/IdeasNewPage/IdeasNewSurveyForm/index.tsx
  front/app/containers/IdeasNewPage/components/NewIdeaHeading.tsx
  front/app/containers/IdeasNewPage/index.tsx
Labels: a11y

#7715 UsersEditPage
  front/app/containers/UsersEditPage/index.tsx
Labels: a11y

#7712 Unauthorized
  front/app/components/Unauthorized/index.tsx
Labels: a11y

#7726 Tan 1579/add main to pages that use page container
  front/app/containers/IdeasEditPage/IdeasEditForm.tsx
  front/app/containers/IdeasNewPage/IdeasNewIdeationForm/index.tsx
  front/app/containers/IdeasNewPage/IdeasNewSurveyForm/index.tsx
  front/app/containers/IdeasNewPage/components/SurveyNotActiveNotice.tsx
  front/app/containers/IdeasNewPage/components/SurveySubmittedNotice.tsx
Labels: a11y

#7698 [TAN-1649] Fix text inconsistency in voting phase instructions
  front/app/translations/ar-MA.json
  front/app/translations/ar-SA.json
  front/app/translations/ca-ES.json
  front/app/translations/da-DK.json
  front/app/translations/de-DE.json
  front/app/translations/el-GR.json
  front/app/translations/en-CA.json
  front/app/translations/en-GB.json
  front/app/translations/en-IE.json
  front/app/translations/en.json
  front/app/translations/es-CL.json
  front/app/translations/es-ES.json
  front/app/translations/fi-FI.json
  front/app/translations/fr-BE.json
  front/app/translations/fr-FR.json
  front/app/translations/hr-HR.json
  front/app/translations/it-IT.json
  front/app/translations/kl-GL.json
  front/app/translations/lb-LU.json
  front/app/translations/lv-LV.json
  front/app/translations/nb-NO.json
  front/app/translations/nl-BE.json
  front/app/translations/nl-NL.json
  front/app/translations/pl-PL.json
  front/app/translations/pt-BR.json
  front/app/translations/sr-Latn.json
  front/app/translations/sr-SP.json
  front/app/translations/sv-SE.json
  front/app/translations/tr-TR.json
  front/app/utils/configs/votingMethodConfig/index.tsx
  front/app/utils/configs/votingMethodConfig/messages.ts
Labels: waiting for translations

#7739 Tan 1579/1.3.1 input schema loading
  front/app/containers/IdeasEditPage/IdeasEditForm.tsx
  front/app/containers/IdeasNewPage/IdeasNewIdeationForm/index.tsx
  front/app/containers/IdeasNewPage/IdeasNewSurveyForm/index.tsx
  front/app/hooks/useInputSchema.ts
Labels: a11y

#7741 Email settings page
  front/app/containers/EmailSettingsPage/index.tsx
Labels: a11y
