Repository CitizenLabDotCo/citizenlab, pull requests merged in 2024-06, with the labels that each got.

#8126 Add TODO to survey form footer
  front/app/components/Form/Components/Layouts/CLSurveyPageLayout.tsx
Labels: a11y

#8186 TAN-1616/remove idea assignment ff
  back/engines/commercial/idea_assignment/lib/idea_assignment/engine.rb
  back/engines/commercial/idea_assignment/lib/idea_assignment/feature_specification.rb
  back/engines/commercial/idea_assignment/spec/lib/settings_spec.rb
  front/app/api/app_configuration/types.ts
  front/app/modules/commercial/idea_assignment/index.tsx
Labels: pricing plans

#8193 Remove analytics feature flag
  back/engines/commercial/analytics/lib/analytics/engine.rb
  back/engines/commercial/analytics/lib/analytics/feature_specification.rb
  back/engines/commercial/analytics/spec/lib/settings_spec.rb
  back/engines/commercial/multi_tenancy/db/seeds/tenants.rb
  back/engines/commercial/multi_tenancy/lib/tasks/core/create_tenant.rake
  front/app/api/app_configuration/types.ts
  front/app/containers/Admin/dashboard/index.tsx
  front/app/containers/Admin/dashboard/tabs.ts
Labels: pricing plans

#8222 Remove native_surveys feature flag
  back/config/schemas/settings.schema.json.erb
  back/engines/commercial/multi_tenancy/db/seeds/tenants.rb
  back/engines/commercial/multi_tenancy/lib/tasks/core/create_tenant.rake
  front/app/api/app_configuration/types.ts
  front/app/containers/Admin/projects/project/phase/phaseParticipationConfig/components/ParticipationMethodPicker.tsx
Labels: pricing plans

#8221 Remove admin_project_templates feature flag
  back/config/schemas/settings.schema.json.erb
  back/engines/commercial/multi_tenancy/db/seeds/tenants.rb
  back/engines/commercial/multi_tenancy/lib/tasks/core/create_tenant.rake
  front/app/api/app_configuration/types.ts
  front/app/modules/commercial/admin_project_templates/index.tsx
Labels: pricing plans

#8202 Remove project_visibility feature
  back/config/schemas/settings.schema.json.erb
  back/engines/commercial/multi_tenancy/db/seeds/tenants.rb
  back/engines/commercial/multi_tenancy/lib/tasks/core/create_tenant.rake
  front/app/api/app_configuration/types.ts
  front/app/containers/Admin/projects/project/permissions/index.tsx
Labels: pricing plans

#8196 Remove representativeness feature flag
  back/config/schemas/settings.schema.json.erb
  back/engines/commercial/multi_tenancy/db/seeds/tenants.rb
  back/engines/commercial/multi_tenancy/lib/tasks/core/create_tenant.rake
  back/engines/commercial/user_custom_fields/lib/user_custom_fields/engine.rb
  back/engines/commercial/user_custom_fields/lib/user_custom_fields/feature_specifications/representativeness.rb
  back/engines/commercial/user_custom_fields/spec/lib/app_configuration/settings_spec.rb
  front/app/api/app_configuration/types.ts
  front/app/containers/Admin/dashboard/index.tsx
  front/app/containers/Admin/dashboard/tabs.ts
  front/app/modules/commercial/representativeness/admin/containers/Dashboard/index.tsx
Labels: pricing plans

#8214 [TAN-2065] Remove the 'texting' feature from the backend
  back/.rubocop_todo.yml
  back/Gemfile
  back/Gemfile.lock
  back/db/migrate/20240612134240_remove_texting_campaigns.rb
  back/db/structure.sql
  back/engines/commercial/multi_tenancy/db/seeds/tenants.rb
  back/engines/commercial/multi_tenancy/lib/tasks/core/create_tenant.rake
  back/engines/commercial/texting/.gitignore
  back/engines/commercial/texting/app/controllers/texting/web_api/v1/campaigns_controller.rb
  back/engines/commercial/texting/app/jobs/texting/send_campaign_job.rb
  back/engines/commercial/texting/app/models/texting/campaign.rb
  back/engines/commercial/texting/app/policies/texting/campaign_policy.rb
  back/engines/commercial/texting/app/serializers/texting/web_api/v1/campaign_serializer.rb
  back/engines/commercial/texting/app/services/texting/phone_number.rb
  back/engines/commercial/texting/app/services/texting/side_fx_campaign_service.rb
  back/engines/commercial/texting/app/services/texting/sms.rb
  back/engines/commercial/texting/app/services/texting/sms/providers/twilio.rb
  back/engines/commercial/texting/app/services/texting/webhook_url_generator.rb
  back/engines/commercial/texting/config/routes.rb
  back/engines/commercial/texting/lib/tasks/texting_tasks.rake
  back/engines/commercial/texting/lib/texting.rb
  back/engines/commercial/texting/lib/texting/engine.rb
  back/engines/commercial/texting/lib/texting/feature_specification.rb
  back/engines/commercial/texting/lib/texting/version.rb
  back/engines/commercial/texting/spec/acceptance/campaigns_spec.rb
  back/engines/commercial/texting/spec/factories/texting_campaigns.rb
  back/engines/commercial/texting/spec/services/texting/phone_number_spec.rb
  back/engines/commercial/texting/texting.gemspec
Labels: pricing plans

#8234 Fix custom (input) statuses feature flag
  front/app/component-library/components/IconTooltip/index.tsx
  front/app/containers/Admin/settings/index.tsx
  front/app/modules/commercial/custom_idea_statuses/admin/components/DeleteStatusButton.tsx
  front/app/modules/commercial/custom_idea_statuses/admin/components/EditStatusButton.tsx
  front/app/modules/commercial/custom_idea_statuses/admin/components/Tab.tsx
  front/app/modules/commercial/custom_idea_statuses/admin/components/messages.ts
  front/app/modules/commercial/custom_idea_statuses/admin/containers/index.tsx
  front/app/modules/commercial/custom_idea_statuses/admin/containers/messages.ts
  front/app/modules/commercial/custom_idea_statuses/index.tsx
  front/app/translations/admin/ar-SA.json
  front/app/translations/admin/ca-ES.json
  front/app/translations/admin/da-DK.json
  front/app/translations/admin/de-DE.json
  front/app/translations/admin/el-GR.json
  front/app/translations/admin/en-CA.json
  front/app/translations/admin/en-GB.json
  front/app/translations/admin/en-IE.json
  front/app/translations/admin/en.json
  front/app/translations/admin/es-CL.json
  front/app/translations/admin/es-ES.json
  front/app/translations/admin/fi-FI.json
  front/app/translations/admin/fr-BE.json
  front/app/translations/admin/fr-FR.json
  front/app/translations/admin/hr-HR.json
  front/app/translations/admin/it-IT.json
  front/app/translations/admin/lv-LV.json
  front/app/translations/admin/nb-NO.json
  front/app/translations/admin/nl-BE.json
  front/app/translations/admin/nl-NL.json
  front/app/translations/admin/pl-PL.json
  front/app/translations/admin/pt-BR.json
  front/app/translations/admin/sr-Latn.json
  front/app/translations/admin/sr-SP.json
  front/app/translations/admin/sv-SE.json
  front/app/translations/admin/tr-TR.json
  front/app/utils/moduleUtils.tsx
Labels: pricing plans

#8254 Fix copy mistake
  front/app/containers/Admin/pagesAndMenu/containers/ContentBuilder/components/CraftComponents/HomepageBanner/messages.ts
  front/app/translations/admin/ar-SA.json
  front/app/translations/admin/da-DK.json
  front/app/translations/admin/de-DE.json
  front/app/translations/admin/en-CA.json
  front/app/translations/admin/en-GB.json
  front/app/translations/admin/en-IE.json
  front/app/translations/admin/en.json
  front/app/translations/admin/es-CL.json
  front/app/translations/admin/es-ES.json
  front/app/translations/admin/fi-FI.json
  front/app/translations/admin/fr-BE.json
  front/app/translations/admin/fr-FR.json
  front/app/translations/admin/hr-HR.json
  front/app/translations/admin/lv-LV.json
  front/app/translations/admin/nb-NO.json
  front/app/translations/admin/nl-BE.json
  front/app/translations/admin/nl-NL.json
  front/app/translations/admin/pl-PL.json
  front/app/translations/admin/pt-BR.json
  front/app/translations/admin/sr-Latn.json
  front/app/translations/admin/sr-SP.json
  front/app/translations/admin/sv-SE.json
  front/app/translations/admin/tr-TR.json
Labels: waiting for translations

#8056 [TAN-883] Add load more button to voting results list
  front/app/containers/ProjectsShowPage/timeline/VotingResults/index.tsx
  front/app/containers/ProjectsShowPage/timeline/VotingResults/messages.ts
  front/app/translations/en.json
Labels: waiting for translations

#8317 Update WCAG version
  front/app/containers/Admin/settings/customize/Branding.tsx
Labels: a11y

#8323 Tan 2069/permissions custom fields flag
  front/app/containers/Admin/projects/project/permissions/granular_permissions/components/UserFieldSelection/UserFieldSelection.tsx
Labels: pricing plans

#8200 Tan 2068/user confirmation flags
  back/config/schemas/settings.schema.json.erb
  back/engines/commercial/multi_tenancy/db/seeds/tenants.rb
  back/engines/commercial/multi_tenancy/lib/tasks/core/create_tenant.rake
  front/app/api/app_configuration/types.ts
  front/app/component-library/components/CardButton/index.tsx
  front/app/component-library/components/Tooltip/index.tsx
  front/app/containers/Admin/projects/project/permissions/granular_permissions/components/PhaseActionForm.tsx
  front/app/containers/Admin/projects/project/permissions/granular_permissions/containers/Granular/ActionForm.tsx
  front/app/containers/Admin/projects/project/permissions/granular_permissions/containers/Granular/PhasePermissions.tsx
  front/app/containers/Admin/projects/project/permissions/granular_permissions/containers/Granular/messages.ts
  front/app/containers/Admin/settings/registration/ToggleUserConfirmation/index.tsx
  front/app/containers/Admin/settings/registration/ToggleUserConfirmation/messages.ts
  front/app/containers/Admin/settings/registration/index.tsx
  front/app/translations/admin/ar-MA.json
  front/app/translations/admin/ar-SA.json
  front/app/translations/admin/ca-ES.json
  front/app/translations/admin/da-DK.json
  front/app/translations/admin/de-DE.json
  front/app/translations/admin/el-GR.json
  front/app/translations/admin/en-CA.json
  front/app/translations/admin/en-GB.json
  front/app/translations/admin/en-IE.json
  front/app/translations/admin/en.json
  front/app/translations/admin/es-CL.json
  front/app/translations/admin/es-ES.json
  front/app/translations/admin/fi-FI.json
  front/app/translations/admin/fr-BE.json
  front/app/translations/admin/fr-FR.json
  front/app/translations/admin/hr-HR.json
  front/app/translations/admin/hu-HU.json
  front/app/translations/admin/it-IT.json
  front/app/translations/admin/kl-GL.json
  front/app/translations/admin/lb-LU.json
  front/app/translations/admin/lv-LV.json
  front/app/translations/admin/mi.json
  front/app/translations/admin/nb-NO.json
  front/app/translations/admin/nl-BE.json
  front/app/translations/admin/nl-NL.json
  front/app/translations/admin/pl-PL.json
  front/app/translations/admin/pt-BR.json
  front/app/translations/admin/ro-RO.json
  front/app/translations/admin/sr-Latn.json
  front/app/translations/admin/sr-SP.json
  front/app/translations/admin/sv-SE.json
  front/app/translations/admin/tr-TR.json
Labels: pricing plans
