Repository CitizenLabDotCo/citizenlab, pull requests merged in 2025-05, with the labels that each got.

#10936 TAN-4511 - Added html_pdfs feature flag
  back/config/schemas/settings.schema.json.erb
  back/engines/commercial/multi_tenancy/db/seeds/tenants.rb
Labels: formsync-pdf

#10942 isFormPhaseSpecific explanation
  front/app/components/FormBuilder/utils.tsx
Labels: formsync-pdf

#10958 Move "downloadPdfLink" into saveSurveyAsPDF
  front/app/containers/Admin/projects/project/inputForm/saveIdeaFormAsPDF.ts
  front/app/containers/Admin/projects/project/inputImporter/ReviewSection/EmptyState.tsx
  front/app/containers/Admin/projects/project/nativeSurvey/SurveyFormBuilder/index.tsx
  front/app/containers/Admin/projects/project/nativeSurvey/index.tsx
  front/app/containers/Admin/projects/project/nativeSurvey/saveSurveyAsPDF.ts
  front/app/utils/configs/formActionsConfig/utils.tsx
  front/app/utils/requestBlob.ts
Labels: formsync-pdf

#10961 Tan 4508/handle pdf export
  front/app/components/FormBuilder/components/FormBuilderTopBar/DownloadPDFButtonWithModal.tsx
  front/app/components/FormBuilder/components/FormBuilderTopBar/index.tsx
  front/app/components/FormBuilder/edit/index.tsx
  front/app/components/FormBuilder/utils.tsx
  front/app/components/admin/SurveyDropdownSettings/DownloadPDFDropdownListItemWithModal.tsx
  front/app/components/admin/SurveyDropdownSettings/DropdownSettings.tsx
  front/app/containers/Admin/communityMonitor/CommunityMonitorFormBuilder/utils.tsx
  front/app/containers/Admin/projects/components/PDFExportModal/index.tsx
  front/app/containers/Admin/projects/project/inputForm/IdeaFormBuilder/index.tsx
  front/app/containers/Admin/projects/project/inputForm/index.tsx
  front/app/containers/Admin/projects/project/inputImporter/ReviewSection/EmptyState.tsx
  front/app/containers/Admin/projects/project/nativeSurvey/SurveyFormBuilder/index.tsx
  front/app/containers/Admin/projects/project/nativeSurvey/index.tsx
Labels: formsync-pdf

#10909 Add option to not allow creating links in Quill editor
  front/app/components/UI/QuillEditor/Toolbar.tsx
  front/app/components/UI/QuillEditor/createQuill.ts
  front/app/components/UI/QuillEditor/index.tsx
Labels: formsync-pdf

#10905 Tan 4482/personal data checkbox
  front/app/component-library/components/CheckboxWithLabel/index.tsx
  front/app/containers/Admin/projects/components/PDFExportModal/index.tsx
  front/app/containers/Admin/projects/components/PDFExportModal/messages.ts
  front/app/translations/admin/ar-SA.json
  front/app/translations/admin/cy-GB.json
  front/app/translations/admin/da-DK.json
  front/app/translations/admin/de-DE.json
  front/app/translations/admin/en-CA.json
  front/app/translations/admin/en-GB.json
  front/app/translations/admin/en-IE.json
  front/app/translations/admin/en.json
  front/app/translations/admin/es-CL.json
  front/app/translations/admin/es-ES.json
  front/app/translations/admin/fi-FI.json
  front/app/translations/admin/fr-BE.json
  front/app/translations/admin/fr-FR.json
  front/app/translations/admin/hr-HR.json
  front/app/translations/admin/lt-LT.json
  front/app/translations/admin/lv-LV.json
  front/app/translations/admin/nb-NO.json
  front/app/translations/admin/nl-BE.json
  front/app/translations/admin/nl-NL.json
  front/app/translations/admin/pa-IN.json
  front/app/translations/admin/pl-PL.json
  front/app/translations/admin/pt-BR.json
  front/app/translations/admin/sr-Latn.json
  front/app/translations/admin/sr-SP.json
  front/app/translations/admin/sv-SE.json
  front/app/translations/admin/tr-TR.json
  front/app/translations/admin/ur-PK.json
Labels: formsync-pdf

#10978 TAN-4536 - Fix approving single ideas
  front/app/containers/Admin/projects/project/inputImporter/ReviewSection/IdeaEditor/index.tsx
Labels: formsync-pdf

#10980 TAN-4472 - html 2 pdf generation license fix
  back/Gemfile
  back/Gemfile.lock
  back/engines/commercial/bulk_import_ideas/app/services/bulk_import_ideas/exporters/gotenberg_client.rb
  back/engines/commercial/bulk_import_ideas/app/services/bulk_import_ideas/exporters/idea_html_pdf_form_exporter.rb
Labels: formsync-pdf

#10931 TAN-4498 - Added customisable start and end multilocs for printed forms
  back/app/controllers/web_api/v1/custom_forms_controller.rb
  back/app/models/custom_form.rb
  back/app/serializers/web_api/v1/custom_form_serializer.rb
  back/config/routes.rb
  back/db/migrate/20250501134516_add_print_start_end_to_custom_form.rb
  back/db/structure.sql
  back/engines/commercial/idea_custom_fields/app/controllers/idea_custom_fields/web_api/v1/admin/idea_custom_fields_controller.rb
  back/engines/commercial/idea_custom_fields/config/routes.rb
  back/engines/commercial/idea_custom_fields/spec/acceptance/idea_custom_fields/phase_context/custom_form_spec.rb
  back/engines/commercial/idea_custom_fields/spec/acceptance/idea_custom_fields/phase_context/update_all_native_survey_spec.rb
  back/engines/commercial/idea_custom_fields/spec/acceptance/idea_custom_fields/project_context/custom_form_spec.rb
  back/spec/acceptance/custom_forms_spec.rb
  front/app/api/custom_fields/useUpdateCustomFields.ts
  front/app/api/custom_form/types.ts
  front/app/api/custom_form/useCustomForm.ts
  front/app/components/FormBuilder/edit/index.tsx
Labels: ready to release, formsync-pdf

#10939 TAN-4505 - Add attribute include_in_printed_forms to custom field
  back/app/models/custom_field.rb
  back/app/serializers/web_api/v1/custom_field_serializer.rb
  back/app/services/project_copy_service.rb
  back/db/migrate/20250502112945_add_include_in_printed_form_to_custom_fields.rb
  back/db/structure.sql
  back/engines/commercial/idea_custom_fields/app/controllers/idea_custom_fields/web_api/v1/admin/idea_custom_fields_controller.rb
  back/engines/commercial/idea_custom_fields/spec/acceptance/idea_custom_fields/phase_context/update_all_community_monitor_survey_spec.rb
  back/engines/commercial/idea_custom_fields/spec/acceptance/idea_custom_fields/phase_context/update_all_native_survey_spec.rb
  back/engines/commercial/idea_custom_fields/spec/acceptance/idea_custom_fields/project_context/update_all_ideation_spec.rb
  back/engines/commercial/multi_tenancy/app/services/multi_tenancy/templates/serializers/custom_field.rb
  back/lib/participation_method/ideation.rb
  back/lib/participation_method/native_survey.rb
  back/spec/serializers/web_api/v1/custom_field_serializer_spec.rb
Labels: ready to release, formsync-pdf

#11008 Add html_pdfs feature to AppConfig type
  front/app/api/app_configuration/types.ts
Labels: formsync-pdf

#11003 Fixed include_in_printed_form so that the correct default value saves
  front/app/api/custom_fields/types.ts
  front/app/components/FormBuilder/edit/index.tsx
Labels: formsync-pdf

#10968 TAN-4516 - Increase maintainability of custom field serializer tests
  back/engines/commercial/idea_custom_fields/spec/acceptance/idea_custom_fields/phase_context/update_all_native_survey_spec.rb
  back/spec/serializers/web_api/v1/custom_field_serializer_spec.rb
Labels: ready to release

#11001 Automatically handle logic to determine correct custom form endpoint
  front/app/api/custom_form/getApiEndpoint.ts
  front/app/api/custom_form/types.ts
  front/app/api/custom_form/useCustomForm.ts
  front/app/components/FormBuilder/edit/index.tsx
  front/app/containers/Admin/projects/project/inputForm/utils.tsx
Labels: formsync-pdf

#10986 Improve IdeaFormBuilder types
  front/app/containers/Admin/communityMonitor/CommunityMonitorFormBuilder/index.tsx
  front/app/containers/Admin/projects/project/inputForm/IdeaFormBuilder/index.tsx
  front/app/containers/IdeaHeading/NewIdeaHeading/index.tsx
Labels: formsync-pdf

#11056 Extract ExcelDownloadButton for easier maintenance
  front/app/components/FormSync/ExcelDownloadButton.tsx
  front/app/components/FormSync/messages.ts
  front/app/containers/Admin/projects/project/inputForm/index.tsx
  front/app/containers/Admin/projects/project/inputForm/messages.ts
  front/app/containers/Admin/projects/project/inputImporter/ReviewSection/EmptyState.tsx
  front/app/translations/admin/ar-SA.json
  front/app/translations/admin/cy-GB.json
  front/app/translations/admin/da-DK.json
  front/app/translations/admin/de-DE.json
  front/app/translations/admin/en-CA.json
  front/app/translations/admin/en-GB.json
  front/app/translations/admin/en-IE.json
  front/app/translations/admin/en.json
  front/app/translations/admin/es-CL.json
  front/app/translations/admin/es-ES.json
  front/app/translations/admin/fi-FI.json
  front/app/translations/admin/fr-BE.json
  front/app/translations/admin/fr-FR.json
  front/app/translations/admin/hr-HR.json
  front/app/translations/admin/lt-LT.json
  front/app/translations/admin/lv-LV.json
  front/app/translations/admin/nb-NO.json
  front/app/translations/admin/nl-BE.json
  front/app/translations/admin/nl-NL.json
  front/app/translations/admin/pa-IN.json
  front/app/translations/admin/pl-PL.json
  front/app/translations/admin/pt-BR.json
  front/app/translations/admin/sr-Latn.json
  front/app/translations/admin/sr-SP.json
  front/app/translations/admin/sv-SE.json
  front/app/translations/admin/tr-TR.json
  front/app/translations/admin/ur-PK.json
  front/app/translations/en.json
Labels: formsync-pdf

#11062 Revert wrong deletion of translations
  front/app/components/FormSync/messages.ts
  front/app/translations/en.json
Labels: formsync-pdf

#10910 Add field for instructions at start/end of printed form
  front/app/api/custom_form/useUpdateCustomForm.ts
  front/app/component-library/components/CollapsibleContainer/index.tsx
  front/app/components/UI/QuillEditor/QuillMultilocWithLocaleSwitcher.tsx
  front/app/containers/Admin/projects/components/PDFExportModal/FormActions.tsx
  front/app/containers/Admin/projects/components/PDFExportModal/MultilocFieldCollapsible.tsx
  front/app/containers/Admin/projects/components/PDFExportModal/PersonalDataCheckbox.tsx
  front/app/containers/Admin/projects/components/PDFExportModal/index.tsx
  front/app/containers/Admin/projects/components/PDFExportModal/messages.ts
  front/app/translations/admin/en.json
Labels: formsync-pdf

#11025 [TAN-3858] Improve UX around project banner & event image upload
  front/app/components/admin/ImageCropper/Container.tsx
  front/app/components/admin/ImageCropper/index.tsx
  front/app/components/admin/ImageCropper/messages.ts
  front/app/components/admin/ProjectableHeaderBgUploader/index.tsx
  front/app/translations/admin/en.json
Labels: waiting for translations

#10988 Replace "Beta" text with "Early Access" badge for InputIQ and Community Monitor
  front/app/components/admin/EarlyAccessBadge/index.tsx
  front/app/components/admin/EarlyAccessBadge/messages.ts
  front/app/containers/Admin/communityMonitor/components/LiveMonitor/index.tsx
  front/app/containers/Admin/communityMonitor/messages.ts
  front/app/containers/Admin/projects/project/phaseSetup/components/PhaseParticipationConfig/components/shared/SimilarityDetectionConfig.tsx
  front/app/translations/admin/ar-SA.json
  front/app/translations/admin/cy-GB.json
  front/app/translations/admin/da-DK.json
  front/app/translations/admin/de-DE.json
  front/app/translations/admin/en-CA.json
  front/app/translations/admin/en-GB.json
  front/app/translations/admin/en-IE.json
  front/app/translations/admin/en.json
  front/app/translations/admin/es-CL.json
  front/app/translations/admin/es-ES.json
  front/app/translations/admin/fi-FI.json
  front/app/translations/admin/fr-BE.json
  front/app/translations/admin/fr-FR.json
  front/app/translations/admin/hr-HR.json
  front/app/translations/admin/lt-LT.json
  front/app/translations/admin/lv-LV.json
  front/app/translations/admin/nb-NO.json
  front/app/translations/admin/nl-BE.json
  front/app/translations/admin/nl-NL.json
  front/app/translations/admin/pa-IN.json
  front/app/translations/admin/pl-PL.json
  front/app/translations/admin/pt-BR.json
  front/app/translations/admin/sr-Latn.json
  front/app/translations/admin/sr-SP.json
  front/app/translations/admin/sv-SE.json
  front/app/translations/admin/tr-TR.json
  front/app/translations/admin/ur-PK.json
Labels: waiting for translations

#11050 TAN-4599 - Add print_personal_data_fields to custom form
  back/app/controllers/web_api/v1/custom_forms_controller.rb
  back/app/models/custom_form.rb
  back/app/serializers/web_api/v1/custom_form_serializer.rb
  back/db/migrate/20250513160156_add_print_personal_data_fields_to_custom_form.rb
  back/db/structure.sql
  back/spec/acceptance/custom_forms_spec.rb
  front/app/api/custom_form/types.ts
Labels: formsync-pdf

#11063 Survey form tab E2E
  front/app/components/FormBuilder/components/FormBuilderToolbox/index.tsx
  front/app/components/FormBuilder/components/FormBuilderTopBar/index.tsx
  front/app/components/FormBuilder/edit/index.tsx
  front/app/containers/Admin/projects/project/nativeSurvey/utils.tsx
  front/app/containers/Admin/projects/project/surveyForm/TabPanel.tsx
  front/cypress/e2e/admin/phases/nativeSurvey/survey_form_tab.cy.ts
  front/cypress/e2e/idea_form_settings.cy.ts
Labels: formsync-pdf

#11038 TAN-4586 - Add backdoor to using the old PDF format
  back/engines/commercial/bulk_import_ideas/app/controllers/bulk_import_ideas/web_api/v1/bulk_import_controller.rb
  back/engines/commercial/bulk_import_ideas/spec/acceptance/idea_export_form_spec.rb
  front/app/api/import_ideas/useAddOfflineIdeasAsync.ts
  front/app/containers/Admin/projects/project/inputImporter/ImportModal/ImportPdfModal.tsx
Labels: formsync-pdf

#11104 TAN-4634 - Add matrix field to PDF
  back/config/locales/en.yml
  back/engines/commercial/bulk_import_ideas/app/services/bulk_import_ideas/exporters/idea_html_form_exporter.rb
  back/engines/commercial/bulk_import_ideas/app/views/bulk_import_ideas/web_api/v1/export_form.html.erb
  back/engines/commercial/bulk_import_ideas/spec/services/exporters/idea_html_form_exporter_spec.rb
  back/spec/fixtures/locales/en.yml
Labels: formsync-pdf

#11015 TAN-4565 - HTML PDF generation add fonts, numbers & all question types to form
  back/app/models/custom_field.rb
  back/app/models/custom_form.rb
  back/app/services/idea_custom_fields_service.rb
  back/app/services/multiloc_service.rb
  back/config/locales/en.yml
  back/engines/commercial/bulk_import_ideas/app/controllers/bulk_import_ideas/web_api/v1/bulk_import_controller.rb
  back/engines/commercial/bulk_import_ideas/app/services/bulk_import_ideas/exporters/idea_html_form_exporter.rb
  back/engines/commercial/bulk_import_ideas/app/services/bulk_import_ideas/exporters/idea_html_pdf_form_exporter.rb
  back/engines/commercial/bulk_import_ideas/app/services/bulk_import_ideas/exporters/idea_pdf_form_exporter.rb
  back/engines/commercial/bulk_import_ideas/app/services/bulk_import_ideas/parsers/idea_html_pdf_file_parser.rb
  back/engines/commercial/bulk_import_ideas/app/services/bulk_import_ideas/parsers/idea_pdf_file_parser.rb
  back/engines/commercial/bulk_import_ideas/app/views/bulk_import_ideas/web_api/v1/export_form.html.erb
  back/engines/commercial/bulk_import_ideas/spec/acceptance/idea_export_form_spec.rb
  back/engines/commercial/bulk_import_ideas/spec/services/exporters/idea_html_form_exporter_spec.rb
  back/lib/participation_method/community_monitor_survey.rb
  back/lib/participation_method/ideation.rb
  back/lib/participation_method/native_survey.rb
  back/spec/fixtures/locales/en.yml
  back/spec/fixtures/locales/fr-FR.yml
  back/spec/models/custom_field_spec.rb
  back/spec/services/multiloc_service_spec.rb
  front/app/api/import_ideas/useAddOfflineIdeasAsync.ts
  front/app/containers/Admin/projects/project/inputImporter/ImportModal/ImportPdfModal.tsx
Labels: formsync-pdf

#11123 TAN-4297 - Improve printed rating field
  back/config/locales/en.yml
  back/engines/commercial/bulk_import_ideas/app/services/bulk_import_ideas/exporters/idea_html_form_exporter.rb
  back/spec/fixtures/locales/en.yml
Labels: formsync-pdf

#11051 Remove unused admin survey messages
  front/app/containers/Admin/projects/project/nativeSurvey/messages.ts
  front/app/translations/admin/ar-SA.json
  front/app/translations/admin/ca-ES.json
  front/app/translations/admin/cy-GB.json
  front/app/translations/admin/da-DK.json
  front/app/translations/admin/de-DE.json
  front/app/translations/admin/el-GR.json
  front/app/translations/admin/en-CA.json
  front/app/translations/admin/en-GB.json
  front/app/translations/admin/en-IE.json
  front/app/translations/admin/en.json
  front/app/translations/admin/es-CL.json
  front/app/translations/admin/es-ES.json
  front/app/translations/admin/fi-FI.json
  front/app/translations/admin/fr-BE.json
  front/app/translations/admin/fr-FR.json
  front/app/translations/admin/hr-HR.json
  front/app/translations/admin/it-IT.json
  front/app/translations/admin/kl-GL.json
  front/app/translations/admin/lb-LU.json
  front/app/translations/admin/lt-LT.json
  front/app/translations/admin/lv-LV.json
  front/app/translations/admin/nb-NO.json
  front/app/translations/admin/nl-BE.json
  front/app/translations/admin/nl-NL.json
  front/app/translations/admin/pa-IN.json
  front/app/translations/admin/pl-PL.json
  front/app/translations/admin/pt-BR.json
  front/app/translations/admin/sr-Latn.json
  front/app/translations/admin/sr-SP.json
  front/app/translations/admin/sv-SE.json
  front/app/translations/admin/tr-TR.json
  front/app/translations/admin/ur-PK.json
Labels: formsync-pdf

#11136 TAN-4635 - PDF sentiment scale field in PDF form
  back/config/locales/en.yml
  back/engines/commercial/bulk_import_ideas/app/services/bulk_import_ideas/exporters/idea_html_form_exporter.rb
  back/engines/commercial/bulk_import_ideas/spec/services/exporters/idea_html_form_exporter_spec.rb
Labels: formsync-pdf

#11117 Align survey editor route with survey form tab + how it's done for id…
  front/app/containers/Admin/projects/project/surveyForm/TabPanel.tsx
  front/app/containers/Admin/projects/routes.tsx
  front/app/containers/IdeasNewSurveyPage/IdeasNewSurveyForm/SurveyHeading/index.tsx
  front/cypress/e2e/admin/phases/nativeSurvey/survey_form_tab.cy.ts
  front/cypress/e2e/form_builder/elements/file_upload_field.cy.ts
  front/cypress/e2e/form_builder/elements/image_multiple_choice.cy.ts
  front/cypress/e2e/form_builder/elements/linear_scale_field.cy.ts
  front/cypress/e2e/form_builder/elements/long_field.cy.ts
  front/cypress/e2e/form_builder/elements/matrix_field.cy.ts
  front/cypress/e2e/form_builder/elements/multiple_choice_field.cy.ts
  front/cypress/e2e/form_builder/elements/number_field.cy.ts
  front/cypress/e2e/form_builder/elements/page_element.cy.ts
  front/cypress/e2e/form_builder/elements/point_field.cy.ts
  front/cypress/e2e/form_builder/elements/ranking_field.cy.ts
  front/cypress/e2e/form_builder/elements/single_choice_field.cy.ts
  front/cypress/e2e/survey_builder/create_and_fill_survey.cy.ts
  front/cypress/e2e/survey_builder/custom_survey_end_page_button.cy.ts
  front/cypress/e2e/survey_builder/survey_logic_conflict.cy.ts
  front/cypress/e2e/survey_builder/survey_page_logic.cy.ts
  front/cypress/e2e/survey_builder/survey_question_logic.cy.ts
Labels: formsync-pdf

#10881 Tan 3560/admin pub debounce search
  front/app/api/admin_publications/useAdminPublications.ts
  front/app/containers/Admin/pagesAndMenu/containers/ContentBuilder/components/Widgets/Selection/Settings/AdminPublicationSearchInput.tsx
  front/app/hooks/useDebouncedValue.ts
Labels: fe-performance
